# IFEST DAC 2026 — V7A IndoBART Conditional Headline Likelihood Verifier

**Frozen champion:** V5 (V2 train-reference structural graph → V4 test-test canonical matching → V5 asymmetric positive rescue).  
**New hypothesis:** the dataset is close to an article → canonical-headline construction process. V7A learns that process directly with IndoBART-v2 and uses teacher-forced conditional likelihood as an orthogonal factuality signal.

### Non-negotiable contract
- V2/V4 structural decisions and V5 rescue decisions are immutable.
- New prospective component-safe validation: 80% **DESIGN** / 20% untouched **LOCK**, split with seed `260907`.
- DESIGN uses 3-fold connected-component CV; LOCK labels are not inspected until coverage is frozen.
- IndoBART-v2, source length 768, target length 48, 2 epochs, LR `2e-5`, real same-content counterfactual ranking only.
- No external dataset, no synthetic negatives, no title-conditioned retrieval, no generic threshold tuning.
- Risk is frozen at `0.5 × percentile(mean headline NLL) + 0.5 × percentile(top-2 token NLL)`.
- Deployment searches only the precommitted low-coverage grid and optimizes **Macro F1**, not a 90%-precision veto rule.
- Final intervention is only `1 → 0` on V5-positive pure-fallback rows.
- If DESIGN, LOCK, or final test-count gates fail, output falls back exactly to frozen V5.

The notebook is intentionally compact (<1 MB) and embeds only the minimum frozen numeric arrays needed from prior runs. No hidden test labels are embedded.

> **Runtime revision:** legacy `indobenchmark-toolkit` tokenizer dependency is replaced by an encode-equivalent direct SentencePiece wrapper to remain compatible with current Kaggle Transformers/Python runtimes. Experimental methodology is unchanged.

In [1]:
import os, sys, re, io, gc, json, math, time, base64, hashlib, random, zipfile, unicodedata, warnings, subprocess, importlib.util, tempfile, shutil
from pathlib import Path
from collections import defaultdict
from contextlib import nullcontext

# Minimal runtime dependencies.
# IMPORTANT: do not import indobenchmark-toolkit here. Its IndoNLGTokenizer still
# imports TensorFlow/JAX compatibility helpers removed by recent Kaggle
# Transformers releases. We use the checkpoint's SentencePiece model directly,
# which is token-ID equivalent for the encode-only path required by V7A.
requirements=[]
for mod,pkg in [
    ("transformers","transformers>=4.44,<6"),
    ("sentencepiece","sentencepiece>=0.2"),
    ("sklearn","scikit-learn"),
    ("huggingface_hub","huggingface_hub>=0.24"),
]:
    if importlib.util.find_spec(mod) is None: requirements.append(pkg)
if requirements:
    print("Installing missing dependencies:",requirements)
    subprocess.check_call([sys.executable,"-m","pip","install","-q",*requirements])

import numpy as np, pandas as pd
from tqdm.auto import tqdm
from IPython.display import display
from sklearn.metrics import f1_score
from sklearn.model_selection import StratifiedGroupKFold
import torch, torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from transformers import AutoModelForSeq2SeqLM, get_linear_schedule_with_warmup
from huggingface_hub import hf_hub_download
import sentencepiece as spm
import transformers, sklearn

warnings.filterwarnings("ignore")
os.environ.setdefault("TOKENIZERS_PARALLELISM","false")
os.environ.setdefault("HF_HUB_DISABLE_TELEMETRY","1")
pd.set_option("display.max_colwidth",180)

# ---------------- V7A FROZEN CONFIG ----------------
SEED=2026
LOCK_SEED=260907
DESIGN_FOLDS=3
EXPECTED_TRAIN_ROWS=14397; EXPECTED_TEST_ROWS=3603
TRAIN_ID_SHA256="9abdabdd6cda9baac679b5cf004572e02326859fc2b13caa37af32c335e6c94a"
TEST_ID_SHA256="e4763272ee9a832ad2141f979a48701222a6651550ba2a88cf6c89357094064c"

# Frozen V2/V4/V5 constants — never retune in V7A.
V2_TITLE_GATE=0.9839511586057019; MIN_GRAPH_CONTENT_WORDS=20
RANK_V3_WEIGHT=0.45; RANK_V2_GLOBAL_WEIGHT=0.55
CONTENT_CANONICAL_MIN_SCORE=0.20; TITLE_CANONICAL_MIN_SCORE=0.90; TITLE_CANONICAL_MIN_MARGIN=0.02
V5_BLEND_MIN=0.67; V5_GLOBAL_ENTAIL_MIN=0.50
V2_META_THRESHOLD=0.5969828254552141  # frozen from the already-run V2 OOF experiment

# IndoBART conditional-likelihood verifier.
MODEL_NAME="indobenchmark/indobart-v2"
MODEL_REVISION="e5b7d7ca907c6ba95cd361270b568f7ee9ceb0fd"
LOCAL_MODEL_PATH=os.environ.get("V7A_MODEL_PATH","").strip() or None
SOURCE_MAX=768; TARGET_MAX=48
EPOCHS=2; LR=2.0e-5; WEIGHT_DECAY=0.01; WARMUP_RATIO=0.05
TRAIN_BATCH=4; PAIR_BATCH=2; GRAD_ACCUM=8; SCORE_BATCH=8
PAIR_LAMBDA=0.50; MAX_GRAD_NORM=1.0; USE_AMP=True; USE_GRADIENT_CHECKPOINTING=True

# Frozen risk / coverage policy.
RISK_MEAN_WEIGHT=0.50; RISK_TOP2_WEIGHT=0.50
COVERAGE_GRID=np.array([0.0,0.002,0.004,0.006,0.010,0.015,0.020,0.030],dtype=float)

# Prospective promotion gates.
MIN_DESIGN_GAIN=0.0015
MIN_POSITIVE_DESIGN_FOLDS=2
MIN_WORST_DESIGN_FOLD_GAIN=-0.0005
MIN_PAIR_RANK_ACC=0.90
MIN_LOCK_GAIN=0.0
MIN_LOCK_PRECISION=0.50
BOOTSTRAP_REPS=1000
MIN_BOOTSTRAP_POSITIVE=0.80
MIN_TEST_CHANGES=5; MAX_TEST_CHANGES=90

OUTPUT_DIR=Path("/kaggle/working/ifest_v7a_output" if Path("/kaggle/working").exists() else "/mnt/data/ifest_v7a_output")
if OUTPUT_DIR.exists(): shutil.rmtree(OUTPUT_DIR)
OUTPUT_DIR.mkdir(parents=True,exist_ok=True)
TMP_DIR=OUTPUT_DIR/"_tmp_checkpoints"; TMP_DIR.mkdir(exist_ok=True)


def seed_everything(seed=SEED):
    random.seed(seed); np.random.seed(seed); torch.manual_seed(seed)
    if torch.cuda.is_available(): torch.cuda.manual_seed_all(seed)
    if hasattr(torch.backends,"cudnn"):
        torch.backends.cudnn.deterministic=True; torch.backends.cudnn.benchmark=False
seed_everything()

DEVICE=torch.device("cuda" if torch.cuda.is_available() else "cpu")
GPU_COUNT=torch.cuda.device_count(); AMP_ENABLED=bool(USE_AMP and DEVICE.type=="cuda")
if DEVICE.type!="cuda": raise RuntimeError("V7A training requires Kaggle GPU. Select the T4 x2 accelerator before running.")
print("GPU count:",GPU_COUNT)
for i in range(GPU_COUNT):
    p=torch.cuda.get_device_properties(i); print(i,torch.cuda.get_device_name(i),f"VRAM={p.total_memory/1024**3:.1f} GB")
print(f"PyTorch={torch.__version__} | Transformers={transformers.__version__} | sklearn={sklearn.__version__} | AMP={AMP_ENABLED}")

GPU count: 2
0 Tesla T4 VRAM=14.6 GB
1 Tesla T4 VRAM=14.6 GB
PyTorch=2.10.0+cu128 | Transformers=5.0.0 | sklearn=1.6.1 | AMP=True

In [2]:
# Minimal frozen arrays from already-run V2/V3/V5. No hidden target labels.
_FROZEN_B64="""UEsDBC0AAAAIAAAAIQBiKIvW//////////8PABQAb29mX3YyX21ldGEubnB5AQAQAHThAAAAAAAAKbYAAAAAAACcnIVXFW0XxTFBsVCwAxMFBQPbmW2hGNiFgAGiiHTc6cFuxUZAFDvBwFbswO7uTsTu+Da8/8H3ruV6F3DvzDznOWfv37537p3fo79XL+98VhYrzWlEYHRAlFMrR6c2I92d6js6jQyPiokaHjY0PGpEYO7vOw0PiQ7k76ODhkcE8ue6jdybtGxev159R8Px//yv6L9CEha0NOD+V8HdwwZ2nzYQ9UNBXCMNg45J+NZAR0L3tih51cAyzYD3dAVXm2l4dcxbaOuvY56PCqWCgVLVFTh/VVDvt4wjs3U0e2+g0BMZ23oq2FvXDfl3qwhorGHUcQ3ta2pYeM3A0bcGGj7RUSheh1zbQLlTMu5X0lCgqYqdzzQ0NTQcnDJXyJ9gJy7xMNGjh4r2mSqm3zJwOCIGZ5M1POuhIynIRNOnsViUrSJsmTcK1RkjVJnjBz83Az368LqWS/jUZQDW39MxrZGOvXEyvOw0jGs0BrdbGVCu6HBMU3F/qAHN3YBrWxPmtKqY7aahfpqODxVM+H6UYJ+kopGzgTlrZbiV/SKcm7hYzHBRMPKZE+bbhMDYLuPdi1i0WSRhUG0Tez8reMdjBg7Rscai421HA74jNARtlHFMUtAwWIEmyOi8S0WtOTIOLpCwapsvPqYYOBlp4raHHwYGqHitKBjxMRxzy5goqKhIH23BtZsK7vUwMG+CjgXrdVx7oCFu+TA8s1Kw/6+tuOK2DI9tKk7WH4xXQ4OEPgcVHKulYnQJDQ8yVDRc54TBJzVYfYzF6X6bxeM1+8G3Itf3XcUE7k/dIzrSvyl4/U9By2Ym1oebaH5YR9VLo3lOFedeKBDPR2DzKgNBXVT0bWFh3Q1MWacjbYCMAfsV9E9pJPrYa/i5U8HhIiZOrNegj5Ux5ZSCpb8lTDl6WCwSbSAjVseXOyqOX9bRKG2amFz0vtDmp4aEPyqKvnQW0lx17Jui4o6njrkfFDQdrKCOn4qc01EQChioukvD66oGAvYOFb5yX/MXUjDDR0fjfRJG71HFlQEmDi2MwKA9sXhUQMXR5zo+p6oIdlfQ/ZSKv2/WCFZVTGgdVEzyZC8FjRcTQmJxflakOHxDDHaONdCvu8a6GkjeqeL9TAM2fH5GQfavo4wlSTpmxXsKamUNp2JVlBokIz/Pb3NRx5LmEnZ0sOBbagxK2Rg4w8furW2H5r90ZO1QYRfCn7NZ1x8SCvTVsLGcAau3CtprMuqv1uD7zYLMwSrWNN4gOKzQ8cbWwJvbsdi1WUPNYTLedtJwrqQK7woq3pTUEFrUwOPiGmwWyDhrby8aHbgXVzSMPWNgq2ggfpGBGl46vKIDsOyyhlalFFw4sEIct9dEyDYFNXwfiBdmmxDOcW5aqhh13oKZa1W8ZE9WKReHtOpJQmiWjoaDDKzbUBTRY01cnWOBzeBKgJsM22kymp3NEC76aXizRod1oIH7V8ojcJqG2fs13Fqt4Ar3zuyjYUBtFYEXiyC4qgk/ewOn7Nhzt0qIu4vrGDRZx+8zKlwuxmIPNSMhXsPbagZsr7F/I+OAlxIm/NRxoFeQ2Km5jqO/Ffw8r2FVIRMdVyjIfq3Bf5eBno90dO1vooJNJBwuyRhzW8KT6iaSZxvYWE1Dm74mhu61YOwAnqOzgdaJYSixNQx9vrfH1s8ySrnfF6f9iMWdl+zxCryGCjJ619bQS1axqo6Or78MnH1g4HUbDWaKCh/qze9wagTXV3FwIILZ92caUTuyONPeKr5dkIEiXDf7p9luCfecTMSV1TDy5jCM1+JwojR76b0OdZcEhw0aSu6QsHBjMJ5HyfhVWMbsMO6D2hf7J6rYMfWbmPVax1mr6eKCLwbyUwPGOOrYrxp4VXMEHG5pqPZSQeJCCVbR7O0XMdwLGd9HGtjf3sTFYBPzMzX0jVEx+Z2GPUcMDF+lwWlwLII3KMhooKJVOQUbtNHYsVnFmLIqyp5VkTBdw3ONWsqee0Yv2FzNxCU7FeVmWzDg21cx9bstGiVsFsO4X+Z8FXotavohDTHl08VzpRXcceHvuytYm5Au5P+gYgVncjx1rJerBusSUdhMT9iXoeXVxeV5BF7H00usF4p/AqOxy0GBX9Qq4QO1oQSfV/uohu/uQcJP+s6ekxJGZpnY/U5HyWo6ooqbaCEq+JCj4rILj1dfx6vLM0X7neyLQRpOv9CwbLOJypyhRVtqiVm8zkG1DBSdrKH0aQsK1tDgMFLBzpEyfMbLqPGcc5g9EsWpGwms9/XvOgZW17AeKp5wn/GGGltPQ79b7YTe03wQ70NfLWsitWVnUaUuHT6hYECjCPyq7IXHFekHP1V0KECd/65hhC01lpq3lb6wlX2UtEqFxx0L8sUZKD/KxLN748Xvrcvj/VkZ13ndO1vISL2tA2M0VM+hB3yPhnGK1+PLPrYykeMr4X5BFT2aqLhYj9qq62jhpqII9+uZqqNLmIo4amr2MRUzulDfFlFDPNiT76NRsyHnm9eQbBUr+F00cJEMcGol/dpaQ74sDWlhOl54a9jH+fwbTP+kR53fr+LYJwteXNDx74WKFJ5j+SIdFX4qEOgzHhck2NITxx7WcDSfiuondfSz0jGcvluaHlCotQmbz2GoQU2tkMsUszXMuWtgnKIhe5iOxfScum1aoz/703Oigfkxo4VqezTMom80ua5i5BIZzanLaksF/3obaHo9AuofA6HVVWS9NDDyBOuQHoguE+gNkopMUcZaPi6YulTx/XbR8ZuKr8EqXtE3A5vEwieDXkTdqeFvYHXd/PgXYSJtoI6O9uSh4QZcphrYnKpj9AML4qtFoPQA6v2JM6LTW/LChwr4XTAS9Y4OQeJdBVUuU3srx8LrcFGxLvezMDUolcx1+UhbsSH7YuAcFa4rNNyr+lzsWJ4+l5whdrWPxsLBGuRMGdmzWPtF4Wh9WsG8ySZuks/iR5ODiul4XF/GcUHH+PRY5Oujo2g3Det4LZtjDRz4pcAymuepZSKBsxTE34WTIVA0QRzEHqpKdqmcruDRQh2dr5HDguhJJbNFb2pYNvf/saAippKBJjL96RP1uT61lfznUIT7maCi31cD0d46Eg0Zz3iM5WS+EcXCxQK1dEgaZ4G9t/djBJZ9NPCinIR3gSa863CGS0s4NFyF52j2LfX8yRwd88ldg00bhMTpqJcZALv7MqLYXx0m0Q/7KWhOdkrcomEJ9/j9OB3jTozGJvJE8eBYfHgZL7R3VhDaKwA9yUf2c7YK67sakMbqyGxjsF+oOUsj4XvPQIiHf14vtiDrxF6oIbgujMW4OQq8Dx4UEn9KqE49kvcpOOFsov/YEKHhjW4oP1WHA0qIB8gBo0fpGMV+SqtZGnaVTAR003EuVsbU8jpyHhcVneZFIrx9Sfw2VJShBzZbpyGTbD2F/tvLmr3RjRqyzUA1rt2V/enGmbhhURDM2i9P+iWMbG6iVhMdz5xVqDsbYiM1fcaqSMTcdRVdkhQcjDFQ8c808V66iiWLNWwhQ76lNyw/a2Av+emyo4bJfu1EHzJZTTkW9VxjkdJDQ2KggvLs5wolDcihBob8ULES1PFiGr6Qqdq2Iff00+HZxYKnKxWU/Uwet1WQTm+uzbolsecaX1GxLV3HBn8TVY/IsLuhwm2vjtIlZITumSycI0cPWzUcH/vRa6LcMZgcls556l7OxJEJ0Vh0kPvHnn26zEAlsq7wkN7jYWChVXVMn0cdrkZO7B2ILDKKQMZoPSYfCrfWEZOsomCbYJTmNc6m9l6gNzgVeybeV8hT1xQ8cy2Gsr48Z1Xq3HMDzVLDxIeTJJTpTF2vaABXDDhVNjHqYLjQvp6EdclkXt8+KCKF4dk5CUExGnrHK+gQIZOFByMzgOe01VCEa6u5nX0VqOPuAhVLh+v4S605RZ+7O0dDQTJH6ax3QtNnKm7xXAJMeDE3PZqp4GKCgktzY3D9qYwE+vg/so7vEPo5fdblq4ahho5LzFPH+rYTGhZPEW4K88Sy1LyM7zKK9UwWjoSwJ5uR5QfpWFvQgvevVeyZpKNl7DAUo47nFDdQj89vyZm7t02G/yQF9tV1BJEL5woa7pAr/C8yLyUrOEk9zShtYPkDBSUW0GPJv/1TPPGPdVm+T0YE9df3joIcemquPxutNNTaRy0pHAU/evxM/s2DPJW/Jee0PdfMmWpNhvuWaGLIVDKiNWfMS0U1NwX7bDn7g9nbi8uJI+9IwP5ojJpWUNzQNAI715DnrkTj3FgLZpGFPrMX1TIqnFINPOcs12Y+kU5ICHvIXk0w8LUUc02Us/BgCjX0NxliO7NGfx1NjzdG214Gai+3IPRfkpi/3FGxma2KxeSwwcdklDilIWWfhzhpWhSGrNHQYBP/GSNxgl5SkLr5+4CGPycVFGIW2f1Sx+HRMr4wpzX4EIyuh3Rsp4bezwnB1obkI15jPP3NyOVI6smZIBmFmZGn8eeylcj3D1Sstg3Bw4MGitHbrg+VUXaMgQ4h7HGyf24vL97nCaeLkbg1Q4EPNfTvGw19gtgTWTLOH6BH8nkHQzUMmy/jD3NihR9c98Ergid/NlbQC0vwmunVA1j36r4xeJqmwH2KjjFkqnjdHwuqKggvb8I5h88vZWA69/Fqn1ThfaiJH2TNO6KJMTFBcGZ+mMg+St0m4Tr9vG/nPgAf77Ge3LrdguaL2HPMLKmjvopjl8bB53Q0shqZeN/CxCfy4qiJMvS6Kh7001AYOnqwhrlrqVv5iVCcc708W8YE+o3qvk/40JT6wD67wPz3N0BGeswozBtoYE8uJzAbLrjRGO3YY1P/UE+HMxOwBwdZnRXPtub1/XMWk3UDRWQZq8gbyaEKkkV6ETW1HvP1VdZ/NI/lU1HG1cMy+s41sP0f9/6JgtF194nxy7j/TRXYenCPjrL+kq248/5sce0G6t4nZv8bOm63MFC3K/uZXLS/EH3iHnuP+citg4nQSAPd6V2D13BPydtXBjIbjZdQYoaBW8zddzt1wQ1mtUFVorBPkZG4WMakuZwxep51Uw0Sc3Pnc8yqjRR0pSeHfGJvLjVwjoy8mAz57pCCIsclNC/aEYVuyEi+pOM69Twf53XHib1C5asKevW2QGe+q0yGcrkRhqL9THx77I1IzsTpOSa6jDCwjyx0zPGQYDobOM3c4zRewSnqYRHOtdU+FQsKqUirqGHNFlEY009Cl3YyprOfK1gxN39gj75sLsx8TgZ2icKGGgZSXOgpHQ+I8S+2i1vGqnjBOjhZmG8em6gftU+491fGMup5z+UarK5ZcPr7eNG5+yFxFPVZGKFgdjR5m723KVnjXrDOzsxgvvVx+I+EB53JhCU03Piq4sBrstNQslZ/Ged+XxQKXeZjd3NPyeU59jnCuKkmCixhRu2o4Wat22Kwl4Ib7AEf6oxbFx2/apL7ZrLebVQMzKfjW38FAzdTe2IU3KN/LmVOt/MbKs56ZeAH81kwj3VqlY775PgxihX9mj2xnHVghqpKb29ax8Txgr74QCZ4kk0eOMU6NjXwzlrB1bJK3mtcHvHsW/r0FmadKuSqtQ1M2Pcinz3shT092E9kuMlPyVj0VufCKnptY944KCGdOt2AeecaNTluJvP7Fw0avX1qHRnuzPKB7IcNObl6YWIx+9eRfBZFrSu1nv3cjD3BNXrS5z90NLGSe/aS3HakkoYLxy0oMphZsM0+8ctrJ3y/JmPurFisdGWvUlu/FKYfrGXuHVser8db0L+YjGrUjXF/WMfp7O00Aw7jDGSUN/K8bT/1Z87nb8LU4wZ+1pZhfVNFhQ4GnrF3+9kr+PNEwh9yb/sLKpaz1xrTEwf/0bCCfLtHDaenq0inv9UM17AyUEYv7zIYzKx45w378Do9kFx3oBRZRw7FEpP8s0hDAD1x9QlqMrP0LubTI3voZ2SDzq7jBePgdzH3tTqdx02s0A+/6CXVZrMnZpAZZAMbHFVMW6djdbyJEp46MtrS894E4P4QFbWuh4EnwnjOQfNVsRjMrNY/VEZObQN6JwkZsgK3xcyc5CWrcBXvVRVrH3Fue1URrffriGM9XNo1R6XPtcWH21RoRdcKtx3Iw0t1HGyhof9U7nMqM+JRHc6vZHymxtZZqqHDLRW/pht41JjeSz5yXiMjntntXmcDNQbJeRzVdWqqMCS/jlKNFWx3kzB+k4lG80fAZL5o3UuH30cdizjbTXP1Z/1y4SY9qvAEC4oPnCksi6ZX11NQ3END2QsadmdGou3H/7z8V0Ny3CkDd5pbcGtCX/Q7KSOE2UxYbSLjr4Sa9QxkGaxRY+YnzmCMWxxs90oYs1fF6Xsauo9gfiGLPX7fGvEvuD9tFSQtkfClPjmRzOPsxvlkb9hRo0by76nbmcfO68hfh9nqhQmfYGrpKwkXf5IlyIWVzUH40ikOE3Za8LC7BMMvHEuWKni1i3rHObz4sAhWkSdbcHbH6ybOUBt7/OP1UddTqUXODwLhF2Sg9CADF+YpqEo9OzSfvW0dgk5nLXjHnB7ZOV1w5L6M7cKMyTpP4PVNGslMynXkE9jfW8nDX5hl0zSczfRGRWZ6PzJwtfnMHVc0dEsyMZ0c86xEfZQoYWBRFR17TBm21Kalr0MQ7GWicCL7hDMwYlIEKgwdgNcuFhz4KKPDKRV9ySMBkgmH8/TP2VzzfA2/Jobj/kYVYcEaKlOXKz35Lvhw3aPOyZhJJisVoWMfWewBr6/gNx3Nea3dJ+vYbWNArMa+Zv+WG6Ah/IWCB3U5C+T4cFlC77cSRk8x4cpzvG21WLzMzHLs+gJhwksFtapquHWonjiCuaT/LvL0ReYdawnd2A8jTQXdlImCksX8Rp4s0tKCSzUs6MgsGU5dWXuZHsKM69XAQFQ5euKDCHytqsO2m4KGG+8KNVLC4cZs4TnBDvHhMg6E6Bj72EtYvlHBbW9yVSsF3dPyo+0bCUs5b/OYPxqTeYof0ZHNXjNOk8cqyKjPDLLTnQwpaQh7Q36idy08KyOAWl6N/CXUssOKkyrGPVbwe2Q0igoeKMz82bCCguvjuffMHJ8cFaTZyejyXkXIPBlppSJQi3N/pLuGa3aFUbR/LELWahj1TcOlIBMrXsvYyEzgXNRAm5IWiMvoI1F6HnvVl3S0tTdhU1/HxsnM0I1XCrlMm4+63ebAQNiQc96766i7rYS4jBm9Lvdkj4Va6GDioU0+9M+nIGAY+WqwAt1Nx3orEymVVJS9FiN6/FTgdIDzUlqF+zQN57PImhU0TB1gYHY6uY9aaqHH/RikYDr7vV4BFU3G6DjEtcw+p8Kvlga7HtzLpyo+Uf9G94+GjX0U9kxQcb9GJIw+vH5r6uIOPpYeue/Ff+8BfE1UkBKrYmgfE6fIbG4FTOQI9FI/HY6rZfybyDq1WSBWiaevO8bi7HFmG2bdYlcH4leyjIH0rzKrDBydQr8pRr6nXnb8Y8Gb48yX+esg8baE5QNMLB+iYA1zeRKZv9dW7nlTE0Gcnc6zdAhDY6E3tuA6OXPYrXBhQhL1IEXC2VQVXssc8J6c7jSFvf5xrpD0twNq/+kGB641ttBkYf85De8lXlNNHcHROtLbThW+FDTgz/5rUCQKVekhO/vq+ExfzpgTLrjPCEbmRvrCIO4NPTFploZCa3W4f5FQqTePUVDDpNp63nsxPkV/iXRzIWgmcwV1uu+KcDycb0FT8kqAekus8SYGLzNjEMD9efBTQscqKiZs1DCzqIp5BzyF6muCRNc7sZjSm3ozjpqw2kBiZc7ykVlCg/4R+MZsVXVbFHbIkUidbMDmiQr9/hGh1EAFmRNZM2f23VEJ3wpHo32EisYP6Z/dDBjX6I9r9grZ1KSmfTgX17nv9I10bxlrJh8SG1hbkBEUizcX6BcNqJc7yLq1dDzW+LwAAz2Yy67asZcOxcBxTCnU5bqcs+hVjbvgK69PaygjiZkz2MfA/bLMrS8biV3acTb6qGgZKaNtQBlUOM8sUEFC9tU7YhA9e0umjBuv5wsz/UzMuDtbSKd2nL0ShJc9mVtyVHT5bUFNMs196zjYddcxjvP2aFJfDF5bCmvJRAEJGjqNfyi+/zgSX5mvbeKYUZnjI+Ii0eEM18F83W4ANTH3vTFy1dYzBhoz57ZsaeS9F/Eiog+05KK4xjzpQjboZSVjUHsZi8lW8eSNRtSNxFG8FnJa+0omSpO9jpNvVzLnXCui4xl/p2xvg2dnyd+TIxDQgjmliY5m7wzsyiHHcG/OrVYwn3t2kCyUSQ866q+jVpKCywpZ3I+Ma4nGBJuGsGOdbjpoSNQ1uB5VsTk4Go72ElYV5dz7x4gt6WGNyS7LT1M7fKivIxU8zTYwYauJiXxMg4IyLOVk9J9mYtNrHUN/s3/JdCHbZUjDRiE5R4f9MHr9Awmip4GizCZnuzMP35Rxq7mOD+sVHGJ9Xl+SMdjKQKnLw7HmpoaQdZHwT+4m1pxPffwThq5z41DtsIGhlwxcfBEhWPUm41Kf/xY2UHGnAtcsHT0bhSNuzzxh8MsY/C1lwcAgHUvPSlCpk3sLhKMXfSCj1TZxkjd9oPlfcRn39k4TMgV1pSJZuQpn/LzQGfvf6Nj7RkEfZv9p8dSKmXbiOHr08DgF707JWEtNmZ1A3Wqr4sdNHYvpJ8vHmAgOVmG3QYLvJtZoNXV/IPXsaQvBy0Ld6cl18znpPbm/zBmv7Q0U7hWF3pz5zczry0eYaMCsV35lKMZXJq9MMNAzJwrOF2Q4cW29Rhn4QP/x3WZgqq2Ek08HYR5zyrDZi4TWPO/A5gp86bML5rOW+ZhLHjqKW96dEH9V11Bpgwa15W0x2onnpG62X0uOaBWF98U3i2eXaHm+W04nM1G3zCvMmNyzifR/z1Iq3JgP0x6qONlQxUsyxGrO8ewHrMFIE3VaGRhbQkcBj0FYzWP0Z26QqKlhdyxYd4z8clTDs6gAnOH6Zn6VcfKxjqz1nB1mRZXcvN6DPdRfR5PxkYhkD5bpZiV+nVUU/xI/iO3I4vsjJBw/w32hB/3qxt4vrMM6WccMOwWg160wOWdcU06mgnNv+2LGLAus03WEM6fF8/yvjhiwjmPWYA/V4V5ecyRL57JHlowWZP+a9MrVgSasv0pIydCRdIJ8Su1buyQWH711vPot43IXA8tYz/P0vOmPVWTvVjCZObLtYgVf6CH6AhmPBu4WVjVZJZR7zPzci7nq7l/xVY8YnOKen5gfBg96Qqi9BZ79TXx30bD4jpb3vke3fzIu/A3FKupeGar33coGEu5GYnhdBS9vGtj0ld7JHB2zTUcCeSCUTOfM8/fnjNlPUzHgvs78M16s+FhDNDO5MUwjq4/Amrcaij8YjnbOwXBknq5YKkx8m0oPZG7TyGQbJ8XiV6t+kN1NbOikomKsjgG1lgi57yesrqyiqGlBFvt+5wYdqzi3v111HKeXJ9UPQHlnE31Z99rbZIwlLyULkVjAv53gTOxszH4gvxUkcw90V7GOOeYOWTk39847ruPTSHrdXu5XMc6fpKLeAnvRuk89RDiQXdINnOMMrWRu++AWiZYp1KXnLYUWmXvFE+QZ7y3UrxAD6EntmWqgiGKgF/vyyKO74n3ywUobFX/InZfJJG6cx2KRCs+j4YSLjN59dFxKeyyUc1GwlHNWkr45r4SJ7BgVr3fEoATnfu11DTbUiRu8tjA+JlVlzvvEnNdQwUYyQdxtA+Pyk3E6FRDV8uwBcoh2WcWJWwaut9PyXpvN3hWBg7uG4ecTD/i7sheYoWdSM91s6BlzFXS5qcAvuYI4e1wsKqxyxwwnFfMfSti/SUfZei2QOYfZgNoZoZnoxr5fzczaZzmzVLqE4dRX2w0qHnDms1x07Cd3pNaNQQT1fcN78m5FCyY9Z6b+raDHWDLBHl73WAO/yKojrAbApnJJrKbWPu3933vl0aU4b69WirmZ+XYRzmOgBT0cdfyYlQ8hLzXys44V7XRYPpDFqFU/V98UvWZKmE29X/NklpD7XtubeSra9FPR/ecWoUtXEx1rUKeoL0OZ/xNHDsdBzteroTrmJKm49yxTKEPe37RERgpzWf4HkXD0Iyu/7AbT1JC2ijrYzx6drmp447tRnGXHLM78H5+goG5HEy4XmWeo1fkSWVfymNU7+sxmFcLCbGF8lIL8XGvWPmbD0+FoQN9766xh+g8Lpq1UcdfawKhVMoI+SLALlbCGLNui/NC8+3yONYnDrMEazi3T8HGih7h+AzNoZQVPmIsjF5hIvKrjLnNm4b4GXDeWx5EMCcWGPhDTBQV/dmvY8uOp+JMsdm6WjBpfdXwra+IZ5+bdiqJoXE5CAX8NfjUUrB1CZi+pIUoqhr1L2sIveqW4cAXzdkYU3lYuAP0zPYDzaZvPRDp5ZQ0Z4EcH6txfFQkPDQwvE4XIGeRH7tEI/nw8kDl8iwwfzkYSNf7eMDLAk8Govc4ZAvun95Fn4n3u9d/vnONP5cXzC6jrzB8TLnF+eytYx2ueR1bsPNdTsKafH6bGTJ7YBzOvNsbVbA22x+MEibNzoEZbsdauzWIzD+ZGPi+3Nqc4B0XooT/J2dsn1sepCiaSqbM9g1Q8Xc8ZddPopQY+TtDRmKw78pcGd7JKwbsWjDdUzCysYQpMrC5NXfmg4nxPE7fOcP8LMEeTnYpsJsMkylgSaSCZszKCs/bsGZmYe9n3chj2v5KxunwYbDmTPe8xXz6wxqxR0QgNYv5eqeMR6/TrZIpY5HE0vtBn7DdMENfeYJ66p2JvuIRmzPahbQzsvFoJu19G45I9Z426XdVWg8dB5uv2CmyP0cv3G3Bnbr3yyIKSo01MSzGBoFBcryFDDo7CznL0lbLVMbsdPZr82XTHYcHNgVlwlgp1RHd8Zf/OeaQjhpnx9LwQHF1jotIOEycKqWgWwszbz8A+Zonfh+jZe1RhlUBf8CcvvqY+RgaLG+nJM2PShNdpkTg9SkXv6QqSVfLPIAMz6GVj6qgoneEhVl+jI5H1iWafl5mtYPExCdfaM/+N3y6khPExQ7rh4nFmzFMaph3ScbleHGpUlGEzW4NTQQWtn5Eb1so4VV1GY2psJ2poXQdqk2cYahUkV65hDpunI2rWf++PfN5li6tTVPx0YO7q4ogN9dgPrtai/4twTB/PTM7H92EmKH2CfJh7v9sXzkrmAuGnuUhIeEXf+j5WcGNmKsva+JFZF5U20eEcmX8hcyQ1Z+Yiclc9AwumBKP6EYgOxTPFgNeqkOgRgmnsvUsz/nu94f6nMbgWruH1M5m8auA8mfJeCxl2qRJu8NhZZJxD+3RUPUYeOm2g/DIDwnsdNSwzhNXUpWMD/HH+loJpu3itZVTsaKnDdhcfe+aM6LIsCu1Peop72I9jm6wTDsTTf+7qaM7M8fuyBpcROtx0HaXfKpBLhSPbU4dvexXekxUIt9W811ImMGecPFhM/H5EQ+X3T8TlO2KxiDXf1dtEvRGxeMx53LeW+cyTvUb+LkOu6Nac3lkpGm7kjb8lo9GyjonCmRqGj6Df7GXOIQPUVMjjixQ405c3xv1339Zv5sbpqRp6lTgoPHNiXd/q6NFQR5er7P9azAPUuINNY3A9jb8nZ++pRl92kdCqgpr3OsLEZgnCO0swDtLLP8UY2DBaxs9bWeKip74Y56qhOj2sou9fMWtdLdTcoeHmZj7mtYKmJWQ8XByOy2SXj3Y6HjTTsb7LE3H+KwX77luw9ge1dzIzl6HBiOP8cr4G3aEn2Ouofr0eOtJLwzjfbQ4z11BjG7MXnp2Ixu3TMgLp59rAw+LxWQq+tmA+oY6mFDGxcZeBzOcKZv6hhjGXZDKrOnIv5pyk1m40sNtGQbdZ9PmUEFT8bmBgCWaXwAzBSmBuHa1j681YdFymQ3lDDthLzZ5h4Co94xKzdqMUDU90CVG5r204Zojr2c8NyDURxwZji6MdFhwmC5Kn/SuSbUI0mKHMTG24FrLf+OMThWseJUTfaA1XqM+en+jNQTJmpfIc7pGoMNDAj98aXnFePjHf7af/KQNlaI7/3SvWu66JZocUXKN2tp4qY3qijo/suR5fVPTnGn9Tv8qzbusk5mIrFXH8uYIooXgFDY/torCgmQFLkAV6Qw1Duaat0bHY+07BrObNxNzXLRqxbqPpE07lTHi3U3HjgYEj7BPvXxIq3oqEa18TZZz+y2L55kTBi1l5MOd3R10LxrStDP+rBjr203GgLXNTFRllvlI/1gWjDHt0E/l5YGwABmzU8HYM/YsZvURJCTWYg52q0b/vG/D4OBzTwk14dc1lbPoCGfjiNepjdeb4wibGTZfRj3l49fZgZNKD6pPjcl/b7ntBwULmvXX01pPklTK1yIsXdLgeboYryWQ0zs1c5l+BucanUCyie0XDqvtnQWDt5zc04ORXAilkqdaCmnffhv8ZGUkXqF8eU8VbJwy83MEeyY4WvLfryLGw9vtkHKW/FQjUsOgTs/1LFa3Pc095DcuoIb45Sp5HRbGWrRJZAzf6kBdZraOGZWRBh9x7CAQT9hfY+w9UNJ2poeUhCdPKGtjWQIcV8+B+ZvpS1N4V38hoqxR4sw9fteb6Kql594vujsy9n8rAfa7LYQlZbmoTnIun3yeEwTdJR8Ni5fEjZAw2HbFgLPtgOj2hVYqBaoeWCvW7GbjZMUksRc3rqFtwpb2E9qU1dHm8Xnzt0AldOWd9XQx0yWRmI1e36WSiT+10MegW55oZsgFz/Wlyxz0/A2uTu2ENc0iNvpGoPcWCHcU1nCQ/FaKGRedoiB0voI2RKOS+h1jSsQPus6dHPJQRflDCtk72mDJbhdVpCZOoPxW3GKjft47oPYZ5oQ6ZYIGB4E0ylEbdcJ48oFKLNz5SsPpsBPry8a+WGGhbvqA4oS8566SMN2TS2215nEsGijFTTObxXOoxu3xWUG36ABy8a2AH+6P3v/YIttNwm704romKTYqCK0sk9G/nhff9Naxv9UccF6hCjhOE8+8VzGNGejQhFpUajEbkP+ratsXCx9Maim32xVkeT2N2dGYvv3A3sIv5evDF6LzcKY/k2nyicOLuL+HpbhWtWjJLcn8/ddDwsKmBdvS6SLLaG8nE1vU+eUz9d3YUJtZgrutkoDK5eHEx+gV9L7a2hObk47t/qeFTJLjfjaW2GbhBtv3C3PRhlIx/BU2c6creGWEgaSszjb+E+Tcsee8TdmS/dVk3UXSYQj+nl+/6IuOLYaB22EGxiYXzN1fGhnVfxXVuOoav1vGEnpDdh553xsRF5tO1ZClvPm5Z5S74Vz4OYy5Z8rT4byMToxpT/9lTe5mLHpWkt1vFYLyioWuyggMxZTHd38S5y5HwO8dMzdx9h3OYPcyCuAzuU6EwFMomPzBzDPukoPJWCa92dRFdUovBztrEAF/O5HYZAY91iMzX4nYN14LIELnvd90lq/G8/b/Hohv545Cs4RE1a/9cFS7NDQQNo4a9bCGeOC8jcxY5Q1ojnmY/t1BleB3XMOwj1xnGYzNzHm2uIZnXED5Pgz2fm9pUQdHiJnbeCoP7agsuncq9B8GCFD43nnymTn0hfNgbhGuXW+GHr4nqQ+PEcmExSFunI5D+nhYdgxk5zH6PTXQeRK6jnlZLIZNEUkNdTCQUZpbiXubeC/XM2Cwu5e9SydlTdkbhGPXbWYzBrxpxiGwr4WN96sc6FSdb6OjkzuvsRF/8pWMMj9GdGWEu2aPtJ86xSIaj98/dIuH1uxh0PUHvpg9sOkRe8v8gnugwSYhrzDm6yV6nbtVZEYPw7ibOU7drazr2jR4sXPPjOVzoF4sNnOLzD5ODrxTV0PS7FwpYWOPcfDNcQ4QUjoBpdmL0oKni0dWdMOg9e7KViXsamYUeKZCFq34OwVNq7ChmpQR3C7zOqzCZK9IGK1gfo2BIMr2C2dplgokNHaxxnFn0zvdIfD5rwN9hGCBkCZPK6Hmv4TUqTsYng+9cRj2vqOGDbTgmp0SgyEQdldh3cxyjoPZhbZg12i+SUa2MBTnMPX+3sO7VvonX90moP1TBqlPk2xwdizmPJhnw4bQpQpKqIob171GbPVif2fYAOWW4gb+HFdR7T82gr/z5aGBusITlR6i5E+izG+pAd1XgwRnIOWqiF3UmqImCGk5c2xb28fxYVLRtIUxnXVM5R3bj4+D5j2xMLiqUqWOXHIULxmgU9VKppRJ8qMEzqXeZl6nN/cjqPVzEsGwdV96rWDrSxG4ecxzzZpH7zLuIxsZwAynBZCnO+8RSJn4xn83g3EvZUYgppmFGDx1xT1Vyr4bsExoWezKjfmMeGRSONGbzY8wUTZz/e63Sa9NswYb9FVZHR98GGsa8oA/9CsDQHgoC55CpupkwmXPLJ5I9ySiVZ6powTqs7H1CWLL0vxls0Zt+90fB63n8V0vCmZF6nh7M3c/rzUcWZt/m3qN55hEzoUXFni86qnDtH6gH1c4xZ3spuMXZrEdPvP+XuY9ZOfuKjp70gieShhstqS8dJQQNkbGc2XrXPBPdy7PffqsIr2FiJmu13N9biOfjIyfdFR3+NBNTfHQ4ddOw7ZqEfEcdRZ877Dmyfm4GW0Hu73CD3BWo4+J2E5EdOKcvJSyhV1+NJp/0Xyt23c5rddAw518odp7bJOTE6LCO1HE/08C5Xjq20JufXo/Iy95p7PfKoo6QajIqrLEgPT4S58mzOdfJZqaCB9zHwC70+1AL5jATNGlhoivZ7VLvMFwiF9ScT325T0+lL4QxI/uEcta2afjOjDnkmYqaZMm0qq1EV2a0oIXUBxcdpxczs3fOFlM8fLCA3pB7z8F0ZsOZL3W0mj0KOfVi8aaPjsx91LPF5IyxBors19E0TEdYOv1qjIqqa2Sse+2PgvQtidlkBz2764W/4sZ0Le+e7sLVeY7uKjw6c48L6YhQdKx+r+VxyZd2En4wL736sl8s8EnGdoWcfW+zUIis3oFZPfeeNauSGsIKqKhfOxQlX70Q0q4YOJ1aBqWK8/kjFbxcoaB2fR39J9IL6mpozl5oQyazIRM1JmMV2qnj/HgVT5tTT3dzrp63FGOoJy/vMdNNUlCJmewp93n/wjBq7CaxArnA86aOVWXGC/P8rVCI+dGF2fhTtVicfajiws9YPBugI5wz34y+vb8u15fO/LDvk3BtqIqezMMpbdhb/H10PnJ4Iuegr4JXT5jtRiiYdFbB/rhnYiZzuj+1wflcAdGT2cr7lYzC7en/rPH5K+E43WWTkMTr/ztZgkFm8HA18SHdE/voTUfHqpjwWYMzM9v8DpF4+lhBryUa5lbQoX6MwacRMuLI3e2WRWLj9J/i76PUIbJeC2rA0PycWdZzvyKjdo0opN5kPmZv3QpSkPEvAk4JKkZc94V9s2gso9+82d0Pu2wKwfNuOK6nuuH2C+aWTRZ8mqFjGDOe11cJF2zIG1+TxWOzdaTTXysPVODXXsM+7k+hvqx9SQOfd94QHryKgTfzvjs5N6sDGfCkglTy0wrmyNL2Cuq3jkT9S9HIHBgLecQsoR61YpxQWfwn9RDPRqv4vD0W+xvSb6lNZ6krPbxV1KrmiIWbqFfPQnDHxh4hLyIRsFHJu78y8zn3KLEY4jmjHfi8QJM9uUzEnHwqZo1VcLO2RQihfzwqaaJjYxVHqJ9B1TVhU6iEQ8vUPC/xzZFQdMMxsRV1IuWLgirMe0XvxWIw+fLWHxO71qsQ3lGLDpF/6D/9Sr0S256hB5JJDizT4PtPx5A1zMtDo9BkINlhoYrtnJ1ahVUcX8qaOxVDVpqBRzX+iEn01C4/dMh6CJw4n6uWsV/tTBR9JcGK+rcyw4L6i0Py7hNIqWKiCjPdFfrxrt0WZDN7HDyiwoa9/PsY18I85z+a/DtYxc1HMuQh/NmfegVmy7Em3BsZEHxl3GIe6STE4ercGMidItFdUvGCa/rEWc7N++uuaHg+mbPJNfvm5ghXCdo/CxbuNZFcdTTukoPfUlsncH47HlFwvoKCUvb0K2aFQe4SmqynZ5JXN9PHSkyfKyjML73z0Y9TdDzm7Ca4HxOb3hqdl2EiLmqodo1M/muWOI5/e8QM1q6WjtfBS4UfEmfkuY5eicxOvD67ISasPsgoxXVNC26CH9SyWZ91TAhSMZQcPIxs/yOXkfakiQ6stXtvBfnaNEKhrRouexiwJWelH2QWLUnP3UNNdjQxcQl5tJ2JiGj6oq3BHqfuhZ4QLtZm9ii2Xpz0gdmrAD1hQCSK8dp6QYEn2e3zJhWD/hwXV5MtllsrmH1XQ/7tn8UWYfRyaumdZiqWFTPwdoqMfeQ176KlhSHs+eQXAxDD3FacGXTTSgX95zKPftdRsAaPy95+dUpCUhI1kVrf4DO1gRm3NPOl68+GcKM/PjnRA89+G5iU2BspWeSMawp2029K/FPR3W0YFk1UcdWV18yMePeiCyJX0c9/SFjBfshJk/Pu0zrTT4Vt6eGwbSXl3ffsuigYYSl7BQdr9sxCC9of2yEuY05tasWeMw0cLyPhYQB7tCe5aHosYlSu47iER71iMfWVjrotNJwhv05sESiUJ6dFONcXHzUz897bqtvnl1Bxjw/cbsio117F65cWHFmpYs0m9gz5ok1XCW4TyWDeFnSL03EuVMWMvwq6MMtcYOadcikGLm1liJVMyNTAOQn09XXMd7VG4KtDEHZQh9tyPd2om9s9Zol/XnAWyGTZogw3ev9PMmACr6kzuc2jhQxrz5ZCInlpI+sSTa8NzFTQhiyV3p2cdbkvckY5oGp5HV+pL7nv69U6ulBwiDDQPVZFoXQ5777DN2fYw280HouzQm1oHhCEv6tMNOK85t6r1C5EwpSmjcXEWBklP6qwZl47yVx3YICBUHpFdDjXSB66xhns6BCBIXMVzKE/1r2l498sOU/fP3Omp1b97/6fBXcV1PqoYMFkag05cFKQjuhHat77MO2v60jwIX/eUHB9Riyi24Rgid8YcUwlDXuY39X6FXGUGdbBgUzAPJRGRqrbW0b+Cxru8bwbYg0s68F9rRSMQotM2CxS8HirgonHcj/XNhRv6N8NJyr43dUGSw8YmHFZwQruX6dIMsrX7oh/yePwPAb5/v0zDWbpehi4fTgOlR0hXPY0MZxev86Vvi1Q/zdo6N9CxajZFmQOpVYwU4oPIeic46MfPHEghPm7pI5ti2WktYjEJoM17mOgFvnw4GYNS5m3H/5QYMX8ETpWQ04IMyq1ZXfWPbEic5nLpaC8e8d9qNthbvSuOWQy6vIXMpJr7r3yK0yk31QRcpR1uUYd9dVR8qCW9374L/ZDEjU9sOQwsTlzq/gnGtNZt+SBN8Vy55pD434NIZO2OBmI5tfIf18D8ffJf5/ptPlFP2QO9X9Fvy2iYpsgo1OYluf9j+OpnZz/Q+TnVlXZgxvIvmWoxR0Xiot6cLZFfzTkrJ1hzZeVDcOpIa3RangJsXIpGf7LOqCOk4aELk3wgkw+6oWMKd0NBFDvDqzvINbn7xxzvHDgFzVoqoSARjJs42XYdZPRN93AxGYKqrF2Yd7sZ87Pm6FkzcoGbtUzEd9Pwxay/7hBDbD1kI5GzLD5mJVCWufen6Vicj3OFfljfScf+HGvx5LxajXrhOJ2BgpSi88xU2yk7y9gBnI1qNs7WFfmnd30qOlRCka9lVG+ETXpINmltYEBK7ui0edLorN9ADqxzx+fpS59UbGZWew4dTjmpYKSPSXsaMBrXl1PXMIcsnYT8ypn8zTnx3ZXRyGoX20xaaSr+J69b/VGRcUAA/Z1yfDU3pdXo9Btgo4NjlwHc/3HDF6jzN6mf4+M0nD6PPWdOeIxGcqb57tfWEN9anVj5tjnb6kd34dBcWONmeOvXuwpajNlRB+NwMHoUfBrq+d97iqFc5Z779ViMknbbjrmZBh42TUEIWTDVM7raPLc5CkGjjH79YrV0Cl3NugnwbdUXN6wQUjiubd8U7F1OtdvMk+ckJDjykz5gTmF3GS6Mds+lfCObJh7n2fv1Rq+ptBPmBEPk0+vUfvuk5MC6C8NWNsa4lqxJH13v7UB9xKZolCMfW7IeZ/XaMh5c2/kiVpkPJ8NOm7RZyY55t5bTt3ZHIPX/L8RZ0HVURpakT9KbZPxLH2BkK9GBLy2RqJHHVVwa6HA0Z45gwyypewmoeJXDUN4HU2Hq7g0jazFbFKROe7oJ+bjnQoODQnBsTfUlmAFUUPnie6tFfwkZ7pmS7AjU8SLJlql/hJ7jGF93vnCi4x4h3MhnjfyPudZgXPRb7GJLrl6cX6lsHe+hsipChZHUJu5L9UKsWfIUmfIgaE/NVQYIeXdk7+rJ/s4SUYTPsa2qgyvFwres+dspxqo4pJ7X4aG9X3IDRdUvKnKnBrHeaSG/f14XIylt8jcv+hDqUKrBzouXKIW69Q+1vBlb66TnBb6E2INe9aT3HzuOvfw3UC0G6dCXW4g32oFy0N0zGunIpXrfGmIOOXBPozRUGaqBrmigjPM77vMYqIlv4HZ3+W871w4xb4zpplot1pF8eKl8Ze58vtECX99JCRX0RDT3sScAqEYx3qXPPRJXDxYx/M53ihJlkmswRn8YeBVUxMu4yVUKEHmdZZwlayRRo09dVLCwEV8HnN5sz28TnrZ/Unch8IG+jzmOjZQT8srmHqJvZit4Be1uCUzr/imrBhKvoltQp5nBst9H2x5poYv5V6LH3dxpnaQpRUF5bvqyFrsj1M9RiM/NXrvcupwvUiMmdo77zNJe/txZm8Z2F/THxtva3jFeruzJq/ofeVr6NhZQMMflR5ALxvTwVNYucWCJOr4u99RmPJDQ5MvXEd5A+nk//BDBtYOoWdQ41q8JVOFUTuvahjrMUB8xX0KbKnhPDUnq60FZagDl8liAzarcGJ+iu+xRpx5NCzv/bdDvJ6TFxXUZK/pN26I1xulCv59VGT4Ua/IdwWXvhTKztwoSqxLdWb4Z3z+PZ77ODX+4jL2HrPWtnAdbZl/blNP7/CYT5+TP7fl3ret5N1vNTKZMz9UgcdZHT+HMMd2Zj+TxaY/9IJLOQ31kk2cK+OAab1UKKMcxKx1BmJfkuGSLHhDNh4raUgv+kFo3TQIF85rONaGHL3HQKX65I1qJppumSEEb5Iw8hU1kr2cnN+E75Mo1Lyl5X1PRNnvGg7UDsam8fQDZt2eXNtOFwP5AzS0Za66PEjBiDEKPp01cN9PwtkNAQhureNz3T9ChWQVxZYrCJgj46JVXdEukM9tzbrT1xr4jMBu5gYnMu1Vd86shwmvHBmp42JQhTnqwmsZ4Tp5oIGMia10XKF2eZErxq86IOa+F21dioy0oTC8nnL2qFsJXU1UsDWx5l4o5m6jPzeRcZy9mM7ZO+FBjrH6KDZmHe3Jqpd8FPxR2uLx/D1C7vlWzO8DceFY4QoZdMk2CavIGAUaa5hKzbzJzL8u8pSQwyyYUZ/XP1fDfscwZF6XMbdbX8SvNRCzV8Em9p/2RUdZ9vJGf2YistXIJzH4t9hAZc7MoPSayO9kYA459N71YDgn0JsGyCjxTsaDGAnrqVMJtrzesjHYeLwxCt/RYbWGOkEua7bTQP3+GvSjEsZGK5A/MHN8lnDELIYm6/YLV5mFx/Cxm4srSGR2zv3uicDrKs7u47ywb5Osf4lOthpS+uRHFNne80V/POTxPtlGILOOjIqeat49FfP7KHiiyjjMPnOzMfHFy0QItXaLnQoH5juX7yp2PGRNekbADKEGcS8/j9Jx+jtz+lINjexlnGyk4OzyxgipJGMp/Ss0QEV83V3i2r4GFtC3Bi6NxZYFzMzUDVfmoVkzlTz9ff+enGBvYv9ODY17MCd8aI6yDjFoq8TgblPqDLNHsd3bhKe3/fC3ShgyOCtP6lHz4mQ0uiljc5aCjj9U+rEGu30RaFuZfpCi4cfdcLyhTiwvq2NlKxWl/R4LAZztEcMMNCOLbZ2h4lBfE2O26CgWsVgY9sGCMc0VdK3EDEV9yn0fJqCmjjP0hrH0YHfyyeZ6zGVkXkvECSGpvoxezMe59yc7FLKg72k+jrn41FgJm3qbKM2M7flMQZbPEDh0jUYLau7kWavEEp15vZd1bH+RXzRy73U+ymxMTz3P47TaJaMxc2OH3dRn1qSfOZyPUzE8gnMfYKIJ/alyNxX9ypmYcoH6G6dgK9mj0a1Q+l009WScMIQa0WO3Aifm167Ur0tXqdnDdbQ5LSOYczIuS8PwUQaeXtJQOpLzN622eJ16VJZ+9eulyjygYSW9v3wVBRfIbnv8SiOOGrnNT8Uxty6YXcWS9zm5QqkDMJk8PWCRip1bmSXq0fe+hmF3gIKq0RKu24zE0k0yPM9ZYBMr4QvreWywjHPUnvabmKl6Kug3XMF+asR79tSafuzZMxJmjvnvvesy9wz09jFx5KsF445Sy7qEwZ++v7wBeduT+0PvXH9FRyZzYe5nE7vMWCRGXzwiBsUqmJRg4sQ7MjRns3wq+5rH6Zn7+fo5Jg78ZS+zHwLZg9aX+okZArnxLGefmewhZ9F3sIbW9K8TooFyG/sLq/j3bM7ukmsmnjPXlV4wUpzewEQP+tr6gdSIA7vFzvTncjMU5CNHPua1PeHebB1rkDcV9MxHhq+uYKyfgtX0WfvPzK3vw1DwvYLzJfgYZoWMvmPFLuyVitTw8bmvLbWTYWmnYyKYHU7pcN/E/k4y0d+amaqkjIApJhyYbWyYh349j8bU0VGYnXldzP38kuSk5N03evt6GKakqohKNvCOPVewagFce6zhpGqIN6lBTetaUCTYxErmpfmfZHqQJ7xaSmhExvZKsSBxmkEu8UeRw/SiUg+FkBjOIVmq/0EFtjVVvLLW4MO53r7bxFD26E3m+aF2JvK/0PC2roaSv3oJfxdPFPqX0XAlysCkIrZ4QK5pxjVVXSahfw2y9Ss+j738JZJ+PtxEoqhhQrdwJO41mCEMNB2p4eEU7ldVBYGfdZx6zoy655bQ5p+Md2t17DthgyivUeiW+7lB/zB0bcOctK4/dsfTLzNNLPxL3myl5N2DmKMMy/tc77YPzPeTyfvMcx/mNhQdRqlYWEnFSXqMGlkTWSElxZ3kvh/9mUtdS+FrOvt9RRQe3ddQ45eC6WTYSGrPTf6/2ZNR8P1JNnhjoE1lzg3ZwnX8AXEwc2EaefRSZWaXMRJec94SqpMrmHWellUR8FBFyXsagn+wDswXD11jUWSWikglW5DfKkghL25h366mJrciz8QvKCruZF0e7ZXw8Us5sc5dCd1Z8zLsjfPbVfRizrahblgffi86X7Dgfe598Jy37yV4jlk6fHm8cc9j0ZIanjaMjF5ZRVwTzuywGAxnjVaO0BBosp7Fa8GOPZR7D+4P8lDuPbYNWbNjlUZjmyGhDnnrVS0F9WIjhJnddZThXPY4pKHjbeqqJGFcVQk9mG8cuceLN2rwXW1g435m2gEmBmkGotjTDRb4w+Gbhk1N6NXMlpcyY3GgDZm/toK49ToGkP01+v8J1mjpExXWxwx0yc3wNzif62UcYf99bDEGU4paIAe7YuhHFUWpj2fI5E4FmGPorTbM8/dPGJg7gpmRebPUWB2uL/oh+VgZiGnkf2q1tpjM3uekYEbTQ5OVvM8s/GrzXFi0X4VjBQ03E3tDLxuJ+ba7hZ8zNSwebKLSZBkd6CH3fMPxYaOBhkVYM+bchm+i8CT3M+urdSRW40zSJ4aQU5vzWO5kALuJKqJPqrg38b/vHsj93rVKj2R8o0ZMYc/kqAqUpCCc4zy0XcmMd1RHh+kGbtuuEo/PuiYeu9UYAzPMPI/NzZTzInTYkcX88hn4xlnIptbXHkp/aj0K0jgJx+qY7DHmzD5kllQFBarTWxrp2O15S/SuGIuEjmG4Ui0YnUOC8fqdiqrdDfQiD+feO1P7tYpF5LDzVgou349C7U/h8PkxEO7kue/Mhrnfj/AhxYBHfQ0vSlALEiSs7X1f/Me8nvtdZFIGcw9rc7G5nvcdVofdDHQLMlCdPp/+2sBgnqMM+dzDwUDRiY1RiJ7/s1IU9lL7avEcR+ldyi0ZvnxOWlUd46iZbx5EYgm5plgosx3Ze2xPDfOW10Fr+lLDr7z+cfTh1SayhZ7YFe8r+n+z5HnuiH06vA6oed97sWW4hhKckbUXybzMOb0TNVylbzj/IjtmUYdLmfjakRmcmv5vCBlsPvnuaCw6TjVRkXO2s1+8aM815L5mUTSXxcPbirtux6KDpmHaIAMYpKI687XLIeYFy05xEes/nHO242IpLO40VzjL9a4tK+OeiwSbSSXEBtRogfkqkrmkyW8NL/9I6OjLGtIXmnuNF2swD5Zk/9/6qKFwj1CMri/hGvXz7JX/7gPosIK1pGZNWRKIPsUMrDgzBG/InM7eGmK7qNhFTbe3jcHZSzKeb42F9RkfuDGbJkymZz9ugaw0E/ZyLIrzGs4wi32/Ro3y1HCE/OoQreHzN/IFM0lOe/LCilTRgdz7sKaGXuzv3O9FC9suIzGfhrk7LbgaEJ33vTH3apjIIG8+ahOKsY1HodJ0GQ7PDKxjXsi3i/xPHSjvKONRD/LjbQMrI+rigL+MtvSTVeSO7VVkbCmk4au/Bol+fYC+up/5e+gVCc01ssRUHT3e6AgIoz5Rj94PiYX3fvoteSVGVtEoiFzCLJz7GeWbvLZO69S8z10vt/JB4pKmGE1WbEw2Fa3aigrnr6tvb5Tlc2t/1uCZT0ct7uEx9n/HG1uFnHE6pjJjVqSOHeWaylFnxv9WILry7wuNvO+/8x6+XtTKWfAup0/ed8vlfhfgpxbk+uxYuJ08Jn4oqsGpswbvA2bea21ShILQyGCEkD+No0XE3O8xHN1QxbRVEpbQe5JLtcOFcNaihI7DnO3F33UoR/yF6eTJDAcThb0MdOQarodZsJFaIRSvgPzMofeG8HgDuO+FdAzpYObdExKYzf7NcMCTcSNxU5ZQoK2KKeSKkpzBEz+D8TyFfF64DXI/H+hTNVpYyLzjSHZ5sDoGGZMs+DFZEOZDxgsye591GoSrnOVO1OKCBnwPyMiixr3Jp+ArmeR/JJ11WBVbG8Xt7hYLxUCxO5hZ2B1Y2CCCCtJwzvRgYbeILXZ3Y4uK3V6xsLu7xbtm/ON77vcocubs/b5r/dbM7L1DOygoVV7HE3rOLj8Tqd7U9ZmFEEF/OF+N2lQqFN70yIPMSMWs+8jUzVYlTNw8EY1th8knEeyNA9OE+QtU+JCpO26SoLB+j43OLY4soCB7qo7WT3V7D8AGA9nH1LWBWTgmHjrKl9JwO6+Kytl0POC1uLQKF69RUxclaJgeZuBTbfZ3QktxjKeJMwEGioYpSKrOOhFqYQM9OnszdwSefyle8mc/rmSfz6VOU1O+vtIw7Ugkrh1V4UaG+hlHbV5Cf5m2VrwkkD+YX+7RY+Z69UQs/cvLNRLH2TsjJ5C7kw1c7azjSHcTN2rwuutSN8/Ty6gP1l6feUwT3g8V+z5b7OADYu0TCmreljB4G+uBc5xChm3C3NWO2n67XRAGHWdeP65ixpJY1OV1NhhNJhllYnmyApXMlHE5c4prd8GDOT/ZVUfpufzMJyZq8rvuyeIpWM9GdlNnNfaze95pwss/Omak6DjAeWh8+t8eTq2Zxa0at/brqi9SA8j0XX/JGHZYR9XfOkqUiEHgnn/rT260NOw1/DPZMyk+0fD5JOHrWSfSZkq40y0Gm7ycaOPkXBTqY6+NzsmcN1UpI9Yj45b9beA6dJxyk/GZ2lOluYEF3vwO6T6CGqWhwAUZSj0TC4ZoSKIGhFOHzjGf3uI1RBxgnqmgwNPNiQWJSWIh92gY05w4OUpF6n9OJDDHH4tT8KGlir3PDVRx0THmLfPzi8YQL1EHd5PPiirIlWsIwosZ2BcZjXL3JRTZaaDWJ2qvO7PdSBmXBij2M8ltq4+IDpksTG7pbfkYf+cTzvGyOBnbqctXeipYyox6o6OBZszDK4zRwp4WOtqQ8Xt/ceAhdTIbx/nkRvIYTJR1avbz3QnddTxMrYAPczS49mfGSpUhLmL/cfxrxJLRh/shm7VmrtBi4Ryz7dcjb0TXoG3iEEFCvsGsn5D54voFzGQhKhJ7UHd5vacW8nfTKzdzrF7kldGCecxl212x/HQZWaYbkNlnY4vGC81PqVj8Y7Gw/aiMtqNlFFwbYb+HVJxje/4sPbiCgZv03g6s8fjwS2LkQhXDmVEecAxWFlFQ5KcTSZF+yExvtRhhE3UhhNfyuizr5oRu3xMG9a0w/866T7bxPse7Ar8D+69tNhN/GpCb2ffKbea8+tEY+V7G3i0nxY8bnfYz8UtkzpYdyLTDFEylhpWaqSLjGg2TWZPVrkRj3E8V0+pqmFHwoRBfkxmPmaMGuepoO+aemFfipi706DIxNud184jB/g/U0NX87L1OLKV2HgqQ7fdkG0WkitlymUhgD0Rd747y5Kl9SRybdU6cmDtdGLBYxrlJvvhjvaPkauLKRx2f9+lYOGy78N88+mNjFR81Fa9c2Zf8t2dfRuNxQRWZyRk9K0WJH8qp5Bgdwc0klKcX9q8ShA/ZVVh7dA0ey6yeW8WFVTIedtTtPUVyHmqH5XmYtSpXwWCywfO/OmavboTs3joy7dbxzk1HsVUqBr/W7DwcX5m13S9NvAkVOUYpyLCL1xCqIIz6Op3a0ZZ5evbAoSirhqEQaysnGfTJJoM9RH0bp2ECs+qQWM5HLWbrHeRaatAVem+RmitF656utfal3h3mnWP05K2lES0eEFe7aChXxEDi9cXiW3rTDWufiFsqZk8BxrHOO7xohh19i4h6JhVnPJyYzTrfUcWw12wkkxtaVWKf3dNwZq6MWuwZ12UmwtcbSCgVgjPkjyU9Q+z31iLCDdx1OJGNNXKCXnjrFP8b4MRKak5GjvXTP9T1/3zhPytWfGrtd9pJRnkyy9ol5wVrb7PcyTLKTtHtZ8SlL1LfzpEDBrM+3cjwa8n5Y1jri0uI+7LFoESgjo5ngZUcx5jbZJOZ9LGT4fhIzqpPH/AbYWIKmW74KdaJh4l2Q1SMIN86Z0fY98CcJvltKvvuioZixaLRqEwjHGUmG9/R2ktIsX9ngaRLYst69K2tGn7VVzDigAmDjHOyz2Zh6WAFB9OiMaaNiqX0marMT70f60jIxx6qrWPj9ijU57zf7BwIz/OmfY9pFTl5+4LX4tZGJurx76qVMzBHouaTeybWD0Ifev3W4hrMihqG+OnYwKxVhLxS47EDfZ6wd8mlxoxy4uLJTtsfP/yQ7fcisiZFoJiPjoCuZII8JpIGyQhlrikSpKObwV67buCkQS55FW3fj69K3S4wphY+Z2RNbVaxlv2Y6tDw5YmM1e4aTpfW8bqljnw7dXiw/jZnlNBY1tB5aRch3cFMwgxp7VVQdWYAqn4h328MxOyHJ8TQVfw9zCM3fxkYnEJPY44eMc/EuevV8JTjnEAv/NtHR8YOzJNXZEQ2VfFfghMDn0Rj0BSOO/s1iF4z9swwYT5zbLpqojx1z5s/n8S8lubxTEgl04X7ZMLKhE/id9ZO7+UhUFj/fyPChAajFfS+LNn3DtoFaRi/xLD3pfDo/lRcwrkbvYM/zyxmPYsdy7xSpLETRiiZZIkTTcmBxen53UJ0lKOGuQWXxTOFjMn+OE7dWkGeepV7iDD+kIJHL+jVScwzpU0U2uNEw6Yaah5w4kAtHVcNP2wraeCCewn7GUSLWQqucmzXfdGRuES337Gy1nYuez8Y06ndew+qWPOWOfpqadwe6I+KNU34k3fuztTsvTsODZUg87rP7pGwimw7sjN5hnluMnvy3J3hwu0XvI6qKj7xf7c2SMheJhThaQZyjtCRP0bBg3usuZoaGjH7TXJhHdBzOrGHT1Fb9rRRsIi+u+ZUDPwqmgggj5XrI6NkZxOdGieLx9iP+cglQWnME7cyY0Q+GT6zdNRfp+Leyn/roKdEinhKPS4aoGA1NW/RWRkma+VNubyoxd6d/8yAC/Uxrg4zyNce+BLcTQh0WS/mK3hPWHBaxSH6XDQzXasIDc59CrlAQ2MvXi+zUKPZ7IVhvNbqJh5pHfAwnppJNlzNmpzlqeHjbQMLn0qotKodBviSvV01XHfrDCmMvlaxn1DynIFDhak7VySIB5nLeqr4ddsXdasa+BMro9cU6htr9UtTZqZi+bFvGn2PNeh1neNCHy/wrr04/aOE5GsmPDo8EnNUD8Gbfcwpnvw7XlMMGacCfT1wiIkqFZ14SP8dReYbu9OJxRclfPqsYEgdH5zgHJ3ro2GuUtx+7+pi0jtR2UFtKsz8mK8TKjHLnBg9AG/+KEhM6I1njlro+eVf3m31yQn1AX2culPCxRXWnsppZQ18Za8t9zJRN2UYGr024Euv2dKZ7MKsYj1Hu1TxubiQGn7/oY5CX5l3QzQs+KBg3mIdb2/VEJZxDO/u13AwB9nRbRB6FDLgdeuvYL3zeJzZ5IEnNZV8kTsD86hzGDKX7Ch2f69hX1sVDR9a71uOFqYzT/X4KqO4jwPN3qeId9/1Ryty2kZqaIHpCgYxp1ff7MQ8Zrtrn/1Ea6/xq/z8T/oAodJAGe94TdbzjgQPDafym3jT3rDXuy3n3M4coMPzkYSXJSRseUz+fDIQUfcPiq7k07ezQ3Alk4hataNRsZeKo8GpYtWCP4Rsj8m+HMOmZ3Tc70suYVZq90ZB280KRlPTDmZmHmI+ON0iCtY+w3+pP35z1opShieCY6mB98uZFRdBrJjYDAVerhLmks+TDxi4TP6IrWRiwDwZfXcwu9cxgbwavO+oyDJHxpsC1MMwE8c6zxZChhhYNVDCFEOF1kwQV9ypi2pBMt4zv1d+IeHYcPI7eT9+ngvKr+2IS/SNL/SBV+0i0MVFQdRm6hw/N2yiat8vW7qgNjJTX+r8kfDrNHPPr0C0W0FfvWrg10EdqwNbY/lNFW+rcSxiDcRXSxETCpIHF0oo8cjA1CwS4rI8Fnv9NNCcLFaPOrvvkok8u3cIFl+67+orAOwR5qLe9OB+k8l9qZzX76wxZqqzxU20SPJHYruv4g5m0GN1WaPrdVQnL2ZvZNjaPKupjJ/5KokxRxW0+aWj3fu+6MW8beX0KiM0vB0VJpYLUNH+u2K/HzhszFdhpfWsi746NtrAa7LYiomx2HlYxU73AUIebbRQ7JuCDT4GyhfR8Iz58PB3CbOyfRC/7Xeg02odlybJiKAG1S2oo3k31X5+d3i7iiPMYQFpA+09vq330d+T7W6zDo6TF6uSZRZwrCPI81X5PZ/mI8u9pZ8NZP47XB2bE2QUClQR6KWgVnFqzfDz4m0yUeBJFQGDI8WnJxXc76HZa/Ws+5IHKqkoQeZ5xe9lFFZR8p2O+X8NuH2NQk7mEjcXE9aa/ugkGV7klclFnLa+Ll/nY+8jMrvfW6EN9WtrZDhuyjJe8d9az+DanIrChTqqzZdfyZ6LapBBZjhwRBqM1k+ihaLTdXtfgz7j/90/2FXSxOZbBlrRT4quZc6ndln7uV1rz6z/REJoHhmtB/Cae6eJZ8nX08nqczzJQmlk9iY6Plj7ES/VkWNJJEK2kMPdVCH/dV4fFLvG2jD3abvpp5ckjC8qo11zclJR3d77xZt+OKWAiqG5q2NPJOujoooDaRLm0A+ek1H/zDIw8ZQPvrdZLax08YX5XMWWDuSCvcywaVvF18yiz5OCYVaR7PcuGz2PQRPO60JqrNTQwB2OwbsXMr7xv0P6NUNH7d872ImtFBTidXlV7iA8mtUOb6jz7hyTjfk0uAgGhvDvVvDaw9m/8ayrwh1PCBPJwJWpyxeZaZ5c1VDWXUbdnCqGWc//OadZyEixjyU05O/eygyq0YPnjlfwfsAIBHI+v0xijt2p4B4ZQdikY9U8A1eYN4wiMu5d09CDXLBFMPGevb90L8fro4GfT3X7vd/VZKmmzA9x6cx9/pFoT21culPGKDK2tV/uoO70s++eOJFDhoO5++BSctQyFRedCuZeNrF81nqxb1/OxSZ6au6t4opmvA7W7yJ+lspM15X5aWFGBcXI7n6HrTXuGl5QD9OYmQr/VuB3SYX5Rsbmfhr8Mjtx7WpFCNVl/Miu4FlWGY+yqHh82AXXmFcyseYCOcbFVm0Urf1Kk+n/S1qbeN1indj5lo7T5OeQkhoqV9HtfcUL35DhEm6iGnNwNvKZtWYtZaSKy6wB7zQyxLTS9poHpRN78aKCGc8UtDq9T3idrsJ3ALOUte8/x3rYKQMx5JCV63RkYC03ijBwu18EXpCVV5CFTzMXfCBTPJjLmjjoJm5hhlzVUkVfetzhFkMxzNobiXMZzLGrZFJDE2VMLq/DiBmKNUKoXYd3ashokMdAuWIadvIzlviZOBUn2c/6y4+QcaGGiQ1rdESOU2CtWxSm6ihRX0XWGyOFtJGDsXUM59dVwWeyQrL1/uUSGZ09yE3MDk6Ot/XsYVu+WGQhA/lRP7+sYr5r2AiHMjNXZjZxpiFzSz8D2XapEAc54J4uY/YsE90a0wNzUVObxEAfZCJj3f/Er2PeCZNYH8tKGfYZBn3ulRPXcvxGtmAWrb5FaNxEtfcYyRyYUZxHXbL2F1mWHo09XXW091kvhK7S0Ckb8+ITXyjXmDcu68g+j/+W3+kCuT1hkBNu/POXRwvb++Wuo3av7uaEH+uqCPs0CzOG9VxTXKwBJUycpO54d+G8UENWDoxB2hwTvp9lbEzQUP+EilbMOW3IVG9L9caMnhnE5swjP8nZly6omCwZENmbYWOc8GSOtDgv37Z/exNv0qOgMoulblMxlno+J4+E5z+WCout98tYQwvLhcGtlD8CY0zsvqEgS0MTX/gdUp7we1QmWzGzW+sg77KXf73vhlVPVDSj/inN2TsnusK3k4FpdxX7Xu2aAxr6tqOu/EwURwuHhOmu9PMQE1M7OZDOPsmeruFaqE4O0eBKLxiR18AH6seX0lWFB+Tpb/TvW2SmLrNUbKKGZFmhIsMvBfFt9otFyGHSD/4d+6BsXwXObKb9btCdrCp82rC+/ur4eE1C2RxbhKs5FfxXjn3dQUMfhXkiXkTtgxoOu8loyt+zfwT/fan5Qgn65tMfCjKR6ZTmEgYuVjCGvVmNGePRE81e69meHHyAPL9sF//M6u9Ejhn/3ZbBEkbPWCOknu0knvgk/3unYZSB38yrF3ZxbKbpOPFGtZ/db6o0Tzw8f75gvRcet1fCM0HF+vOK/V7qKBcN1TJqOBbMuSLnpLSm57lVs9/x2ZhGvamj49xEJ3p1keC/QMMYzm3sGhPNapCrybZezCa/+58VGzO3fLwsIzyjiTH1cuDcjRZilbKXxWr0Ft8tCrbwzzOnG8g9ZQTm+ZooF8r6+8BMHawhsaCEUttjhQdkmuLkbeuZwIYYGfOz6HCL0xBAZrXWA5feqMOHunuzL+dxpRPXy3J8Nq0UevYwEMTf919HExfo7ZMayNgWpuD1fo5DJwmPakeieKM4oRl1K0P1MFRNDUDvDdT8ySoyxmsY3oQecUqHu48CR3YdD6IlFGfWhSTjyxYd46lNby/oNmePKi/jZZP54od1Mi4n6TjZ0RsfhmjkRw3BX8n9pWNQcR/7/cEqUW1p4oU32TL/C2GfWEc8R6/ryRqatYz8Su1ONTVYrN6S+nz9p4qKkwdiwH0FH+fouF5mmVB2/FPh62ARr8ijPlVNfEtQcGKUiv2sjTtDdPudDOOcjjGc8wze2XApykATrTje5jbxg1yccXSEcOgNM4lrDDLe8sbssk5ETYhGx7Q48UTVKOwaFYOynUyEFTDRv1uS2Gg8a/lObfEBc/TzGllRUyJ7TKNf+CoQs5hILaHhfG4VfbbLqMzeyBXzWHQPYcb31IFUHdbeMWtbxaJszxjyhmzvTfZ8DetpoYL5C9gb91jvOfl5rMlqnOuIvibS2EP7eY2HrWeiyfTZRxo2kMVmlmV+zuTER/Zr45nMpWTRpsNjsbTuCBwnAx1ZYaBWkIQjE+hvrv/W92eKp/dllDC1cVucIa9Y71Z5sFZeP1KQ87U/qtYDZjQx7P2J9obJmFpWwyeOde+sGgLZv4v3yVgVOBRbOf+VyAnPyRwex/6tcfxzv7XoM17GzhZDUOmYNzr6jRGasFduvFTxivV6/qQThXUNPTuTn0+zVl/L2ONUMY2e1OuihpTC1CCnjExkjWlVz4qf6FH7G5BrZHpw04vieuajK7Mj0SFOxRnqQd8SrOlo5gxm0J1qDP5Sk6oedmDONgP5VslYUknBY/5MrY86uvx0on47FUX3ymjPjDSjaHHkLV8ItWc57HOO3i7LLubvnJt+nCp2ZCaudJmfdS8MKuetO/24UhXqy3oDTY98F7/c0OFL7mtCvT16QLXfWa7On8/L+jtKLXItzeteI+H1lAikNJPtfVyKVdCxJ94Tw+jfa2rz9z80MIeccJs9WeF9D0yjNmwRNJT8LaMm+3kjPyN9qIls/JlnPTU4yVHNBzLPKU5cimcN8vO6MCNafnz3mBPJg/iZZwzMZX7N5GZgwyUDP5j5UzuQeTprtneM/6pjhC97tJYK79JFsWi+jga7BqMHa3X0VBlzMobD600ZZAyNRr5sGiKGana2eMZ8VzlMxdZjTfCpo4Y39B3PAhPF9K0Gnp/89652C16jkEfHT2aFyAjVXht3vIfKPEq9Gm0i/Z2KXrNVpG6mx+4x7GdwVW8pCHlqIvufEfCeoOBidc2+32/tBbixTgRC1pJl05wIXZJZHPmW49PbifcOstDz28JeuteVdwa2Mqt9psZtWDAEK2rrmLlTQjZFRd67OjxE3b5ffZJ1lpP6HSzpOL5BxQ6zOk5cYh/2MFG+cjRWrI7BxBVO+DNTDuacev0w0UeW0KKlhqlD/bGDnJMcuke03gM1DpGnfTRkOhCLvjtjUOuEjAH0fmsvlkthNYQN2xV4XSRvJ2QUEycqyJek2XvynSHvL2rGHg45LlrPrK012VYOLlDHQOP2Cla9nC12o159JxsNj1JQfia/2wIDuQZqyO1u2HsVlp0mY+QHA1n2MQvS40axH7zS1grt7zgxnjW7hDnEO1lBN+bG1WSyjIaG/Mz1x06VxPcoHade09cHaxiak+Na5JS49PS/9TQnpmrI7siNtUfeC9P9NeyZysxGD87G73WnGPNyLcV+N0K+rMDsVhHrK+mo0Av4kkHDQzKMu5eE99SgyLo6Xo5cK15cZiAzs/Wp4Ya9JnR9rIYRHLv892So4RpC1quIojf1c/ohTTUxe7uBXus11OU1TppUTRzB+YujZtx+LaEX/bl+SicUdpkrnqEv1GlL/i+lY8ag3kiOVpBETn04g3W2ar1QeYIOF/8YPN3lCoGZMKdOXZpC/aqkIUesikc7NCwOJYdRb0bf0fD0bQQ999+aqKezdDTctlCsODQWna8r+MJcXv5eHnEqf/fu/KyJlczEpgpP+nOvE06ULRGGRp+cuJKsYy97bGpyTfHUK/bcbQ39qPvXuqhoRG5c0Xia8LadiZ+3NMyOMTDlqIIVwzWsJGdUX66gZ0EZxb86UawJ+ZY1+eOKDF9mOUfjMtDH6Bi3WrP3W77XdAhQhOPjSx77EYrbuTkHxelbHswbo9ifzIwR1rqGQk0R0Ib5np4HkEcbxeLoaQNRzGcJg6KxqpWEwi+ShNsz64i5bo0RXuzWkfhnrxjNHBFeUUFN9g1G66jXgmwxgkxv6Gj7XMPRow7gDMeC/WGd72Hdj1y3XcfsEQbC6po4uJoswGuplFnDjnPkZ/pYthG6vQfCZPpYE1PC2abkDnkIhs2IQr8cCoKfsJ7KqGh42Bd1+7KH20Tjd0oEIgsaWJlPQk4yenvVwMnmzInWu0HsoXXU21QP1lZhE12GtsAx5rpiJWVMeBIB46wClVpfcwvzyp0o/CGP5KutofpkB/zoZ/4/ZPjsN1CjtIq5dVQET3HiZikN/83LgarxMup9+iuUPaSiyXSOVQYdOUv2h09KDAKyGihFbd41IRILRv6b2+X03pDuEmIzMdeRYdzZp2XCpwg1nTqy9JOxmNoyk/2RNp+Mz++pkhsCWmsYHaRiZh5/dM5ArWZGDjXnCO/o5SOZYa+DdTDAiTX8eeuersdvDSVc44W65Ku3vzcLGZmvPKknlVwSxafMjQVaF7DXm9el/tZg9v7vP14b9c29syE8YB32ZcbWV+tInS/j7wMDi5ghN5IdOx2qibjO7MvIf/ciYoaxHrNVEl/RH2vPZfYfqkNkLup2oCsmftGxkD3w/D25sqYM675t/xhqyG8VsWR4jw4G+jMjHcikY2pneltcMzSbkygWYY/XZK1eC5Dwe6KE9PzWniBDxPc1YlCY/damlWFnwqHs0wcxKn6kqZjK73BmiYQXpcjBt3X0axyAD+SLh181lNevCVZv9S/6b31Bn8/WGaAKWiRNEPw9Kou5Zh4Vt+1OF621ZUdNslRhZnTWY2bO47EcJuYxez9mJt1ObUzw4f/vrSEXtSQ+Qy64pEoYnjmGXKUiT30dk9mDjrUG0s4vEPJ3VnCQbKaTq0twvMaQ690jZXuvoJzUUmlxe3vtTkZeTwX3WMilDSz8EI39gxWksA8G8FpWNjfRcflEYUaSicb03w/kk/7hZKoFZGfmF4+8MRhyg72RSn/f0gdpR/Mg+4YA8emoAORpp8D/tgwvcvpa+lCuviPFkS02i+Pp7df7KZAUA3GPNVzNEIpWngYmWXubrtMwqxx1rZqM4EVRqMa6vxFh4PJFA35XDPhWVGHcJX9w3E+SIw5nGGKv9xQax+JKCL39pYFPnIvMkoKu5GXXRjo2F1Ps926/kuc93zJfMRu/IqdWPxqN2Jqq/XzNOiPTk8zZ5byOF8zg/t7kFNZ8c+b5zR5bhQWc83RmvSd1DZhHdJwnB7ScK2F3UQPRmSeJC2SOV9pwrKjB67POdaQHefYkt/ZRUPfveMGT45x5hY4M9KS9QQbun5QRMc2BypzzgF66rbE7MweIi5jRQrPTl/ZZZ+AkCiOpoQ3J+5/Ig0s3hePWt1Th0Hx/ZlYNd5co2L5HQrH+GupRw5ac0bBt5HOx4uPxQmfW2p1g3d7D8GBNslPp5qj5hCwx1A8N/SXca2igEzO6tY+39X730T7UjV4qXqYYmCAb9vPNWE3DpPYaCjsNHOEcr3coqEzN2n9FAo5rqCxK6K7L+EPN6zCKY3WS40jtLnud3/11EIrRn7u3YYaqJWPScQkbWcdryg5AC3Jx+tgY3KvJnujRH+34Hbv2MXC+lCei4xWcLRkB4b2JXYsUBDFDNfhbSjzDDO4ygPN4Kdw+DzWxlYk6PmQd9lX3MklCiyoxeBkehd61wzDsST8sYwZZxvqYW0RCz8FthJh8Koo/0HFtwUZhez8VfgcUnKtALi5PrphtoGuRuWJD/r4P1HLXTQbukoU6sP9+LFfRgN6cTF6p19FATjLy8XyLhfwVOf59VDRnru7bjLXzpgSubtdg3Ueo1UtDXJyOTfzvyQYaDibxuvvL9t5s9/+qsJ4zXK+nwo35+jfH6GETatAVzb6HG8e5nF6iqNjhy2Yx9ZoD8TfJjMzXz9nX1jmUW5iVXc7LyFsrAgHWM7P9zEPurNl6Bqa+Uex1wGUyOJFaPhKK9T4P2TvX6W7CVXJAhtpDMPaQht/Fw9GP1xV3UEHxL5PErg39MMjbWnOuYcg3HcU25BGa/9DQso2KOcIi4WWMhEkL5wuz2Ie5LztQhLnk6J6KQkky8fk+XWDQ0176B6NykIZ4Pw1flxvoxqz+S9CxbHU3scihIdi2g2xX32Gv8f06UEGJBB1bKpro8d06u1ODgx4+5pyCAseHQ92ULiZVUNA+xYENzIAfPKjV2w+LX6+MFMNW6VjRl6zCmvWcRa86oWEJ2fRASwd+f1HwOo+GPrvckM58v76ZjuKjyJo1NORlj41mjbVrMgxPj+8WuzZWbT3ItUvBXXLnWPLJn1d5MaW7jhv8XtZeYi7skd0j2QMbqU0fQrA/Vof7N83eo7vuBcneG/TaUtneA/QOuba5n46J56sBQ1LEvvSW1F30ctag0Uu290/dtaAoZm3S7HPUVoUw27ib2Jug4nAnjnu9cBwQDbQeL2FXUARqh2rofTeP8DeeeSs0BsddTXQgj1pnq96zdGoJ83Jdsm9H6svpp0KXZzF43V7GjFSr9g4LidfYw9S6e50UvDSYS9PjhAWs9S/HNJS7zoyzMhINmFeaVGH+pp6eYQ4sRd6UFkTjbhETVZlxrPvfn78zAz3h9whQcZBsmIl8tS3/PrH3GPLbGxn1K5DTMoRhFPmqRkYDQjUyZFEd/ed/FXNRSzY3qSu6Z9IwcIuGB8vpQ//5o8ieouIe9o+1dnZpoI5vOajx3UPgQ2aKo75n6Erdnq3Y74tfC+grrrlPD92lwTpncC3HLCXuvWBoTngEs45cNKzxldF2h26f9daF/TfnC32SOb1v5c2ClZuL0As86fFNujCHsY8+TDZQdvpCwTqP4DGZbOTbTuKAmZp9HkS0bmDWVNYTPcDzpgO7WAP7KxQQf9UzEbZbxeadHe11Xd7Ls6Cfu4rt9I7nZIxKzI/j0iUcytYTu1ppwCDmJNb16G/MZaHs/8k66pasKlrroQefccKttoocZOAhzFlpH6cK9crHCy2qG9hRXEe2M+zx6cyDj1W8YE2/qcoaqzhPMDnvRaiteazejdAwPkLCIjKsK3NiM2a7D/SlF2TFjMzyBUcOQtfOXmjI+snwSUbB9io+pOi4+EOCGaBg+JP2aDXxo5ibdV6gBNm4lwlfVUWVdPKUTxsUxjyhBOvlMse0Z6FYfD1Mjz2bAb5twpC5vopVZOmWkoa/zGhe7ItkNwWHDsgw2kRhYVcVBZh/tzEjx3sb9jqs2bM+irUeaWjEsXJ4Mbt7mFgUvkGIYi7a7/DG8NUS8o9JFg/k4+/bo8I6u9t6DpJEbthcyLTP6lvBOYq8SI2RDOzMaiIP6zJf1UgY9UPR7RR1h4y5l7re/DJrgv3lZZ0/DA3DqLneAyQ0Hj5esNaUWPvdfqymo2Nie3ix5joelrFvqYoprMn/+hfEo506bk0x4ME6qLzfifXs7RK3OIbUy5cpTrzIkyhm8mUveGq4cG84Mjk0JCc4UauAgTvMl+vvBmMq/WYEM5PnrmCENaZvHGcPkc3r/1LQmyzlTr8/eFhFwXtkweEc55kKlvj2FFZdVTBmtYlGkzmP3jJK17kpXuM177mgIIzM3vIuPapUU0TTu4q91OyzMepso7bt7IMNwwzENDaxZGyc0GSMjH7k6fCPzK/FB2N2N2oVtdGFnuE6TEH6W2ZTfqdt1JSIJv0w82Y3YdfAyoiU/LDREYMBxwy8CNBxN03CuHEqKtJ35oYOQ9k0DQueGBhUV8Xfgyni/BBmp31ZxYshDmisu0rMSdm1s0JTzmONmwpk6xz1qzryzrD2/EoW81KTk6jnXZkZ7rEHSpzl/I+yztKgdjj64hWsPa9YW/0VKOS45sWi0CiuMr7TL6x1xSP2JYrWuhbnXupSyCPBi146fXIIyh1R8eAa5+ezjOXkuxcFTBiclw3U6I65MmOGV12xx61oe/2UV9kYOPbmF3dWUbCa+rwkSsNZ+vC+19H49Z8O1yP0dGtvjq8NMF+hXtbW0cPLwESy1Bd6T5l35cXctTREMZtXrm0gF3N1ndEK6ns6cGEc+/e7Zr9j3jpvOBqukO33Cq1zPerTD7LNl1B/konzf8n5gowN5GhrL+vQotY7lJFoVp4130NFW15XMWq3tfZXC1KwnNzx9gC1hHy6gvq8hmzyNZC+Sc9udIxaTc7fSTZzqOHYOZh6RCY42tpEPrK6Ned7mH2ysWd6LaPuziF/Ho3CoQIarDMLrWfN1r4hL8iQk2M0MWytij69+b0qG8jBHJjRvbFYf++/s3Se9HLiOWvR2u+6MZl2TtgBse2gWmjmRc351B8dOD45etwTcjOLpccwZ3Bspjfrig+vJEx+oADeOqIXjhNvj8gg3u3gQNObOrzWM6NP4+9aOwLWPqCrW2goWP2nGNRqlvCMWaoQuekpfes4e27HsqVC8FEDibck/Oh6W8z/y4El5HTHshFolemNkNpGwa01qr1/1M5fXZF5AT1zJRk9bp74ZLeJ+Op7hFM1/p2znC0TczT9vXYW5k3qy/VxwehdqAPSXf6dffJ6gob1T8m/9JKPfgYu1fPGXvby7TcqPp+lBj3aI5Yrb6IEM924jDpimf0aO5eKV0IM/PkjwWOHjLH1TVyhTo7fygzNfveYR15h32Y8pGDAtRhUfOlEEVcZIXsUhMecEyf6vhLyMN8PJWu+vP7vnCiJeXlcQeaL5Iri1Zsa9tGLCvnG2nutq8wArxdYZ3Pp2H1Swwuy6CtZQudyEooWNKE2icCbCAWXmKGvPy2Nmz/eiTku0BPJS+O7U1tdVJwhn5rNVeRmVlk4hPmQ/N+Q19C8fAzOZjGRyKx1+JpmP/8MZkb4uZvcmJv1uOyYUMmffh1m4N5/MXhfzcSQgyrk5QXFg1sMPOX1W+8AxdN7EtoqyMC5fFtVxxGnDoO6F5apPPYP1ZDpgQZvcawQRs1oni+LOLROE9FihRadmZEucj6ppb3oBQ2pky3Zl5266faaX+vc8JhZBrJPVvHGZP5/EI4Z4Q7MPmPgM/0q34VW2MXeGpOdc/GM4y3quLlFRmoVzsEADUNdBOgfdSzRhuIUfTJhLtm/TXmb0Yq90RHP72jdU27GcZTX8bNvGlgeYGI6a+LoHBUT3kXb12Wd6xUREoGGnciMxQxc3SjjY00FU9ivfdtRf8ao6M3sN2GPAzGjnPhD5soTeFGw1ogdpDeeLsC55c/+Rz/r/pG5PrMD/eZlwAZtBLo+0TH8VBvhEWvVd4aEAt4mKlj7DGx0osHATpieLKPc4AJi5acS/A7q9pnF/7G2VgnU0wUSNnm1Q7K/hpwfh+NCNg2+gSOFsuTbO7c4FxOpjxNi0CevDyI76OhGHsk2XcYl1r61P99JTUfYLdU+T7oDP3NCgIEe5xU8ic8lpudx4ndBBc2OaJhK3fhbT0Jv5slg8mg0NVeby0xaQMdgRca88b5Ywh7LTiZKcR2AM9Nj7P24Cl+UMSdnFCYN1fGJXjPiEevZ2gv7SDSWNlJx9IWBGeyDA4WyImAi9Y7jE7pqjNCBc2bdSzmVklV80s9EEFloLvn4xfgj4pxWIaJ1pkrYRgeSuslwZW5zt/b+Z39a+/pkZy23ZSa1njENvNgDwc5T4jtyF3JGQvhr2PceMn+39jnQ7fOMaqkKJnWh1n/SsYi15PWJjOanop7cEWMWReHyMoneTm9ItNaWGog7TV8ea6LbL5leoOJdUWpxSIjY5L1qv5syLW8I7u/oKVjnTf9szjqoTyZg/Tdnnm/RlzpNDmmdzUTp+cyJ5Bj3Q8zaZMzOzLk74+vC3KeiX7SMogkaqjKfVeBcx5ywzkFW4FMiBvMdOoJ6Kdj+si60rU/EFfQOaY6O+vSC/dQeb/rf5wwmImfKKDmS33WnAyeoc2W9FXsfnjsndHvPXhdmhnSJOpGPvNCbc0nez3WwG25S0/IZKjYxy/eg5zgWmjj9Q8fekw58yWyiLr3rKnPghNU6tioG0hxOhJC/xNoKYsloPXvKSKCvPMl5T3ywkb6/12Hf11gsDhesdavv68v4818zrH29TbDW46+PkaEXcKDnAieeUkeyFlcwh1nA9yczO6/V8uljzCH9+FkvdR01OHfT8ssYSK1fZL1HXc6Jni+jcX+NBv/55I6JOUTr+VSlffFiEL2sj6lhXXbV3j85M7P0N85vJWbSjksdqFeiIPpkcmAcGXkwc01X8l6NrZeEfMxJsT78sx4ZkRRoomUZBVVZJ+n7ZTwgW9UkZ53uRmZ1U7H3ci/Urk5m7R6NGm0M9ClCH90yEMdbdkHA/Sh0qqrC+ZT55CyZPDmzvXd0ezJ3ObJL+U67BAxQbe46yPrzpm5vIo9kJIPFsndXMSv4OkcJ84axt6hRSVnpvd0CxClNO6Al+SDb5z2CZzYZty+raG+959s1As98bonX71Ebq/A7M+tOuBovWPu/epNPpq1sju6jDPvsgd7NNSw9tUH0Y8/5UwvzZyd752dG3sD6X8FrWGDY53QlVWeuJxtVrUr++KDj/VmyTR/Z3ktvRYdW4i1m88/04t+7Nft9x5Hl3RA7ULfPNZPrKJia2cBNzvGNfQYuxzgw8a6K6nepRe10PP8+AM9P6ph0kDXCDNWRNdiHGrJuoWrXQhr9wNlKhco5tN7L399LQkCqiol5ybYdJPz+RP78T8XOl/xOZK6b9LcdiTruH9Jwea2Bjr1N+Bwjm/VWsexsI/E752eQ1X9FuqIvxzkmOgzvtrdBvRoqUjeSY8iyQS4m/hzuJxxeImNy6X97Jk0n7812GvZz5VU5Rwt/6KffocM9WMcNr3DhTfVo1Lb4f4COrK2ChIIFGon1G1Er/qg4zZrq8KUjFpH1G8xQUGZTBHo+V+39rjUy4jfmD+vZSCNmotL5yXDd6X/k9tURKn70NOFhnbnSUUXlh+QL8ve8TNTYGRryXGIPM0NP269gdFcNbs8k1LwowVHDxDvqX7l2I4SA7CbzzkpRP6QiKns+rCcjWPP+ZrGOwIfksnADfoN1jD0SCLe4U2LsEOsMWOpShIEfg0x7r5iBrNuEmmQfen85H9ZIm0XC+HMaolmvvTrIKDsqN8I2SfbzZ+1eDHzJmXPrURN3ROHxUxWzM1HHT8eg5TYFd+kbXbIqmEUGH9/ktZBOz+nHPigwREGBJiY2laROn1MxI465uNwb4fN45n1yhrVWehxzxYXFGg77OBCQW7d/RmlnYKSrBLEL9bScgTVRD8UxayXM3qcjZLEDQ7YPwe8W/XAn4p44v0gQEplDPlPLN+Wmf75youVqBw6XNJFepARmvtdwe5cTB6nJk8hAcdTk/VH8fOp4wRXMhzWYaTnnPXw+isXathZ/UJfulNZxiddtzCJ3r50mulP/67dQcW+JimvgfL5SMJE5rsoNCUnsxXknnFg9KxLrekQjD1ko483+uEVWqn00Akmco+pewzE0h4K/6/6t19uwg70zKgavo6vCnX24I7m9uHudap/hMuymii4TFgku1Vhnm8ihZ2XUudQFLTIq6ET2GfhJxQltGFYxv3R9QUb6KOMqPdraY2HkEw11cpuYeULDiXM6IlhfSWSfSrdrYdviIfY7cJ6V6KvUmDB3A2MWMEMX9BBmt3TiIlngfa9AFHdnP6ZQZ/IzW5Hxy3LuTqUxn2bW0YyaNJ0sEpyoIKCehvSGGryoQX9qRUOhdsfGKgjerWPjqAh0Kc95DaTWdLTedVJwj5pejRkphF4VFC9j1JiV4hx67EJ6VQdm36ofDQRQ6w4FSphRnP6c4sBXQ0M7sszr1zL6sk+ss2ieH1HQ2DTw+LOG9jmZgw4ZuDthipC1nIpz90PtvRf0jhIGfGM+lDnnZENrD5Xtvwx4N1GwN9UXj09r+CiZeEq/3LNWszNn3feTBWuf7NabTKzO44/SzLlPHy0SvHZY61okRHydLRbsqKN07XAcKKsjO6+91V0Fi6l71tma4TccKMQsPIqZbtIJwz5vLDLYsM8qKHlDRbO6OjpRu93WuiFTfxUfqIkGvfDG753C8U9OHBhtYHG8hIqDyctzTOwiU105Qb3880a8FqggB3uvOGKQb1MG+3yM+LvR8Myj49gWCete0psOOdF+cn2x8PqCSLgqYzu1yH+aiS4tFHizxz8Ms54xGshCPz/yQEeZKwYiPxgo0tGB+xN0lL9P7UqmNlNjp1OjolOpb8VMXMyn4041HR3CTFQvouN7DgMbc0tQn/iI1h6Td6kd1v56jefr9n38YaskFOR3KFNDQepiBcePyKjpTs3rFYUuZPGggybuMWddbl2BuZq1GVgTi/OaaP1FRRivNY7j0N9h2M9NrgVLqHdDwyXm+llhGhJm/dtb9zF7M9M+egd12toXZSa1rUGoDr9BOhKrhdkaV/2gjJUuEsbyO1T9yp7OmijEDdHtM3esM5TLpck4tiS7eLSugUl/Jbi1Imuyzp8V0iD9pP52jxas/QFH++mofCEE53Ia9n7H1ntmflUKiilk12/kpqLbNexlBnywij7n9W9fhMPkz6XbDeSOMjCF41W+Dj+T4/6VXP2HvLjmM3m8Jf2OWWgd+2GpdEec08/dXoPfwl/BwyMS3lEjG4ytDpE5bSb56Ez3ZOG8pww3ZuSWuSIwJknCtR3+CM4/3D6bogf9eDZ9zOLk43kVnJ4iIwv5v2f4KU/r+W1W10jkrvUvI37mGO746xA8u2VC1SATDZtY++9K6NTCwK8f5McNt8R3ZFORfOhZQcagvtF4WdhEYXJSaXJGRY6FB3XEOlOtKhnRhTX/1SUIi5m/Er9Xwthm1GjqRO7COlmMGZs90GesjB2p1L/91FGOyzV+p4yDZ4jWfgU+5XYJK3ldnk2Ho9+zVlhzUUR3ssLNguyJtyr86C0YZsBBhtm9QkUtfscWz1Ss7pMFs3dECsXPqvY7VNa9lxND/q1Lts4XLUG+ScjAPKUbyD+K48ps1WZtXTgXKbhf3LTX2uxj7n3FubiYqxcej1BRI6003Fw64MiPv2IMfbn1cAnf25JF5rBGctCfnyh4Sr/KeUrBOWbt8c2SBR/6X7YcJnzddYz8qmDp2WWiX8swtFssI2k5M+EjGY/eFcbz34FijYfkkfOanY1GMitY5yNuj4nAC9ZHrcMqlnN8BtPfyx0lIydOFLrxml5sts4FMNCgjQlpmspxcgo9avoIM7ZoWGx5Wn4TIQd05M7jK9Z++UD8zbnyYS7otSMCOcJKi6OWylhfW0eVbhK6/9XtZ1ezmDcsFjzKz3k9wYE7TW+I7mRjgdq1fLtue3cb+m9F6mP+xhpuFqOej1cx8rqKh+eoXdVV6JUj7PPsoqz7LWR+/3sDMfzOemFUcQmBrMcpzOzni5qYUicG16pHYvhV9jvzaj5qU0ZqSJKHjBfW9U+Mwg7m0Xo3FWFRBQ1zxikIot7ku35MGP1HQesekr3PfPYQ1tFsMr5B3mI9WOeGvGmgoWRgF3Su0s9ey9W4joxuk629FJl3wnS06KZhHjR857i9aUj/+NMar/uQy4qSf2sa2BKjIZDe8Wk/e9ezPc7k7Af3aA1trjCD9vLB2iQDa8nrxyeRZfIp9rsBr1+qOFuCPvlGwZj2//a+HHaVzNic/fWtJe69myh4jW4u7mGGXsIaHhG1WlzUVsLDlRqOftks/L5UAn+us05iNbT1j8DkGvTwDMzkGaYJLvx+nlN1rMweA2Ee/Vl1otjTMMyoYGL303BM708vO2LdKy2Mw2TCpNYazAFksGMq7hr9EbyV81eMjJzPxJ0/7MdIA93cWOsBCo75ss7pSR3WTxbjslADyBwHz6v2+tqgXQo2fu2DfIqKPbGbxMO5VZR6qWDC5mho73T8yGrCPG9in64gitnVWtPu9p19SJ5PPS5h6UcFA37LaNxMxYaxmu07zRsyV+Qy8I76O5E6JvLzqywJQ8tYJ9a+Yg/VqSVumcy5GGHa50o1eaxBaDEAvVZHQ04uKLbs/lU80NSAmLWXUD2GLJFHwaebZ4S+72T73NYrzFvuCX5oy8x35jo1tsdwaNTN191VZLgr2edKVSdDdFmo4X1n1T4nr04JFb1mVECvSQbacszWBnkJDX9oUDMy0woKdvHP3wZ4Y2mtlggpb6CetT/k9zYIzCEje4OjwmnrGR655l2KgsPkyKcnnfaeg6MzNBE/HyYzeYxAvo7UXupBELNd+WYmtismUl6NEuNzsZfIZ12YP4rRPwaP0+A+lBlmrIIp1JPSVdib/Dc5XMkgzGw9W50TPebQHwI47rtMTN2g2fv9+BxUkJc6mEJdGUrO/56VOrJLR2QWE96BGp5nb4bTkwfY+a9rIx1t6MnvtzFnvFWQjbU/kczVkVy3kt7q4bpTaHUpGltOkUV0GS8/mGieskmc0Cg78gxujY6zNBxnjR3ttU00qVeXJzAn7xVwpLSGnrc1zCePZrxEZnFhju9fS1yYni5uCiKHzpbt94ate1OT4tjr1j6D7JWK1JA+nMudZcifU6gnM/49E+8sGZix0kAhT44XWT7xRxS+TQgWE0I1LKomQ3Ql340jl7QwUZs5oRPHwnq2M30e6zjFxHqHiceddcz2VbCHnNskzIk7zBGR21qixh72w77xglpSxxPBxOtesn3eXqFqvD6Vee+3iopkk6XkoJAsIQiYTKZfqeBOo8LI0Fez11KGsxeLk1Pu76Hft1Ow/LiGVAfrP558yx4oVYK5WGLuq/lvL/mHay+J1j7JY3Oq2MX52sTaGlWGepigYd3NmcJecrsfs04pamcLetDNMU4MTdHsM9kvZHXgInvrEa97+Dp+/2QdV54EIjVzLXHrdwV/mOOj68vo8DhFrEMNtN7x86cP52xg4kzPLeLdFhJaTRyEt6y9D001TOMYnf39QvAo206cu5f5bpo3riw0ka2FhllkU3d6c2iukWLpuwYara6FmHIa4ofpeNhKQtZLHM9nBk53UZBEPzxITf/ZWcMG1mjHDzrmjtQwY7aK+Oo6kjtRRzpJ9nOckZM0+9wT69yObO1lHP/iwO8pThiZWorbXjrh+Kkhs+CCi9Sb26VVNHYlb/uZCFytYNAiFd+SybQcv3lHdHsPSF9qlQu9M4YcfW58BZyuyt6sHIkZ5MI/FemJHPsbY0NFqSIZ/rYTZy+odt+UOSyjAj1qWxMNq3o3Eqzzdcr3lNAyQsa6tQtFn2cyCsbquL/MwNaVEnIkmphzmRlsIjmKmjUphOPDrP7Fw7TPgDzkqaLwCh3rwk3k7OWG5adlCFHk43mnhCZnNbicceIXveBW+DPx2hwFFkOUXaLZeyleSTXs54bjNsjI+Jwem3WMYO1xsLbdX/FOMwVee0Lw5YCKId1MuLkaMDl2KeT04D0x2LooBvtmasjYR8PDkwo6Uz9XftRQNrQLPuvhiKaPzi2oIu9X9h455+lMEx2GXhEqkGEHuelwITtYazvrUGeknfw9g4viOrlhLHPGGNEbrmcN+97TytY6zvtT48jgr/l7WifUF84PZfa8JuE29Xz+C+a/WmSL2wr6nFSRh0xo7TEeWMtAJmbGVyV0BAbGItdkJ6YnMtdT30owA04l3+Wqp2A1e2vTLR2DskoIZzaf1Zd6xPH3ZXZ3/yHhWUMT3RswE/J63vSwzrNU4fNcxshOhp3vgj8peMG+K3lIt88WXt4kENnK5RH2j5UQJjuwlH37H3l2/F8Zv8/oGFXbicjLvO5l5FnmjaBU8mHdxpgcJOMP9WM/vd3lDNmDmT4tktma+bLnfRccnqRiGvs9O/v1BMdkL+skH3W/cxcdW15rGPdIQ3hlHYsqZhIrshfqe0dg1RTD3jO8I/3w5pge2NPCiQSOmefVQEge1MBp1OIADSuaGcjLnrte3cTk99S0vDpOjnaiQBcDf6nT45gTB/1S7LN0rXfnpDeavZ7xz2wN/aghXyYb9plIGZnf363WcFKUsYA9LtQ1cclYKlprA7veYhZ/M0k4NN+AL/XOhX4xHk3E8OBlwoGZsv2OUR/O4aW5TiT7R4lF95j2WXaW/23+T0fAH6u/DFReTPbVqAFkCeteVhhzlvWu0DD+7NOLCn49MBC9iZmX/fRrxiFxbGHOVx96MJnV+myFPvihNv2JczIgl0TfC0VyKQ2dIhW4kJuqCTOFdvnni+HU1CxnWKvj6T8fNFT47cB6fsbfvTJakWUGUoOsfQY7jpPgUScYtXmd1rOxhPPD7TM3mm7QUfuFgtCyu8Vl5/7tF1dyKnkz+3D7fe78L/i9XjtRfNK/d2+PMcPPYk1+Oc0sus9NLMPcoFTwEJ84h8Lorgh9nzgRwP6z9qQfSS+b5MuM24K/p7Fs7z9wSpbtZ+ZHyKUnyevXb0fBup9xXgtH5i+9xCD6cSbWvvWM8m8AfY+ZvLUf9bVQb9wvomB+eXpvLj98+I89TP2rF6+jbWAgNn7zxVr2ckPmo1DmnAI1dAxcruB93lD73Nj4Gg1R6LDTfqehM/XlF8jvzJNlGjOnfikpfHqtQmW+usi5OTursRhJPp7QQIEHx+fHrhE4RhZ79U3D45wK4t8ZcGW+C25p4hozY2T/1ghIMHHiaDSei8zMzAl6Id1et52+RUcC6ypuqBPt7ihYuM2BSrVlRF3oYO+NnErGLsG8/3G1E4XbdcGBNMVer3I660DUa+yH8zMMrKE2WTly1iANme7q+BakYJuDXOoxSnT15H+TksU6R5z0eANhZPAE5r0r61WUH8Ycgkj83K2hTHEFP9uZCDilYb+7hk+dVHhvV3CbWjid13ErRbX3cFmS8EKUqMfxuZg3i+rYUyDWfvZR5X42TDx+SPhB/k5dNhQzV4Uj7IuGlFUGOiU4UJyfse5NKKw1oNa65RUtdCx0ZX44wetlFrrzgX7flfpUibWWWBoK5+pPlIrQB5+E6y4SHtHPR2Sl/rxh35ZXMfwzr6favzPFXMm3dzUDPrU0XC9eSCx457Cwkwy26pWKIC8dRznWOfm/7MwFB6tLSGRet/bf/Ek/X0TWGlwxBg2iZPt3hvdUMLcymYd9/TffOyFuNtlpL33rcCfhNzOXX+sg+/whH/pl3y86ZswKxzX6ZPKYaPv5heMQPf8/FU1+9obL90di/+wGmpHz+zDrTdvL7HyfvNP7X19XJRdeJp/5Jeh2/p2yca+YLDuRrZqB9K7WuuQLYjEXMimvd9Q28ltKNDa/jBestYyBcQaSqZ0q81Q463SfrGB9i/niVTK6w8p1mxXsIxsubhUE37466tFbVwyW4PgYbrNcB9b8s8cKhi6SUSKPjAJjWRvMVHnItp+mqqgzUkfeTxoyUAfrst/D6TnWHiPlyA6bJA1g5hLcZHxPAlIqXBGtPfQKV9Uw9zvHk+wwqJuMnfk0RMpuiOqZTRw2XsOjhgaakhvEt/Sp/E77vMAkZiprf76jEzUMndYWWVwShb0FVGS5wRx3MzemkhumzTGAgppYl/O5mzVTqriM9iJ/n4tp75uQ7wD7iJnFt7qG+vQw69nMd+beUWcniHWYP9K3GWj8RIW5O138U429f9IfyiEVo/psFDdQDzYMV5GD/31F/Vk2SUY8x946Z77haQX7feOEpFk5kbVMNIRoZpa5zLojZCSSmadMIIfO3S6KzMAL8xhoQ169GUf/or+cINuk3eQ4jGOdNNgm7AwyMGcU825NE2JmB1ZR977l0fBm8DbxgqDjb8ZI+xwzlbnIsck6S0FHaX8FKzgPC5i/GzxTUJ8ZtP6REMygV/eMoKf4KHjFsblR1MDdjjriytaA/0MFJwv3R2jTUJTImB2r5shIOSPZ95fnrlfs+rRy95e2BrqSFQslkqtPGHgoWWtj+P1aOgWvHp2Ej6yL7cwuiczel6gHY4J9ULSzibSPue2zHwZt1nFzBhn6uo4cS+nvaRJmJhqoTk1ZPXCXsHX2ODGV/d+8X5SY6jNRyJtHEjJV7ClY5y2fqWPiVFvOyy4Z29oxE1QLRklmoEodNVwcpSIiK9mNPLXvuoFPZaxzYqkzUW44Q/9zp78lkdFWkeXX3dTtM+dvkqtKD2IOJg8uI58GM481XWPAhfVRuT41rr2C3qzpNu8ziv1ra8j1yYkuzHcNa+uYNPzfGfbCEBXZDzYRa5NPmpFrfv+sIzy66Y8a8xV8uE4euEXf5Xx0XcexDlSxZl2YfQaFdT5NEq+zCuduErPUZerQeOrjPmpZQ+v5/+sC9j41uR/qOMa67MwsevjlNrGJP339p44BfYeLTTmHXTl/vSMihGVuJirVmCxu719FWFpFRqEiOl766/a5lCPTdHgdk9HzpIxerOuhT6rAercmYmE0usbwM8MlXBw9R7gr65hTPQZDa7wRMx1zwusUa4kM9H51EFoFx4viCx1DA/m7C9M3N8uYST/+Fj4IG8ny74JUbFku2XurfC66VoylV2Q7qyPr2Rgs7uPEhXr0Ymao+8G6ndN8dsjQRpj4Pcob+z6R4dJeiTWqqtB/lsIycoC1t9i3FB1ZyGZPX+rwb27g/mkV7aw1e2RuiVlyAOfXuheb2p3MVYPjGxOLv3PJvcWC0ZRs30+MRfG69KDGdTGBGhTa4IdgvvK311Hspubfn8wMHs+8y+z6l/Ui9qbn1zNtHx/zm/rWklrwfJZQZq0Dz4v3RwnWa9P9Jtr3NJDzq4J1sQbWT1JwmP37PdIUszMjrDup2fuVXeD3Lxql4OF21kikhsQJEpaMkPD4l4yFVxV+T3KxbwzqMttdYH4LvqQj1lDttfPWO3Avl5GHqLunJKd93pkrf36m30DsuSMjJCoGCQNZv7V7oPJRcgFztLWeN1cZBcsmUh+3BEDY0gLvyZwb+Pt7/uT1XZdR/r1u72m8mfXwjvWYXnKaWJva3ZW62j+Pilnp1EiyWT6OedE5EnY2kNEol4G59TX8UiTkc+H3LR2BwpGhKMs5LzbfgV1kjHyjJLiOk1GM3LS591yxhbV2Z7iMLdb6h0PJ4uBxYQiIsPZX1ux9OV4yN27wdRVW0xsOJLJmqEel0g0UYb5Yzcz0MSdZWB0hnKT3WO961qzwTLhW3UDZ3tSaJB2XmT+OHtOQh9xxPnsM2lCrpmxlf7YuKO5oTC9WIHwvoyMX86hjp2LvMTwhRbHPY4grEoAty7KixlsZqyupeBuhwmPVAKwtxRzY+pLYc6SJp/TtPSU1pObgnJwlB7F2csZFcz75vZapNiM2XiLbe8pb9yoLUnNqzKQ3k2UDP6pouS0KL5hLPEeouNqETFBTt+/1dGJ2Tx/qwLfBKrZxXoaQBRY2NTDTLRAWZ7WaIaMxdaw1Pd6LXJbAeT9Azpse1hhHyUrWex/XtuoYo5HvbrEflAj8OaHhhUK9Yy5LclPRfzP16zFr6JyBHS1ldNkZjhInW2LKMPI3mXYCs4d1tri1fvweee9oA9N+F+bbMAXlWss4SN73uC1DZ66sldm015AmF4/CGHJIVA4V60Yxs5H971Ljs+fQEMHafhcnIS1UwtBHDiT7cbzKmKi6V8MAct+V7bOFd4EK8tfRcSTdD8tZJ0kfHXi2KQjezCKTP88QHeldEOFw4vNdBQ86yXh4VUWmIlMF6/08rYeJtjd0TF4dbe+hX/GchImv74r1jjALx4fgIeuw09sgNG8yT5jYht/ttIYb1NeLd8lNnirGWuvwOf5+ZK7Pv1kjZSUEGwa2kWOt89ZuXSGT1VexqJ+KrfQHv9Eacsd0xZEqDnR8yFzZk3zH8UznOEwl2293SFh4W8cZ8v521szH/0s664AqsjCK262gqIiu3Y1dzBwDExEQCwMDUUSaF9PYir0qFgt2YmF3d6yxdmF3C3bsmfE/g5h37/ed8zvvzXz3CPlxOnvsLzJALxVvyhv4Wn6+UOXzfjFgroJDMTa0UXSEVyM3MtuY/j25gozR3Lc8C3V836gjbImOF3k2it+Za4edZqbKMGfUOZH3iRMu/Lrlbn3hPDkS3emn/g0SsIzr3mQGWb61jOP7qBMHNGyl7oRGSNhRMQyp5IhZvblHA+kpkwYxz0soPtCc62rA3ky1njWfOrSZcKiqjiMLuTatdggnmFdz9dFQjPn4/Bzyyc0jgvm8hHBYwkyyaNWKnthPTipXKwJlxskIfjlYdPzDDHqzEdxZG75k7BtGAl7VqoHv7FHzs5g9lzVrbt2RAU68+6qh03hqxTcde0c2AVp6W8+yPsjB3EifspePhYNrWpS8MthHwZaurPV+Em5XkuHRWUev/SoqbPEVBrE/fC/a0X6bjFZ7yBrcv6/m/fL02YonSuJgCw1tEmXsIwellqK3Z04UlkdLyJ6sYd9uCdPsCfDIZ0edD7OEgqXtOM/fnTmfe0rtmsT8lKLp+Hy9Ey7VTMDDb07kpBdU7aEiKd6GGuTLDE2xZmbXuSYhlD4s0odaZr0VQ08XFm/T02c1GSukM8eb93aVIXPUWcys2IX5bAn5sHuQ6EPm71JURSfywtMfMtoUUK2zGdNYPzNC7dZ7VcuXU+d+69YsZLmGgTP3BqFHzW3CS+OZsPoDtagDPZZ99nO+hHzRsjhxrcR15/dM0fGT2bfoXvYes8gLLxWGt4ZT3IPjLop1j3bkYs2a4x42RcLDcgaSbtYV/TZECEt//5mDXYc6OfBwLP1dR78IA5ns9Yv0yvKjbomN94UiqPdZoSp0/PdVhqNyjLA/hb/vAnWG2t6YGWWZ30j0fS2h3hoZWbMVdP7O7DT4oBCyhftcX8Zc1ok/c0S2/hoan9cx50U+MTyHEyr9bAI1vD8Z4jk1rgb7/myyik1ksO3/atZZcuc9HfBiffbPlNDxmITgniqUoxI6bNWwaoiBsQ2YY9MlNDpcWly0l77iomNjT14Hs3Xofg2/mFXMz5yKM4v4Ndawh338zwrmgRjNmtnxuJCM9n4qs6pkPbt81vhzr/LLe4FYlahDTS6Aiswo44aniCWZ5QJjdXhTJ10rROMwf8+KxxKK+DYRW5eScIMZfRK9wWWEA0YNGeOqemE3GXbcUvYb/XTgPnojr8fnq806D+YJc1yT381Fe0ED/V7qeCTI+NTSRn6Nhs46Mz+fP1OPuehfCdW7STjiL2M9+elSlGGdZb2IOWFprtPisAwNcYND0PiSjPihJcTuLU+KE6k/xdJVi48ndVEwkv93ea4Dd57IWLrAwIlD/bDSy45yvzSUf1UPQ7OT/acZaNpTR7uFTjTcLGH+DR11K20S+h2NxChXCQsnadjwQEL/3AaWPRyKyeXjcYQ5LeAO65B+eL+ihJA+Etp6acjzXcatawpy0uN+szef07edyTp+D94gPB1GbSmeKswh1xdaqluz60adVbGUmddJv3KZbWDe8xDMeOfAxxCIVYsolhdcYR+cp8efqa1Cu/uPeP+KjKhcBiLJLmuaeYpL350TH78hI7bW0ZB+soZ6GDnWsM5vvMTa7ViSOu/DNe6toHJNZuItNuszq64LdKx8RZ2dosJzvIHtjyaJQ/YwH5y7KA5kfdbL4t5OduJQcdn6DOvLVbIadURtriOn6QdrqCPpqmDmlMKzDAwhq76e0hD28zbUexSOjvEydkxw4OtQ1comDz/xOsg8L987Meqwap2Zdu6lp1DwlxMjUpzITJkv+ND7G8R3xU1y6nSV+e9CNXGZt47koHmC5zv215cy2MXrDg5yWp9l215pmP1cxu1+DvSSmD/Mcz792Z+nFayvo+A7e9Kc+VmzowLpvIImfRtgYwsF8gsZ52PaW7Pln25XUHKaE4WPV7Fmpm5kbhjYklq7xhO/JzRG6j4Vj2w2/CDjnx+ioFuNX+LKh9OESo8k5KQ+hdeX8CiQr53s3jrSwD53GRuCHdiUi7rCDNDjiB/O7TTPGxsj7g1pBU8vA2USFGSlt8L31OviFOpPIJni8vGh1vmFdy9JcKFflvn8n9iM/FpxtYycQxIwR6I+XyEz0ju+sjbM505bqdPE/rlsOG7eR0FOmthChudQDdkFHWcLh+N55aE4U7E98rqRS2LZLzq1dLwDaR1lbBu8RXjxZQAKk0Ua9AtBn70KKtllJJyyI5T/n+DILj7NzuvMbiAtSsZU7tuqTQbGUyOPszeVpBjr+ewJu8z3iJnlbnJdqclP2RvmPYbZmNl8mPECdQ23yMitizmwkzmigqcN+ckPn/Yr+JZ/jHhOlSz27XeXddHVGzZy7YNzZM27EmJes+cd5nnK3vBjprsy3UAq/T2rlwHcSBPHkzPMOUQ1Zkm4SL2ttFLGjUHMe7u/ixmXqX/XyO6pZPWfKqoz52a2VrFlJLMfe2Q/PSCD/RqbyX46d1x86SpjAHOROePUZ56BaQFkiwAnsjOzbsihYaSPgffeutCNbOhDVnri2h532Ot/0w/+80jAXOp2Sjqz918yAv/mddF/4nv8YbRS9LBmmRo0er1MXS9JXjxL/89J3zieh8z3KZ6ZlpnDg707ScJdLwmlDSeusk+rzTPPHaCm0+smNOqNEns0NCTb9CeffzqtWmclumyhp/wj4fxNMnSweR+HhoGz6QWtmam8dJQamR1f6I3vO9oQQE3sPV9A7MIQuOU3cI+10dw9DP2qs153q/g5ra/gQe10yWTWnO0rZmdG79/HhgURKtyrSBgbmhPL508W8vYhk52mN/o5rPsVz3cNQ6+aEnZT6/dQC5sy0w7wNXD9o476ZPsnczUse64j47oD3S4oqBFwTpjnT2+874d4Mu6QLtxHb76eDyouZtlRtA+5ld+7inl7MhnjU29mS7JDi3olcMJk8H8VDD+ho4a7EzXLKXhMPirsIaPfYwX7qXX+GxUcYP+Dmr6WGhTAvFLlbk/BaEZ9j9fwIS2CzK5jl/ms3eJQvLkhYcoFHbfIr/1HcV+ndBJSPs8Wqth0dCWblXuiocEeBXVYD+/Pq2iTruHxCh1Jl2W02xgBP13FDGr4mG0x+PK7r9g8WMKCJXbkPa7j5grZmhdaNkZFu0YOJEYb6E5dE0ZokFg3G8twb3MJ4o4wBypurSI+HKFireRE9+sq8puvi9npOOtqLOv+LX1sb6SKIjUkjCS3P22vWOfNuftGIrGDgQebJBwtHIweZITeDQwUoHabZ5vX+D7MerZhbBj7sVoPRGTSpxbbrRnH++kRY9dH4/JwJ36cIIuRtfvX/pObclUogajCGrLRb+PJ2fZJClre4/dsro/wAAmXyeN6k2j47yUjJnC9yfmzFsrIy15LZdZtPY4+1suJTlsduOQ7RrCRM7uaz6MVpz5TU+rT67+W1+F1X8Ig9n3OsxKeMtuMduM1kEGPbFaxbqaCS1n08F8yOlxxYuNRsml/w5oJfJ+9edlnoPBjjoKDrG0Y7hhLRvDgazgQXR0NZg+Fmb9D+ysYdJc5u2SwNXv/Ti7FusdtVRr3+gF5rnVJ3PVV8U+0iuju04QZE+lP7PnS3+i7izSUqiujMf1za7SC+ey/feSgsqyjBw9lpNA3n/fVsPCME5W36QiZplr3O23m+p3IZqA396DzByfSa+uIbUdGpVZ2qGDH0hDmoCyu6ToJ5Qs8F/ZtMzBgVTBcKioY0kHDz9B4pKydJ1xqbiCObFSpUjnUKn9daNxYxoK2zMfXnbi+SMZbrtWyVbyWO8x5HaOwhexhnguwpJ+Cn+TRjadsGFleQ99wAy2y6ViYh1mdOnYgPRw/NQ2xrSR0+akgJV7BvW8S7GavZyM//0Mfov8/W0q+KSijVoZDiFiuIWJ1LAYf7kJtcuK/BaPE9syUJeoPFHfPZz7KtkO8Sg7bTl94XJq50P26eLu7hDb0gkp5nDjax4CXoeIa+64Ha3Uvff45mfOnrGI9mepQPh0J/asjrKdmnZvuRT7ucFvHmylO6xzcOHJtX+p+f/b+pcEaisfeEH4/lVDwtgOlS9TGzql2LA4xz1C04149GZ2G62g6boD4e1sB5LzpxJkrGr4x03zfKeEt2XZ5MeZ6ZpTwD2Trwcxj1JuCbWSsm00tqGRgBTX2w3v2PP1zQaiC7sxbkwurcGRGCKMyJOtZ/y7lVWuWw9jxCwWXYgmoQo3pRH/L5HXP5volDqsmnjtJtqWGXXgbKJqzjJ6XVWDOGzef/0xeoqHzSB3Tq2twayLjcNIQTDgSiqhIB/pWN1AtTzRO/q3gGnUtLZEa2TtRWNOeOtCD2bCciuaev8TPzEQp29xFczbuxSFOTDeZfmxLvCUXrj+q48EcFbO3Stb8mvmd7Jj9U8d8H9E6U888q2ANM/GEG/SnVU68pj5vpMbNu0IfJxP85Bp0+KEiijlkBVl0RA+uzWgZ0ue2UD7YkMP9iJgUzP2rE49dhxx44MbcWjIGh6i7wVkqhlD/vjBrl7yXV+wwP12stcvGDBiCQyLzwmsZbZeTQakveXQPOBeo1vkAHqxbc1ZmhzT2DddyHa/rxroQ9IsqI5rvlf62aVi0krqxWbOeDb43b6SYRR6/kKbjWzcNUe/NsyIWiJuv8fWznrvtla2zpl3mzBVmPyDDDtCQ2EBHmwAVYn16jBGF6T1zib/J4h3Gath6SEeuWzoM5uRE+qv7jBVi7wrUen5vm0IaQqZmCEHUxdcFmDNWKShHfw5bFY01PxzYyP3/+CBAuFxWRS3yY/wQavFqFSn0uYPk1PfUs4WzciCveda27akQQk5oRU2IZ7+afL++Cf3SPAdxBXNK0xNCbCjZbQmzNFmmVJ7uKPVMR3tRwu0EGU+qKlCzAgXzXLIlNZlp/cNxnLkrVzsdR1Uy2A4NNcm4p1x16L9UbCSLbbg0QRiax4bUau3h0ycC0aFO/BxFDqxiYNBzDYfbqHiWm/u81VXsSy9sGhAPd+ps+Q/ky57ThAKTeqBjpIKlbga+cr31gjp+HJZwphbXi0xkPnswZJCGaU15HZ1kFK4uI4J59TDX9dWx/eIdSYG3S3v4xaq4nW2F0DqjmrhrtwY7PaSUKz0kv7v1zOaWbgrwzIktXxTrDDPzs3B7BxUJ1Pq4O/PFpAZReBdnoG+JvUIHemt6rIH7Gaz7v/8TvStRVzZKOMHcNnenEw3qMnvWcWLcJgVT8ztwmXpTxXwGpaiBQt7k7GEa5pCpLyyQUOy4jNXXxomhi5nv2JMflrEWmHO2T+WanjDwa6qGCqwZ1whz1ppuzaiwh7UVu62RMORnoDVv04ssl0HWKzhbxepgajR5cgW1p0MlDQmf2mHMlQAMoG6+GOiEX07WMTnChwyYl76Ug5n8Fut7fqCCsh7d0dRtKHoHu4jDyFmbyemfyBTZ3kvI0ZB+SCYpt+fPvejR3P/9qQ7kbqigy+0Mcb1rX9SuxK+rmoCm7WTrfW1z5nnghxNix6jBggfzdSY5qWu7TcLn19zvyQ9F3bw3uZCK88yta5d4Y3/DrohMVRE4zA7zOcrVKxUMJAd8z7daLMQsc6OfyaMGnkyTMV3mz3/A7M1eGFqEmTCXBPeK9KEuOsrTW9aFO9G5OrPDQck677oSs395erbJeR/eKmh2lVpEVrw1MwD7qMVaF+bXy9RYrscB6tbMDhKKfnDg531ycg166avqME5LONJYEcxnilI/K9azDtlPMf9G98bH8xI29YtFA67trsSW4j9tw/HkMJlmFLVmvoIljyUUIHPlTTTQ8YIT9aq7o/UlJ3aRby7FKtbz+/H1DdTUDJyo9lJ0YVb/wLqaxqyQXFnFZY8Ya9b6/uPDoQ1XEPJIxj+ZvkJcTQ1e423MIwbO1WD2jg5HveE2bGvUF9Ppg/M2qijFXjpJxjI0Fb1eUm8SAsm15NkU6nJlA6H08o17ZPhe07C2goqKZcPFnFzfljvmChXYy4fq0v/J2WGPuqIne7r/iAhMW6ChxHVq0wUVhzw1+F6U8OFzAySSBzrxNb3qZsDhpmLZy2ShVRkZE0upSL5YSGw7NRbxvJb92SQ8GEadtymorscjJ/t5JlnqwniuWfaBYlcfDafInjFBMXi6WUZ4dg3+3ahvk8mjiQ4U66Ji8DsdT3JUxbBjEg55FBTN+7YSRId1zs6DZgNQjXy0s2AhMZ05x/ys0flQh2eahmBz1kcJ9nVu1TrXcaS3BDVOwpxDwcIN1myTHC4Y5KQmMOemMefvcfGFc6qB6nd1jKaWd6wUTebUMY4+M6+OH7pTIzY0OCaaPO5Yo6Ai/bv3K2bU9RIOztNRtpV5vrWCudOLwE6/+8neKRihI3WaEwFkfIk5su52ZtMbOtKZC8w55x9/KyhQQIcb9yOd69WBvWLeV1yPGvswLhd8qB0Jw1XsXRWBPkfIUnuicKw1WeMX9X65AvtvrgPrpDfZ3zx3p13nrYLbdPIwvcb83KPjOdYhX+MU8kdO+m3pik7MYg5b0FtGm5zswRsaVtoMyHPiEFbKgGvju2LrtBjMeUUtmxuNm38ZGByuYBZ5qnuXBDTWHXhL/g2KYc7KcqDaVh33qc+5e7AXPXKjtTkTqJGKEZ10ZP78WzRnX01uOwx19Z7YRi7tQ206mteJNew3N/ZB70fMJcwsHSdRS3ziMaqjgWeZOt6TtxrftsNz0VD8DpDRNC0WHu91TPbQ0G+HDWPI28sKyHjkQu4x9TqZmkvNuE5/GvdVR4UXMiaXtGPclRhEcv8u1RstXF84GPuq+mGEslUwqsnYssFAWm2HdU/lWe7HBHqSyPr9p3gCBi5xwFab/bK6IeqdVjA6/xrh8xonWqZK2NyTPMcMHdpNxqWBGnb+0PGMHvd8ehQOsvayjTewbpQDtTob6Mx8eXinynxvWLNPvfNp1vx186yhA9yPEftVHPezQcqdD1WcfYR8GWSg5T/EGHIghilwDhqOwazF6JOSNWvUvEc43qsIWjF7HptKr+N+durVCDsfa8hFzas7hXXXMgEJBzVcop4N+hyL5G9vhNrMOiVZf6u3KGjbV0dzkyFXbBdfMtObZ0JVnKkiT6qORl+pHcxbxb+IYtCm7+In5t0WU5k769hx6KkCT/ZGrvPmzFDq6rdNwvZxKhbWUHHrqIa/Sun4dxF5hJn7ylCy2cTWGMm9MN97njvEQNnr/LnpsvUc86s0rv3pcPRbbyCATBzB/FFlko5zYBa76ET1JHrUeidyfSaTMYvsfqFj6MdIjGQNmGeHLWT9RZUxEJnGPPuXi9gsN5nlkoLizKUfKxrwp4eUOazg0WwJnp5ksWkfxd0HZFwfqODhhu5YMiBVCA82n5PfIGx9IiN6sAOeuoKb1L/mM6tb8yvWdlJRJy8zRrB5P6UD27f+OWOjw/G31vmNh8pKWLHLgSctyafUsy45Lgutzc/d6SehI53Y/URCrVkSal4Qxfr0JvNMiRPMVOfjUsUvB0tgHDPqjlwj0MJHxfQlQ3Hsg4q8vIYlzOSjksg8+ZiR6JPn27LHWOtTG9uxaLuOvQt11FuvIeUM/SKFX8MabN43CCt/xOLNhli8muVARJCKb8zx/mvKixlk4qiBXBNBxal0HWZtJbL/ysXL1nmL/9H/l7NfxzQNQrkYAyMPt8XwIzIeJ2kw53Uv/Ye51zCwfjJ5KpeOMF/Dmul1IJK57ZPKvGSgW/IKsQX3fua/9EWDzPpSRronPX1wHLKfjod5D+Lca6o1d978rK3PdLLRfBm5mSmnfonCoQGHhUZ2O27Ty865U3Puq2hCDso5TkKWmSGZaxuXljCDGTYkvjfu1tCQUVXFX2SDy1EqFGpeJebqWat0bCoq48UWGa63nAgiX99hPvX+VBEXjtnhNZW5wd2BQGbTFsWc+HBKQSRZ+Cr//E+eGFRfcMF6dshty1/i8zsqumQ3kPntpmh+Vjcu8bzQ/MEeYQ9//us61Im33Jt79N0TCr5eJl+nvRV619fwlrVfnjwz7byCRg8+ioMDNYw/1kfImc9Azya1xXa1NMxmnwd1KYmVO+gBN9oLwe2duH+LPRTkxB1qS621MhZxfY8z75eLU/AlyRf7ZjBbTkkXM8li62c6UCVaRWFf8k6aeZ6sQR/QcHuiEzXXk/uYv+MfKlh0mP06Q4OrRwu8maUj6T/qgIuM7oFOVN5NLqV3xRo1ceb9H4/1Yc+40Ycrm8+jsFc7DYtA3G0JlZh/oot/FO/Sn3+1URDUdIL4Lagv9lYzUIJ1vfUOtbpQKaSSsSJ8JdxjzvvYtAliWZ/T89jx4M5tccsuJ/JucMJzNq+/jQS3acOwdJ2M3g8ikBgVJMw/xuyyTcKoyTpehJJbHik4GKcidYiGy2uYrZYp8GnArMlsMeER9ZY+cSJmq1CLLH00QcG38Rr+zpUivlokY09fA3vo3SHtqevUrCrPRuDpLxlzvUOpv7uEDl4q3IbK8L7WF6OFv8T+48igP8iirPt3/L4IZsYRIczG55kryeWB49ohjLl1cf9YtGxH3j90TthXMC9KMX/Egms6S7POHFPYm1vYdw24hxtC7Nazp8Wq90Lfvw2cdB2JtCgn9+uDEDJdhyYqmFZUx9/ct2kOB+6t+XOe+ep5gdCiNIDa+e8YDTuexzMHx+JxdIB1hslMemF1gRmG3PyZfW6e/3SloY65/PuJgjIaLmM+G3hYnHhKQuPPOnpJ9MwfYbhGHt/VXELXjjo2D7ggniit4Wgi+476PeuNgqL0oifs65QoH8F83+YRM3xECxWf1/H1H3biFfW2dz9yjqLj51hyJOvQhWvkUkXBzhIacpSUUZr9fD+L9f5yg3BgM5lqGpk8jjXDdbnVVUUaeTHM047pUTqaFuAa08cKcR0mD3AgnF+bEqagJjPegk/km2+s/wgFC9hbl5s5cY75eFOcjkr8Xd7rHWh+uz188yi4+9opRl8zz89RUIKs41WCWnDKvO/HgWzshfJLJXSgRmSjXh7gNS+3S9a5MScvyGjGrG2eAdLnEJmi9GYxqqmChnniMDdygriygWzNN2xX3YlG5DLz8wiTaVfTF/5irkjuasBP4LXx7wGShF9Vvwj/zpCte7PL1ZcRKKrYxDr6tIK1ST3M90DBIPbHAbL4GzJzoA91uW4veNIbK5TQsY4/I32kDteJ5MMOQWiWWBlqeiwmujMTPhwuzMlOJnOdI8x5y3ohCyh9dP6OeOv8hGFkjWG7yN47Zex7xXzZXEXsRjtCdxo48oycGilhySQNrdnLJ5qpqEkeuPBrrbho9h9ejg6REEAW7V3OAfcoGxrWVzFmsoybi1VsW71fGLx8oFVHvmc1nHSPE8yz7nIvkfDMl2zqZ6BO2REYm0l+X/BINJ/jdSyUEck97L2Rvl7cwJw1DrSeq+AitWUFbPCuGYsFZyXMJovsJfP9HqtjOZl9xzYFmwu3xRKbE13IMMs7GWjjr+Lvk2SsI9Qr6u7UBBXZPfpZ515mbNDRuLA/EsbrGN4qHln0J68mmti3CHsgD2tRVdCcObIOGbvoOxU7Ewzx8kzJOvPEfaCMZYs0LKOHLCgUju7MX2WYg49k4xr05R6TSwox+2xjrQROkLF3K/P5slXCtU4ayvroEOY6MIj7dptcdb+BBjVLwWmJtcfr8wjQ4U8N9+0zAhr78rvbMeHAINa/N/f/i4JaW+nfrL2jeQ3Ub6xj6lkVJ+NV+HsYWM284tmRLJCLXDtaRsaUP+fMHyQHr2H9ltB0NODPKHWb3sG9XZcUhx7Mw7+/088u2lGuEPWoPzWU9Va9jm7di32UDBD2Kx7z2Q995wXAlbn2s10W3tfhelODH9KrtsXT93azZztrcJC3JpbtLFadxexmV3D1hYokrsnrJho2Z9pQK1bHbmZol00qwuexV5lpLi7gzyQjhwbq1vNVSQPIoszEbfwlVHuso0cO8sF+CZ2yKdbnvY18u6H4afIEa+w31zZXvjg8ogblP6HCr28YXN1DsXpTDtTxYZ3dkjEoQMMFL1+s+9IPs5Zwjb5q6EbWnliQXJwyQRzO6yidoSGzrooHUzXMX3pWKKJoqB0/HDv+03CR/D2Yvj/h3Hrh8CoJ2hCzrhQ8j1Lw45uOvHytnXzJ+tRUH+bwhtTApEAFWT006xyCdvSgqytllCXTj/9twx322Dbm9wLs83usneJku2lfVIxupWJxNgOXv/+5xzezv8IMJWM/M8uodwqeMPd07mKHx0oH/ItG4sRo9u04GT8H7hNP5WVmZj4QdvYTFl7jfjeSYLzRce8Iczm17tRYBS3X6ai/xYFWYhz+PaxiVx0NOQ/qeDzyj9cfbNVd3Eb2THvlxP67XNuFGgreiBMr95VR/O0GMUBTmQcVeEXJ8OOaCkeZLfoE4eZ7DcNulBbNGe/P+/W23q8y7w8y6tLX2H9lt7NfmPP2bGEtxCpCz+vh1pltG9hnTSpQj0oaWGWev1NNRVBdAzPmMgtdZ722V7GZTB5fXUcGr3WkN3P9S/bUBQ2fzquInuJkVmC9tHZim5+GWvRp924q3lYh443TUKXGCfH+6Vhk0R+Xe5wWxp1gHnnL31lEwpOVGtzpu41mKShrk/Blfbx1f6F5bs+lAeRCD+4Rs1ejaw60H98ShVZIaLpaxRd6ub9WBzL35ljAEqF22BDh9loNZh6aXElC2BPWGll10Hbm5aoaZvj0xcOeKky9vL/Nhpu602Lmb2QWL3fmqv+4DlfnCUfIJyVb6hhNNnt6h/Wwj5k8krXe6rw4iXt410iAZg/AtmQ7NuwtiA+DvJH1rTiO7vogViHrmO9XnRtqIJi60uIe8wJr1Pxsy6+Sgi4rmLuoFaWbMI/bZIz/qqC/+SzPvt3iHPLLyS6txXYv6FHUkonk6yY3NQQG62hVXMfDRlfFAX4qYpixTlF70rZo+E1m8qR+/ua+/6xhINU/Hk9H6dhJby9BrVnZUMPri7o1M+qrj4Ix9ULg31nCxqAPwpMacahmY/+xV8z3UpM6qDAzdbN/c4o7xtmR5j9b2NJMwodRBma/GY67hTeK5lma5tyjOmfeizW62zCb+nWocwIiqBXvS5MJqXljqR3r89rhN48cXYK9lKzCu1o20ecpfaSwjiZkhsZkopz3UsRVX3R07q0hS5Osz8t0euvdNPZbIPvaJxCF+dqbTDKwwEPClTwaOizfK5pzfcqMyBTM2TJzCkmoTS4owK8Xd2jWnLHO1MADO2yIL8macgvGFOaJiU/InN4a9rDPay0wML059Zp9NbyrHRdZ2yndddxgrx63J+Aoc/HGhcwG2RVrhk0T+o95v8bHIgpW7dYwYNwBcceM/qL5bOHSFDtakafcuhgYkaMjiq2RceOnhnG+Oga81TFigYQDYTH4GCLjB3tlDn0gbp6OlNsqrsU/FOK4fhuT6XsROuYc5tc8G47LHbvg6gUBIjN4cmsDiXkroMglGSPHkTeZX5NWqDhCrUpl3u44j3tWS0bmag1tgyQcbTocY6QX4nrm0UP5NRRo4UApMkMme20u17ccveYTNfznotq4RBYxfWL7D9k6u6pEoIx2ZciiT1TcLfXn80N/cy4S/eyc0w0J1NlZrRXkqG7gX6cTI6fQu4IUnO/sxK4+/Nn8HePPynjFfWrxzZzzXlBsqihWHXzvqmHuVB05QunlmczjEyVsqaVgR71A5IpVkCfDQI0fccgz0IaHmZI1N2pD7mjkpW69eMR1NLmrVC/x54IgYfN8yXrm6wp1wXy/3LyP0Jzb9ryOhJ9PbThMbZih6nhH5jo7zMDa51HW80JuR1xQjl5gnpvpv0nBFGbEi9t0a9bpSUcCsqgNf9Xtic7OwWjN13q4hx3L6BWHuM9/HyKnmXMwSgZANWuxpI7EiyqwIQemM+dvP50klsQn0YfscNdVsT5bXf/MidSeTuF9Gyd+dKYv/Zbwso+MAcyaSnvNum/LPJd8eEUd1+f2t54D+pJBrfjEr6M/HQijTo0m77XZIZ5aoqB8sdziTeqx0NGGdfclHOum4MJZA57M0SWYicOy2xFzyI7i33qg8Q4Zj7rfFlzXM0tvZX+fyYGvOSWUrS2heEI4vvk7sP46/X+YjDRmHx/ml+q5+iDfHB2fLui408CAxJw+i8y84U0NFJhFXaZPHRqrIpIZXUrXIXbW8aEce2qvhnljDXz5VAAzyCz7ZppzMIaiZTi1gBy8/qoiuKeqcJCjG8TJGJJnOKqRK08yg1WsqqMwPTmYHtB0gg0He6iYfcSB3EYwuszQMazyOVEhL7medeJGfHF8Y12/76XgGrkvMYY5+6SMfic0JLzzQMwDB5qQ5ee2oL+yfo7ldkWXrToeVdBw5YGKU5kaKjVhTqAmr+BebgvScfOeB+oyq5pn1v7uLGPVONWaJ3+O2p8vLRBhHS6J7bkG+5nrK+enP+VUMaClgaztGrqn2q33TnYeZ5YhQ8UvJpeb2corRXxu3q/rJSOkrIF2HzXEkHNy0Rd7sAdTdymofzcO14oZ+HVXxnrzWf3fKj5EssbP/NFtG/elwibJOsv8F3un1sWVYjZ60Ghm8i0bZCxkH12dHAU3ZuxuR1SsbKDifMHbwkpXFdPnagj31nEhTzRGNmLeJi+W2WpHJ+rzTPLelccaol/I+FqF2ZAs0zxruhhV2Buu/J6g3BL2ddSQv30esUzEfeEYtXpxH0940GsfMSfumk8ubGRASxslTqfvLstYK0al6rhEr7alRKOniw1nEsjvp9mTzCcrZmuwJzpROENHZpaBuGT+bHLUEDL+m7UqrhfQcJ+9OGKMig3uQ/E+4Ks4xoWZi3zwLHmeoLGuzBmUaSt74SjZo635PHqsiqLU+nv/6ti2cqnYiPt64L2Ec8xo8a4jcLP/IGyKlNHpsYz8jQKQQpbIzT8vFxrjIuugfFMD+QdpmFw1AUnmPIHP3oJ5lvsE9vS8pFQhZ4CKy0VCsIj92J9Ms5e9ltr9pZCDtWmeGzCyuYZ87/g6njM7jDTg2o15ao8D6eRVPVq25jDNZM0cPLVGrFg/CJOo/fUHBODdI2pWrpZC1tmngvlcrsk89cfbcfyHjqddZBRJj7J8yL+IjJM2HcfpqTkjDBTLrqPmSQmrH9H3zNlCp8lT/sw4p7hf3ST887cCvZuMqdyrtdfNmZX0kudOhOVeJpQ8QD7dTj5uSWbVVZyOpm6U7I7psRrKfQ+wzkq8GXNI/OVQMXcTNacO9e48tZisn599Es59fEBdN+eFpRTV4HlRxoFwBcndHonzNA37WOOXFvPfqL+zltGfktuK5hkit1qy35iFvpJXM1sYyFdNwuPFZCkyTmqgDYsm/5mb5c66ep2sWOev7XLR0bG+hDaFFSSYZy7WMTB5gYbyru+s+yQWLnMiZnt/zBpFPWWtzr7J37tcwyDqka8b2VXSMTnNPDtPhesa3ZqzWSA8QphWS0Pe5TrytJQxLNiO7p1DMaiCgpfJsfiHWenTTieKk3u0Gnxd7UPx31INg702i8JcGUVba9Y9KtcWyAiVw8TrX2X0oQY22yWjV/aOYm7mng3dB0Ih100vmIBop4zeH5ix1thx6wY56bOOg5MVPKQ3pZU3UIZ7mf8vAxnZVJSsZWBHMHmyuQL3nSpqNPslCoJqzXiZuEdGVXMG2dpYjAqmRpP5ilVVsZ5sMT9YwXIyTys3GdMSJagZEkYlyKjYRsPxSjp81jmwv8BT0b+QjhJvR0C87Idnr++L54br1n1Bo+gtl0Ykib0bRcI2ijmCWj+K65n1SrKeKT2wUMGcdRJCXtMHWmkYRe5PIQ9v6BWP4on06vY7xX5n3oo77qvWzCjnvTnCKtbR3Qk6Pq8sJT474iOa5xqnkt1eD3LgF695W27yYW2ytjkr+qaOq3KqMCkn8xSzTuC3YKHJHBtmLJSRTo19w2xz/6aCyNojMZaZ+JVC3SAn99g/RWiz3I7q9NvNXOMkaunfMtmFvZB2iLxyS0cyrzXqYTy6RSjYR+5LdJWQPJw94r1fLBgUglwVZojmXMsFfuZsQgWF6svoEc7v768h6ZmO5vvdRf8uzPA5NXyZrmJoDwkjOlIbuiqICWZO8FoqzmLe3UBf28012eVJbWbGP/EsDCqv6WeEEz2eSdZMdnOeYufRgzC2qGrNrlwZolmznGoP1bHWxQvmmTzmmaMTy6rYwX9rwvW7wjo5yyzV6A7X/yp9NsiJ8cN0i/kH+krIqEE2pb4+byChe/BisQ9fs3aefvEmBxoxywyKdaJhe2bUZQ4UvyDhkr5QWJGdukGt7TLVgWfMtpMv0Ntb6ehfgnVyinrA/b+1XUUGX3f9Myqyk6ceZ+P/uxio1cOJgfSWYge5z/uThMHUtTn0po5jJHwP9henMScedyjozp5O9O0JQVYR95MaslZHKWqHlxFpzS1P8lTxZjE1bTQzgu3P5+tvcmvWe4SrPsqod5yv+4ITtXLr6BliIOG7gsJct9wTFOuZsgEr+oo1VQ3Sh7/EqszrXwrJ2PKWGkaeCInSEGE+f9SPe5SuQFidW2w91Al712b48rgEPn5WMDwveyqysHhm8F1x9mUZyWT/5tTddLKnRk+4aa8uXmC/Nic3RSY5II6lZ9GXE8uGohzXwZx92CFNR17m7Tj22c6pClZynfzbpYuRG6lXxZmPx2wUc75kLcSYs22DkLU2Gkv2HhSb3WOOZa0dpO941zwimPOG3NJV6/4+tZqC/5arOFEpEk2vqSg9SEb5Z/T+jCxxE/WiHfvZbRH5bbOMRmXj0Wot/YCMdWuwbs178SNj3Ww/AEqcn3iU+rZ6YxOcI8M1bunEEGr41IQpYv26Esb960BoHwnLsmlo+Z8/8l9xYrG/HefiFOQmA3fayix+rpD40V+GN/PB09MKKvvKuE4+qXWU9f/JJiSfMfA/UEsDBC0AAAAIAAAAIQBjwOuP//////////8RABQAb29mX3YyX2dsb2JhbC5ucHkBABAAdOEAAAAAAAAUqgAAAAAAAJydhXcUS9PGCe7u7u4SyO7OFO5uQQPBA0kI0c1mdxZ3d3d3J7i7uztc3N2/X8+8f8F3z8kJ2Z3prq566qmqtjulaZsmzdv7JIhOEFesR8+I7uHFbPmLOXpVLlY6f7Fe/cMjwwNDu/QP79FTfV43MDiiJ59H9AkM68nfxStUruRXtXSJ0vk9+f+f/6Uc7+OUcru8Mq2zV1Jt9MrRCK9c3u6Vmxu88mqfV3be9kr6w0nlFt/VfhEjne57pdpZr5zfHWGrdssr15t6JfsDr9zRvZJvr1ee0VaRC14JmuyVz3FeqTjPKyHFu+k563nlUqco+XWN5/gZcsUrbbt7ZVeQV5bl9sqZm/xsNqTKVa88SGTID9633UCmwAW20L6Z7QEnvRJ625D2qdxS/SH/Dq0kuSp5pekEr7w/4pVVNq8saOiV0vW7yqIV623998TK23J81sMrn04Z8nhrrJym31wxXknXCvkeeZElSm7s8MrwTV4ZG++V1gu9svEcch/3Svv5N7ROjb2S6I5XiiJHq+gYuXcJ2S565Tk6uJB+k03rlFmbyzMXmqeQRolbyMzrXrmSWr1vyDH+fWO3Ic95viHvy2yvjKLPz/S3PbMhS1UbIV6pkLuqrBrilXmHkG2sV9I4e8hj9LeL8V748UBvhS0mr/FK8/WVxUDvD3luLPIeWuAVv1axUpo2liPz06Ne+f66l7zBBoPuJ9WaFHFLI9p5M6CKpKpY0NY/1CuvkSUv7+ak7YbnNunDChlSuLwhqYoPkMkX3HJqildW09bpubS5xyuJsW+OVd1lO/qOXO+Vr4wjvU+ALFrKv2mn7uDO8voy9ruLXNhNm2LIB95v7zTkn9srfzJ9dNQAQ3Ox8516hkwc55GEfF4OXczI0lumJsiuF3lpyB90/JJ2SiJX/uyFteMtmtj/u+eVwoe9cmRVBVurU+gM2xT4ZUh1+g0J80qvE17Zss6QMPRcLDJaAhnrib+57dvR7zR0lKZWnCQoHC2LdkzW2iL3p0N9ZclFt4wuGSntwd6r/F65ttgrF+nbb+FbW1/wt05oG7zneHTPkTOrS5bcea1tD2Bsow1JC8btW7ySFJyUoc/R+7FBHXQ50y1dwN3FQqltz8Hh/VW95UEhp9ymjw0DvVLfHivlTnul0+9IGTw1Vpry/oIO/fSyjPcSOtUZ4xQP+o50yZxZsZIMjFZE382CYmUZNr291itZrril7cf59ifoTeOzZ0G9ZDZ6TuX1ynzDK9MHGvJ3QZS0wgZbDnplLXr8U53x3blt33YMWyPra2QeyRgaYI9X+Havrw/1A82jJYD+B7dPo1Wk3RCw8/v1JM0NTkqhx8Hg4cpZtyxQ2MzkEp8wtwR6ftguT8JOjK/a7IL6adp3/46QhKOC9EeMv3VebFUy0DEfrDZGvz3ou9yky9pK8LrmvOIIQyrxznXanLIKXBXb7jiIzjdio7Loq+mtFPoUbPKd99fxe+hQr/iM9siQFoZU5Z0QdLWVfibw9/Uoryzak0CrkhguQR8N8O3/8KvlLePkNm3mP4Df8fwT2l7fvZG8eR4pYUV5Bz21w5cfg++h/B5x1y2daSsGeVpOR7aUpWTbwdLyB135/jzs+IyOWsNfHZBpBXy3dDh+q3llcX+vVMJee+lrXmNDRsB9dcd5pQS+NvC1S3YW6ScJNUPOpHSKDfnyoo8aKRpKeF23zIl0S7M6HolE3l1nvFIr/WH9+zSvnKTtDOhnUSOveMHNq6Wh0nCoIY3fGZJxQaxEoZNNhbGNg77fucWfvuul/um4jz3ctLMxCfyErb/HZBf/5l6piQ5e4T/jeuNLk8Nk6zav9Idb1/C8HXlvI39X9BMLlg7h8w+XM2banlnTLW9eh8tGsPB0DnpsGC6P6WskfrkktyGPdnvl4Kg4SbgMvI30SgDtvitryNn3Xu3VvM1azIlpWmf6PcwY3qJjx7E4CfJ8thfqZsiF3U5Jiz4nHLlgW0076cDsn2tuiUGGN9WDpc9kj/xJFCXtsWfBgADJvdkrH2d30WuXaSOrt3ql39rR9nm0uwb7/CIG1I3Oa0sxYIBUxz5euOvkPPgeHZ7Dp4ej93TgJhPvrccvznmWaxOwf2L8rxC/DZ45wvi/TprrOLfaa/LymwJeOUBb/ivgWnRZZLxX/nbBLvB0yBC3fMZvu8I/j9BXW9rZtsQrY/iuNrab74cu3pazFTncSW6Bm2bDeGdMDc23siF+8ORdfGBujmx6Hfpeij/PQt7q9FEeTM/aYMXWavsN8Yf3d+x3SWbkN/ChgfGP7ImHNNKnN4+SPIzlRzQcRGz18lyzGpGy4G0zWUncOrgI7mO8Y5a4pQF9+ePXFeDLJwUNecqzKqZtx15jdgfLFcag5Pg6EQwyjhyaS+r07CpHkGcfY1+2sYrfcp7NzDiTEEPfgJevjP39eis2T46PMv27PP/O3ZqfDIbJnzvosyScnxLslQZnQ+lnSjO3XMVmjRlPryMeyTKDPKO9R5bNx6d2ek17HeykyZWLxPhC9E8sHAY2F4D3CXxXFN+0Lw+TSgcMyQrOfhSfautxxiOJwOcz9HoOPd/Dlg/Q+Rn0sIx4sBxdJkqK/dGDH1i8X7KmlMVWNT8Y4uvuIx/HGVIQTKRwHrDfp4/bPNOE2PZpAD6DnA6+W4B+xqZ96shK2+Fw7VW4vr4T3KGLv/3gWMbfbkicPEBfP9ZN1Ksi84R5LYiP7aTzKGI+8vaB80/y7qz3vRzR6KIiHLQNPT1KutoxGvy/Q9Y51/pJsZKDtUB017tWN70UPtGHsW1F16sZQ+ZdreQk3HQZud6kDZBV9KOw4cjtlM/Yq12laCnH7+DWTlnrgr//GPICfVdiTEnpcylxcw4YnQx2ak6LsSVCJ0nB3Cs48EgvMMf4BjHWRZ60evB+j5yjLcPHkMilhqQHGz/w7yLEhFa8N/uIIWNoNzd5yfWRBjbzStRUOGIMbR9faCtw35CxZfAH+uy8vpNMhiPs3cAXY/1X2CMZ37rlEjLdpO/XndAX3PvyqSElfatJO8Y7NDJSQuFKJ3lgLexyC64dzFiTEX93IfMSdO2zuJVU5P0RyLFo02Lbeb4/etqQDsSsGRky25uAu/18XwE95ceOH0a5pG41cNAnoYnFl2FRUuzuRL/qM/rIpGUhIvVT2EPpR8WtI8gwCl95+HyWn7wqIhfQ2ZtnNxwHsUncTpdc9PfKyolpJQXjvo+9hpODnUTX93b8sh+9oUuBUvO1F65oeY5vJ+gSK9XQ5Wt4xUbbMTy/cwS+q3LMNGABvU/nR+XST/vNs+tgoxmYdzGeT28G67V4zmV4pNKUy7am8OhIfOrHbdEqEyuH45tpM9Nvw+byhdjti26aotfMyTZoLnyy5PcQGZeU2IldZpHfzwGzvxa4JfR3jCwnVhxUuVoGsENekJD+h8yOkmsT+skKxj7/nyGZ6fcVuquJ/Z9EGRKLTufBrUuJUzdov0VaQyZ8NGR7K484/1W3rcYvevnWk6347ukk3SQrsfvUhBCpwns357SQLvjW2mi3zCZ/mNu7sVRC5r9D4IKidfU4ntkDvnZuzyl3VBwKckk5OOIsmEyXCx472UrugLdi6PIl+XtA2yR625VwGfLleTjflg47r4XHTlBzFG3+3vHiXm+Jb2hIHXRZBH4w0GOPYjtsn1Yb0hA9+b5xSsyv/rIPzk5I3pe6AxwHlov5BsvHmuh8gkeC6etMCTiTnEYDe/X5e3Va+i85QOZis9X4xK3tNkd/ZJwHTtMRG5NRB/W5YEhedFYMX1mO3ddgqylgdi56Xsvfl8jv3pciv8WeU1aWtVXLuclWtPxKh6qNgsH98Qvf/FQeERmIjsmb3uyLk/vY5y52GVNkrZ7vSivxwBlXeH8tP3PAWewiy555wGhRcuV6xzzSFP2XRcYvxO+TtJ01PkayMI5Us+CDzTlkCW0uBQfV49wyl3cTMiYVn2vBTbe3kq8fM0SS8ww4X4gvv0OXH2jvP3TZiZh8lr7m346TPIy/Km2Oxb/LqRiOLhIXHO4Ygd5jwV6hLJkdF1PDCeD/avZWEtIuTJomsvj6MjqfWNYrjWYbkoV4vsPpNG1akfx1B/VTredpbefQnZe+i1E/TUavaej31CVDaueNEqP1FMfgynO1HcGMme9V7PLj2Vl6b+04caIIGIuidp36LJf4g7GDYGoWv2ejozytW8rgJS6ZR/yZid5X164kqeHqIHx5mFFXSj82JDXfrS1O/kubXvKRZnBSUeQuTfzd6R8qUei1BzXM6puG3Eb+43D+7sHYnWdOVXVKNPEotHmMqDpoG/2+AxPjwcAGdH+R5wZim4G0VQP+rPEjVp7RR+HaxMTow4531Eqpee4neUk/5FCc9vJJK1mwjphH3KzY0SsTp6aQJZ1dshC/71Q3UkbyezK+OSjHf35zc8I7tBeBPQvb/KQlcq6CAzJ4PPIJHnoYnkJy034P7LIqm1t8wFEucBWRbZambHV/SVupgC7egZnovtQ9XbrLYfi2FJhMOLmh3MhjjcU//yZ7fp7/BOf/gzd6XK9g+zg5UIqBh19gYAI6+fa7rCzj3Z/4yHYjSqrVKiPz0N1ycqAkO92yQtWiYcW1RcT5Pa3SaA3xkX3If+cy8YU6a98nuB0bjew7QB6pHIv+nmHbbeQ62/ALH37/Qz+14yfqK/luPX7RhfYXobv+M6pqyUd/0BTvtnkdLPPxw76qHkcvDl/GT18tYuOk5UziGXrZAIccwvcOY6vcE9xSCVz1pK2vqr7DXpWK5xQbYy2QPVLa8lnHgx4Z8wS/JxfYR+5yBB5z4VfByHGJ798z5nBwm/WGxfXt8KHoW24Z3pbYlNgj1/GRvtihRCS5/dvDtsrd3HJ2sOJ5twxDZ7teNpFwdFnrq1NqEStf0+4kbNKrsUf6FZqprYUHM+CjduTV0Hc6+i+UOVpqgNkh2Gj6gq62Lvy7Pm1o+G7/tI1lFxgKmL/HNox3hrYOkDjsXhn51+gn9HHp0mlL0UUNnp1ywCUb6GtnjZT275XJtZ8Eyit8JzRPnKTZ0dVx8upALTTcK5v56cqYi3w3pBkyp2WsM8BOuthA0crhc72t+aQkzcgB0V0T5Py6O0ZuDNnlmAF3DOf5V/CI37979j/oOn4P/g22vuc4rCXDt76d9sgobPmIXCJ3L+omMPiAPufQR8MpLnlKXdYuKk6Goce04GDl8qmOFfx+A35UvrwJfJxHp9smwNXUPyf+l9t3pm+lgx1X9+v36nukFLZYDte9Alu78bFXo6w5rrXkKb/B1GB06EQP7cjFLjDehNOCpAsxMAU59pk9lg660O9v4nQ7Fe/BWIcQK75+opb/ge4ml7OwsR5c/FplSFnGOQP5DsdiU7C4nrh+nDygAjz3m1hU9Dr1PW3XA7+r0dN7xflvDGm+zJB9bZPKyA8vtYfn3LL3VKhUV/GGMeaB5ybzXLD7nj6qfJxc0gbIi8MuWUacC+D77+GGFEDf9yKt2BaDbDlr3bYL/neSGvAin2VExrVw0DeeO0DM3/bAI2PxnW2MPTU50kxiRgZ8ckLJUvIPDpsM98xFNwWI8/YzaWRi8Ri5hS5Po8s0jPUsvLarbFlJdQheveKUigUMswaY1oP8HzxcC8CXiB1v46vZ781JYldzdddSkKMcCJHX5bEpPpRisCEOYmPqs8RxfDE/49Wx47dMbjO/f0edUuGyW9ZRS83lu8rLYmTfEeUbbmkzCL4cbZix9Bz6EnTelJyiPWNPn9KQuKrLHG9Hw3/8vadwtKQ7dc2R5b1HJvVebR8G/5bBx6KxQ/6mhtTAxlPbUZ+ij60uQw5h9x9gseMqK/41qUtcW2uYcwyXeO9hPsPMo2ot7+rYy2e968IHR63c6s+uYHP+cwI8VgN+bsf3lWi/52pfW0DGaJkY7JYJO+/a1ZzcL2zTf4s1dzLpZ2fZt8eK5eV4dzr+unFrfwn6mFVKg5MUyNEUHURigwrg8CLYCyD3yvEuxuTGl3ZDOsILu7FXWfLa6BrYrsEH7RAYrA92FhTwSFb0sQYcTuGZvmB/OhxRBT9OyGfraLMgNqhBrfEbHPhEe+QDnx0GL3t6JJCxPLtID5WuuwyJbxIhHRmbZhhyFp+b5kzuWIKN0pMHNVFzqrudUhJMZQVb0yYb8Fu4xNHHM/5uRw7iw9i+kRc8TJ1Dfvu4pB0YzrEj3i8f2DmL3gPAQARjaXgoTtLCEZlPGNKKesef2D+eMe9/OUz31DPkNWNYxrv+yJgZnUc1gYf+xent1DwBPlOTd/uTS2W9ECIuYl42uGIFeeXDZk45ka24HK7ikRZR4dIAGdU8wkw1V7bHI4H5Den6MEYaTKoob9F3C/RwkveXlQy2TYzzyHjynCXYLqtvnClTNGOtjM6Woucy4DAKnvHD5g16hspZZDkM96yE7746PbLgeowkhU+SMMZCxL6Kvl+1LNhjQtnKdpVDbkJP/p7EuoccqHFGcrcSUZIFPJYEXw1v9hXf7lNtV6jxtrYhhwSzYaOiJGGBWEmLf2dqZshwMLgKm6gcunvFQKlH/EutfPXBG/sXsBjNGE/czyFhdwzZgw/tSpXWdglcjUhZQ27BC8fgvvVToySEmJIkG/YKJc9MDf7Qgd8YNU9EzYauBuOHycgPU/JuYfpsvh8eAJOZkbP9imtaLO/nfAInuA1JmL6xxMR45EY9P3PuKSfv3kaW7xlixQaXNOzqlXy56koVYkDBKJdUerJL868YZPJuPbgkgD4Sopuj9D2f+Jidmj5l3jhZWcXKvdT85j7w2RG5kqjfrTPacyD7JGJB3US6DMJ3krQHW/P62d+r2piYFjYP/PL8v5f39bUNukkMz64aGCfLaG8+2Gx5U+Xo7fQ8m6KkM/G0aTF8hlhvHx0luxqQrys9k2P5IH/JQR6ZCRaL8+/3xLLv+Nlp2vjMZ5XQdx/0coechwxX3rr7mb4exjjyef2l9X1rHUKtf5hrEsusNYAP5ORF7G5Zgt4Dwc8f9NpkJ7hMash4sNOPv1Nm7qRtX2TIzcKxUpk67QX6Sfn6o+4uESu/ka+iinEVO0h6xrIcXd4Fk9/p62RGP235Q7c0pF7qmyBcWuFzr+Ot3DIrch9BBh/6+PwlSvZ9MWQhbQ2/3cK2AGxuXBQju+Gs3o0zaifAXMmrTtkwO499wgWnvA2qKZ35Ll/PXLYw2ql03pBC6KAbz6SYldLeoCfxMathzqeMRidP1FwjnFv+aWb7zUlVRBhTTvyqJbHHCZdX3GbIdeLDdWLOcfwqMfKrtZhCL2rpc0svc+jURIXh8uWaIZkaG6Lq5KMtR2u+5AYve/STr/ikgOcy+M/JDIYc5NmXRdfZkm3P5ZiPTnKAi8XoJRCZfenvxo9WtvRpakoN+mv8qrGMJt/fix0ugamLb3I7qh+w5rbDwMgv+Kk/8nyhjS6tyatXe2T6WTW3ds2+n/Z2DOM5sBCNnS+Op4b0HNYukONfe6hJOfQ4Rs2V8RPL+30Zry/tVqW9ovB1uaJBEnQ3j17JrsucUI/U/T1b94Mzf4CLJ2nQxUNDFpXoLKknXtFOI0v3LuQaz2Ik5ZdyshdMzxgUKVv3PnK8JC+uCk/vz5LQdgFu7PVtqW0fPl8iW6gUwT93IOf0YEPagpPl9DscWZOO8UiqDG5zPUDlt+fRRa8L/o5jellJutwtX8HxWzA0sj+5Nn0nIJ9e408cVXP89K3qqW1w7itkVGsREWMzybfo1FpldHkLvzgAZ6SYHCfL0el+auuD1BhTySHvwKEp1Tw28drg7wgwWQO/noOvulY7rbWerS1k5wi3vGnQTw6Ch7NwZDy6KxpCvYFuiiHbP+wVzXhq8rc23y3pGN/GXzWlTno/fV9j+KSb1/T123x/L0iTXHBIw0sDJHLZJcd97LEY+Z+Dl3rwZ4zKXRlrC2y9dqE1n14YORcx7mMTY+XkDkPSE7O3MO5R3tQykjGlQ96Cgf1NrujDePvfIJ4qHsC3hpG/H1W5Eb5Wbpoh+sjS4gfnvqGmLNcmt03NUV9JXk9OgfEcxKnsU8gzE/a0DaaPlDaPvE8WJcnOW3PM/vWLSd1rl21ncpMz2aNNfyoLB2xAJ9lS5pf/yL8ih3zQKoCvm/GJ9J7g4MhNa048QSbiUU1DXvZCN/jQadoMYqx9/KJkxcZgbTlYU7hq2N2QxdRAyRiXD1i+DZ9P32BIIM/GUbsUQE+PwN5z+o1ojqxjL/qp+eO9Rcgx0Mld4mRtav/fKm7v7yAvGXdu9DITrNxzRsopfC4rtuqqfPF8tGxDrhxl0eUScoa3saZtC2dQax1O6ffOkAX/1bF1g2PV/GDMY+xL3vQJOTvP3qLViuwshWnnJrzTZ+QQTa2DN4OfA895ZANYVzXj0MtW3C3225D36OEm3NKOMZwep5vrhXvh+Yd5sRG2Uvyp5mj8yTuO/DSkPn9/J26t/Zpa8vLunQ1xUoqY/iVhjKxbAh+e7SXJInxlMfmJmh/oDQ6+YJPo+x5pjVzJ6as8/n8kh9dc+/23t4zjW9YA+38dE2rfTxtSiba6YKt91Ajj0csMsJiS/N4X+V6mJ77qHkmLDFV6Wxzf8Fp/yTrVKwMZT2swP3mfIf7nVb4NtzD2gsS3Zic9Eow+gsFPBuxnB3v76rjlD36vOP2Wh1rwfYC8JA+pRI18GX9czueDa1jrjA9pd1Zal5RDL36lXdKJfO/Ww+mOZPGj7Wp++Ddt5hk6Xmu2tbdUh8v3bTZkG+OO4Gc1dirXGL8da81tH2dsPvwMWEK+SpwvQc6zekktObPFIyXwr8nrDEmQj3i92JDy0+NkY80YuV8Auan38jDGXcl6SqMVP7RM+ON77Kk4tDjY2kDeeZ486Wm2nHKUsV4pl8H2ZoFbmvF9BnQXie47NkolkeDkEHqPYizrJ3hsaj3hEDlUn0+95TB+rXKcnNhoAzLUSBwi5dLlMOd3Cp618h4Vc5edby8LwENeVTOpeZZm/aQynPiEfobDn4Uuesz1TLVuUjPf/9belll1XsVRWRxrAl9qhcu4ZSb2DVPcQbvjsoTIokTkk7bGtgqH5mh3kbtSsQjJje+HwoOfsdE7nxjJSWwcvyBQ233HqnPzoOPR+M6+Rm4JbhMn6eknAN2U57mW/02yfwejbnxt2GmXBMKrT1Te0zRSjmGzp7QRP578CB9d3R3cje4tAYnBJmNoQrtRFwfISOqdE30S2T/W6Cuf8PcuEeC5oleGPrDmZm3dOkr3x2f0QfPa6M+C3JKWPLntGUPKwUcpt8VJNfh+VvQ7m7bJJS3P/dN/IcNW4mdmZM7RzZBRYLQamGmCLC/4d4lXcAX2yxDrlu9qPp24cx3/aUuut5J3Tv/1l/lgdGfmaLlS2k+motMiba04fBqcqhpJ8ZSqDdqnKqi3GqTii7VW/pDfiWYP1FXNXB1OuYev3e9Jvlz8k2OBWnPDzscZ9wvGuYq2Tk7a4ZhbzSntW8HNFV/aLhZ3Sf9rhrkXYULrdw6VA/Tj2Y34Sg9q9099U0gaMJCKdi4h68+pBWxqLWzmd0OS1gIXh9Ta7wApNjCHPECeo+Dt35GU+hPslWhoO5nZ0SOZGfsX3j9Ku23gz9Lgqzf+0ppafM2IJDIUW+brkMcxE/l1/KnTjjipHhAqaXh+Ej8rd7mlEbj7jt+5sPXFgmFS+KtHsqPzDUM7m2uRKm+Jxn6zwUrLoprWLx0+d8gjBbLj17xTi3ZOtKamgydmThivqzmPcosD9IALHlkG5sq9rac5f8VKi37Bchic3lLzVAXcsr/kFS1bhs7yRGfs8E8vbD8D/x7SooJeLnSBXvBcsDlncP1dQxm19YzWlHabrPfIOnReZ4AhF1cbsuWaNX/yhPH1TtBV/pEP3wdzrdH1A+rC7eivGXbbTIw8RzwN8RoyY/cuTfHfnoCB+sCUcBaft1iaRFuEf3Yll/nKd/OxR/HM5DVqT4J/SZvKH0cWxG/O+8jtCXP1NchZPFFJWyJknv3nnGNo3BhbGtoZit6Ubu6glxLw5cY++NLR8jINHXbAt84r3KGDQ/ut2jDBUurGIhZfN9xtyNKMUbI9hddcmzHwrXLEwHW3PDKKuJkVXTRtFCwVGaunY6xcKmDISORbilzB9L1I6YWflzPJSRnH5ySGNMa/WoGHCc2K6Ofvuk3/2MrYBoCZiSu3OD77uyQbfczPU8gxFRtv57u2ZZ2yaa5LkuBfcxfH6qNqRklTZCmBfZOgr/3InxJbDHR6JVzlv2otxbBqWLX2+e+sIX/x6VTL2ktXtQ5x7qf+pA55ABwztvJlWxjyN4V7F/k+1UsR8+zgQc1Nhs2tIF8uWHNxbd3k/38HyCg+Dx7nkuXov8H4PLaDcxjLeStO3Q6942jL+Mquz+do8rmexJGzz0ZvyYhL45CxMfgYhV9uTJDTkZc+I1uij2r4FXG52X+GXOHZkDlJbHPRYa138/Re2GMNcaEFPBID71zpHiez6Xca7T7c4Zbhzfj+tksaljTkGTrVqKedG3vInMgwObDfqg/7nbbWR2IGPtUvJmouP8nn2zZMpH27bEiv2eUdCQ/2ER/y004no6Ue+DjJeG+io1O6IXe3drZlDl9pawa2ktXqa7+BvXfxbPAwj9SCl1bDW8fIa/JsVHENnmwRLTH/YmSNs71W1rVHe9a4rS3N2qbmOuwE2lXzDaP+SyijB5JPFnaa8zY5sW9BeGBqtCF+5PklykbJS9q7Plmt5RMjnxuSHU6JelPKPgjffUqNnWSlIT2R9egxa20gC5jvfvu0NvhZnFy5XsWu4tTMWmttw9z4Ozl8a9o/9MuQfPDKM/SxifGkmdVBemK3W2fjpEp1Q6qhIzWXkgfMlF6/0lHsfLhExtyzL8Fu1+n/X1XwUSJIziFvxCGrRs9HW6OJ8+vp347/J3hrSLc/mkSRz80Am+/gzGbIWIcYpfLH9EusfXpnbMRmOGDtF49Uxw+3bj/t15Y6o17eUMmGrasUB4/4TzgxzreNR1aDx/zg5h52T5Stl3w8FGXOI2TZW83RsEwH2dAZbCLfNzCy+OMdR65RurSLcEodxvul5D/t7N2yek78Y5rK6ScwduSNzZdLXoM33+hY6QummpfMYv/ZiTzzdZyMVRxHDb6TMTqx0XpywcPk/JuyuWXt3mAZSv73lnd7+8dJar77yPPdv0WY+050dHX5QSf9nZpv590XIRFyd461tpEdmafNIDeqTd72w5BQcqK26OMXNvzJuE9RkxzGFpcZa/BUj2Stl8++FF8+j44GRhJTX7vNPSljyJuOwGt1yNmXPxkgj2j3VwJ8At9cVKGrlvaStYfmln8nsX3dq+dCf+uxr/p8Mn6amdqi1kQLe0N0w54qqrbd4Jl48unvm6x9hlnV3ijqwYVwWWCqCHmg4jIyfL+p9lF55NO3OHO+U/FToeIeqc3vT+S0W3m3+ERDuoONa7mIq/Be/XhDYvg7Dzp7TC645npTaUT9ey91nKxRuWnJnvL6qSH3aW819Wh5eK/Ne69DzVvUREcL+dHAaigcNBcfb/HDI6/6OmWLvYf8Q/8qnqha7OhRl6RHP+vx3SiwVsqVSx88mDjKmN5i/+kj+8kH+piQzy7BcMtVcLx2Y0FZztibwEGHEuFnyLmFn8fYfiMYbJbZKYvBx1razZoOWRifB47Mhi9exNYPyIvz8Pz8tgXEf5shs9V6E89Wp9968OsmfH8Qz//XwC0r0eGdDrqm6p1nvHuoML955v5WP8l4obms82nqeL8lTrbChdViuugnT1n7xNS+jRNBcFnJQClEv15y11fkpVcWj7VtBDdhcH7jj27ppfbA7bXWV9LeUvtTsS/v34UDch20YlQFVZe3N+RYbY84efdEDkPKwsWJacOfuBeEPItUvYzOh5OzlEV307FHFLmOJ22cKJlqpbLqytV7LF1FkC+o/aKt1R5SsCk84z/ZkEV+s/Ui9NHC3y1Vifd/iqfVFQ6vklNFU8OrvRoK211DU9hG4zsH/5urHYFX05U2ZO05QxxgZ3q5bFKrxg7tDXzXkHeng3sNey+5Z8iNf8m18/j49IQeidvtlADaGFHNI94CF7WMxMLRz6NlIbgY5WvtN/JhTJnVeu/X+brvt2F+ag2x4+Mhuoo3vugqG/H7hGu4/g9//DM5QnoRX5Lh26kDEmhzebcLfT0sRvzv5pba3W7oLeA4tV6jx3mkLdy3J2mYfMKuPnneO9K2hr+Sx0pJfP8fvvQezvnC+5XA0i9sFMN4sl40ZBz6GqSwvXqCLrHWXmeV246vr/ax9ZfE/appne945PiVWHmEz7VfN9Lm3GbN0xSY6itTpKpsoIbO0CevLRt43Uf+sC/AkMe0+Yp84S25RwFsU2l9bUmIT3SEe6/9C5R/1SMcadUaDLZLhh1G8N2ZmoZU4N+ByHkQnEXkdps59d/PcfIKXBRBB/fnGrILXz/SRO0VDJUiI8AfuCvHOFLAbfHk9hWJ2QHwzMIrhhxGR6dosyuxPxqMReOvI7vFmOuE57Bl9caj9SrI8MVQ+VmkOGMMWXVf9Gz41QVV5wcGiJ1YOAWbVKeuU3uU1P6rU3DJffy3E/ZJPvGQXoh+ln0wTC7+e8/i5C+lrf18gxpSDww2ZBa2OoLefi4Zp9fn+wcdPJKGmJJJ1QDI27uSIZ3BR9/vMXIBHF4CO6pOO7PIkODwIEeSXVMdn/GFE/3g4LnUk8TReNpLQ9+lwPQL/GzyUEOeGm7pviZWvsKVb7oRy9DzMfwgnD5yZUPuWukcx6jXUsAL0xt65Aj6WaL2hYOLwzupA1aoveD4Pf61Hz7cDe8NQ/Y2ai8xYxkZ0FJW0HccfparboQMTkLdkNsjiS4k13rvyy9V83h0tfcpsGQu7Vxzt+xBj7LUkB6rOkhu2j2LLdU84g3ix3Hw2Rv9lgJDSxlbWfQ6FRy1WerSVqh1d+J3pQ2GuXZyvGgn8WGsVYM8Ukbl0qndsoPauCeYepb0ohYIt0QdMeRgXkNOEu+b5Kglvth4N+92PBIo+eGxtHDfmraGOFUtWCShHD6S2J4Lbpt8sbfUpN9WT52yGr1NJS7W22xIk1YT7bXxz/vYqDh5Wcv9QdKK9qIZ045+c/Qp1H9j0c9jZO1SivbTF3aMr+irvyrtlnVw1pX91t7iavjlJrD8elsLqap5zb1y1dO5pHZHeIS4HxIUIr2pIQtj/7n4V7O64HHYNV3Ni6cj31L7uF5vSiUr9hW2dUjoNefw0tXAJxSmwP5OfO7nnGwS9rCEVAZ3/9DT3xTtJRR97kXnfhUMaY0sscTdn4xva5eKehkwdu1GD+l4yClz5hny7q5HBqKXLZv8bTO2hsgMuPFReThSrTsgz48Yjwyq5ZJ/6zxSCn0Mhp96BYfK9z1WPjB0ShddrS0+5bs/YCkO/9iMPRqrfbbosEJafHrccVtTMLYzFP2D11nobTU+sicOnCftZp6/eEmOuznEI1VHeOTlQ2utaSh8FJS/iCMnfvMW7CVAT43II8LOWPOrmbPGyUxq/8v4gQ0//0vOZ5AvJEaOL5kqyXn6+UjcmpXJGk/TsuQS5Do5kPHMW5dUUPNQ+FJ9dK/mKkclrG6rc4sYgJ2fwSfL0Xn8mmhJvCXa3H+eEJ1meoJeGNdLuDUp770AF0eOnnNc3RJr+mAOzVpvr67Wc2+Tmxa1+CAlOH/G87kWWHs0f2FD34fW/g2fHOSmyKR02qqSR+a0tvYLHCYfvIYeX+GnC04YshCd9FL7uMCRmueaUN+QOhesecbWvLtA5RHgbVTGo/apyBA02NAyfSjjqDMFfsNPfo+MkBeFMjqKkv8M4FlVg/0i1zKIW07GFg9OXuOjoYzt4AeP3CdW9ek7QXsbgm/w2Q9kvfN4t81no9oPw/Mj4Tk4O5hx3J/dzKy9S5MXH6E2ylAtTkYmcErebfkls9va+30OXMxEzs9fDXFXri2jkH0PelFrQ/2ORcrZLWofETnRbKtOzJUcG3iJFSrGIOuX8tRcLw3psyWLQ4Nbc6Cb72DhWpUYmTJ9kzanfHvxnrL2HCic1gZzqe7lkfWJ4uQGz+bPashiar/B+OXyJm7pdEutU8bK5oXWmZi56VrKZd7x4Zk+yNntbD9ZkMIw93RP2gFPg9EF4E7NYTvIa6bdsfIS9/0Okpy2rl1ariXEdovPG7I/4zfbgINq/dgw96yp+WW1L/z320jZ8zWVvouYXLBnS70bPn4GH91BHlv1uLVnW+3TvAznLkWu1BfcMgg8r8MX5+MHlw8Z8s8HP3h/0F6cd4+0pA7oESdfiV1n0GWWmeXkYYZJ2h2e/cA4Z65e4/e49HZHXXz1ODbf38Etp2k/8bdIaYhNHeBpO+NVe19v4Atbu+1y/KliyNLgPtJguVUjFGG8G4pf1ieC+2n44MVjVr3f5L8CWqYthiTm3wUqjHVsVOu5+cH9a8M8e3DkXFdJOaybIzE5vZpTdfN+XnBQ6+k4XdU7Hw+rfNWQIuQgVVZbdU97+pzLd8XchvSt4zLnR2sO6COufan19mqfGGMqz5g1ctx7yJaCfMM9gDyxsiHvGyA/ObWqrzeofZHEiMwZA+WA2ps1e7jeZXwfbc/GSAlb213/TgzeQR1dCLnikevzGfJTZOvQ9JxWldwgeUNDwqbxPf33fRgqB29ZddYunzb25Ov7SD3yFg0ffV3ELS/3WDzvt8WaF00Mhi5eJvcmVmUbk1BT+xfKpK+pBeyq6/jHO/MrWevkaR575HAJl7Seakj+qGhJBjcMTmXIxswB0sovTl7iL2p/5fJLHim2Ma9erjIYC3dLinqGVH2RTtp4vGb9MrRtbb8FyBdBLLlKDNgLxybfl8m+7WqkdGNsKpacVnuqhm50TAPDo4tFi4FO0lU0ZDh2mocPz8cWa3jmmzq7h+6eDMykz94QK3WOWfXCPrCVHv3cJK9tps4XgKWU6GP92kzyczTxuNYfXa3hNXYX1BuB5UzorVx8HTPmHWQMf69Fy++q0eaZmaitoXI0dUNzn8AheDJDBHnmYrB/J0h84615djVvcBH+K8V4vtBPI8aWYadHxvL8ydpx5rmqIHKzy8jenVrPSc6yAh2snx4sucnV3rhd0ox4c5LP4m9a5wNH0MaLgbHSf5ZHHoA3P2rFPqfi5FeqmnLnoFse0fefXG5ZTB9Fi3ok9SxDsoPpHcj/UmH3tCFfyFnG16lg+5gnSDqjm51RhtT7AQY+P9HmjQwza5hi2Fv594sTS7VWSwyp3t0tHcDEo1VVbD9p7zDvvSfP2I+euuPvAfDoS+LblLR1xLXRkBrE6DdgfT6cPBFd+1KTlL7cTav6l/6f15d+qWfqw1TOiM2WMP43V639eJfI9T4Rt8qCR1U7fztn7V8M47d/bDG7E5vX979qc5AHViA3+DmonBQBt6vVPORjQ64GoF89oX0yXNG8mrW/tueVUVog8bMIMSpLScZezZC95O2p+Ul+wcd2oCY6r53ePJtoQ+8/yLWTEYeL4sc27JJppiGF4NqJjGG+2ut/28qnF2yOlcy/2kpcW+JHxpTShLxwMjmamn86VBCdMqZsyFbFN7WUQI6TjEH5sav1cD3ZGsPMnzPTZ3h+a5/WafQxaX9m2XjW2vecOKa3ZO21xd4LXld7dbZWjNOiwVHqB9a+3AfnXFIvjUduDqT/v6FiTwlXTo2T2CchkhB+PFndLQ/Az+RBGW0tVI68qqmmOECtbfXeedIxJVsFOQGGVJxVe+RmI9t+/KQDfduy9JWWat8jsf8MOBh7yVpv6bjdkO3EsjoZNamUm3YYY3VkUns8u2O3bS2DpNF8dY4RzKt1YvRU++IJx41Lau8q+SN66AHfDgUjduqIXGDmKdwX9dPHMQF/TAUfvEW+xoZHjhYBR+g6uGYiubynnT70lCFFz1rret8/9bRdbgqXN4JrsLXad6j2qoTRT0lq75boxPHUMLmkeeZYc6/SDbVHc8M/26LN1LoR1Aaqjo0h1uLDf6hPp1609nmeAq9/C7Y27fELnF9DLz+uWPzeIp9h7n1R+39S0s9mfP5dO5Xj4g87nDL4srUOUxK/zpvfMOdfjuc/pdfb7ydb3jdwBA7zyC61b6eQR97AK8mIq6vHuq399bc9klSdWeUztfei4Wm3fEmRV1IgU+kf0RLuwoahMRLvR5xA1jlqveSHR08NhqqdsPJjB/Y7Mq+d3ui4tX7yBN3U/ukWLfc17few9FKlb3ObOo9ho/20fDd6j3VutI3XOrfb65KaR4ILsqa3/+wFDy8pKGp99ivt18oQKnnxjymHrNzmOVyv9sUVSR0ny8HkKzhmuzpXyPfTqPO+ZtyvTwMTmUcFmHvHlW3bNyotC+nLC278N7mpz73m2bKOzw1JiSzLpqNH6rg2a9FzADpGn64Hai9RhHaB3wEby0o7/LOb1lb3OXhAD07cWTKqMxn11d5lxvSrtaytZJ3prJPcJYfXeKQAfuZj98gH4p2as1Cx/yd5oo68Tnz6G/VkxsUeedKGGqyoU//H8+0ObdYzRHpkEzaamcYuR1Z6ZOS42vZ43yZyNjrU3AO16dhpfTBxvhbx6IzaR46PVS5WVO9yPU5sfyqb+8I+jLPOtNSgzTvkqdvQm1ovV7X798vW2u6KP05zbePMTPKRZHHSCxmvTHTJFZdHLuND7fLiO+qMIFjeRK4Qhe66TXWLD/avkyxYOvUdrwdRO7U6EmPum1T7fmzYthF5SRg6DSO3ddFXEPlClYGRsnhAnOyB8+ZO8MiklOv1Actz2bevCZMt6KHmE0OyMeZzJw3ZsVfta7PmQw5kipM2CS87em8MlG83DVm+OUoaEKNPTS5jz9qsi/17bG2H2mfpd9Vao1LrzfuR+cmuWuJUZ4taWmcO6ozzSHHk2YWcu7B7tw1u07cm0HcE/VTExuoc+lJ8pEYFeORDepndnGe3wQVdMjsGEFdr3/Ix1wMmrLLOXf2B99TeqyHBkXKKOFS6FmMv7JHtyHFmo1tqXbH25Qy8aeFiA5/dreYx66a+Pu/8fK5a50Amov+p5CdBa639l2r/ciTjv/4rTlaSR/UH02qfZz/wvRV/n5AezkOeMXBsW55rddDKB9O1z6Wr+fsA+hux7qYjJd9lj7fOa/TFHn4J4uQv8XF9JUMWYFN1vqb3RUOKD7X2uneoDW89MmQwfp2MnPjcnZGOBAeyibNgqNiqXbK5ksRII9pPSKxclXaCY98wanjsuZtxZEHnav9nAPWHwuYUxZ/pfOU8Nn131S3zcvlqV3xi5ROytsrkkSp7DUmPDmvM8dqDeadFXAo5O9qQdNjr/l3LRmruZAvtePh7RY5+drVnXu1/X0M+P/GktTet82C3ObfZn3Yr9POae/LVftC+deAp/KzNkCh55LXymOvE7ghqpNwtDLn4wS0dkS0QLh6ELnsSD850j9GeT3XJIzCQpbKPXa3jNALredFHtp4uWcnfah9QiYpJNbV3r1crt8yinqvbeKH+oiu8iU9tx79V7aLyriLuCHm+f4e2PBz/ao8+0FtnuLzzWEMuhWZ1HLxr7SlSdy40R76NcFxSOOZFn3Famwwe2ZsoWn6SWxe4YOXGRbCJ2m89o80X7Q6clpQcbBq/Ow6z5vnd6QzxOWyd1VqxzpC77wyJ4d26yNJU7UVNRz2Prtakof4jTsfzbG+1tw8O+3zPJUuR5S31ZY94a21j5bWUWi58ozU+HQV/qHWwmuBIW/5AC4FX/t6OEQf17UPaGJAwuxyinVrbrfmjREHkATWf6+pM0sbfhrxR+4PQ7W21H7gNXEOu1x79X8Pvwomha8uK5MB2Rf48sW275DLjX4LShug815p+758YYJ6P3Yn8au9zZ3jPNtbiqdRDIyTTll9aXXL18ti8HLKd70YezHNry4XLNXxsCHqwdcrpGNLTWn+b7ofvDbH2OMTvSKAn811sm3XNmnutgvxzT992fJvyzabmBvby2RFVX9KGquO+Y+Od4MAgfziOXoojQwZwcKecYe5Zc9639lupvRFppsD99FcV3Kr5IaXLpeSi58x9LcSzooZ5l8L30iW0Oap2ACu3R9klY/cBUogcI9H1ZjZ3fBlzzjkAWYfj05/UeQpkHbOpuS2+MPZI4JW7+N46ZMkC542BH9Q9EWqed3qemlKSXKooMmSE/5eBo7Oj1Lx1NwnpBIc9c5nn6uf810zi7IZ0398OQxRyPH5hmGdDq4OrNGkC7KmwlcrnqyHD+7eZzLs8blCn1ECubjzXl8/fRBvymph0oIZLqtcHY9mI7WFwNpheoM6QxQ3W1Fr0bNqcdbqJXvy2IXkZzyywcpg2Rv6OEHUGv6ZvOymt9iOgjx+LnDIhIKnkbd3BrIMProuQT33C5MzZQQ7V37u75/Srr9La/47Almssrtg7Bz9VeykaxEnLd5q9iDqvhvydcvWVxY+Km7lvrj5b9QxqrxL+2HS0tT7dxmvIMt59jS1vorvW98NE3Wnh8/OYHn/dbfL2y8su08+nlae+AqOj88VKP/Cyi9z0Z9nKsnjMS63jXVV3eyUJ8XDqNEMa0sYuuOlsjLXH+Qjxodonl0RmrmC7p87s0M5rZJh6zrp74mwHQxxVLTt+qjbbvisxPn5/m2MMvtMUnak9AhcPGZKvg1Psh6w9FeGvDXloIEOMITdpJxF2HoFtTpIfv0eOC+quDXizW3Urxz+NbrMzns7UDqmpN17yTCHqlgVvO+ursWXRPtidONuu1wltG/ls7oVWzZuCdj+3d8kLNc8+2uLfTHBoLXR2jzpnLjHxquujniFhd6nQyy1rXxmS1g6/lnhk++hOImp9/Uora89q59FOKYxvD1R3bZC7ZyQelT3ZV4qrnB0d2oYNEAN5pT/9OxnLzCyO0sus/DIEmUekcMuOeta5pC8d+/mps4yb+1n7itVeWbUOc2iUIRPJma7fsc4GHIef8uInMzf42tX5fDUHqPYnG7xnA985sVWXZTHSBX9vdFqdKYePoxLI7Cuh8jiTIef1BdroubHSaZdTnh/7bv+j8oL1hrRTHDuc2mu8Yc7NxcNrCYpg02JdzX0fj3pYvnI7mNzCY51RrUlfo8vFikZ+NPeXIfGzAuXO5Yn2RujmBc9eRycX75OPlXXLyuRuKX/Lmqe+hy/r4KYRvvaX323avHfcdhoSrdZ8lxnSeYYhgeioK33MJLau73BU76vmw+Gy09s/6stKB5vn5D4PKCnObnAM7aXn3UutqbHeDxBPCDULOcfCq3HyEv2pvSn5iH/TiesniA3ZyqLvFtYaz2f0PD8sTjojbyM4eSuccumGdbZ5Pt99wO9ydrP2dN5hnC2wWxl8ZS98mOu4lVt2XxJsnk0MSR8jjT+U10aQR71Ff+0HgXF0dYQcQ60xJMLPEpYiv/B3y3pi3zLGmLlyIu0Q8jeAX/o0gw+wlwYWx9aJNM+QlU9QzN6UemImmLqF336s30mStJquqftRhm+zxqD2rqv5YXUPST4HudEEsEZfJVWeRp5e7agVt9c0c5pn7k7BjUE92ktceLQ8QB9qr3ibKrUcEya45d95az9/uJo3A39qH8EicLSMePsITmvP+6Pghv7E1cRR1l6pQOLeCnLinEG5dHV+KdVWa9/o+SSGGbc+wm3qjpJTm/9qOvhf87aNngtdZvf2Mu9oUfM06e5Y537U2U91JrRrqGHOq2103NOP4h/L2jRwqDM51+l3A3rJO2OAuIg1n+rESa691nqVuoOjO/0nJEbljAY3iQfaXmYcaPtJnnlUrW1Xmqa9yWNIic9xsqWLW6Kw3zUwlRFc+GOLTRfU+Y4uktXHLW58+QE8q+Y3J5b3yAV0puY91R65yN1T7S/R7TzkzjwnvW5r0Vaq0v8sR25J9dQpVTIEm3tJ5t22cBTXOsLcg3jiZl7zXK86FzIYrikphoSeXqY1TUoOR9zPT9vVX7hlwUG3FkgNpng3JPFo/U2LCFmap7F5btw/Fj058KMLbjlL+z1zdpKPxHO1TnYGW7rA0rMf4x1F0Gda9Bn13SPlFlvnC2+jz+EXrbxT4XdlHbdMQWd2dU9Cj1hpTW4+eVM6RzL8boW6d6d7sBQir7xBfEvi19w+fml96QtPLLy+xDFV3R/VjryIOm0u3NqCNtW9Rfc937XU4SGi9pEmQmfbwM4iuCOPyomfRksQ8SET9nizwJCsPOMNdIu656kVMe6A4ZZf62P0k7usPbgnVxjmHtsC+LJad3sBBl8cU/cHeSSow3e/DJX6S0LqlkW33dJI8XlKp+QOcclF9Ht9WpSMQraG+GFRYkiapeqOH+I033WN8ciWVVatpdbos4L/dOjyFngozfPB+NXvWYydZ/MkIi/3WnPNZTq7pX25SFlVypBU+8JlBrVI5Tep9QPEjLTFvOba/3N8PTwZ8v+zxle+GfgCN28aueRkR5fE9XWL44h1Vne9mtfK6nIMxsfUnSfqzML95Vm1s6usezPGBm/UA/I3lL/Z99qeNyY3VGcf8ZuS5OFRuStIoye83zxa+jCOL/2tvP0N+k4E9lIwls3469rOhnmmdz7jbMVnn996RN3tpO5dG3TaWnNY/MYpfcBaspY5pSm2UPOCw+CMHvDcheDpWvWBubWQ5rp5V46KsaqmVLl2yPUYSUkfu/GX7ug/WTVrr4s6A7gJnxwB/5+At2JzW+scPYhRcRsqy8kaYbIrXzdJuM5H7tzqLZ/VPqEKjSXTklhz78xRdY4/o1uy0rbfnK7i/yZIOjT+rJ+h9o/tYsWe8w/dMqyTmps2zDWygfHFdXWfirqLLMl5K/5e+t8dVl2JsevQzbCDat3CkATkBjq2OabOMnZPJO8Y6zZiZoZThnnGIETVtWqvEnVJVtqbA6c0TpBUBr4xzP3UFcmt6uLXUzbb5A82bHknXEZX8pp4UWsNf5dV1NqhTxVzvcg0WJ0HBn/r8I/6+MqEKtSpgyOtO6PyBVK7wDHUK2upYydRQ2e66DHXSoai47yJRfzbuSRIxcO+Rx090auas9hH/1fL1XVMSBQlxfCPP9jyBxxygpymCHVDn+SnNXWP2ytV27xJqTsWHLf9Hm2do/yVLkzmLxqg+TC+4k0M8Q+zziiodYIE8dYZwNffM9mHfzNkkJ8hs+FT/UUc+VqENECnbw9b+wC2kKf8A7OxZ6tJETB8o6JLTlDjKZ9NSt7zAZnGOJpIUvLSt7ciZNtij7kHcBT4dnyeqqtzWVdDrT3/UTk9Mo62isK509Cjml9X89gv12AT9N3vyV9HpbOG1EVOG7yWRK3Pklc1dDrFUaWnhFF7q3tjXqmzCuC8VvXGsidNpGTNAq8SCzIwtvwZDDm5V51nMeT2A6ek5t+fS/pL3z8xcpkx/+a9+9hxM/5eV+3Jcxsyj3xanZErWd8uWcDPnmJO+Y5tduPvqfJGm/dhqL0KZ/DJ4WqvUM++EtDQZZ5R/va/c43q3PWPLK0kU4r8ujrLr+5Oyha4V6s3mXq71T5d7Tf7WMgrO9BNAmrpBvhvQfca+xF46ClYXZSXugpeubmZuIWNV4KLTpus+++OLb6oJd/nlDkv/+rqbjl1F+DeWEOmNIBrhhbTFqp9Dyq/3WXNtfWFJ7JNDJDb+P374m00tT9yeJFouR7ukeTZR+kVM4/Tr2PXh7vUvW9ec7/srnYNbMfA8wu1ToxexJc4O80lBYhpcxIV0r/FuszYfYhnHmNzR2evuSdE3SGy9lUi2ViuhKymhp7fEb7f7JTmao9xt/Zix68CPkWaa8ApMgfaclEDpGS8H2fio5+jxJOgqn0Vdrsxxy11phLrykSZd0nmv2tIfn98Gd1upE/PUeuM80renUtcigUDan9vh4YV9fAT1l1XSbdEyrXL1p0fPcnBJj/sJOPA2alifaU5OZJapyu9JNa+GlsXh7OHqjUs+KXy9Tn2eH6r+fbD5DHqDsDwUh5zjmhuOkNqtXLLbLWfC24fUsTKb6MWFtKK40dTwVOkw4qLao/uQcbSQ63rYL/+5E4R78foGfDBD0/za8+vzHakwHbP8IksDw25i50iyCNnvOwq26nzd5y2zqSEqvP1YfW1x+S06zPCR4wt9GkiM75MzQo3ucAKXHuU2LAN/nX5YQtwdScVeTdjU/VPldPWflnf4dY8265PnbTv+F1UWmy+xSVPwZ2b+FBYnaf8GCsPLrgkGL9becK6K0qdn1Xntg6g88bURhtL0B/tRkeF++U7b51dLYmsbdHBP/z4b4bU9vQPvWY+o/JBz8r8tq7zrLkode5pYlfrDqfe8W4T4+q+ruzYqc1e65zkGsFm6OBrnWhyQo85l6T2mX1r45VxGxhPnY4ygdpw/5U4GQeXDTkQJfOKWnvgc9/oYZ6N/gOXjZqV1pGUf1/OHitT0HPqlW5pTj5agrxSnRuIWdDU9ghu+6XwBFa+NPNINjA6S+GYOqM/vJUXjt5I7ZE/H5x0KUALmRdszk2qe0fUPUktF8fII+o1l7rn5pS1D0blWW3i1+i9+qs7Aw1TrmJ897g3PvMoQI7h25XI8SseiDX3M91fZEg/agC1JtkuPI94DY90KWGdD9qj4hb2Mfj9kbad02gD2x2KI1/yuKT44/y2u7esfSdL5sdJqOJu/k5FDheMXWKvWeu76uzm5bCB+sCsal4XHaYxpH6AdSfr9Stq7TtGYsDP0u8DbQ3Qt+dfJv25EaOlamndiab23r9EhjbwQN1zao2Sf6vzzr0MiQTfldWZBmyzslFxx0HaD6qADdR+rVXL/XxLUNM+PGO7hB49V2Lk3+cW8oUcJKq3R2zg7Df+dgb/Gr+8mMw/tlDrA+7cx609arZ7LjlTHj2czCmlsZPKEX6Ry16EH+YPNKT4VmtOeCj+8Rh7rZ9mSGtscYzx63B5GLlDIL73tLy/jDtk3UWk5sgahFzRkg0OMdfE76D3zcfVupZbZoDR83/c4gS7SaZ5xHeHIWEp4A9yhwTh0Zo6+67mfk6dtdbjCw6K11VulwiuUHlezYNB8rkOOiZGv73plurYrMl2a5/s2Du97PPQWTee3/R1l76yJBgnVv1CLufnmTajXDtZD8fm/uI25xTUXPxvcJLmWVabmkvvQs68B9kbJg81a5oivcgpJrvN+4/cq6poy8h/i5+1zka9eVBTYjvlkozoS93RlTlPJykBntIhp8LCBuqAEv6n9Q343Kg3E3R1VuxhvmBZ2nip7sFnOoKbL9ksDlKxStXDTsaS/08zRyS4TtPFY95V8victQfk3HzD9OmBvzNJdMF8ovb2pUtDXQH3qD2fYWBnMToOvmzV4uqeo8OHrD0i33z22dScrjr70vKTRyKob758mKfHZEypq/NtbsU7+WprG9S9SfBxUrXHIEuI/JeR3OfNWr3Y2ZT27dSGy/GZCzmJ+eq+r5KGqDOgRZH1Q3FrTafQPmut/TyxK8FCa29d7+plhIRFnjy07tgN3+GWGi+sNedV/d0yGZtGgWOTF9q0kGxtrmq/XnnkwTyPqH2Dm0I72dXdZl8X95bSDa014icLrLk8Hzio1Bnr3oMoaqJjRl5bxZWGeUfdgr3v9BXkQmnJd0rVozb1izbPt+2rZt0R0uuOIdPQkzqT/wT7qnteK4ILNQc2h5x4Ip83w56LMvWRAZOH68pn1D1ZqajRVJv9Ww2xl0aWTMR2tec+T3ZD2qKP2OTh9vZwbPm6bjnF2K7Xtva5qvVIddecOs8f/3CAXIF/yx6gdi4aY84x1S2D3hJl1bzEAgeceY08W+0BVvcd/A0JNOf1bpKfqb1Vaq9cEeqhgXC+i3p9dON0UgX93Vd35g4wzPh4bZ21LyJT5SZy6Lp19vQKvqzmntU9juq87+uO/aVmETXX55EBmXuZ8/GXqQkfjIgTtVak7sPTq1LHgYOJOax5j/RwgYqDai9Lfsb95/wASa9i6PIOfup+zzLoTt1VoOaE26EP3+OGXAq5b89Hnd1GcSXP+JCn3UaGZrS3+VmU3oc6Jic5RAG1lkJMLYieHzM+1fZEYmoyMP6RuFIYniw4dbrf5DPW/SZryX9yNzTkJrj+76rHvnQ1eN+SXMudr6i9zmR8pnl9+TIKm7SZZ08V4zXvelBzB31oa/p1JTt2WuyrJU1imHe8rV1jrcW+5/t2PZ3SpLchC8sFik68/IS80/K4pCrYqx3VQ+rs85h7TbcQa8/Bhaky5LMZhhU3XtWEsxlDP3j5hFq3VPfBFIuVxL9ryaHDbuqVkbo6r9bzWx9zvT0Q/1c8q/ZYZaSvZzl6Swi+Ph/8qLVv+RijqzPqhRdacyTjvZ3Muzsevuomk8B06kbIVskt/2Z5ROr2MM9+BJzPaFc8lJd3Zi6w1qwO5OhvnlkZ2iNYclakFkRfbzNYewPt2OYVOfZQddcCNl51SN2NZUhBVxMzT23LeyeoFy+Cs9DgZfqNuNrSwMcjOfCnWU8ryXpHG6m726qX1T5tdQ76552y8lad+b5i3Q37bKflBykDy+jN8Jt75DzX4qyzrvfK/NHbjvFx7Dk+xNGkstd+Hjus2m7tz56HrC35O+l3tzyHg1bw/I/6bvNOsZV9PZLs53Zd3b/0gRzsRmOveR6i9i2PtAIjwaE+5p1L98kvapODbWOcH90T7W61lqHOdIPrzozVMRgO/+Uyz5L/5r0U9PEcn6mPnh+PHaz7n7byrTzY0kBHvilu2NW5uU+M48z5RvLmUxM5dsht3gH7Ha7Lpc5fkzNfBeMN+LmCLxTH5ovJd0aA/+zEkr8HneZ9fclVPB6QWn9Qobc09Y9wXOLZEOLvk1RuKYZss3PhO+gw9+S9+tJKw/SF0Va9m7K7IZXAZSEwfqFCF03dqZxmhLWer+4iPhdRXrbxfSZkXzsvRlrjP2re/NiOROZZgCd7DNm+LUjCD3nM+1KzkC9PT1PeVmkFvo8+71LXNcyfQubig3+zOjR545HH1KTZbhniS3ybiP93alVNZj/4ZM8GV9bS3JJpTKwM95thG8u4puFzlydGyp2R23Rtf1LZjz3H9YWziDPH0rrEh1h/Hnt8nt1YV3eNNyJGZj5Z23YQbsl0zFrvuIzs9ennTd44s9bdG2aYd12spV4tnMnaT1H19z296ZxrWr/H2KemW3pHVNCjsa2L+jzBq0faje5j7MPU+iE4HjmDuAXXRpVzSz5sN7Czx4xjZxj7Iv6ue6qHqHuG1Z7NpV+CtBchwxyzE9A/uVf0f+KIqFlUr5WulPaZPDCRmiMEH4nV+RpqNCd1qJMcrBQytwEnS+CGkuRHv5Dr5tOLDlXbJ8nqMe/W6PnijmPMkCJ6JHYoTlsF4JDAXdZdrD5rp+izvwZLBuy5Hsxs+X5UVzgrQNuqblRruGq+7Gj7adqMO9YeAHVnZakhsea93kuSxcpm/k5yo6Z+RO3DjLTu1v334Jmm9ntfehIhrcnJasKH44pscSw8Y8VAddZ1Ec/NPvjArvLLA9PH2XYXjZO07w3J2NQrZ29ZOWMqnk2GrUJjDPmSopuMXTRKK0YbniSh5vx5B3W3N3L6dcMPnjnl781TWlZ8aRExzyF79U6HrTp9dLg6U1PCpu7w9uzqbK4nzs26za72tP8DJ+fIZzLcts40KBysKpvKlv37ZNsnbD+jl0vK04c6u1x+aYzkz1nP4Tb6yfnl6l4p6kJ4b5qKL+es9btmaw05jb2Glu1k3vGt9qPnBYez0V1Tfgats+6MV3cwd97RSnqp/e/IV3RIbblzY4qe5bZHtuUnv8V24U1jJU+ebHr7DeqcmSEXs7Z0qHsp1B40dVZPzUueo35q+sQQlesXYBzbyI2ugv/teZxS57R1rkyd6T8wt5esizOkcwrD5Fd1T4u6R2ThyEh7KmJS8IUeMrGL07xzQq3B/bsWKqt4XuWXikPUnpKEl51mDlCywn1bCvCwTM2R3bDmD9TZcBVXFSeo+yDUHUfqPrf98F3BwzHmftUU5G+NPuTQy1Q3xEb9qe739O+g9swZcg/uzIntN8BD33j/QFAu+1D0kqlUkImxqeQiOcBm5xnWOcL0Ga3/n4K6+2Usufe+VYbkXpFeP4lcCY+oOT5wAQ6e8ffKaTHyNcd8vUG3Qo40WzzyYQN6oCZQ/28IlbNmH2KIt29aCSzfzdx3mWBQtLxDh22nW+t9RX29oi31mPNHP/aW1POetPZgLynkklh0t7DOUNuB83P16fDr0S3WneilNlryntztlpKnDfOemfwBul3t5xkKZgqrO0X47MB8l8whf+wNP53eZd2/1pmf2mDxc7ghd/n3h6A4Of1fdnk40mXWa+tGWecUV9601lPVPQr+DVpIXv5eBi8Xv2+9/3aKdWdRa/wpBXnee/wpGzI9xx/PfTJMORtMs+KHui93Mrxyd5Ihy9HfKDXvCn7ukDO5+C4V9nQN7qyp/anqnG3V2Qm1qpM98h863IKujvs55SB93ZjtkfnIeBMbVs5k3Tf3B/lGtKJWrhwpBjlCR2LfkUoeeX48ryzLYt0VcmspepkTLLEjPulD4DjPfUN2kMttyXDHoe4rffsoRtzoX90z2oHfO9S5Wfzp8iKvea94rbQDJKYt/kc719BDh/XW/3uhLPj6MsCaz1JnHvr0jJY+PoYUYmy+sfkcKkaq84gTeEatRcSrcyq0eYnfaXZY9zQ1aBht1htBbreEh1vzBXFXOkuHl0sdF9Ja86qj0GsA461627LlRXyhXzZDNpM7dxxvyLcR2WVkp0omDhMjX5ZM3cy9FD2mWes/6iy3Wusf3ck6Z9meOkydjVPnFvu1xwdDBsiERprteHwnKbXKqkXUvr7/yFPSE6e/MB51Z6Oq0dTaQwnaDkdP6j4g9f8oUHeyhYG7PWBCnYu6DX4vxTolxaQoUfosDWZ6qHMrh53merC6E3lgt2XahRkN7Op+iB7oSP0/DCqefulIUjdGEhK3v61dauvm8Jp3jMSP7uCwPzTM+0Umkbc/Rhd/nfVsPoPwp5PW3d2191tzcb2mWOcaakicNGgVKSume2SZT1pd3Zfb6Cdxcj91Ql7DPMcXssVa11yGP2dDBnXny0tl2wERcrxwWXlATKxHPTIInhoRa3HsTnS5+0wj+b2ijE3tQ/yJPlV8+oJ9bZet/2+LOpeg8ry68dbdxHnetZb9YPUWOclAP/SFf+St1cWesI+6A8RaI2zfHU7/D0y0I37Ps/4fKznpb80ua++cOgfZ/bz6/4lkk+f31F2kHklyNFqqNDFkEjHi7v+xdJXhUSRbFHeXxd3dWTIz3RcL7u5uISTEZWa6gxPc3d0tBHf3oMHdFneWXWR551S9H3xAMtNdcrXq3nNg83hW+3awzruWt/c3yF9yHDI1FHq875pbxULsEfmNGJZ9YBdgE4OJ4dnLltcpbvkMb4jxs25tc7Rci9b356yJ8kDWM3yeZCSBTbVTY4zJeknQMb3frA3KixilOvb/GOa45a1XNk9a4fTFvsbd0jwED5njJaRW2JvvsbeOjh51DtLgSU+fNhG6TmMjYt5/MoVLR8QQsfE6VuR9K3s9X8AeDb+ma2sbYS88YbZ0g9wRm7bU7AnO77c/Od/t1zUN7IXNzboQPK8C5GzURUvd3a+uUcZpDMjnSNsDcWxoPemJ717GOrAutfNl9v7FKI6hLPCn7AdPMfSxyRqf94kemffcK8HD3NKwLOKbT4EKT584OEkhZylZa1PAkhp/PjH+2Kb7rA/BpleAP4rYOspVYvp2ow788J9b3KpX+2U45ve4uxRn7wzeRf1YkQN+YFKoZE/e00U8hs+wg7wTCIU8L8Q65bynsSbZD0ybTUyUu6xtuWmLFzbU/vXYUQ96mwMysxPP3bRR39VPxPsqQWbaHekrF7OHSIG0OxxnYH/uYx4bUhSVChj/sb06t2uC7+49rbHFiZ2bd3u4OObZqq8tL/Ku7vjZPnyWcTb5ZfI/2uPag7z+BNZx9X9hCkMoLIfOhyuGBareb7NPI4P13cV5J/5ygvOfXRucdpsYOfvZK7VrDRH2U7PH61Etj/TiXuNzds+G5qBFljpfbevp6khS+p1j1sTKCm9pJ9Ym4WW4qlUKx5qE/L8mg7Vmh3/aMjU5/oZcnMhVy8yLPSTWZfp88x1FWd/W1SspZ9hy8ZRb5l13y+xpIWaTF5YcTjVIrrC+m2d6rdKbrPV7krGHkXqnLcma7nCdx7iSQf/uDY+S51gLD2KEz/DdC9kLVBf//rTGWAUfuxI6NwO2gtgxXKuhKzqrcwJik6XHONqWwJgRm/UZZclb+L8fWK9KkM/2jP1gBw4Qn2iyW35gDsQRWgK7sATvug8daw+f/Limre5ZOuLfGV81kc/NoCtbLOkLW3ZyvsZYYX8/c/4c8ZYUKhJvVqusa6salMWeYT0XlAiVgu5LJut2iU90CblnAmTzKvZgHPErsZfvoHvXM9aTooj7up/QmBFXL+kex1kpFxqHYdtbda4p0QV+mHEz0rr+hn4Ncuu+MOLUt2oE243Pl8e4D3/F+kJ2ShS05IM3XAzoZIaOiF2ga9bFJibxNvf1jZIrq+FjW//reg+5j48Ll2/I1XyDsObhutaHNXMt/wqSTfj8rPL9pM6QGOkFn7pmtEeyrbGkE2zC2dgwyY318WB9J0EXvvgkMzfVnWZueWarHo1VjXq5vvTLbvDeLuG+7qf8vCRM+kHmH+zRHFZHF+l7UeKWPcbe/emj7Q5rlntCPvbA/tFuzIEdS7YkVK5UsSX9Qsz3qi39oMu5a151NnzlUdwlrMdkf9geyGmFwIsmbWNBPDM5ZGP5BVs20I+zpg1rkekfS+H19kTM2ex6M3Xm3uyWvjegP75aP0yq/WdLFMba5KTmsCkFefsDa9uDPCAYb0s8Zyt06zJ7k2B/+g97aBDXfeLZnJLnkSV/NIWvgd18sTHImJ4UMpQKev3bV+UWxJEqSbyNB8mlPfzbs9qw7Y2OGM0x1+X7A1StNnWf53bN1ur7IvbGkUMj9ri+86mPuXVd4JEMQ2EbD+o7OOLRD0TMlPuJpcb7uIM+7ycWIOvOj2IfTj2w5N7Dqc4uaxGPVmgtvN+Uz+ud1ftUdzqXaIyvAalt8SlTQlpCHsjzFZQiRvXaOTEOnlfz3FDdIV8k7pol7Vr0Vxw/rE8dNteW8tM0Vukq/H8nMfUu6V5I1sw19c8l61jzuDWvqgN9ifV7+3998E0RKVcRL67coLFY2FczOM4SF2zv7FodnezZIH4D88TWozxSA+vx6N9S5upB+txYoOfn8czfkNXEkmnNbBMgv7CdY5FTfoG8jcN44q5YCieVWIX9sJadsf51Nuo7jBnExkkyw/ksub+yh8RDHFnWIyXva34QnrtfxnsyDxpvXrQRq9zRXBJdeiCfq/3JaArdJIYUY7Wc+UabjYu1dk6ArKcOt6XmDJ2z+2635b9TujaiwHJbbreNN4dAXzbWWmnGX9UcfFtCoyVxEutWIQfpThlbakQLsW8LYrzsCY3F554v0Xf0dU5oTJ6+Kyx1Fs77qCdYo2uwtRO7Yi2LDHASi5N3KBE+g6Qu3lVtVHF5nz65sY91lWc0PnWlRytNi3ihkM+cZ2z58qyUMyO+k6pblOyoMsQIvqtxsnJ29Fd4wnXywJ5hniNyY00bY98xppPzvpmpNuqeKOKTHC58znF2H36/wV8mIy7qtyC90W6zLUkbuKX+Ds1nMe+tLUUxB986aSRrEtjb8bbi9kr38qorHONxhCL2HI14HbHcF/j+dX9GOTcTQ5N9M61jVB43CvrD2q9fsFc8Y5oOeVmFfPEd7HNJzHfIeeL9tTf9kYdcwboRb/ncukdmaLcYxXfQ+7mvwl9edBC2uyryQeI+Y3/WIS8l3uJa2KkleN8r1uVDvxrAN/Bs8WpNje9ed3Na5/x5k402G4s5MkCOprQdaR4eQ0zUKIXpzF7Mv6JgM1lLeVr3Qm5ePEguYT9n43fk9+B55Eys2TLsaUasiz/iTOas7Ldx27buEZykMRAcO/5v79k3/92rzgd4R+vuGyixsBdVovtLZ8SexJUi5hA5Ae8dbC/lb+l9GdM1WppCvybkthUvygHI5KCbrNc/YGbs7RV/+Ncu7dvKSeh+LtihyfjevzeDVLzyDnvdDjEv6wdeZdO1/z8Qh5QYaMvBb17VG9wrtrBZHHsS+TSvMai3re4V2sTCV8xLKmdiO6n6oK/Q1eKvKkiRxXpvJ/AOCHZnN/an/CHNQ9Uki9NRH/M8HaX3OwP+hIyAHkPeK0KPyWP0HDq1sZ9bcT7mg7w+6bzDMcXhUXjuYZe1jBKzhWe6wyFL78/3craAzJfbFuJchXcmwA7fSJvGmQY24kV0Lxf7zSchdlg5CjZvhUN24zmfKzd3jMKzWKvQDOtE/roOvuxtRyxHHJHSmcxE2DlP8Rh1FmEjPq+S76OT59WtEm3Zj30+jbXLmK+v5IXfWlBX5xqjsdY8t/XFGv/Fc7L6eOc5jUN2G+NOhM6lHd1Blt9ZYlxF3GJfssUDnbhMfFJ8Lt8fvkaDaWEakwvjZE5Ijgjyev4LHQ2oB3/X3V8Cd1iSGevapVsyhWHFetN9qwo7qFvpq+v+AmIgEtfn7uiMjsYHzhi38y12Zg99b7C37G/87gX864timCPGOhDPsm+EyzLEMzlhyzrO0/06xJqKST/aCMZ+9x6IOHW9xu/bMFifC/RJ99QRgD0a399PmsH2pE7U4ywSbCusoGmwlV1fBanenfv9YI8RNxM7eUrZMDkGnzOWNYVYv/74mcR8dR7zYn0LRYsJ+cwPOd4ZZcuxp5a02mopDJsN2/W5UZWaRSVnpxVGypndZGlX1hja0vbzUFkHu9Py7/6Gu8cM15Dd7CfAfJADRLyxFR4McULDMPfnl/U95WPEU5+/WNJ8fLT449k1WNOB956ALD/DPCaYsBnQ2dQL+gr7PVmnOxCxyiH8bifioNzHbPGF3TT7wQdgzKy73bNHn5OVI1Y44tXnG6Nl2F+Wul8jtlci9pLY2taMAJU3815wWS/YvptJHHsn21IZsZn7HOYNm/UOdn7qfd73RsnKTaEunlNNWmTLh7nImT22qr0jDsILrF+X3DmcZzGfBRWQj9Gu7rbFgc+6XRjzJq9MW691bljCCeM51mAszxBgBw8m3nYeb4VxnuceIF7dGyodsqxwrBv501wKfYz1tSWxui3zEcPfvqr5+aIG1jQHBtx2OE9aipuJtexF4NveFQuSoQ744twfzJg8QbIhjS0hyE+J483eg0Do2hjInf9ifS7KPHsX5lkTdq8W5uRzUP9+EXLYX4+QLyDO4/3GBazZWexnlK3PG+7Ead6pjP8lkxDoe+IBW+r8tKTKnSayj2cHX7qpM86/a3WXgfcsufv3ENXrSL/BvJS1zqNmF5Io6Oj4vbache42fX3aOQLy8fSiV26laKniJHL4Jd+p+2qq/MzvoO+suMBXzk2GD6Xch0Fmhnhl2YBW0mRJUkcd6FFz6HPe9UsdjVsjV4Jf2FY+VJojFyEf0NLtccaUU5bcx7xvnbBlYJHGCjPiHOLMdLDjvyBr1xErsmYv2dysTnKhMGZJhz9lEMcmVGyuan14jlAA8f0d6G569vaP1Riot+M1NtvUq7pnoQ7i7ArY0/HIUVjP3eGCls2FrMNa0tl89c9So9HsCJkHOVrL87pwzUP5fZGuRZewjvIf9psYNwNglzdAZg7AP7IPmGfkO+/WkPHdvDKYWI85xEF+YXtGUYU1GZY7j0zEHk3A+5I8L2OU9cuqOBS7QT9CsOcycazPYd5RYVwbUvVyjdvtliPfUjh7YJ1WN3Kr2r9CGyo6WD9s/htmDiLm1Jn+Qqy0fUdtSQMZGg8fVP2DLVnn1XI9OhoulTF/V1Zb9fiSs5PxF3vjT15lLU6MilM65rIkPqSvrHqTwpzMe4EQW+KQX5XHe2/2/m0su/zMVXiM7j1mvpqKZ7qR0GfIU568vgqHZ2R5xG2+2831JdvLtLuaAy4tfOwbfP4V/Nvlzg0leZnUwl552oML8Pm8G2C+kubrHp95WJMn7fsqLLFasCP9sPfZoWuFE9yyEv9vMFFjdHf8hHy2DuLmejo/9R6x5QdkhT7krD3KWQay4jypeQaJ/UD81O7ZapiB7WMUj9oCckpgHp3n2LIT++cfHqz4gFK0HSBbVvspbrEbmSs5Miy15S7W65PYcrqZpbhVgyGj5Gzpg/luwHw/Ti9l/Dgfqno1TezFrXYBjmzYu3bw5WFV9Z3xo6wHHXcvay7oZYjV227XuFyf3baKY4kP0we6+/pOb3VvdOaIpc6/2d9VlfoWjVg2GfT8p42coawxdZYtfjvDRRI1/um5VR6JJ47sNI1HfwTv/0ifsy+5kSkrbBl+txWxRrtK/aXuqPuuJnt072wlrNk1jC+m0gD5AZ+aBXrAnJfnDKwXPxG430kuo/SwY+QZ5F5nDVjjisQcBl/VNc/tM4Wo8zRyvbGvcgeeOxXPmhG0zMW8+cstHUuQG3okfF9VfLbYgetO8hEwx3o0Po2LWLXkg2APCrmYiN2w4lBFKRLCMyynqyvi/P14zsJPo032dZUNHmb+xJyuEzuTPRXBOr55P2WiyT4VYvWvhQ5cwlr8gG4FjIdtKV/ZZD80cSpZr56DOXM1+IMWFR2b0kU6vr2Ab8G+d6Kt2KIxEW3Gx9gPx26P8zx+ztptcoSOhyxPD7VlHGIpYjzlhF4vgbxNYg0Nnuv/MYNMKbnVJK5E8SZYV8SKWZC/1kJOXYbxe4b6MrBLHvPRROSmsIXE6+3RI1gCkWPdbwu/9Xif8wD2wC80VIq3jZb0frZkrv3WODWlqWx0eiQ31ok1L/0wfxPfL4xYoeS8PjK4m1siA2A/JUbdYV7eGqP6sOa4ZhmVKnplIdb+4KehMhq2u0zr+06bGNHnAyVNX+j4pm1GKeyrjWeRu5v3IMwD4xBDkqvv5n59dvwOa5duqcYs8436U+Gpsz4iM2SkSUvYZdboY+w/IXepVsH/cl/w3MT3Qx3sKSHebR+Mzcw0VGErTEHOOBQy0xVzSnustLweZUnTZRrfgTzQi2sh5sD3Zy+2pO3uCJnqmekqvs2SzezPOqjxHsvctNV86Wdu7HJKPHlL8IzQExml5HiNkbYQfrRtWvgGrE3FRthD6H1S2P84rEEw3nV1UwbHvP/HaROx14Oxxy3uzze+Qz9S9/CKA36e+Eg7H80zN+G9xOogN8ZXnvF0NhTXxNgn8KVJ//Jhvl16vOZLDLdzyIM8kYpPL1eCLTwLfwsZ3b9NnzUSI6DDlr0+PFc5N7SKfP4Fm4E9SPhoqzP6z1iDR+t0/Sl7rJfi2bkxv67bMpv0edcP33QRM6wC1vL4MdiogR9crOm7PD1GcZOxZ4y5AXlW2YcTmRn6UjVUndONpf3AZ0Jg44oMTiJjkX/WQaxFrKCnn20JWm8pXqpHFXVfccC84gb7WlYVxOcL9HCxr+5z/e6KlyHNCs0veChR9w2WmIVYbrQtGbKPdFb8+cnxor1X9U/dOlFTwmeHu85h7VZAPq8jppmDPPPdD7fk/I6YAzn5Zex3poOXTPIg7INO3q9vSRzzHjy7wPqzLvZ8dVytuUef4N3xYbb0xHOGs591u64x/9mrk8IjZF0heT184O+n3QpVvBjEfDt2y1IcZG+ho+uwLpmKe8Q9xhYvbNa/eE7ollDV+1sVa153hz7/IE+9H3sc8I5uURr7snol3cdBfLslLf3lAj5PHGfy6Q6+oPe8u68lsfSZsFMtEqLlaJWisnYdbP/03uqumbghlL39xbO6XuEdtbDHK7og5sf8xlltjeRbbcWls/VWtLrbJd51M+Jg7/A4WXNxCXpaErE+79duZzvu0wy2/jHk7yJkrj5yvDuFsU/9bTEhc6v9aphzdixy1B4QLYPibRmPeYxdrXueiAO6COsxLWaIOS4sqVPxnM1ETvv//pBX08c7LmP+WVvacqnwOsfmgIEyCP756yDYw2zXncSE64l4mvhRKzbMUbWpMbCLGX5vM1jLvrt0A0c7t7ahxD5hzZmBtd/m9cjvKW7Z3T7OjMuguU8qP0GujjmWwb4WgjyMdeeWjXMsGXjZLQ32aMz3aQeYt0fKZr9B+i6rzlZX4fu6XmQevpMF+zuygldeY35f8e85WOP78TqWJU9tjhxeVRvPmt4xPdsb+xvmM0bBRldDvFA1QPdTHM3qkYrwOWlSZXfx/pR1HpMWaKz1vjMsKVvGT5I9Zt+wLc+xRs/wnv8iDNW7luVItOqVGfAccVTMSzN+Ww1HT8iDuX6IEK+fY47F+jc+pXGKSnSzJTfPDrt7JA/s1wT2JI6wZN1dff/J2oOFsNWHEQP2mpfO2bmA7htoOt6t7MKU1bSzX53jiQ11WdcATQnwKn5s+paZ0PN2wfqOIW35O2bC1f9jUYRu9yEeSfKLF12TO002GCuwpoXYEUfu9pOC0L9ZGMuH3rr3hz2/xOqfd1H3Tu+gjpYPlo/P2qna5VzEUVppK7+WHjHYd9iJdRh/T+jNH9i7QdjbGU0/u4gZ/LNMoJTmGSO+E5StsIrRGJOzBo1nyu8R2xWEzJlFNM/8S+zVEtiOmH6+alyUeWIs8ryf3N/eTl6Z6Q9ZnYeYEHp7dpeuY66HOU/Kr7GcvFUau9gjlv6uvmMlnt3ilrpm/eMwS67/ymzM3FVCcm31ysHxpnP/v15Vi0AcAsoe+xjLNppnVPAgVlnXyEgYZ6nzAnIWr8b++GPvPOkGSZZ+j8wh0PtL912qp/yyecCHtcc/+wxRuGiF37WW5LGlFbbYLcjUQytaKkzV+HyN8PkyxbGP5SyFE9AK63FiJTG4Eg3iPY1vCruEmPEm4oU2u1pLmpL6zpdcrKzRaHvp/3ifu8qoOsIN0OMxBSrI4kJ9FR7Xp2K2hObtJ2OOE3dfy0Q07PGih+GK54D3h/GXWYf70HgMHb+H+SUP7+rwXajPUvIczOskRsKlQ14pRD/crIjJnmT2V1UlduQiS1LBJ69E7OOY5lW4PplgL8MRA/OOyTEg1vT5dsiVE+9NVa+c1O2lzx5eQ39yRFnq/tf3pa3u9J9C3h3Qp5L43b8neVbYRQ4MjpQ5mFdqxIiTIIf9sDcpId/5r+q+gjv4rA8+G7NjpDHiWpSqLVnZuIA8Cv7TQb5pymOHW7pO7VNnXQNcv2SA4mdnblUc67U02C2Fr+he+IbRi81v7CvOYklv/J52nn3nsast6Rdqqdg9/VxbYqYiB/vglQpZ3a7pF/QZaz2e0WCtmidqfIxe2CNiirfd65WRyE9KndM4PE/e2Aqzd8qYaBmO/Z5/1ZYDsC3hdzQO8KcNkZKduFOw40Ng0/tg/OTffZh2qFzD36H4bmHiM8Bff7+ha5qIb2OMtKTRNM0VvBbxxqcuhQze50/eps81il1I7mDf6uQ6ltwcv9w8Pryjg/344ZOQo67WmNZvsEZpc8fIruuaT+IW9JV+WohHBDu2pkaIbIU9n4r9fILvPJ6s78mrdq6meCzJ11DlxGgX76ceZ6lvRC6w5BPk+h5ipkWIN1d/tSQBMVdG3h0/tmXTrNWmZ60tNRDHBD3UuGWjPgQ4HiLfOQp5tB7ON23evyFm8YW+X8E8RyOvq4m/L4biO3jGvcfNJXcFS3z795Ko2/Ad2NOo9EPl6LRRZhxy2aWsQ9htK1zByYm2wo6Wv20Zi3Uq2Hu/a8efOu4iL0SR5NHy8p0tm32gcy+CFEdpwqtJDt5fMD9kTUfij8+ucw9TSFve2zbc6UxZYbCk4B1Fb82ZNbBICxc5vdnzSOzWtBNXOYj/+gKx6JIXGeXTIs09cBzjauVT1fUn1jf7TtaoWZI+QPfiEWuLeHyjYfvbTfdKVfy7417NIbJuDuJT5IjE0iuXc7fLD7aqF/RxzGld71jzaUlJmi5G8Zp9SWorfMDaud3yk709kK00iPGarNW8C0W63DTJP3+rfZjqH1hMnGLI/OezWhakMex4B6/CeGFdPjme6xWPlmOw3d9L2lIefuYpxsqa6gMXWesBP9M3TNo2Dlf15cWRGzC3PAn7kyXpPoN9UT+vWLKvTwezmD95MQdL252zzDTIuZlfsf+OvfNns+70uYvcLna3xkz6ANlmLyrvlR2FzvqwruwY/n8FMtIxwzrHooK9FaZZAehQ663HHR8HHTTIH9CffV2wY6e/95PxhWzFrXs0lSnxCRrvmufPB3q61d3INqxraoyZd9Jvsuoe/UDo9kP8fNFoXWfyF+I13j8Uh4wwv4+K03ztxBlkvdz5R0GSeEnX1T+bfshZBTJSNc83Yz1kdnqKEQZxyfudsuQ29mot8tKskBHWnob0byDXog65NtTU/Z6XsUYZ72qsmDPXNC/ajHMa6+7EzSTO85Al9mj3xnMHSWozJF7fP8+H3MYhV+tQFL53rJ+0iNA1kDwP5V0MMWATZ+N58AG9BmV2JX9ZVDbCtrZGXswe9SuIU/6FTW0AO9m/RBkn68DZY81e6VHJbHnFWtqcGG9K/ZnlkKPznaNlIT7XZTdrtutKnZ26Rm96dq8MY851JIn8tSHILDTKlqz43XbksiXCLCkHnYlIqfl3L+ZIr/AyOkFeNkq0pMI4o+tGS8pWEYobjbUpRyEPs6JtVTMRXX6Jizj1vD96h1j0Cua9rPxHF8/8WSuV7ILuLQxLWUnxqnxo65ESPWAb8dwftaF7CyOlVXy04nMrdM2SzPM9MtYi9mcpWY15NIvQ/Xr5GdNsRCz6I8TMC/k5diuTg/gUjP3fLbDlVlhxx7H/LHVf04DcW75jzcZtLakGOR+E7w/4M1zdC1bE2vqFR8rKvLAn6/VdXHHo5wSMtxTksBDlBHO8Wq6NnGvslI9Yi/4Yd3rIWoaJkNt9xOP66rOqZ4y4seaZFvSQkZCPy7Ar9/HuIpmg65CVxrC/ayBjSTdFKdzTQwmWROMZPft4FfY6+RzrPrZkZTHIHZ6zcLRb4RSQjy7yhMa/4j1IhiywOxN1D9qwTgUM8uWyDplYH55duk768hDkfQV6ScMQjVtF/tsh+JnPWc1FE9bTVvV3rG3cCrt/B99ddOKnzyLYsaMd2yjsBWL/EQeQa1ATsfaSg/resxX2OmOP7CqOH/EAMQH241mo5hHdETfCQZzsOVhHnquSh6dxzBYHz95Zzz0mrLBxDXL0YHszhUmVLlTX9ST01dyanoV+iuOBuLW88yLfWMUzmqtg/xXdX/oMOnd1WkrzCfKYwzzjh56SUzx/VlvYe8P7s6IrNHfwjKBwdUZRvVaYEQRdK4fYqe1IW07E5jDIj9F4n6XqsLpnsxSWwwzs/fD2Gcy4wifVWTzr5FjPeu5YtDQapbmnfzlhB89ovLZBuzWP+xWMvxlsfV6s05uxiGGhO0sgZ4ORT/Peyjys+90abkLMl6jx/+pUhn2KzmUojEn2XuFni2C3eI5/ljhAyMOO1bel/Ra3FEVOVDNB+/IA2IeyGBvvuR+1XmxWgJ28NDm97MY8umGOXUvZMg5j4r0P702iOgXJKfjwMvCp7YdbMqOhW2Hr8n7kn0Oa05u4KA8QA89ahxz4gsaWZj0a7Xwi4uX9N3jui/mmXO/o9kBz7pBDuTbyhvIR9V2t8PtS8Emdq9mKWy7dFeJrxsjeUQUM5lg8xzs5p4TilSbeMevMEkI2Ou5g7LyfP71fc5qxFpkYQX2xhnvxN3FcV9e11PlATciSHLBl1z5btjXUPXHTWOu30JIniF2XniwsjVJ3Vzkj7/1yB/SV1YgrjtcbYd7AejSYCz3Pn9q5FnpHXCBiSb8fFSVdauF3j52qBjaAGEETu6o42fpoKx7hLdjXTGMDHTzfHHkxQvLl0rl/c/ieCMd2n5axhiuOZ1/IbZZuscUX88hJ7IxOmc2jMy3Vj7+7iCUz/41Q9X4ToFcbbuv6/uzQE3Kqvcc8l2B/+jb3SGd/9pjuM26XtRXPUAn2bUKugwcgr/rXlrJzdW0165iC8buOC284iFeQvPQG5/iieN7k7nLxViVZ0uGuuR9ruKgeYg/Yo52Qxbjjupbjv6q2dMQeFIDt2rQj0Zy5JtGHNbasoeJ5TDlikyyzFb8o+x+J+5UFOrwLPqIL5ODfUnmlR0tbcXOxDoI+8C3mdCn/XHMlxnf3z8Hmzr9byN8ZbpkdPyB/hKy1wO99oBfkq+IZ8SGsU/Kf7Ev0yp5tY5zkmgyDHyePIPlkli0tbw570k3d2WZrZUkmjCF+VFr5ur2jqytsUvatOjfqCL0nP2IHyIcz0yDJhfh37F6NubLwmi19kzdxJf9kqRyZOBqzYbeaIo8LPDHEGX+lvpP2gbz0zAuGQbYDq642iPfGXhTirr6oAR0u0tnF8yDybEyHvm7crO+u6vnrWHDSOfJWDJKByRa6Gq6OUVgwB45o302MpVyQhw7Qla347Fuez0M3HsFWtEIOkLROJ8VnF/nelqTuKCnwIousj8ruuPfcKzb0aP1GWw5j3IOzOOQ0Yp052PORh0LV2V4U5Cb2tS3F8MxTFW1J2xR7tq+Oozd0YCD8znzIZZ6O+5w21rZaOh1j/OOxVS31kn76LDkEYyHuRYucg6Wob2lVn3sL+3xpJOKdbW5ZNRD2Hus47k/d80m7XDZ+u8mYNhT2dB7sYEvkSYzRyJ9zrEBXCTkbLClza/7ITx/nmKwTPRoVIe/hq5bHa36rOrC3yddovq/wK7bCvryEdSveyCOyO630NF86Hq7PZ5IPpy/2++2AoUZVyNqE1rC/H/Y6XnUuay6DbE4cofWyHvyZP/Lv7+fLOzdhDs936XtW9uZcQ5619bat+kyWNWytsHT3Qca/9EgllVdrbIKwVZrj/mmyH2Z2xpGbLXlKDsQVuu+4yj7dm9sOeUsuyEyt5kHmzVs8F7AVLi/7a4mpdazMSFN6WZLjzU/j6l1bcbpNYY4UGKR4+5angZ+A3SNGIHvaX0GfJmLsfdN45RXWrxRid9bYsA6Hfoe4KbwPmwLbsWJ/pCTDHHb5hMvxHvrOssTg1OZyPPfbRc0r9TWBGE09JdOrZqqPq0uVBPM66wtejXI0O6xxwXYcbaDOqMnbSpzg30lySfkzUfIH/t3xTFvpPypEqkC/tkEueEb0O1HzXJC7gzx55K5p+yGd+QJ6FAyf0TBnqGMv1rgd/EUG7HGOmbZUm5hLHi+4b/JuqrevJS/nHzQ3xMI+DpjuSnnWFn/IHrmoWOvd95ulMAe7N33t4l1wwpBwdUZ8JV5jdREjkTlsg9wrDMZUa8rB1iYg9kK+vTxA1/EcmmbJsA0aly8e8hWBMXbEuN8/+Nc1BnlVe7yvOuRwyDSN9/MMv9tJvDji6bH3EWNocQw2F+8fmcErCZ7a5vY76eQ69nUbZOAt+V6iEWs8sGTiKo9kyxAm2zHX/JNs+Zi1mPP1ba8Q23dciC0rElk/2dP4Xqy14T6aXdWB+2K9e52EnMAG8/wisVsh5WemN8K7w3RPTuE8UZIycpjzcJcq5nf40yewk6wb5tkU9Zb8oBWRk1/9ZUtF9gOLxhyPvKfvxIkpFAG9vLuBHBwx0qiaV/Y6CrmIRcS6MNadEP9n6w2N3VJ8dLi62+H8vuEzFyCXuyFLLzHWfHc0hgF1t9yixSb5NlpfbOVM2Vn3BrRZ61V8ew9bYs/xzkWT9DPvIq65gnxrHmsgsZZpZztNPzx3MHHaYAObQE7ewc6v+23JJshOHcR7m7EeOfH5DNBn/9dudY9ELPntBd44iZPcdqOuxUqO+Ldse80ZWCp+vU9b2J+jp/Q9D3kBWja3JPl1jQu+e5fGYk93S/OAlcZ3JnnLS9ltq41dGM/IF5aKoSfcjDW6HtQ1fvTxOeGv05cOVmfT88LbSr/7zBX0venKasmdTd+OdFXDWiQZmEVjPGFOLbDuSdMPkI6l3hi8B7vuamAWxHyvQ17Yo135ja3uVJsuttWdMX3DIszFtcArR6ppbsFHiNGJuVU03C3Jsut7HPYjkPeEvB3EGcuFdXmAvMLPvub874pHOrbC+od8NX772ConqnFZ8zcTn6Rc/2hx/6Hj5xGww8SArHLclrAkMYpDpFWZSPH7YituMdZsMAY1EetZTYoZlOtdh9wKT4x6Q+z9n9hjD2LSMkeLOcmvU35ZgKSEPpcaO8Egf2I21sq8C1d4QcWwPhvOWkLsj+PtwmQOZOMN1roxfDk5IGnHdjIHhB911thrZttG7PIYiXk0zhkBO2A1tOUd5vPSVc117UCoMIbofFBzM7zuou8No6frvp8pU374EOOg5oAL5v7OEeJIe8MsdWOAXMU6bPWFH8TfDry7fK5ISfjkli3YM+L5psa87mHMjOUW+U4wWXezt5vuqzg62Zal9zWf29gnR53kHyanDzmCebY2A7leL8S1zbqKKyXs01ro8Vv/ZnIec+LZU1H6KNaSQ/b2R4VLhWHVfIgDtANj+YOyEokcBHpdAT549X3dL0CMceYcFeDvie14Fmt8BmNZi7HnyYf8MZXmUk8drzFrmtaAD0cMW/+GxrRmzebxeHJmQo+I6w8fPwAxRprMmAdkck5Pza3N/C4M8sR76jI3NLdwQpVm0rDITEcV6FPzyX1lUjltV94E2uo++MzT9gqD4BDmeRHvWQFZLr2vicl8qgfmMwx5Re6rGq++Ksa9CDZ14b2LZqnPtuIqmXNE97NVQozZGmv47JyuUX8NH5sDOpc773NnK4w9aEc9SV8hSmGG98Bc/T79IR8O5hfWkBfrVE2a/2Op84crsNfvsG/H3CGKw6HTlmhJ9Zet7qfJ9caY+uAVjdNFLl3WzvHekTwm5FllzMQ7UnIitUW8uCaXpc7w339DrJcUerulicHewPn7iSnQ3Id5rPe0xtOJvZzD3FYlpXP6Tq+qMTrOu4F/oyQ4dX9X1c26Xp3+L1l9XVe54ZLGmY+da4ujnaXiJHJVsVaIuNsHsFYW1vSvWx55ecSW/jmjZOMFWyZUtmU0ewtOE88oXA4hNxw5BDoIP7BxeIx8wPz+gN2eN9Yr3stdHTWLljTITZEe/qQ23lcB7z2KeLs7nnEFMccR7FPoUFvhDJ6Gn8vnnGa2dXjU3diGP1oozo05kI/e2WzkZFUN4lYTL642fh4fOFTVc4+DbazTuY8612DtbeB8yDdjanJBdHU6lkG3Z1ywXTwnadM/1LECcfudyl6FSZ8S69QVOcexu8TPQswAPTpRI1LdmY87b8tIfNd/VbDqH54AfW/faKOrOuKJn6v0HeWjPsjFkA+3wPvOtW+uzvU6tEAsXStC8VJWK+dVPAEN9lpSIWsOGbld1xgE++EZkIPa2JtOH9yKNzbZp3pmhFiqpmEQbGGjBO0neCY8dHMpx3KetXJtMd7L3zO4OizVvEbsHyXHJM9Bhr4eoHDCo9ZD9pvA3uLdjxK8MmrBQnMWxjv8bjcJwJzj4Yu63NJ928R0YB3ZxlVRMh37upi4Q1jfCwlPTdaTjJmlfXelzwOlxcs3qoebeV65NYnm8aOBqk+xUqLuG3uI8R/FOH9A/l9V9siEienFg7muGnjF1R++iOfSV+9o/unABzo/K/X9k7lvj465p0EO50CeieHFGjCeg11nTT/GvtztVRguT6qeN9Zd1zjr5GoipijvPrafW2kW+ccw5iA/rPGho4wz06lYqzb2tO6hFvKv0yPNI+oqrHr2Lfvf07aTGM+ZfXX8wFoK3h0PH9hdFkNnHzhhy3KNc45bbSu+D9qYVoi7v7JG47zmiCCnGHlpN+zRvClVBixylewx1VkSdrMefXp3jAHf8WK9O17UvUNRK9xi7rBlcm/4JQNjTxYutf7Uz0yZB/Zgn+4XTJ7vustzR3OUjDj8tw/PPp/t9FP8Q8TGu4C9T1MhRDrNYDzWWnh/kRXf7esKke8pv5h3Oywwxq3XfNalr1oKQ6kiZLYc4iHqNTmZTcRKae/p/HdY0ycmOa/nsh8btuJQvoPmrUdeFYdtg33ftdQt99bncXJsvdsiV2+On8dpfmj2t5vdyhj+iI2q9UeOgTFHHbVkRF+XZIDvabZI9/eURCzFWK4Q4nRiKCcgD5lwyE/+xdq5Ouk9/0W+xiUal4p4LeSoJhYFMUZYo9L7jEfhxz3Hunv9As3daYtIttS2PGVd/jNL+uP5J2DHG8NvJ54vLlGFUrnYN8L7htF4b7s/NXY3+QJv3dX4fDWbQh7/u2V2jfvsONwVdq6zV/lvnrfPhM6OnbvUMK9ofvgJ+P6GJENVXxVxExxPLWk4NkrhKxO3hHczKSBLb74VNRlH065MgX3tvB+xCcad1a+eqjNsOHew6XeJ/Ra2XMN8i/ePETf2Muax5plfijFmSF/N4T0e57qMvM3z/x7gSOS/jbEW7XrwjmGtsT4O9hffS4t3XYK+7lyvcWBOJei4c119P8dG6PUV2Ogn+N66525JhN9bgrm/+3XDkRo2c9XGYMVjdumYPlPx98Gfa/o8Ia51lMzDZ3vCFj/C9+n3WSvO2lrWsy2EfThE/X0/0UyYiz15lUmyxlaU1vunGIWgp+N3a16tN1O1fDLvroSY78hFzd9Avt15d/TZwehdpR2bu8c62R/AekzeZfIs+rnY0g6fvXl4ukHuhyJLkG/g9+zNGQ8/kAn6eiCyl+pnffMmyPXFm8Sc3csW772zrhJLGzoT+5d05q7xw4d8y0vOamxPcs7df0iMdrxjLOs6LfkIeTu7J1LFC8Tf3kxs4WWQJfbHvrPUneJYrMuRJF5pvkbfYZLnpTzWLSv+/QJ+gpjAjCeCsdf34LOSPA2U4KGWPKja3TmpAWQBNtGAfWbt3dHLluKwv4Acu0GPTS5ilaxH3BG9uJHjQh9L2sFHnILd73NDcwSw7oN31KxPJQcF+8IPQj7ZMzgE61ccn1kNHfJu5jNiZM+RliZxaohx+RZzKw/f0mv+T3N7Cq+S/fV1a5lJ8uqzpv7fvY6NeEaFg2uNnHNHOddDliJP2Yr7gryUf1zQ/M/kZbiLd15qlVZYW5PvhS3DEJ93qBgl43/mcxA/66+PflK6Wi2DMsT5xI5HvPTOLS8ikZvgGUuwDoPx/LiQGPGBvF33/2D+/mErXJWkk9zyH3xQiboRMgMx9WzuVfogKRAeLSsbw59DDotN1Hmab6JHsmOfDgY8N49+tOXxnlquY9CPdH/dNsiJR2yxP7EXPY5prtlbezS+uQEbc+Kijr8m/P8sdmABt+L37IU9P3JHn1taTyHXXkvqYV/mLb5jtsZ6u5cddXTEXrdYECxT8P83azF+6Pdm5LPkSyrbwisbEO/Sj/Melpj+7TIe8cnZ2a0wav8apjmgcuIdS3lG+ATPgP4XgJ87vWaMcwf8SqbBuudgndOWBzV7yBPIUV1iOlJHYXu7I9diL+Z+xCLEBDyHOR5tESrX63qlxQbdO98COVKWDbSbHpm0xqv4zogxVubqedOJOOCkY6jY8F8p/7pmXsZ8KrEGNt6SkfDDeapjXIcDXD/OdpLZBy15clvrbkfErglXNKZxTnxnJfK14XfXGibzDeTOkassKbHMlhvY0xl4x1DI6I462n9+wFzN7Ijxl9uqppq9ATxDMhpprmLyF8VhvL9HQGaydzPTQXZyYw1mYv/9spc0+vVuJV95T3EzSuFyNES+MXPScJ+riC/LI+6qWVFzeDSA7+mPOOUvrEnlV+ccjMFY6zlh/CcXY4JeYfr8ahr8+pyZMZKCHImQlQJYn3bwh+EFhrlmQmYvnl3loB1YPTpS9k6PVhjDqbwRio8h7kMJKZgk3pU2T7CcRd7M3HDZ1Ndm4ETkl5WSm6zXYcy/tIjWoYyQE555no/3kazYg6Wwi4wRl+3RmPKMwdN0Yt8cciTs8zPIxHrktuPxnPY7dV3rym36rKcQ5nP7uS33zmlO12SFbAl8DnuUsogwzuraNljlUa78UTIVc317TeNwfIfOpUBOz7oP1pU0gM2MRDzQEuvgTxyiYtDjO5qL4SP8OjnPyA82fG2YrF3sLwEdEd+s19jTAQ6di7J/vMt7W4pCPlgLMxhy+7yVzgv9WfcG20pOJfaQ3ugYLX68wzmk61dqvrWlLONcfC4D7ElgG6/wrrraGVuyLLAlDu8+ABn7F+MZnyu3Yw98YK15tmzNnVmaYhxFifuzs7bKR2MvpzCnjfKXfR8t8ZxtJ7NhE5rg59nv7XGyPo89H8RPGL/fX2HoF/wWLduzv3N2xvoa+f9UvjvuZj1ZHHjBefwfW7of0HXbV/AdL9b91HyvbIauPYNvbvreI+N2hQtzlX92acy5M9Bp8oUSU5I9binieIafV47fG6pwlc/F6f4I4s4/hN8IygGbDvtwAHuw65RHsmGMFmxItV+2wuMeAduYd81KR6djlpn8FvY3sJriEAi9Yks/rD95llkjIli7QcjbH2H8J4nxUiq9wX6TuWdthSlcC74j10zE4tCHv6evN/cuDpITd4kJgxwr0Vb5GmtCL6TQPjwx0i3lLg6UJC0ayh7oyCrGGbCHtaD7O/Z4Vc/ha+xhkXwe1Wt+d14SJ3FmeY9ytEZnRy/s5zr4HWLg09YMiariYL9E73aa0+PVxaUmcX3XJbcUxsytSvmNRvkt2d/wmNm75hCFw5odukdZ/YL14V3MPqwZcevctW2Jx9xSYz3Yo5S7xVxz+sXlqpd1PeSd+MXEijTq2rK8jC2TYOcLIOZhPk8c8v8OkdMDsU/mkg5y8S4JjZQefrY0++RVuJQTO9sqVm9e+IRrLWM+yEzgAqwN5pI/sLLzV218H/rcDDZ+BN7XdJCfvHgw0PF2mcaQar5E35uRn2YevpOmWjKJxHuPN+ogB6O8Kmav+8mtuOzJR0HM7BTtNY7RYPjsRS8zGvk2LnFNrhwpT55tdxBLgLVdUsut+EqWIq7g2hzMvtLFOjZy7nVk7Txs5AA8g9yMrKEg1jntUaXcyI+Paizkntj/k75V5fL23M4y9z47JyHufgA/c6dSoJTDd1Zl62gSz6gH798w5/R7NaatE/K+qJktfhhHCch6cAu3qtHmeSNx3GsNj1K1HNfLTTE659nlU+SgxsGeBLkiFypxzgTy/5D4GPh+eMN48+PJ92aLBXsd7IULw9hzdJzpqA+58a8/UGFxtsAcizyvq7CVt0Gvig205Rj2e3rVNQ7WPb6eZSub9g9k5FLFCNW3f6n0IUelGI3/M6hojMyCfWSt8gjYv3zVYGPIOXtUc8n98cit7mTvI36eBflgr9WvYFvyYP578Xv2snzojDn+09hYuTVM7mBM57sMkVp7WMdoKz5e3jnd6qvvhjtDH9i3wHtqYnYUXKfvjjP76zuT4p3cqlY584N2khtx+reIDAbv4gdeCXXeQDw6s7st2ZEL7rjZWuWsJyNs2e+T05n0sFd2XNN3MfuOIQZtbMumxm7z5OXmcgzPfwE9WgEdbzceeuZrKz4Y1uRsHVDJyd6insxtsO7LRveRT5+96r6C9/Ose+HZCrHsySdGTu9m5zWXdTjel/qrj9kg2Cu11uRUfbFjT2x1pW34WsVTtxvaKj5+j38vwx5PGYT/zw+VG8NsGbj9nfkAev4LMhD9yNe0EjXO9+bl2EfkwfGWR07g935Zop3PIcvpWdONNf01zqswFLwYz4sVmRXWzUXIN+vujuEd85EjxxC7ZRTs9xFL4RHWgk1qBT38xprQewsc76FPq7Nu9SH/3iDe/+K9ebH2GSEDpxbZkhcyUvbcJ7PwH25J2uEvI81m7QuI+8B6g+f+YfJvqYmu1xjTS/jHB8RX3DPGZQ6eb/IM6Rf+RGNtVt/UvYLkb2zVwStFq8B31de1ElWYq0/spO6s2HseVNOWltin5tGaj7crsRnv9zHY57UCNtI7MUL5KN5hsYb/cZkwcWI+Ry/YkpY57Oq0jludYBuzxKj6gup3PpiNFw6VMecqSVO8K+iM5ulhblIGur8xqLkUhj69j9W4tUVehjvuEmOUeBIzDceyErq3Zyt1bTj8zNK1zmDk8DeqvXeUwphujCkvDsztmK3vst9tRszQjT1WXolbHCkDYEcrwge2zhajcOsq8s4W49gLHfNAhpoHQs+Ri37ea8nyLvWF2PKx53Ud57YfZ0z2BLFHr0Vvj6r1bpKwzTzWKlTSJw+UKZ9sWTaopnwMj3S9rfrK0fmu5kJRfHCwZUUxpqnwB/OyWApbnTjkPyFXPWtbshnj6NYrpbHzRISEttW9Kyt33Deel0xhTDnCuv2u8jCiv5BzMOc83VP54nWMSSzKaMQvw3n3sVJjHs6ZYsso/Jx9p0/2pzK+N0P+hvW8w1oYyNUR5Og5TtsSuzFa/onMLWM+VVfYOV7I2XDMrx7kYVQqyMXU7s6buQarGJ9yxzMYci/uhR+7AZmvsL+Ck3xBmaGzje+w99ktFSCz7JE8CbvyK4Wl+rP7noqWwr2gK4g9yfdY8oSuMVQ42Fc0xv8R7IXrSqCUwBh8aofI5sxYK545ykiDdcXHsX5PX0ZLkVl3zB3jvdIQtsYfcThxage2t6Qi/G+6mrCLWMd60LOOsBONPN3NXrt1XydxSXjfTdm/ijimZJnXDvp74kkSj7MMPv/8oc7T3heIkKzM/1hXF65jgPKrLYP9y8PHaozTWB9bcRyGD7VVDdF/LT2qb2ZbXBkXceLmwEbUjvhpVqkWIqnwzGisyUZL4xZun+mWHdiztm5LtgzTMRrvwch7MD7EK01T6Z6Lj9Df3udYR2BL6SteeV/EI1ch0ymJL7e5u6oNJzfFTKz1GLw7FWy20fWtGX9F86MRZ3jxTa/iSlwLH0HubMULhdyFuF8fJiPWKxip5vnoRDmDGGQbHnVTWEqrZLkZPVpkKtblQLBb1WLkRgw5BTl/Tc98n+fEmsbvJhf6ZdbZZEvfmxEypJhHFo2zJf+yhuKcssbxCPHnGMhx+Vhdr/jkdUOJHMu+XuSYaTEn2CLG3ORO7IFn5S1tK+yneQFR0gJz2hyZ2cU66RXBsLtXdH1xZ9iUxphbzgWWwkQljhbz40vE5SjP/v4gGVV7oJRjXlLckrhisDkZPVIyVvdVs1eEPaHnzmiOl/74DrHeUyBn+wSdGV+mu+MjxtX9hFcGWpoLqwAxBGaMNX9Cv7rgPUGQsQnsKejndmQY7XRUw96+9sYonDn66wlVEfcRD/+67q9ais8/2NVK4hEnNbuh+TMWzpvpap0fn78fpbgQG+x0K7xQ8jqdStVOlt/Q9UF5mmme0/qQjyG/chhjR/aT4aEOg7aNfZus7cqAGGfLf8GScb4+jyJ3JXvAeiCWfAf5J6bYZextjZleWVRe31vlNdIo7IuM9zWWPrnNP52ornobxtJeZUkhJWfoftVY+KrROTTuQNEtHoU1/WCMV3Lf1nlTo9SlzF2skbhE7CtbopGDxmK//q4RpvqMG68h7k0uxaHwtJ4t9SrY6qw2L/xBJqx1k/GaS34vcodKNXc59xMDE/JQeXKYvFtCDtpIGYs4z8qEzxleWYy9Yiy1GXuaB+uQrgDW9LzGl+gYZUul7pb8C/u0gz1x7H3Hz+JzHXSw59AD3e0zMIX5+7etcHAOP7Dl194hwvw7G55ZE2v1J2RnFp479Q/4EzxjZFPIKmKS41PiTJ6pH8TYPFcKOHi+MgCffwj93Yz3nM1hSfAir5QgJxr273ecxvInv/AFPHtoRa/0uKH5SwOu6XqndnhHZuxZR9iCEl08Mt4X/re55perXkVzBmw/qXFYXY2yOLJvt+Vax4aq5rIl1rx+hfaS7u/DPgUfauzL7a3XG3/GZHHOCHRLwTXtJQBzZ510MqzfD+TLUbk9ckPaSlSA5gU4jfGXhEynb9VSyDXT0YO1Jb8H4s26kInESxGq37zOK1vhPfrCxrYbZKnaJtY0sWdhfVGvqstNu9aWhP4vfAqlgr9uFSnJZvmp8+ziIzoZ1eC/D/oeMfLBDsV9e2bUwDtiIduTsXar404bd5ZZkmkM1qlyiPxzTJ+B3IOs7sUek9uPdRyfiVsEHTwEO77Qtk1i85M3fRTe0WSf7qklD24s9Ou9YA+HYH/3W3Ll+ERXaKJX2YFSCUvMn/jdNvZ3vY6U+3hGGejcwqm/nbRbZrlImZ0acQHeXwvxRc8nluSdreteZmDMG9rbin+1ZX+vOLBu7NVLjv/X3eeRNsit2As8Et/9wRhsepyj/sTeqtd//TbN2xL7LJmDvmAynkccrU7I0VoM9EqpDNVc719a8hPx9ookswxiGdXBXrAWkP2f9JfZaCewXgb80O8aw8122NfOzZEjYm0DJreTod8tmdZT1zn36jTGmQZ7Tlwbcj8FH/joOo53JbrqGsTGjcDPp0JmOjx9aPKeu+QWLdcPWXuCNWk4MUreXSGWs6k49chV0LsM7AD2fKUjTNKQ6x1zmIK1tKBXTW7qegaeoc5F/ELulRWIB8ccTSOlvLaMqL7QeHhaY94W/oAcdc4gaba8p8LOIdcw+1tY31ezVDfn8rnJXQ7IZ0BoIcRHHjnHc2zozWF8JusakTFnND8Auc+Jlfn+ji13L2jMpwNnLGm+L5/Bs9IVsDvbMa8Rp3RvcLlkg13Er+H932as0X3WYIwo6GKN7S7EB7Pmaa7pVXlHGFERWEP4YfZcpT6p65+m5qgozoW1DXL/rOipY4x05DIL5b0Q9vFSSuP7RH0G8fkuuWUOOhrCT3aH7s6bijwU7277vb6MR/zZG3Lje+KrowvGUR42Yo7TKy+QIxRFbMhelJ/4eZFvGYx6Z21Zuj+p698ojRGbEnE443vi+VctoOOx0Z3OOFp0i5YXu2EbsJZGjZzyBmv9DOtkYIylz9lyfNpNH/KSjfriVXmpG78nlydxtx75uWUqfld/qa7Hc+I7sumgz0+PRybluWTGZ+krtQOh28QQxbuXjdW4C+HI/woUSW2Q36IM4jHWIVqQ8c2hxR3Zt20zE23t62tCzqaytgB6VhKxVjj+Zu/BAbyb/OoT93gVBw+5qon1WGJ3RpM8G67BF8zLsH8d0lmOQmvGGvceIpea7lU4Ub5325ns2bwB3zelNfK3veGKw4x34Xtr2DIse4iUGv3AOBnQSZpjX6smaec8E6i59FrArj07mOAgZ8hFT7SqexsLX7wEMp4KskYMrviW2vbv8Oi+CHKPVsf8TsP3kN+A93m+2yoZrE1/zN51yH+7Cm7Vt80Ynbzy1RP0+SE5T4lRkS7FUuPyKo90mvlD4W1OwDMGY+2+39L3sN6KiNn26f6T3KuPmmsfR0sOhyW5UnaQgoWwj9C1POyHgE8kxjjrykv9tKVj8ytmP9joxm/LuqYSPxiyMnh4iPSA7fwXa3UNc0h6SteiVzHCJRC2iziMzot1zb69kiudnLFS4yTxXJuY57vqHDcCp6V3tM4ImYGvzn+8p5Pnnv3XnzLzQbbzQPey39H2I0u6kpINerilTISwj3IY9pgYElWf9XCxZq8Q/Cc5J0eyzwBzbrxS93upWpEltro3/1DIkrR4f1PYjX/ShCs+ZfJdJxlpS/+8HhXnP8D3F2BPyLP4smqIDMQYTkAfmhbV54BP8LxNzxrJiZa2jN9lK77MEY+bml37Qb+mpHWwnnrEIN3r8BPy3hLr+HF5tCTJXFfWwSa0urrZ5VnmlW7Ym9mIpR4c0HcU3eKjpcJftsL1XjN8pjERsd6qI7o/mP376SCDebFGpaC/cWs1R61x25YjGPOIk3mlCexDIHztP5VjZDqe23xdgOMp9mMl8hxyAXKPHtxtKddrF5ZCeXtKSox7NN7deZOOI3YdjpJVsB/nJ+RSGFHEQVwNXT24Q58HL4Z+PWgDOfprqnMjYuiQ6D99KmGPRvHMDDlp5j0znKz/7VKsk3SGTU4GmVyE8febi/1+gfw4iSG74F/IIcAeLNqUs1dsZ8kdtuSpYkmROZNdLfo4pATG77XJJwh5Qpyya2UF6QEb0hox1Fn4luGVF7gOY12/EnNoVIzcWmuJ43ofhSlUCGtyfKivpIDM+pnkqG1vtg4Pkcj+v5ys29qVf6ji2ckxrKPUw9qUarnL1QY6xbtGJ8azB9+/Cdn2ntP9/uzbX1GSdYW2+Pef7NiCHHrapiMuYlmTz30W8tJDozPKRsjZ8SzEC0b+e7KiRCB3f7JC43R0JbbmH4UMxuNpellSEDEuuZyJG10zuyUenu0tYf1+RfMn1rF7l/9jMwVZEoPfDYdevT3tVusZCvnIBDvQBfNOWKVtAetY5m+JVnXFxbBvTVwx6g5qHOLeDD5dZAJ8n40YsNYftqrx6gj53Y09PZ9H40zvxhwTc4W6in23pUoqfe/BHgjeBRbm2TH219ynz/sYR03A739t8CqcwOa7o6Q2cu6a34+5MnfuKuTN23nfIwsQH0352yt98f9yl3S94fIVAxQHoytbuLzFz6sNRKxfFnNo7jZ3Yc51iX23HPLyvoVJ7KvtnUrI663nTfKd3BuBPYnS9i4E6/oT630COlwyK+x6imYSDz/aH/tXAuuVFjJWrFuAEHdr5o1gOfoI6wBdenM0UqIgA59hf/si7q2PNQnF825HQx62ae4Jnmey1rD5oqHyd78oyff+izO6aS6pDpvof6uL8xrrAPfacqeirqlcg+9/aaWxBm5gTpO+hMgAxKzfa/5p1nxAXPJXPiXYt/jGqzC7iC1BXseFJ8JlFezTX8gHYibZqj//BtY6MY4YBLZMuKb3hveIxD7NgGcRf51cQ2vDNA/n1YAhcvu1w7XvzyGOQkt0f0VCokf1Lo+LyaDyfN5zf/foGuGmPwY4zY6If3iHi7jlYIui8h3xRBfIajQ+06p0uGTE2k2ADvRqOUiKzyntJE/bXyVtGYz1SQJbewy+uEaTUUatOM0J1S+TV8WLTvjZyZDZsCYDXUXG3DFCYJ9OQfcfJrVl5T+2ZM+FPYE/rwG5KNuzpot1nEmQf3yFnh64prGThmHc4zGPCz2XmLmu67Nn9gk1xL7+yBem+ph5L1Bxsa1wGz1YvzPMcf+1ZfJk5HH7bNWb7O4ULdWXa573Nlin3q28qvaf3GEztmvMWWLxpH790eXG+vQM1RgLfx3RHAuH8bMydZFXQs9mxrxwbRwSKsHEob6E2OnpLsevyW453GK7qzfkr3+0JUNiImUj7GORyAiFX7GvqebCuAD9STLfK5Or24pjI9JaYpC/0R/+5TFs3CrIfDTiiOBc2VzTeL47zZJzayPkeSbNl1B44R7XpfmaU6I/5mpkne/a2rmXuQ1ysDYbbCHkN9WmlKpuuBP2swni7xutEQ8+s+FjEA+8CZY58OfrikeK32PINWSYd1vszV+NPQvEmt1vkF1uIdcavzJaVn201RkS+SPmf+rtYk/k6cv6HJMc0kq28P8lUR7Ft8g4+aZBjulCikN4wqx+kuaM7hEiXjdxly7gz4yD+l6l+BSN6eU5qeO/fQWITZzE0RX/zx8OOz8lWmpE2IpTcMWpYMke3ERYgxg3V/dB8a6tZHdbRuH/46Hvi2f7S7GXu10zSzRRGKidThMXXtfX1kvfW65D7xtmtOTOP16pC1st7mfmFY8tj94PVf0CTbBG89Mg1xrqlsL4d/G5ltytZKu+47spLInGWjX7HW+y55V3iKP/jJaNWJ+NE6Gv8LndCsK3w4b16umSVW02maxdWlZok5MYZQ3hq168iDV4V9fA89hVNXUL13PsVx3o1j3yWW8gnput6jFmT/zp+A1/x2ePZS/ytSg5mny+8aMv4tzVyR3EZ9jXpLGjMWSrON5b+x18bVfs4bSPPoVNS0LgC+8iLlo2SXOgzSjhVXbsPzz7TmwvYf3zecliThygMecSYIPGI3cizzkxgWZmtCXXQFvlZg272LLwi62wSebhefs2DZW0sZacRGxZbS85kDSuwfQVlgyFXJ68oX0sbfl/sFHBsf5CXPf2YolvP50XP/XONn9d80oD7FGyhRlc8w5XkmrY4/FVA+XlsGj5VTqTmQz25Dvyvs+lkculrikX3kYq7pkdOzcbhbD2LeDjj/tgD6trLqK92CPrWE15NvSRox1kn33lxE0OhL3K7YRfaWbLcMxtCmILnv8b37xyqj78C+y2D/S2X9uPjseIdYbCX7KubOzjKPPrFl2LnRLyepLYv9iLgK+VJQFx/8SopJLt2z7nTCNSaiCOT5a3slTIUtfgvdEZxICsMyiFNd1Yxpbda93y2PIo3oK678aaYyG77KNn382ZTz2cRc9lNInrkTI98pubmnOsDvSn+Z1m6nz7Rw6P6j1tka6ZNIJMVzzVVyZXwr71buxinRs5CuZ2tRSe3FysRyvE5uQzL10wSAJYFw87TexE9rYxnhr1K8QkhwnxqPKG2NITvoj1I+R/4jwrwlY2xe99GWu2fucgZqzfdOw3bM/c3UVlNuL7oWd1jcpH6MUX2OjPTUc7cyFuJFcVe6M/Neomb2bWcfDcZvcttzpnDYFsBsM+HoDM7nISxwSyWzhYRszQWLAF8M60iKsCZ+laDvZaToj728fvHGvb4PNox25rzPIg2PG52UIk/K7GHk/RAv4GNuT7xa7yG/JYGHMtgd/1yBIgx49rjNp613kWYsv7BjkcxChaDHt3fYq/FKmRUmYirlyZ8rDrH+bzFZDPFucZl845Y/Ad4pPy/JE91Dchx+vxudabNG/MQcyr6nnNAbKycSXZOm+ikQM2slsnjCFTUpO1Z8Q35N1sifP6PuLSB1s2pA1VHHGsAZaYoYr3lTi825tlMitWtlVtdkhfS4grtB5rXBm2lFjhP+GTW231yvmNtqoNfI55eKf8NuvwPG8N4s66+o45CPvp19wjfe7sM46OjFHxWY7z831aYm1X5HnuU/y+PuM6Cp1MuzVI8Scsxt5Ov6V1txB7ulJg3ZC/RuD/EcQt+O5R8Vs9zH3bQ/h6+KwO7XOYk67reNmzbLD4/oecfdEgSYCfZY8/cUQG834ybbhzt4+t5GgwsVUnBTvIdVduo+a8LQ/Z6fa7uJxHrnRtQV6DfbxHMe/RkKdn2N9hU7zCXkhi9ASyZgH7kNwP79wXJbsh8y7Ixt/Qj3vwe/H32b+238zK/gmMwbqn7zsbwRf3ZVyPdxJrdsCUt2Ykfn64kSXhPSwpjzz8ZoVIadzfljNjrrg2I87J2ixC3dPnOKCxzebBXnzq8Mz4hrGT86TGuO5yJt5WZ0lHjzYVb0pLXIzTztWQLau9EobP7GDtN37WtpolYxBTz/EYjoDUbtWPZ+20xL6g+ybZQ9WE8oq9/M27yNzIER57ZecLS/V2Zrlx18V+l0/IP/sWwzrQ5zps1YdVBmMrhXU5D1tRBOvWOpPmdGLuGnzIlo1zNc/82a6hqi43JXIa3j9NxvNq37GVn+d9XfrrxEGMkn+whs8HWLIFNijbHl2LzZ6Ez50GSRv4jnnZEk36qIzV5jka9IcdQpx76KwtKbBO7GO/eE73neV+3t1oMztI9Ym+xM8HXdZ8bUu7+ssz7C2xAIgRx16CTJCzJJAzxshJkK+wb/36ZY/C2umLn/GehvbnpTtGYazyvrfa1CBlM+pg/Gdhi//L3l78j1tSFLH0gLgjZodkiNULFnaOQ8wbMAQxMPQ4KPiJ6ZengPgjtm6JOKthY93fUWTbLgd5IQojborHGjXPHyMfUn32KTuIGJbp5XB72CTEvH3JT5ZzlZM5SnXs3fPlGpuBPQfkRmSNHLm1t+z3lzt9+siWS+xv1jwEvFcPOmFLCaxDybvRiv+yM+S6MJ41B/HwGMjl2vnMG2NUne6lWF3jOwx5BvPcKKxBLPaduLbPM4RLbJIo+fkuTEqFRajnhvjNdBFDYidiijTJKzhK7tHxD+Nq3u2RG3YTz0S4pysCle4ngQ0mF1pxjIP41fT1GyYdN1JeDpNBlbxq79mX/P5HTZN9vlsqv3NlwHNC6tDe9JTvGNdPxp9VWikc6fYHt7iqIJa9EOpV51WsD+reMEruYP418kFPYVt+JQ+XB/HPHc/m1BRytqXYb8tXxDgLEPstx1pcX6/zy8aQ6xWQD+JrHMbaVYKdJYfPsm225MXnzuNZFnx3m+pt1dlZdHf8wTwbQR7JKZQUsUrXih5xzRnp6mV2kDJYv0xWNlf3JfqsLeMxfRdFDKb30I+/f3glZxm3uBdq3p4I6G3cIh0/2VinWrW3mE0iLUnSM1oq74iSXd4kkhb6KtMmOZrlPOhc2wyfwXMeHYqQQbA3xyC7/YmNjdgjU/muErHGFtrL4z4eKRysY+aXd7X8lYSOjn2x2rEGsTCxjVKQ19eLGHi5VwbChrRLecq4HmarM5onB015OdmS6htSmTnObzKP361h7J+71uw2Ruv8c/ZwQSb9MK/hezUeW623thxp7pWbmFd/jGs4/A1xkdpBJ6ocXWCMZ+7We5mRP07fL/nm1jwj99ZESgTyzAzJJ5vEeeM59y/I0JHZXunPeizo6gbYLuIy8jyJZ/hnYZtHBboVhjO5R4kZRV6WA1UHSxHkL1NzBTmzvQyT0ZDDt6Ni1FnqcPgH5tQ9dj30Gc37zIHfHbszxqj7+cT0zVUPKbk0iXtU6tNE8xLifp53rIGvHgcZuQ87/i9+H4KYfFsp5HRrbYXzxnOLDCd3O4ccDFJ9ABdKIK6GTCaG5XCy/mIuZPfa5Z7qvow1SnVgu7rie/kGxZsJs4ZKEsjSJejvHNgGcqkT1+dl2utOYsv4tffKFcQPrNP9e6rGGft7BfKahh0kAHnwhBIbzbGwPcQKYU8B746nxGlcjTrrB8hHvI9nTp+xR2Ow1k9vap6kvFj/Chk0hk3NR7peg2fH5PlZs0PM/1ZVNdhbaLVDHIm/WRfQLP/fJnG5WYOUEuuwDu9iz4tPiUjZfBxxK9Y5P3JkchKxF32lc5iz8SWNT7jgkSW1RyCuiwmXTenCzQvuQpIzn1tqYe9Wvgk3O2+0ZApxOvJHyWOs4QbIzYrLyI9y2nIIsXwbrOEOfD9TdujTq30uR7zuRfoHdugS/n0Kdq4C7FqlwEhp+Yclbfb2lprHtJ9YdcGtcJKfbtXYxLPYM3QiSt0fMq4ZTmzBZSXMm0EauzE1bPDsLS3l81dLckPeqUf18Z7PkMmb0JmuiDkCkK82zvLN+fiyloOBeMagzbCPGz2K05z3AFc3B0mO1qdNH7ybvF/7FnQX+1a0HI8OVLhRVa56JTvkfitswOga8Klfhxl1Wi9y1MuKXAW6tAJz4nk56wiJ21Ye7z5TPFr6ws+8gU381VTneAtHt1H9Qtb6biZxvGphvD2Qk7BPIhbfJdZphj36bmTtI6eUbpRfLmDe9yDDLSAryxM0pnogPv/i/CfzyHdLfmzRd6H9fmQS8ug+KTfLeadSCeMsZO7pcH23+gh2La66x2crMdmHQQc/RUu2Y7a8PahxpVm3RV7yysORn32zTd6bfpjuFmuTJekg7yMhMxng86omPDHI3XijdD2DOOHENczW3ZJFrLEcqfvxvmGcDbBW/r/aSmzqAKk6ySPZb9lO4vYRN9Iedd3g+X8ocuFNdwqKF7pTm33D+DvouaWwDX12tZEdWK8cvWLkFfFvIA+9IcdBeNegbawtCZFUiBGGsu4IPnboUV2jc3+kJWOzeuVz9VRSALHJOOjSLfh/e4fGM/RrNNOnAGsF8O88P2y5jDnkQI6afZHmZLiD+I1npRGNbek/N1qSzx8k7NFj/eWWRxpjbfzYrnInT7BkmhQib+APyc+9Z6f2Cz6Qa+Zx7iWWEHf91xTIPOY9+Y/NxrsA+GGsj4mcoPEQ7b8mb/BI3i0a061VMzHIB0fOWuLO7YnWZ6wF8O4S1n5zUqfOzlmwbVsQA3D/WZNPDLEWiLkOfomUbPhu4cHwY1iT/Ike+Yx5tnhSzbkEsRZ7CMvjveQr/7HcUtxAvA+pfD5K0h/1Sv3dtqT1dcuD08FyGOvb9Z7GHKDdJi7NzVkaV/bxKs0FFogcjT3n7Cn+ib3560OYfMN8C8Af5UsO278ol2tmOs3bdJXnsr06qRp29gxVg70tOt+r7OBkxDKPYHMqX9V9hNkXZzTWJHtvBmDvG/MOIr8tBa6vdn4rcMjJPt0zO/JJHvxdqo5X9h/WvWebI5YaByDTaRq0Noi5ext+fWitSpL7tK1q02KJNw57fY/4lKnCFKZrc+j5ecwrB2zUaIyv+Mv2MnWfvmPPksyW3oUKS16/fOYY4k9ft6RSri1OYusTg9JvuPZjl6DX06B3c2J0XQ7rDKriZ73Z+/E+Ul6sdisOtzclvLIAY6YtJadiJcTlUZXWm6yTWc9eU8h9iccaNz3zl+wOcrmT//pO95XOXIiRpg9KpuL4q5jrAMSzdws2c1zaj73GZ4jhTny0FEuD1Fkma1y67fLIaaxzq+Qah+li+lDF31nteUrFJ+P332njZxlLJnSNd/x5sJKDfbmMeZLDh9akX8AcbqQrp/zQ31c1/lSjuZprsVQRjVdw4oTuC1+Mta2A//+Dfa+9x5L0rLWB7px5GCljcljylHe5+Gy5pZWdBfGeAcH6DqLeSY2LuX75DDP3cK9cnJNCxfjXGi5xNIYeXu+BvO6SW4pBDgv3tSWmDWwVnjNis8YLI87Mcdh5njsWzZ5gtv7LlqXQ20CHJUNbsS8btjXPVIMcIux3rFXPlnXDPPIMc4qAb1oKG/0Tn0k+Vsv0CshDtrS2FMa/yb9GHL4hM90KA7Aw5IVY1PH7df8h6yT2Yp4hWzNLtw5uxfm+97K2ycQDbsQaBsgSsY9aVYS/K6lxNqsFnXBswfyTfbEVNy7xXBu0bSXvW+peUdaMPJqmazKOwV87WneQfmc94viwwbVm7/9KutaYqI4obCNgtKxr4oOqwSZEEYzRmGJSdu+dY7A/JKsmPuKCqCj4qK1xrVWMuDs+SGgxpPWBomx8gi6RqH+M8tBgq4IIRtPEVRqLtqGliaHWaLQtifT7Zn7u7t25M2fOnDlnzjffsZhoYlRYczV99ji3f+QqIc9YxbxS6W7a7md+KndCyPAsFkNXHp91ZA/Wxdy87XKaWD30fzPik0+j2tiOPujufcjXWaMlm3WpIJObmVtl34/Qh8ahalmH5XhpQ+wTT0M7Hm04wUsqLS/Iecif51uPISNiv5YgliPunjjkbxA39cBGFHeSE/O164H9GVwdks+KnqiXS6eojPuWP5F1jfoa/nOJZW5qtuthcAz2Wewf2djjK98irmtXEoY8/+IZc9ziwp2Xdgx3hidJ77fjFLl1yRlVcizV/65bSxnj81mH3XXpfT7WNd6Z/LVs+ERLAM8VXCaGXps4gnWqE6+88NXkww6EI/JlbavPkxGUcowxulWb+2LVv2vjC7XxHPnSTiG//4z8Fb7ak7uk+t5uU2tiP/r9pkrLcfg/FxfaNTkJev60KEXWXc2TOOYp74U2sX+DuqtaMJeFoUaXvJZvoLcT8b6Nu7WpMa5uk7MTOpTV5VyCvjvQn1rWUMZ7fngVkVmbtNC3P1gxT9GnIC/cdH4+YLGwtTkzZOiRUvkK/uCJMsvJTj7FooRUicPWkLuyGf0jl9MzzM+1RxuENXlYc3SyA/8a3/XA//hlyDbJ9oQMfwz5yxmLktPyc7TxD9ZN/QV7vyM9CDufq9SSNsup+F1shMPYt6WzVGLJWprGlEgrdG15wmiX9wS7ISsZiEgi3jke/agfDzs1U5u8bx3WDDHew/COafAjPjxF3GXE1BJlzdWRoxfJamI6Vl71Pcd+lPMx/IgPdkly4kcuz/EWQPdH3QtL2QSP4QhhHF5HDkPIqfj6IsNbHoBfPsC7NdA/jTaYX2ddb54R9m8Lm7obf3RskTTIoCsXfuheW7+o97q9U3b3RMjheUBDe5X/Fsa192jI/CcF+tkCP41yIK5tLXRHJ3lV7KKWuVlB2XKmw3Gw15zFWBb3l7u889ZZGZZC6GEAfW0/GTa8tNkFXoe11H/C3C9/v0PyTuWbWCW5+nuV1W3vsdHerEc7tx5a/mZifAbnxBTz53/it/Kl6W5D0OJhqlYull+/8Mu5lLhim3c6rY+QmTbbT74h5h6J78v52+ZlD0THSmtXiUzBczmwRb+9a3Spy0HY3wrYvWbEvtGEAnkKXQtgfuqfWb6XQ/AbHv77XJU/qnFuYF+ve12gMtDf2DXY/f1aklJ7DWax7gLWIdqueR+RQ16vBIeHZaBnvqyCvB6gXz9jPWRG5/uZm2YOujBu71cEoIPF2K831Xv9UzHO/wFQSwMELQAAAAgAAAAhANTWhMT//////////xUAFABvb2ZfdjJfbWV0YV9sYWJlbC5ucHkBABAAvTgAAAAAAADCBQAAAAAAAKVay24UQQz0XPmK3BakXCKQEHwANxAXDpxQRIJAQoA2iAvwFfwwSXanx48q270ZCXa726+2y9Uzs/n35t3rt+8X+SW/d1fXNx/3u5dnuz9fLnbnZ7tP3/c/95ffPnzfX13fzb+6/HpzfTt/8/nyx/Xt+PHFs6cvnp8/OT/7e3bi9WgxlyzsEumICTfg3Yj6jiXG551VcWuiRxKWgW0yEONMkInO1nsbt5FSIRlbtJHEGezZB320msbVuogvu6RnQnWQrl+WbGj3tpZMJ8f7EysKHGbekQ2aeLAXB97eFXVG6Bb9fXvZ2APc5w+JN1sdmVdflClsVRYckrc7GwtjCTiV75ViPDbv7BWb+GTNw+QWR0ho5BdsCY81LLtBJnKy2ICAZbEgsEPPRhSC68azWrVIOwbI112Q7PjKDB4Nic1P7nuiZRd/6GL/8EsmLuImkF6FOLCqkuBxrL70ml51ifiJqGJqKX1aXCPm8gAJsrj8YW0DCbH7RgHqnQev3QCH06y0VbW1fi+Vp9CqVhb7pa23jNzgUkRaRFLrZMJSeRAJMtUAZp1Up0lAqJWZp6TsxHw3CAjC4jo2qU92qcrz7UyNreFdiE0TOnlqToz8ZoNQHgJIfUWcZvDdvKztooKWyXIwIE++7HkDw2RNIadssoT1eo1mhUPErcsXnVNoTRpqEu0ItVDB/d4eSxRCNBJscYdL5KH1k+CMaV6iilEdWfSqKCrYXKNPEPxM6R0d1CENDXlktJBMCA5k+KgqYPxyUwpMZa3mqFHUv5JeCEecFEOJ2vUEminuKcdCtE87nB4XMHsBYrG+YG8ox6yROEF7a7zByAKidnGQPrhvsGmy88Wnu3GmJITQIjOXtkIyKXupr5Zp79g7vZQzW5Vz07Go/MBFiAXUV4UhfuDaODD8EjB+AFqATZpqUf9FULpwNpdZfiGDe8GcFXiUE0rJxUIcxhqknflM12QEQJr6NL/oyQPajnmU+C36FPJok9u23GTvICxLmhYw7ytmq+ucA6ghi/fdAx99+66ysQ+hhR+bFZp2bhRHRXcJWb6VC5EHPGAOd2kSRYuhNyvZeYEmHalXh85RSX80L59v2zCGBuYMc/s1TycOdSZGrkmXCzHCsBPnk2wgKQkibrxFL1hgiyJtd5eFsMSYxEWbuaCR4cHmEXWuygDhvRMuHSAG6viRT7Qkq6CPijVdr5UnXssTcxEn/YD02rp/DGxgi9tr7kiWzJA/PwULGgOi5EwxrcpExmNCR9SlFX0PACgi+ED9DcJg/MLMQ1/tVQwjUgwb8JqwBwPF+I0f2CTKcbz5D9pODd8TOKqW1bZzLmMhkju0NoZznHB0XT7aQKAhCaFvrXE/BKMpPF1Gmi+YMvsQD8OJqf08bQFIQzeHQdoWGQqIXiHYsWOYvYBfWgxZBqn1qq20ulfy5yqYSPRk49dEcd8BrdDIgpRg+xDenpgKtFld2Sb8TX8eKSn3Grh/AWPzEeOpPLrBFI3R6lpaE+vAVmWONycDMy5IM0VlD7jEi7GZ2jZCdOvb6eX5EkbvfuMJZSzbT88Sx0C7+wNDfL9HtNO/ptnSPFs8TBVkg2ydyGOQzKE58BJKTuh3ZiER7L0naVYVsBSkrWCmcayMQmeygaiRCRaWLHU6VD0xGMT+Zz48nsATRYId2m5aGSanw1pAJrzB7zQZ+1I1Akg8oi09MJGBdegLy+FxA5UhzkRF0BPkthnb5LVfs0mfAAv10x7biuxAjQNkdM3HPWYfSButG+nIYgIH9xMpN8aF+BovUQzw2+Y7QCj+iFvtpcw4kWtuHgl1XS6mRi0XgHQHQrxAYhBR9/08K97qJPjmvkSLOIcRKPWDXQ9XGdoSibgxaMXcJ+oqus0VvRKdpcdL3RCErA0d0jc3nOkFBmxJNgkGBV6XB2+CqBLcAXH7TmhxWWe47vc0y5YNiqq6sOCLOYHJiNARP3H78R9QSwMELQAAAAgAAAAhAA58UB3//////////w8AFABvb2ZfdjJfcnVsZS5ucHkBABAAvTgAAAAAAADiCwAAAAAAAJ1ay44lSQ21nTu+onc1SL0ZgYTgA9iB2LBghVpMI5AQg7pHbICv4IepSvs8HFmwoAZu35sZ4bCPjx8Rmf/+9W9/9ZvfZfw9/vHy3eevf/jy8osPL//887cvHz+8/PH7Lz98+fTX33//5bvPb9d/+ekvXz+/Xv/6p09/+/z6+5tvf/qTn//s448/fvjXh//z70cV9peV2V8iCl/m5/37vp31+iP78vzTX1/vvglITcv5NgIzYxZ4ldfTKrm4fUbN1Oq1Ka8ogNrYEjOFAlvN+Sgb1XKSsyE0D21Cv3P9fFsn/XImf2TjkD54RFTO4FzW0rpWstqGMuWfg2lM7XVmdfdf3gvWeKlMiHk7CYjrNt+hSjlgG6KiQjFmVl8tLmGA92eNctS1IS2aei8/qITmw6+vTISCwUHjmIGCjr9VSVIkyRfwaD7JyEyZBlfTSGhfNDq1qnujVWuxZtXgBwKDRtIpqpZ2o+B4u2y8WWEsvhk+riwt0D+z9nIFZW8OphtjsSGL2iu5bp1sXxgQr2PwKFK0oEoQ86PosCZpAo0giOG2rzi2sUYd4JXbXYQSYnu65xFEr5xzI7apcZt7G5dJhMEywZuIAFP25E8PGzWESg6LihSvTJMUHCHBYeZXGVwWw4bu/G9UF4aIopWKLUQ9cR3Qmu/BPjqHueXtUk3gIF8tCs+XnTVCVBIISdZpaFLbfcu/V5hgpGsjhHlMCcgkIa5d3cQVQ2fiM9I1eFYOTJd8TABoyXr2RBrrVC3HkCJKFLx6i87OQapsMnArSIGX57Fl/vLVu38Z5G/lHtlJAbXTLIqJCgbZUc5jpG24ZUQ6GAE8SkGjolbFMoF4VkrPQe1VlyowzGIZ3tMvcbZAuNF8nFGrsMv51t3clb7bqnE+jLlLXSV0yqKd0SUTDqfinGfVs9E9kp/D5i0iYypVZi0YQXFx+KDGLHIUWA+WpYVJOKjposdEOalAeI0oqq6inOYu59v9/VLUS5sEG1hZayvz7FXxBbkOUIzogoMyr9UfcMUrBRjuby05o8hkqMGWWnrcGiwfRYQnyQ2J+i1KeIwkdGXKmy27GzUp9ZCitcxLo3iadXRdPlChx8scTj5btV6Ody2OzmOZqH9mUWVbUa3UDvSE5KcU1nBzjMY3g0fEheYZdTqw0yItPJ3eBbUY+K52X6m1sjshjdGsZY5VYQEofHIpw4icPu10M5TJNTm0t8mSeWEDRoWjgkILVRiYejS3OyDWlVw3zZQTpqg8BtimNY3ybTgKhbrKwbnykmi405dCdjc7FxaqDiKoAWnpgcgN/9KgmtaLC3tTVTLabIppTBGDsMsVfXwhqhCi/jlcAlhKjVj+ud2fLHq29lOCrnGRlnUd12CqaNGUcxPAwssZkYc1GE2TPA/pKrXwMCmzXJNaAzIGF0JXDdRuY1YMFa3pA4F8xI5Lck8jBZh5Rmn6J8mV8QQOipi3FQlsXFc/Hfo1IMwRQqX7iP2EAgQZMF3KJaXlHFm9KTmZtMC/HFZBSZ9FyuwIhUXR+R+dl2xaLjKVatkS+gU+OD8cstpmcLHFaGOt8RhnBCl92PwiEFdveGJm4BkbGU8MUz8bymUma5762iMvef/B7YgjjzuLN+8Oe+doYeV/LpxvxElLZs2ObmTAPau75PJewbhpftCqZxO5w3CgWxZkZi4PuJc1O3PvKeF2V8povTc8h4cnWXiusjY19id3ELwM5joja7iR6inGGcchmZFp5Pu6GRY0rrA79l4v6SByE31OyiIDh2KKbpZM201FWAfO0ysgKw76rm3k8wjPGWhHJ6g5CPOk+jMGiyFfrcmBfFiGnWw4zowLAWuaTBQ14d52k82Y4jkyD4bCvCyVlPHSa/FkorqPF5DH6ORp5dF/UIfDzzTEUqx7DYxD3Gpd94DzYSbBa/27dMa0kmSLhVIwYcMHbR6F39Sz5xoMM0USfNjY1mhRDFeEUnuQXvEACsI3bt45Zh3kqdilyZUctbGr+dlGz1mNRqgWOXp7+wOulhaCTm7iPfiCSwoGcMMByYsoyYcLpBeDEkgjUNbZwyNn39OrGwqkKbPOjGS3mB7AQtPZYnt7uWJsLcM8tl1Ufdn2bttq/KdhyBy8ZlshYq680sJWqqa+FejG97brGv1yLR6Powix1bDclpzmn5nAlQx1cZZn1ibTPcbAJKl223XnvjuZXVSzTMHekG5F/WBkqmwGQ3gpvfoA9dpo2a1qBLLlOzGXW8aDb4FAs/NRlP86wEZ29yWQGMJupcFWI0iePXSzFOLRQH8kPyxuBgnd09ldB4b5s8PKj/FsYeWGR3MBsDVjk/w+Ygv1PkgleyhwW2w02mfqxCXOYcr48my649tBloQXiXIs8yaEVTEpHtWDJ7LDbK+eJVNTseveMIty2YeHNOL6oFMaQfWnK8nAFGOMVMs0TBwiN5/1CsGye2PzjF5YSCn22JwyOsxR5mYviusfg2bSi0p0Sq/k+xGldPd242II3JVceSDleZWJ9PUsvs1nWLLTEwWlKRNDLBJ3unI9ACjrC9zfvZHUc8E56Sk0MSDlxsXxsOxyIwCyoO1R21QeCplBNvCjcKoRZBPZ4GSwEBR3fHN5MX+An9vJmgzWrDj2qPR56jDFebdpC7BgS7+L+N3utobW8o9N6vXUFWbaSvsSxCTTXXXOfa+nCJQiXexYMfuP0HZsxsO5h65Ox6nSWauzSzH50Lz7+wUQdHutF/bDbmFvcm3QZntKZ3fTxNRB5J4lHVL9h43JmNzcB1NlK8S7IGCzB2P/J8LhpDGAEwdMcnaooGLx9qA4SEqt3cnJLvxA0MMQnC8I9V6+9N4U8/x8dDeVFoeBlCYi2o4tcFx1rcDaoWB5SInPqcGaeZg0qRr5JKeltGmAj45KoG7diZV0BdwZUop9pr9k2PYjVQsYa2QYfdMToQvCrsed5f4ThuQPNDFND3I5O7eAklLeGkwpD6pN6AusMjPu68d7FGmQQkl6Uy8OHR2a/a1XAHdOQB5UELoiiy7Cjcb4aYtvUQkaKkRvRBLVOdeJvOFbJsnh9YfonOJpGcRQDw1rIR8uTbaw4+4Mg0dhEuSRrZu2oJU0xoC/OIB4PkxU+Rbga5FdGtNMs8YU4yyKp3eZBC20Hk1TDVx6/J38L+4cb2JrzOBZw0IP9lfhSUpZPiXUpvfkPyBZdlt2K/lt++SAxPeh/RURIp6CgUxEN8NVL9nn/k9cVWCAiJfIgXqhgPA6mDIiD03wiY4EQNmeK7m5c58rPsf7wLCQbIy4sKEuAqeNr2A2cQz2XNX1GOtDeUe5Ntfw/yJDbgcQPoeoaZjZdUC5VLNl1hX/gpcINU/eVxrQjUKrci/OlDLUzgAP0EbUeM7CG6+SolMdsfy7XEFlkRWDftfrV8ajTZj/qhSnxtFrYXH+7SvFFMeEVITWz5N20jL98Bpr4uQFoK9F7YoIaVXKmm3LpVNYuJW3qmFv9ZinTX/JWG9K3gFegiz55Dbx8q13Pjy53vhBKp6UZZdJO1Q4XooKIOq0fGobsrCUVpSPfC7TUi++jKxkO0ZbMnA643w3o86cIMt7xWsp3M5ORbf2Unwc2qSp2Uf79oxS7cEAXcKKaxkpl/HuccsQCQC1i4hhb62FK57mN6YLNWKs2tUNvC86cUKVZyIPdo4nfxjozDWHGEAJWmo2O/wypsQOWNsZcUFnQcOyB/qCgTdaLN8MNj11E6vwjwnbxDWcTn0wTopOzB/9WuZDWUK7XtUI445fHtmLMZSvsThCOnQ/a2rcG7HctpSdz4wJ67nt/TIeyoSUNNkFC5Dz7ZmOKIhF3YPrsMgbpJbGVk1FCzDnjgTtiWrFJMXFiqQImCmCRLzD5f4F+iY/AvuLDTBP7TVXy3kvgVc9aCsGW9+8Gs8yIiXUX+0Yydj/xymlN35UpwyPBjhx9NA/1mNy4JmBIxYjPhUq++ZM5YJnGPERWgq67KMCb2Y85xHN+8ZJxIn3WJyqO9r0QJDvVE0ttNAiAGrn7QAHpFrVhmCATKamefwSRHZ0zacCib6ALdCyxq6YwvqXgRqgP+f8B1BLAwQtAAAACAAAACEAR3nvWf//////////EAAUAG9vZl92M19ibGVuZC5ucHkBABAAdOEAAAAAAABTtgAAAAAAAJychVtUa9vFFRv12GKhIAZ2ICrqPMtEEbETVBRBuoaZ2Y3dndhd2IqJYmO3oCh2d2AXfgve/+A713Wuc8Rh7/3cz32v9Vuz98y87v18eg7Km8eWR6sdGBQ3wly7lVPtNiOb1a7vVHtktNliHh7lH20ODMr5uefwiLgg/jwuZHhMEP/s2qSZm0eL+nXqOxlO/89/7IN9zAhrZaBnRxVlMnSY85kx5XEcPskafLwl/HmrYWyoLxafUrH/g46fI1XUzadg957/RFYZDcUXxCF+u4bUJgoGJylI6KviY4COIsMMFHNUMH+TjMyqefF7oIyuE1VcrcnzVNEx8xP//ocGl0gJTeMUDFyj4ddcGU2OqbAdUfHcTcWEPRqelSgoPD5bxccWBnwzzAhcpuGRj4F898x4KelYOEFDoSMGPCvZMPOygsTPwfBadN80w7EWFuZV0SKvjKklJWSOCYS6TUN/Nw1HbDLKL9cw1xSJHj10XB+vo8YAGbYSGkrO1BA53sC57F+izw8Vs1gTo4OGsjctWJ6hoOooGesnKPh42EMc91wnapVTUMT5hRj7Mhqps2UU/2TBjB0yzoQZqHxRxZf/NEx30DGgmY70LzpaRWhYvlPB8F0KjnSQkXRCxaWdGhL3y1iwREIZxzDcMxlIfW6g+IcQ/Fdbg9RFhu/FGNydpsNhuQVVP8bBtZyK8m46sr9rWNlfw6HDKlR7P/y7oCC+T10x4JyCzt+t8Jjjhd3uVcTkHzZ8ni/hOc+V76+K1xvbYFtnCQkLrNhYtDz2BQRiWXEV78ZpqN5ax9XROkKnqtiZoGB1sIFV1Q0czNIw5XIkWnP9B0NVbC8Ui3ZlDXyeqKDOYBtmP9YQXEjH5Y8STsfLuL+ip+hTS8P8BzZsmq1j3gsN2ftk7F3L4yxRUD9rtSgjdGTNV5F/jYqudhpE6x3i8hQhTAV1vGio4ceMDFPn0yoKDWEvcP/WfJQxjzXfV4R/dyMGt3jcdb8kVBipoO6Bsya3BBn/SivIriQjz1sbtjc4Ju4cN3B7dw8EFLXB/IW9O0XFqTE2BIxXsWuYilLN95oKDDTg00SD0yoD34uWwL5dVnwrUQyWk1Z4JuhovUtD7cYGwg/I+FyLr/mu4PdnDT/fSnh2QcWU6ndMi1I0tFAU+B2X0YB/dyZTw84HEsJhQ5PfZhRtqeH8P+730OaICFGwy0fFnaI6bNsUzByt4LWhYsV1DQufKcj7VkYca7nJzD2ro+LKzGqiv6Zj70sNL4vF4QNn5/4sBaUPadDZT506Skivr+E6+3UB+/7WEQX11jsIp6syfufXET5YR78IHbOW63DnPjXq1BSreS0mnrfE5DniyQoVt8cpaP2mHvqfNNDdJKGEZMO9UhIGjNTQOVZH7XQJ+U89Mw31UvBkm44PW4+LMuXi0ScmDo9szrjWV8GI0xL8ThYTb6qwj8rIcF6qwXKkIwIkBbNa6qjuyp67q8I/QcU69qqLuC6eRBoIcTHwUNFgV6OPQKCGAqdkTBytwbrMjDfUmesfNJwdo6HETw3NHEehyjcrCpXSUc0vSuzbq6Ar63mW6xnEeV71hzP6SUX4bQ1P3miAxcD+6o2xoo4N+89IeBdrYPkqFQfash/ZGzPy2mAdr6Fnqo5HJcLxe4wZWhNfNJ4iweFIumhbV0KLqwqOdtKhtVJQI0jDdvbvHs7e02c6ImYYWPzGjNI2DXvsFdx+r2HFCs70wmB8Hm3gTFcb3rP+dQpp2BtrRqKriscRKu5tj8Z0atfsxjrmdneFT2kd65tqeL5JR491NfD9kgqf3hEY9iEKrUNseBQjoxlnSG9ZBYWoHd+q1UflKAMralXEvUYGOj5QEdRXx6hdOjZawhHZXUPGexXzdAuifFWsLxeIYgct6NqMWlvHgMNYK8rd13DJScUI6lDMVer7ZhlProRjZddo+JxR0NxOQU89Cg4FrHj/UEHRfCpmHw/H493spUwLYnntjkcN9N2p4iH/3Ob8AbE/yYR24VPExQb0E08NrU9rCNugwW/WXHFkjoKyaTn7SK/wdheN+P+nqmmY0FaC93sFQ3+a4enM3xmt4k24hq2zo/G5so7b/QKEfzxn8rWEHpkFxesgHe1Zx3hnFcV98wn7Czb0eSwhSzaQ8k7D3ygV2dTOsX4KLn6WkU7d89ysYdO0ooiry35YoCG/hwbvFzqm/FHQ7KoielxT8XOxjubcv/opVkic56sHFFTcpGBxloyIbBXXo8LQ57sFk87pyKyvI/9BBXMGqTg3ib2YqiCpro7+FmdxeX4wUnpq8AjQ8G39F3HPj/17TMF3Vwu6bRqKix9U/NBUPG3Dv9c0FB4Wj7rVdNwpz/nnfDYoreFBsIRf43TcLx6PIvGSGNa+A5a4S4hJ17CsoYy5fVQcPqGg2BgDkTtt8MxLH7+uojqP13SEDK8tCgq0ULHPkDElWcHO2yqe/OZcHNDRNS97eLCElxNk5OVcmibQdwXn7WwcJs/T8fqZiiKBxcS94vRdRxm1HA3szM85vEXdeWTDHfZa+hMFYezzUo/Zy51V/Hofi6dc09SlCrbm0VEwVcPiZSoWXdGwSJXwvqCB2r11qCtVJJIT/Dg/UrCC0L0aPlY10OFgFERDHafoZR6csc9pKi7cpN4G0zsc6DnL+2DoKfpzPwWXx5YQx4orcJqoYZiPBtNp6r1BT1il4OEPHdPLxeFrWwN96iv40NPA0po6Sk4MQ9lWMqoUkXGlpxU1B2tof1BF1aefxDZdwxWe8+RnevvCODj2sqHYIM43PSHPpWZ4MzAe6ZM1PKyl4/hFDedWK9C3ahg52grHAxHYcUVFZs/a2BnHuia0h4urDYPfBWNwtozD5KZRw6042/Sd6cICHYM32rCMPNWir7eYuE7F+T/U3vJDcHz4TbFoOjnLNk+cHBiLvMdVbG4voRnnYMXtAbjmraJhv3jUKc++ISdduKVjp2FD+AgdaZ1tWPBQw9qBVnwgrzis0VH2hoyhvbmnswxMc6fmuxu4VtPAtv7DRf6iGgrSI57uVrGKs1Gppw7nLioijjZE4iEzZp5XcTyYnh6mYRLn8VEHHVb6vzlJxY07EryW8NoWKpj2VYXzYglNqOeJb3TEZQwS96uq+DtIhgf5527AMMwJN+BfVMEQ1YDXDiv6N5NQj722m/PnoqpoNlbDEL72aK874uQ1DaMujUTiAgWNjqq4z54d9EnGafZytWI6ynEvr/eUEVQ4Bs6c59ftbXh+7LNptEVG9QvhWFNHQ4d9ecVAelTnUhrcnytYcliBe3Ysav1S4Z46MrcXg4tzRnrtMo2saUUkfW9oRjtxs4oNS3urKFlGxWrW73vgD1OvhsPQ9SUZYUIdsauGgWSu23GRDM9QgYVLDUxw4M9mKHjuQu28slcsuWeFy3cTjlRRsJ01eENeqcI97bPAgNt5HQ0kFU3tDayk3qaTNQL/6ajiqaC/g4bT3y+YmnkZaJOoYXxZDTe72kMmr/TwCkG16jXEgmUKDnXV0beMl1h1R8YO9prDbQmld8s4tFDDm2Ma5pCdX+Gf0KlL9QqRJxvIKEH/f+Ato/k0DceeaFg3j1rUnv77llr8TsW29uQuev7ne0EILBaOIeSHvssMuPyT8a6vgTD21/NLCr7U1XBgkoaULANvz8s4xjkeuEmDP33edfpnU/m5nMWovmi+X4VW2gE1ftnQAmbsIM96bLfgfRPyJL38BvX8TKKMAu00dDR03DyaJtZvN/CBGhtfLgom+sGnMPLhPTcMvKkia5sV/vlHovs7He3cFHxibXZ5bhDpV3TUtVNRbv5e8XetimEKe1AY6PR0uziVLaFAoIRLa3VmCg0bTvMalpUUcz7IWPLTiooNA1FXjkQo2dRthYRSzA6lyNRPHP1gpieepqa/I5tFT5fQlZo8OF0B6L296YGuZM0HEjWA3BGz1EnUPMOeraUggmyyyF+F7wDuMdf2o7cVB/0VDOtGDqloRQKPs42eMm+hjPB4Hi9Fx/5Wv01zW6eZhvYxxA1yVmZheta4VsKjooKl0xRc4DFfbI3CBn8dsd1UFGtaERcvyWg6XYf/R17Pbe5tioSR9PdjnI9tMTrq1ZEwlcy+YhZnnzzSiNd39auGO29ktPjLuWMmeVqiF2zzDVxm/8xif4z7GoMvO5iN6M8dyKld52gIuBGHvZyfvotVvLhLDfihII+Diq2PqDODVcyZZOBAAQ3F7NgP5M8Br2VYyax3Nqm4uLeuuNmdXpVmxdK+dUWrtmaoL8noLZzRmNngfWUNZXZSc8iF7ieYkThXvSbY8OCshJ5jVHiSda+SB1OWlRATJ5GTWcfscgY2UnOfF+6B0cwNTx1saL0tRCS9ThAlyDmdC7GHZnKNrFm5rlXF64bkHncdDRNVNLCPhsZ176lAnaF+3p2U83r2P49TkKzp66XDvnAs/nXUoNJHsqdE4Ew/9sxEHQ+vK1jPGXizjJ5LzxR9dOx4Ts200uu4n4PmhWEze6ZMgIysfRJm1jOwiAxy828NDCCXvdozCLuZ307G0FNHGHCcr6PTSQ2dOFMPLzNzVFDgzNx5Y52M/k7kCHLrkQX5xdT77D3WOXCmikbMCieYe+v7WvCyF/Myc9pG1j69ViRShqhYaubak2zIZkZp01XFmfFHTC1eGRhOPfhFjWr0tiMacaajmJt+zmdG5BxHeA5FFjNfqEVD6VgJltbkE0f2VOAWMbX2KDgyP81hj5zxMDC4jYGYztHIZK60cL9Gb9ERvEHNXUuHXVVF2vC26Mnc4kj93TbSTTg3tSFU1jCbvlH5m4yqx6JhYg0vXdDgRY+t/9YJHsyvfVpr+O7N/NCDvlT7qAh0kbHYz1t4MaOdWCljExm0/0YFFcYquHRYxjJ6p1N/6idrdIG6XrgdOZK9fXKGjiCy2uSqR0URzu0PetsY+qc0hP9foZVImDtOXCxgoPMsGV1VDceZL59/0vFpNbPIN9bykwZXeuCbYgbKUDMSI3l+rjE0wMAGemaeWzJe0CednypotdEfNvLRj/lWxPWVMYOakERNOvnMBstiDasfsF+gYcwpBZnMZwf22eBeycAu8viX8xrsXTX0/RGHab398DM/86xVx1qLiuWdmKknmcTFPdS7fGbc/21DEH9n8/cYtLtBLYoMQWfOZchf5jP+eT9Zdd7KDPH2sowL0wzE/2E+o/aOfK6jZScbppGtvDnzS84/Nxn1bOg0UUZsJH3qkxU9e+mY+CPVVIba/+0emZQZvALzUEdbXmTPsIha9MA5tXXsJq+d6xqPqJTPpiDOYNIK9jj14rh9JPq1miqaLncAZsgYS85f+4q6Tx1eVZGaxXMPZWZe7dYBWYsk/GDOFttZ42QNSd10DJlLDl2pIHxkUdH1C9mNzAJ/A1s2DBN3HOOx8Rgz6wsV5R8sEHnp9xHsAW9ya1yEgWoteJwlGp71UlGCufRnZxlrh9qwM1TCrSQdvarrmPzzt+jVWUcKNbLiWB3XA9kHL2WM79gc/SUD58i/b+epSPHl6+nBlZsFwTlLQusZFiwhMydV1VHotoz53JOc97hmJVvRmpn49XrWZAe1eaYBPYR6P6YUNo7QUHkLOaWNjg0JOubEqZjPXvK6xOvJ1vGEuTSK7HylvY7zXHchJwkbmW8m2Olo5c75Y4ZcP9VAFea9suOYTX01XH6gYxFrUnqWimDu0YkR8diaxvzPvixM/q08x4rX9KNPn/Lh+jZvrGhDf85rxfH3nNMaKr4EydiSJx75kl0xvZAZz+rKeExdHc/+NV1TsG+WDk/289tfcq63FX5jQdpAD7GQ2fzFAubVCyo2nSOfU1fnsPZ9elmR9pDrIB+tPWBgFI8R7aNjIbXmwGB/jCdPZT3VcPgt+XWgjKeTge33VUxnX395IyFkjA7vovSb/lHobqHul7UiNkrHauaJr+fInV7UDR7jxQodK66lm7xr7Bc579VdoycnNRmK0+TgWdc1DDhJbWMmOmjQr22sc7SBLpV0zMjJKzNDUZc/axccirnV6OXcV5ODjH+XdcBDRgbztWNRCQuo/Uu8qbf3VKQdZUZihvyZk9lfThf5vyqIraIhuWh/9G/oK+ozj4/2cRNxkozUV5xx8vID5uWH1MANH+jrdehb66nHXHuDfWRy6tIo7uXmxTaoBRQMXqqjKr166uyRuRz1/ZSduLFRww4fGVIqObZaPKrWC0BmwXg0/qsi4TDPt5JzzXXs75JfLLeT4TwvDj/lAmLlTQX5yyoIJo8XZ11nd4/DbjJ3jpeX5++1q8xMH0LOMweic00Fyz4zAzwz8K+yhMxkZugxGrpxvTu2qrhS3cBr80hkMZv/acsZaqngq4eKhY0HYr7NAMjn749zH5n1/85mzamR/+i/N8n/b8jGYSYV05y5n+VkdKI+9mWGm/BbQolaBp5sVFF0RQjO1hmFosyOXq4yTB2jsJI5fEOiFZ/rq5hXN01k83XfK6kIuGnASi/56KljMzN17U7s66cu8Hqq4vQo6t4kBfuLqVhsIW/0icNqZytGsj53ejoIlzW8nuIyCg42MGuXjoozVOxgT23PlBBPPp5J/e0wgEyyMBTjKtjQhFlqRqyCjDnUz9LxOLbQgh8uXmhFn39CT5xOBh2mq3i2egTurjRQebkCe+Y98SwWbRuxXpzdM5zhRsxbeh0DrX4Y2PqdGjGC+6Ex8zS3otIe9sRnDQvICX/ytRM1+lgws5sEB+bRx5w1Cz1whKrjButYM5O6sZ2Z+AL1cp+GoNcqRt3Q4LNPQfpvDVHvZPA34DpEhssaK35S+/oqHUT70jzf15pCMEd4XFVwumFdIZPha9GzPD9IWDWA3Dc/FveiY9GsSkthoS/UI1uVMcu4Tt6duFZBG/p+6Bfmr/n0NT8N+emP/pcjcYps24T5okK4kygw3oLzGQpKzm2L8R8UvKX/LBtdVlRqxWuz19FxoxXVS7rjywIemzobTz7cwTU8ZZ2ncU99S5Gz9svow9yxOJheX4wz3oz+wV58s13BeGaR76y597+LIo0ZPIS5+1yADWVeDYFDoIK11xsi9K0Fvhk66m+RMb0860jd3ftbxr3vkWjH2Y2/y4z9fL3YOdSMBOajocxr3uzhUZ3Jz+TXX8wEWxrb8DtSRnvm7hz2Ks7cUfIL8wS1+aq/hIcPLpkOflLRkRqzY+kIHCCXjvLX0OxlNTGsoIxxQ8jzvL7hF3QcTm6KAsxPnR4YuG9WsO6qjlX1DVylVu9/Fyreu9PTyxpomsXzL6VH8VpPcrYOcP5l5oIzC1jbDfHoP1XBI2rXMjLVXM7hrdEaVt3TUIXZ3us+/U8oyEt2jVthQ+H4OATUljHFzorNhahVbvSKbexV8qLL8P/dA7h/j/WaasV4elNoy3js0Nlv3eIxcayK5uEKzFxf29WqOL1MR7YhQWGd3tQi5xwegkkHbai6mvrwnw6PUGZ66mddZoUaxSUMpC9WvnZRPCc7R5IpT8+l15ILtHJWDG5vQGptoEI7A33oKTO7mxFIvZ9nzz6Yf9Rk4TXM4HzahdPnft8Tdpz5+8PozwV+m6QRg9H00WD0uK/gb6CDqGNTcKWnhEXXVMjk1KmV55n6BmjQf+oQ+21wSSJTmVWs70gfijlhejqQvF6RPDhchakTPWwi56e9jKlk9A4r+Do/Fa2r6bn3Yqr/qoBE79Yig5wU2FjDrEcWuJMvbzPXROdzxcEAM/p+sGH9Rh2NW8uYxb0uflBH8d0a6pj3mfRu8SKstgUPyPz1mU9D5nF2ybqThJ24PsSMtdSMVy5WDLkYh5fMDRLn+sDe5uIW9WPdWgO+zH5HmkvAkDjsO6zi8m/Wh1n/3GR6yPsyYgEzmnaH9duh40pvBYpNwrKiSUJ6EIX95WLRhbqbj32xb7yOWWMUzMt575zs0rsCNTPcgPNeZp0ZJhT9EYH821Wc6+yLyBUa7P7I6Eg2+bJbx7c0CTdNRcUi5uhJ22VM2injUnx7BHBuf7+2YXYPO0w5xXzaQ8HC71VFSBMD40LOmA4zA0ydHw1f1moWNS1xeywG3CDnqeQ08tCyvSoely6N5+3Pik3881Vqyo/a88XgcdEIq2vFhBIG0snb02dHIp1ssmcUe91LwdXXGtpzr+v01fHuPwNts7XcexGH7xbH2Cot8ItMqr0ho62UUGG0gv+oGYO4p8FkFtcjGv62Yk60GvDLoJd6M/OO1BHxwgr7SvG4l78P3OmXGQ5ROJ8swZQn571LHbWuy2hsZc2PK1jEbJzynJlLZr/tJBcxv7wns6S0kfDqgQXNB70Vv7i2+/zdKQdUdCPrnL5iQZ81EsaXoyZOM0SHqyp+k+2WkPsXZNow66+MQuxv2xUDdQrJ2HVeQm9qd/eFBu58Y9YsTt4kI9UoomB30EC8Xs154xzXWRmLQkky7G/z/PU0rKtHFmXO/8X+uTvKwJc6Cn5Xt2KMexi+NaJXT3DGzn39Rco/BUP8ozGqxyi0eqSj/FkDv/4rJRqwjx6mmJHNHj1GLsmgH7b6Ggjb3Bum+mOsuFODfLBBgycz652tCjqWjIXXYhknXowVY2sYuL69KdoF8NqZY5yZY97Rf6dny8D30jjIHDqZ+eA/qBg+TYXPyokiO17C43oKxHkLJk1Q0K0bc8h+DdU4R9V4nnVk+m987bZrNjSIIXP10RAbwhw686QpkPw/p6SOyMXsI4PaeV7BH0nHC4sZs5gJsqnXAR8NvGGd1phi4LhKweWCGjovscKWT8ZRMtCIMzrKNDOQwGtfvU5C3zEjIf3T0LxOMSEyVOymN/9jDm7hqsPPpqHcksKi1cqaSGJecSR/brHVw9laOtJOGdh9jDqzIBZ1PReIvu5aru9q1E+vhzq6My+2fEnfXMqfl9PQlV5UfL0ZBUYyp5Hr/nTRYF4u4Tb1N6kYM2Y9ah1ZqPBd5vJkGUOYSdy9rfjSyYBJxCDu01DcW8hsYE9vW0W9faBBZoZvyP8mLGCmp1cOqm3FYvrt2wstxbFNKeLIrT0i8Ap7ydeGtAjq3GMJ20INOJInH5KfHjPnhNFb3/Hv1G7MSdTtBgl+mHbFhmN32bcbDdTOp+HcTh2bhrIWycyefH32DdavpoohV6xINOnwp9dbqCX2YyzIR7/0HKTCbaKKoE2dEP6X3u8rw6G7gYlk71nFFIBed4UZPKArZ8tFgzczzp5aCm7PuChKTLITm5/oiCXrpN1dLTqdjMNY5sXB6+PgOp4+W9CKhXbkzlcKHrCWOfc9whuo2Pk6CkmjJfyaHoeZBQ3MHGRFmIU8bDawlt7d85YNHYdZkSeRDEguC3qiYm8BHSHp9I11Cibtmi1Anex6VoETuf/WgXDsJstW+BKOm+5m/KMuBXVWxLGdgRjYR8VbQ0OnGzYkNQrEJHK82xX6ZhNm0+d5Rc79hNUKeeFqFGwnqUfkg56QcT9Ixynmk7s7vXBhOJnRTM7Pp+JXLbLgAzMG/CP/zFIwgL1xM1RGrZtkt5kKTlU08PuKihmp7AnybARr84xz4MHjIoxzdXyqeJHYDQd32vDKVcUK6nH6YOq/iwVHTey346tMZd9XRzcyzr7u7AcPDfcWKPjnbWASdaMKPbRliTWiN89r+6zgEDn93WQV/gfJYLY41C8rYct0GTHkTltcfmHH2tfpTCYO8kAh+nZt9mUAfah1SRUhnJtVdy04MJdae5mzxF5dMsmKWZy1DObMgIHMvU/IsGH2InEr9/KsijXMs/OYQdqQ+XLem73W2IpfZUNh/7ISTjJ7J84zkHpLRgI1/lMKeZUcc6ldTdHtkhV//vNEryEqtn+UkS1raJ3aG839yffkyyLsg6RzMuTjXO9z9i57LOOngSvLNGzia0uM07CfvviNzCexjrf/WbE8UEJ38u31YxIGdNfg94G9W4m9y97rMjkY41+5YRnrfidUy71XHp+h4XiVUJGTmV0+Mtf+lPB8gYbCV86IADJbm045OqLj8y5mjbIa8m36Ik6etqDKdQn5TtQQNnrTTGYoB3KfSf4uVk3hbDG7tgw2sI+ctm/ZcMxLYrbh3nciq/vtzTJtt9NwihkqorKMuCJxSJ1lxc0AZ+Rhzl9TSkdDvT38ud76rutFJ+rOhrxcD3v+dpaOvl10vGdOqe9uwGKKx4NZZsxjDhnr0lrkGU5/Sef+Dbei6EMLXJjJXh9h/W7IqATqLrOKO/PiLUcrzOcsSKBfb4sKzX3O59kcAy7U+n7UxFkFxoqtrWRYL9oQ4abgXIqBeuNUjKaOdF3H3nWthrTTErbHvBXOmTJKZ5vhtHqtWFrIhqguAQiqQn8qG4+znMe4dQVxPEFGTebGRZmcMc7EAe7jnjd/RYDTb1HNsRI2ztfxqokF9on7RVqkhq0WztFvHVWu5rwXpiL2NLMTOdzxPX82hTmOejMinnmUTHqhkY7z5OtiZI1ocm+1dTIGNg9GodAe8Nti4GdtZ0zhTK0lI2S+HC5cu8qYTbYoMp2ZrrWK9CYSzA+ZtbyqiNLM7xmsc3OvIWhS54lod5a+UqOR2ESdy+rTXDTuNlGcT7Gh5h1bbm3a8Hz/pTLHL9Zx+WZ1dCEfF7uqYTJ97zI1cC81NLqbDpMTr+M5tT+fjuV+Cn72lbCggIZC5IzsNRqWD9bQhnkdqzlf1JjQ6go+kRMrlpFx5K8Z3tyXjDbheEtPes5amB9rqOcSjWV5ZRR5GY1PZL4P5NSOBVujlV0MzpO1jlLHy5eit1RPEpfKxaBZVw0T840Qp5fIqOep4Td9aNl7CZYrGhLTisOdHpwdZuP5dGSxpjeYqf8wBzqN4r6TG8Hav2skIS+5L5IMFzYqEj9GSehzvTEymyj46NcEx+7E4CRnaNjnJsLbbMNy5s3Rag94PteROlzHNnp55VP94H6E/lAqHiuKML81tWIe/fZOd+a9IuTppHTTrqMaXN/LqMoeeP46TDSgpjU4UEiAfd1rEPuImfg2c1NCHfIVe/qiScGHdhGidgMyhCJhaUsNu2vKKJ7C3mRv/Kz2nxCB9PIn/jhEPUv4quLkHQ0Xqsajc2EZPtybqUfJJkLFwHgF9ZpxPdV19N9MnlioooNnfxy8qCJsINejcR3ftdz7I4Py1cHLl7z2TK6rrRs+OWrYc+6S6Y0pDufI5FmXFbxwpF8zh5RmlnjK/dx3qpp4MP2bqVJeHuPHNNOB/gq2T9FRI4+BomS4imHsuXEKVt82EE0Os+1QMWpTJLyC9wtf7zHi1NsTpgmDYshvKo5MV3Lfb0i+HItk8kOtCzIs9MRN6xV8qyRh50NyVH8d9zPjEMLr/hmiIi89/E1XAx8X6ri+tImoyR4/+zEC5b6pKDc4HiEOGq7GcO9jZJhNW8S+bXFoW3OoCGRtkx2aiZw83Xy1guMruKf5dexvauDBJfpjnIoH96Mx6ZgC93YSXo+U4UxGyHkv5fYgBRsvzxCX/rCG+nlRpZ0Nr8kN653jkTdSwhPy1Sdyz4nFCmqRF+8MVXGPejPgbxxM1IpNX234qlFP+9Iby9P7yTEH6e2JhbhXy8hr7cmd53jdzKXL3XWMr6tjWHYjEU/ONf1krvuuIuuZhrQDNtSrpGFachy8ehsYcy4abtyjQ9/jsK3GgNz3EWr0umaaIGIxl/0XuEeDUysJ8/vPEE2XjcSnjhoiOFPXmp8Vn0M84JmqYOAkZrJZEgrzXMnBFnyoQY2mHrf1zHl/epbwdpbR0lHCbubNLY/JSXXIrxUVXKcedS8vofYbskJiW9i8ueeXFCwhm479quMYM+OxJTH4S34oy16KeHdMCPL5Knr9sW8KzvQ0cIZsOUlVMb4te7SRisKqjvbk1xJ3dfy5q8J3koKtSQb2Ho4GyM4vY6x4X+e56UxVZg/qRb2pQ9C7kI4nzirOMytdkDR8pA4dWWVDwYM87ycZbzrzuB5ThI3MvZ89EF6vKlI2tUUjcvFpzlLmVBXGNRmf+P9fyLJ54nW0diwpvFKqi+BYHX/fKnheiDN7VcF4NxVSkUhmAAOLx2pIHk3fdFAwmPu39wQzEec251mxnfT4f3UVBA3Rsf69DfbUR38/HW1Xy+iRJmPFBPZAQxUl/3B/OJ+NqpBf7sWhpb+MsT+9sLeYgRD6U+Ha5IZWOhZlWdCRPZjqGCly3rdQehk4VYmampMlqKlu7zRU70reYj/tqReF2HXx+BWv5Wax6WNjMYHZYeFhBaOGSbgeky4cGhk4Eaxjx2UNJ/creEodq+YUgzMFmZP/Uo+uhKBezvvp5K1nw1QUYA+1yHlOYSt19J+OaU9C4EudfPVahlcvBQWjdNhv0RDJf5cNolf8VVD8uoqNq2sgT1kdAeSgnPe23zlL6FDYwNxjBhrwNdNZDyt7o0jXVrAwY216R9ZS6A3Mqrvb23CeWjhubk/hXFxC4HYNc567w5l+OiDP/57bKDrbhm/pKgJ32uERObt9gI5xU/ebluo6jlLTgrtRX5hvR1TW4fSWtb5DnmXOa6noiFqp5d6ryfEod56n3EEb4htpGHKdmaok10oGX9hdRV32wzTDgNMy7tdP6msfGdXaaTA6MYPTYwaw5kf3yJhb2sDstswQ5LCDd3QUa6jlPi8aN5NeQJ4byH2qOo0zsuydWNVNRuVZkbhFLWtxN0mcvGvGxgsWbG1O3o1mn3YxkH9jmqkv83zWlysiboeBrfk5F0Vs+M1cfmBJOdxz74UY7uHBi/SRUfFowSyyn5xXYEuksE7VUJDcd3oCdZPzlveAhs8V8uGuB7NIb0ekxEgYQ/asXSIe46sZaKlq+H5sADaFVxU59xCr5x2ILjs1tGDG/fBAQUKv3eIMj39PtuDWCXrefmpDkeKi4VoFI5gxd5IBFtRrjGYeg5BOps8uJ+PxPgUzQuIQFmHDAR8dt/zaiFHkQ+WhFU+OaDgSTW5oY+DeGs7IQAO912koepvZ42cgfGeoqBig4H6+fBhHfXP8Qq5k1obELFNEZh5phK3Mim9Tm+K7p4pTTXaboscq6BXYFk+d3DCydzhEFQOZj0uLno11LEsLIetSqy7JaGiVMa6uionkwN8eXVByeo5eS2hVx4qRr1qLbguZLbjflhQd5mRq2zIdPtRM/0Pck+cG3qcG5TL1hMYWhC9hTmtHxuMM/3RX0JJa4UONcvyh4jR74VQNGW+r2PCWmXftF/bJYQ3dwyUMu6XBiz6xiD24vAY1kDk7c7CUe5/wE7Xl9pjCqNldxjfmJb92MqYmS7g6c54oHheP5N0K4vc3Rh7m4o704H7fZeRj38yvbeAG80kf9sc6zqPPoSF4ySzf4oyUq8XlAqnzXM/u1mTEdvQi9t6OzsyqN+if1Mkn/VpgsQtnM4KM0pTssIV+zP/2rmiD4wMVXbpEwuWlgvyzNXSoomIXf6fgrpPiWGKmiKA3+3UiD/pJKJmlsWeYl5M0ND6vwZPHn+8p4cUiDRnrgzBtk4qoWyrKLOE56GVl+9ngQ/37mhwlBoz+33O4r6d+Fdd6kymmKHC9S0/7reEh89VBzt8eK71iqo7Myiq+BbL/lypwISNcZU5MasRjWTSYF9rozQrW/GQPzqklhrq3w4d/7oh+bWB3F3v0ibSgAusVz/NOzB+NhI4GrrWPx9iGZOqBKvK3lJHKzNXrjkE91nFmog6rm0GGmSrycT7XcUaGXovCo2NkEx8btlN7/CtYsYm5rH0l+g4ZyLyEOuPTE7fpp7uXqyhVTMFh5sQEcoWTt4Zb3TQ8eioh9LAFi/8oCDhIreDM1WuXF+athUT76zpmP6JekxMvj7JgbHcDy8hqPY7reDxxr8nFiTNbgnmT+vLkkIomD6j/8Sqs84fh80Ny/SAbcl7jNTEavnuGiR2h9pAi/LHeT8Z5Zi+H3cyfOc+rrjUwoV00ViTKaJ7IHNsuFmdWqJjArDOJ/GV7JuNQAlmLfjK/TjzqfXSHLVRHhatxyOT8Ju4IwejR/uLrS1vue3i/6Bdrea3B02S0Gsr+rh+BJmVi8ZC11k4YKERWmc9cms767ikooVZRG97tlzE8SsPST3vFl6IyxFbmwXo68v/jTJXWMIG9JLQi4lpJzk8rA1W/arg/T8LolxKmM5sOJsd4bTUwZL2B8r101GamGxRDruU86OO8UKSFiuq/dHR5Z+CZRr4vrKAA+Wg4PXqDJmHE27OmJf2o+1tUXG88CoOaMGcu0CGvJtcdsuCjTwSSrygIPiTjD6/PslbHnAvc+94qPk+GSKUPzxiScw/YQJGOKvyWGPAeQS54Vx6pzCL1Ouvozll6H0K+ozfkjTdQp5cVl5uShagBRU7J8I+NRp67GlYxE579qKCvcwxsm7ku8mkYlNz3Kp3rXzEt537Ye7MfP6qIYZ3HTg1A1O+K+BamYNY9Mi7rn0omdmYmHOCvYHdfatnCByb//GruDA7fLGEDvavRBhUfvko4f1LL1YMVQSoeJ5BDGv/vGc2GtbgWZtm31Bjf3Sq2kDkOZZOzfshII3MtPkvf2aSj4i0F71g7E/u6kyv3arEB0xIbuk2X4UEmDBAGHtcx0L0X10oOiD2qo5uyw7Q8lRrssFGkHTGJM/y9l2s5L32oE59WCL+GCs6SzXMyWLE0FYsH65iUrGPqRjIw5zNalTGyPs/vk3M/95Qo11NDU65505NYNDrRXkyRJNTnulx3UOOZxY4zm9gaWnKz99o88bCMtuBbIRlZsGHochvKTdYwiPvX4aWMvZ9lZgwddS6xLzm35m7xmEY2eSyHoSlr8bWyhvNdFASSEzwydQxlvhzH7F6J1+chUzuGadgyepAwyJPmNLL8cub739Hoe6chCrYLgY1anfPMQSxztZzBmZ8bhsLM41sOMzOQ+/tRl4d3Yebeo+AWdS3ATkHeFPJ4fgkzT0agM3NPi3MKmv4i3zx2Q2RDPfeZbn9myWXUlddku/5mHRHkxpAmai6XDHOQMeERffS8Ey7ST4eyJ3pr7uJ5lopJF6XcZ9a+2chD1xV0mx2DhbuKi2X+OhoPuS18mMs8lyioxHpZyMdnKhpIIdee5Qx3duFryLJXycnXBqtoQ3bLzyxxgFz4JayoiOLMj9QVZFFX1i/X4HeIOl7EgvfSX5FyVkVpXrfz30Wm/PlckT+dLMDetuywYG9pHXFmGbOW6vjAtWfYK/DtquCaScVzOxexfB015rSK/dcNHFzEDMPXNB0RhcZkhjUDNIT52fCE7DR5Z6pokWZgR849jtPVxEv61CpmmP++cE/2kI9GxaJl4SoidKUCpwYSqnNPUiYbqDitEA6QQU2s2bVsDe+ZV7rVqoDfZKEHJXSMGcl53l0Bfahlp4+q+HjTglS7NHHlP/rePXraD87ioyiE81xfHsi4nmqGhxf3grr8apuCChlxcMqvod3KUHwpacGlsiqmffTGlMZvxMqyZtg1eSsGNWM/hsh4TR17RF2Nnm2F3ob9cLa3GHlDwQ0fGcd7UBc+0VMuqHAnhyYt02C3KK/QmRN96MOP5+oILBGK5uHkaep7pSsqXjPTzqceV/AJx6gpVqyvcNZ0g1xs37mwGI8xIpRZSpS2ov5hCV3JHwWpK6m3OS9+neAdaoXLf9FYcCRTFOhkgR+ZNuf5yvt9ZfS8kQfbXQ0UzEc+Jmv33P9OhDMTrYtWUN0/0xQ0mxxd1MBnMlzpLhpKpuUT18fImHxTzfWS6Qck/MtzVTwvLMF9SSBcOfMr70VhGtkyqEY8ZnDu1hfXcKgJ+Y39HbztsnBrF4crE5n5Pmk4wGw9dKkKF2bj9i4qXMlSYREylu1njuR+XGtuh5lhZPSe78Tn26wTNaTe7MFod1TGg2Yytu7VsLmfjBbUvBHjFGxPjsp9TqChvwFX/lymbrReIONjAnNAAPmHWXLPGfptjiezR45wf/+Sh33IdVZ6fwHO39kG8WjXlT7bkVxDb6hOjThaUkbpxFiYyO4DyTM1vcx4y2vRqNf2h2VsJEM1ncK5LG9FCRcZDRJ1pD6Kxsma1OY5KvIcYw6ws2EVj9NtPD2A+vapVyyCNihosEPDYnrY8NJ3TP4eGtJfcjapN1eSycbxNfAkNSI3w/QszPoN0zHx+nvxsgMzuTsZgj3tmeAoLjCnHQ9U0c+F+WwgWVgxsIU9UISzWWa4D44kKnAgpynMR9upDaqTgU/BnLkf1XG0FLWlALNAxSzxjrM/lmsqz0ziKuvIx7WVNpiv6YUxM1Ukc3ZdubcbQ1WUL2vA3a+aqPhax6UFD8SCVxqq3NRQa10gOpKD4ujX9e/Gw/4Fa/94qfAZJ+OOr4K39MGU540Q+UxB3GAFoWdl7OCxt1EnfHOyeLlDpihm88ttA1D9gRWfx9BLf8u4dFnFzNGcR38Va1bKmHJSwtpXOvYsMFDqloE3i3UMaqrCp0J3TCJ/bKjeHgu5zmolR6DQUxUFR6ro2pp6Nod6NpXuzN5rc43H5N4//vxbFKPuloinZjnRL93+95zWTmaF/Hf80JKZKue55zcjQyGNbi7237MhD/d8XB1n1GKvnnA00K25ga8JVpRin6+n1vs2MCOYtd7eVEIz8mJhMuYv+p1DDw2Jf/aakmcrWPnXQ+QZbeTe2yrQ+JMpxHcEvKrIOHNOxbwAG9bSbxNbKhi/QUPDaWGYM1yBW1ocTNShrtSHsbXo/3dy7pWwX5eEoyOvs3N58oSm4iIZO09+GVUHR0GQlx0iFSxcqaIG+69LiTZiE7Xmhi99cZKEFOaRs/sVTCGDtWVOrHZfRmjlG6Yzv8ksMeyjNSqecL4C+stYzt9/5toOD8Kc8Zc8EsOcmnNfr3q4mxjIrPrigoIyB+Tc5w5juJY3ZLsrZMpH0LG0kxue3jfQhLOe86zShG02WAYMFqfpzSW552WYoRcW0lCjuYyBZD4tgj1+gTpxIx7/GpnRkbP7aj9/fpGveSTn6rvvCh3tXttyn/8RPyV8IRMVZ3b1/KMivbqMkBA19z5MY2bukmTtBqzZolUSKjY2I61qT1F3sYKd5Jsm71+KzeTHyZ4aHB8q2EQ+3DlbwioHatp2BXbMlN2DVXReGoPOnK87eRV8IPO2cdPw5cNI5GFdVmbSE0bvEeXHG0gfJqMwr8mF/DZ7Zj5sYQYvzusuR+2c6ayRmXzwKioUEW+/mZ5UNfB3s4atnLvpKutvZgagv3dqZcMyZokNL2QMbnzAZOF1jKr+UexL14HyOoL+xeF9tUgMINsdecNs0Z/7RO26O9SGILLnljk6npNPR9Nrkul5kyY4Y+E1DYdLts99drxazvPb2TFYwPPuPaVCrUYmY95vuCgeLSuq+Jqtw3Bk3urMLNrJikMB9MVBXC97rsaZJmIP57zFHwuO2RlopCWKiPsfheNsFVN4PfOGRqByEx0XVvriolBzP9NZZJ2MZq1VSAsNaPdVrOgSA7+Jaq73/8mWUO8Js2HO+4IBOp4ekaAeNtAmM0sc3UfePRaJSS1kjHVQcbOlC9rE9sWOIgPF8H8yzk0bgMntVNgCumEI69w6VoZEdm/CNbtf/SZSWNvHoQE4OF5GOzJKoZkyOgxiv7+Pw74TOr6F2tCCfpj3NXWX3tGK1zsOZMGzzC39yZkjyLJnuuHLSRnvTDqa25H9yccdeqiQ68hY39PA6I3BmHdbxRGyTHmTH7KZKxvGaPjcR0Ul5vKhCQYSjsi4OFdB+QrxOHqKczGPNfdRcCg8Fv3Iz/bUz+bhw+BV66BoczQIa8dqyGIeP+BH7/VUcOGlgYspCnovoh55UbdH1hRBZPRld1WkWGXUIWe+rdBQ2DeIFI9GdBfKGGYH9uAEdx3x5NJDho5FZLVxu3WUYpZM3ED+57xcJseP4Ow4UtdfUeurMju/mU49jaWWcP17Pajb18g0hwwMlsIB8sjCxZ1wYFGYuJJH4QxbUbJfNAbM+t/nrtrX0nKfvZp3yoKpB1QceqqjrG8MykbomPlKxfS/Cnb90GEXaCCV/DOFs3+e2v+Js77/fEeRRg11Y85qy3r+nS9h1kMJVcl7R7bq2JZXRWHqYa8sGT85qznPebqyL9bakaPXKGjzn4x8bVW8cbMh6YqOjM8qgpJSxGHmoac1dbQ5XA5bH3M2/tpyP69R9i/z3bWByMyyQaL35mc+a8xZfszMUlYzQyllw3hyfKl3NizMwzz6k1wR+9pkmmPFED0Om/c8MX3ZZENGa2bLShZkLUo3pe9SMIbnbjaQs/iNvsd+Hsh//ZmD98dpWPEnGtc2yWgSxpw0HmIjc4DrUQVHJRnxKxR82m/AMXCXmJhl4NH9EHxvQS75quA5c5p9tgJ5kI6bleKRlc6sbFkvlL/0lUoqNp6hjuajZrZXcJge8WmVgmnk/3r2ltxn8t+QZRcvlFAmhhyeYUOVKBU7HmuoU4O9HsnZJI8sZ5563E9F1ZYq+rflHBfUEFVvj7jLDHlivhVhTQuJBTOYHTjn3gsUJNozm/9VcY6Zd9X016Iye3hThoG0nPd3IoJxuKGGd8zLRrYM32rMSpx/t10yno9pjLNHuB8Lycz0sgH0Yh9mqTrezmLGNB6fDJrznQvl5utwXM+10o/nHHgq3OtST9tKaO/GWpH/KscYuFDIgmqPuHfjk4XjDHJcZCg8Kyp4UodcxEzclxlhsCxhdm368hcJtch8rsx/+xZIKEJWv0bOdmD22+3Ec3DmSpMrylDvP5e0ouAhCwqxF/YXznmPW0YNct+wfa2Ezzv2RGcNlntq7n0wuwk6/mvVGM/tqRlFNSRvk9BlK2ezfTjkQ1HYelxFWgDP2dqG/g9H5H4m6c99MmEAs75DJDRe93udfEKOyQiip3KuA1UNzx5IKP/Ygot784mjd+MwtLiKYzMseDlPw9RPMkZvIG9Uo6dxpoePVdEhjfy+QsX11gae0O82nhwvZpHBenIvkw/r2JFPgtTIguqbFSyhZywgu3gnb+Ech+Tefzu4KefzKOxHcr+/Q2EsSjxl+kc+/UrGusls5x1z27Sx5WqRfl1Cx3oGet5mhqa3qrzuFa00VKPX//6iYgtn8Tu5Yg297jd92K2+hsFk+pznrbx6MIcyd9WfJSP6vYbeEwyIjtQ6eRgO0Bc2PGH+21kHsby+Qk9Pmd6tM3B8DBnRvSlQgf3K/v3i2Vikn45Ba/7+ZpuCntt5LfRtD/KF2/X7Jp8kKw5Th9xyPltGRk0uH4edRdXc74koblJwoqIf9naXMZRZ71UZA4M2SRg8jFkr53O+5akxtxTk5Ol1E+gVYyOxb5gBU4Hbogj3bSg55MVXGXjtJIK5fx6LySRkoSoXwjGPPbMqgR7JLHtxo4Fdf2RkuFlwL5TMVsuK7szuFUdImMZc/S5bxd3jzKaJU0TOvWgvcuCFOq3wi+x08qeCyMLUAerwn8pmfEthPzJ3eJBXExeTJToqWHuvPn6RDxcuUtFwJPX/yUDoL0uKnPMZngEY+Hu/qXcUfXCejH70H3MxMhB1MG62hgfKZdPjzswmzH9VmMd8HSMxmBoSPDcIL9x0zKmsohz3awxf8/Gkgox5Ono9JbOdDMZtBwV5OedD/t0R2Q00nKnN37eLwXRmb4O9+ThNwmh/K+qd1hHNHOVVxAavIb3wjrX/Sv7KGsycsZKzP0XDliQz3IOYbx/o+HmEM5+UJJz7FBOHqtB/uC/ikBmj3+q53z0xnlq0mjlDVNRwIuKy2FJTwd7UL6IFc39IrRF4yl7rti4Y89dImFpPy32mIkRRYabf5wvU4H5exz5q6sqe1C7y/6CaBk5f1RDrqSLcPQ72eVRMnapgN3X52BjyLrnRzZPMcY4Z0+SK6sySdTPoPeThArMrIpScNn41GY/z7X9MxWxmsGzm1Rd5/qe/kWTxK4d0FH2pwfugioBrfbDzhhVuayzwKckavpKQlNlKVHoUiv5DYrGR7B1EJhjXVoHGjNezoIoM6tEC9sn3VXFQehuo3UZHaDr7oRN7mbpbdaQC/ewwsTGV+8y1VJtIFnkZg0dfdbQM55zdTTMV6GhDKI/Xx0XHOObgnPswEfS6OTmfjaS+3iZjlDhGD0lV4Pm2jNhMFvKe+b/nk0fmldGGrLtksoFbxTgvzEgdR1IL6SWNOoZj02IzSjB//Pe6p7hJBnNqS81b7i5mJXNvm7CHJ5AVa6gwqPtZBXSEHdaQVlxCuFcgrpOHL1RWUGufgV/9uRcXVXzupON8KQNFaigY98qC3pdiYT1ghunMI5PrYxWenOG4UWTiZAmd8wTAFs2euKGgbwsD68gxCS0NdCSjJVTX0duns9jLOc6INlDGFIfWUxT87Kqi7w0ZjbIUnHnSAjVGaCjiQR91ao2vN+Xcz8lZEgKxIFWDK7XmFH2sKK/fflI058aGPmMlnGUmrFJJxuoazP1rZHgyk6RxL3uM15GX+1ClEzPQHAWZGyUsucG8xLp6F5bQgPzRlt6dTi1JuGbgCBniS6COM63jMK2ZjP+o+a/JPU+bMWOfz7kHpuZ+NrFh/qK4dH6JsJtHDjtvoA+5U7Fjre0kdGDtbrJvI4INnKKuNe8r4fQ4HRdDm4lD4xWs78UstUPFQur/7vkaru82w7JFwrzUeaZHoQqSE1TUaxCProo7BiypJSKYwVaFSZgUJcMuXzWyqIZ2/xS0rcQeoca9PMY1rjBw3ZF9+ok9SgYZ6ijj0BENc3M+HzXEjHf5Vbzl2v2olaEfJ4vkdwqs1H3Prcxa9ODOZOdwex2dmA/2kJcjeP7d5Qz4MtfH3zVyn6/LXq1jSEUzqtvbMOCkXe7nl8ZyhnKeG90SGYP+zAf/knT4ZkrYE94CzpwZj6t3xD1yS8OyFuR3iceD3ubc+8OPjw/GjwwJofTOoFE2ODozM/4Jzf3ejsaRDqL6ZHpLL2aNTxJqjObMDaE+COa+ZB1PqDWiioJJzOmRLhpmsfa1kxaZXmU1FE8zFKRQw6KPO8PjMNfMPVn604pPVTV4UPfO9TXQZQt1KNPAbHr/OJsFo/5xb0brSFulwivnOed7cfBl7kkpYmBgwZbiFvOotb6OQvcuiIy0KBwiezhciYEHs+WxXkPh2YIM8c5Ab/Lc+y1Buc8gzvoQkfu53kPk52KHmAWY7Ro1Lisukc0GMQdmlDBQfndHtC02QfyLllHyuYqBIxghR5jx3qkJurannw63ofxOFTt3KORFDd1To/HyLfs/zUAdK/mBeXbuoivCu40G21wNY7qo2OzEXEr/t8s2YJdJFuym4Nc6Fb/JJpWYqWYepNc/tWAK2Tb5awvxrhk5hd4TGawgqZqCmC82FDxdSTw/Z8aoEjK+nfIR58kEJzapufcpxuRkgtM8D9fVfnuSaJHZFyNcWP9vKmLJS/GPpFz+d3sYA/tvvOYwHTWZZ4bSf5f5yhhfWIc7r6XceBuaD2kP5zJa7jO4kSlq7jO2U9lnv4qGwuuBgrMenA/miDYpqaZKLajV1J81T2TUnxeP/2JtWEw+CCpHr4ikr7N+R1rqmHyLmfsvay0M7OE+TQqPRHBleutgZoGdMnq+YR7I0WV6dX6y7m0y6uE9sShEr3BL6YnLJeljH2VYq1NfMmVE9bfiXkI07s6SkOXUB7VlBY+p2zMuygiiX2XmsWLjMxVXqhloyIzz8Ql9i/yXrAVgngdwiVmnFVnbjxkgqn8tsYk97Mn8lPOZhQqxCaJnsowZvirWFhiBCmSE7OWu4iGzyoq1BpLKUJMHUuMrxeGrPV/D3G8jGz5lBorjvmaW1WG9Th87paIouahqdzL7ERUxnIdq5OBuNW0oS+3P+d61SfSYMs3pk8y1Aw5Tcy9EIH2RhmnMfybyd4Et/Fn8YfE3eJ/YV7IWnhbXcz02J1Oe3CbDJ+e5qg7M3LdkvKYOlrEy/4oodDghYelAHR9Y/2ILOGPkwCVWBZ/JuXED62P5Fgt6dOkLVI1Gq8RopDP3+pF9z66Tc5+dWTWY+TbFQL48Mp6Vj8X+lIooFVYDv8cxozYxcr8foZUv81l3G1qRfWoyo61sUgn/MXfmfBfZ3HJ67vvBeYfrud9hVZN635yzNfW3nnudHT6pcGHvPXqvoPTSnvjQWsPOxzYc62FgVgkFt4qouNQr5z4etdTTQLsg8sgYMyo/JxfVYA3SdUwMoWc75Ucr6spdZs2ezG+FLut4/rYLTpSZJyrlkXI9dyr5KYo5I+d7L5aS0b6nUUPO23DyvIRO01TcYjbebopHxA3mPubLxtSLMnztXeYhz8c6Fpl6YugjssISHcfayaJrlp77nsUaq4564X1FE9bAUkvHgaE6vVHFu/Zy7jPU2yeUwTlm5la/FKStuy/uTsgrvBO5D/dlzGYemV01jzjhqmModfQds186tXbGMQm7yEKXfHJ6OEyolZln39hwm+xSJjAGtQvK6OKqIO6ZkvscwAxmKGc/HXNP1MNR8uugCSNwdCt9jH1QhT32k/V96DYMfd1l+JcNRCHnkQjrq6PYZA0+v/vhZM14TL5txZLtGuZlaTjM9XqT2aqXVhFNTcrL+TlIxp8wh/07N1x8mSHjV5SGtbE6Vq+XcWmjFRuWK0g4Xwv9HK3I+d6Yz5UNxI3h+e9HwhQUjUqXZLSXuL51Oh41IzctoF91oq/yuFdz2HVtN7z0IwduU1CKPhdSX8ZVrn/PWzIR/aTwOnLjbxWdO5A5hlLb4xRUVFnXVPrIKxnXC8j4t17H0+/0N/JfwkQFYWTJnM8ot52pYU8bNfdz1+XTRiIk47UoeoG6eMuGR2VnipasZZ+v7bCDOrb6MXt/sg6MUjCCTFvY6iTKcpYP3lHh+1GBU28F95mlVxyQkUAtSCKv5Xz/3d8Hv8XmiTKODxma+91yOd8F+OmWhMe8rpivNeDcVcdHD2al1vG577V1aKPgvcsIdHrOzC3lFTnfYziTa3N7KqG2lxf2JfaDK/XpTB8F09ir0Y2Zt68VEwtXGyidypxUgP8tpeKAWcIIZuoXtdphMbVjfGP6cF1yDTPjof8j6azjqtjaKKyCHdhdiIKCYrdnL7ETExuVUKTjxDTmtbu7E7uwuxPbz+7uFvNbM/5xf9zrlXNm9n7ftZ41sTdzpPlMiPneX+p/TZBzUCzCGkvI+1uCa0wi7q808CsqElnt/OzUbtbf+1CsqOj5VkVBsvzaEAe69HTi3JUUm19tBU94fBUu0e9WK2jl0LC/lI6q1JxOhXUU7SzjIhkyooX5Diz98ig54pSBfTkUpLplQhZqkLrdXBciGvXzkIeoLXvJI29ntEAN1tIXURZhzOCX6I+fy/6xmfeYJ1MTF/114NVoMmP3HGJTdgnzN7NW+NnmGoCbOaeT5vPvMZd0f2ZHN5N5qEPHmTNCaxso86SeCPYll3I8cvvoyBdg4K1jp9ha1sAf6u7s3SpWL6RXNGyNc1t4bEVfiozjtwknc9OcLxqGVFaQRiZrRo/qGBqHDvz3Fg4VgWROQX55KBRxjFz9nz//ney4eUcTBAzVceZEHNpRaxt3ICuzR1LJL5fINr3a6ciek3mnjUbvJoOSDYdRI38fk63rbHPdXwt3MmnfZk5sn8nab6XjQ3Mn+URDH/JwzvQ+uFk4GS+ak6scyShBdln4nJzG/n3E3H30oYbLrMUs38/bWjMH1eusYwy/54WejHqtNITb/9g8qUUbWLMpnKNoqb4IoqamUz960/uOMRebazht5OebNW6u13WGvH59KT+HfOvGHH/oQAzeFZTx/YxivX+yp4aKKmSw930U9LiaCOO8hFeLnTjP/jgT4EILZpIldgOr3g6w3o2+zgwa10YR0iAHyi1ibqFnhnx14T7H609rzlUIf7bJJUY30FDsi4qlZXRqMnmajP9EpedUZO8tYH5iPhr2TsGcmXYE7BgmRj23w6+8C8V5Dt4LyEnMaduZvaLrmO/U6rCH6ZjB3/M/1RFvZ3Os6CtDi8k4liEWeSfp8J+ShDHVmeNayUiLpkeR7dIXS8j2SrbuST4rmB9fUlzY11ZHAhkl9Cu5dJ2KewF29I02r527sIm+GOino+BrCaELq4r0mTo6ySo+9GX2aqaj3X0NbvclVGYPfyVLm/d3S9ArD4bVRTHzvZZ8CmJGOzDjq4SZg+lVnKMyJ8PRjXX+s2AJkS9AQ9UFVVD+l138IC/e4fxP6jtGvMiroytZ8RE1chvz2GPWa6dY9omh4OpWCRlZ+wmem8Rn5rjS/sxJZzmfY9NtXfJoSPvpFJeOyPjCzDU5LQqVWTdhL2X8d5f+0JKM90RHs0y1sW5HBXzpS771IzdeIyf91w/Hdznx8M8gZOX4mozg6q5isaIgqICCrxl065rwr0ADV66Qh2oaEPyOo2TnzczaXXl+FZmxnmVyYuht+sK9sri5l7r02BN1tRLWPfGJzO4Vx5FlOF+THhp4PlbDSnpU6FYFB1rY0eC5CzuG0If2Z8Aj1txm1tJrZu2yG2QYxdLE09oadjawW5y3ebEDKzZxTH7Rt89JGJJVQd7vsvWc7LXOS8VtHl84++3ThmpY1cCA+r8k+OR3ovGvL7a1sYlobkSi23gJj9nHl+lh5vXBHDNri7bVZPi/ImMyZ/UNUlCa+tNskgv+nck2ZJRbY3Wx7TQ5/xzP55kM5BmIg+OScGeUCnONrtCzzJfnVTQhL9jJ8Ht4DMNeV0evLhoyTfHDqUAdlQwdQRsa4B4z+BrqyS6Z2keG60OGMPNwppsaM0mqcKukIZj6m50a5G8+g5nBwM+bOprccGCKvzc+lI3BkGgNP7IoOEePd5Ixf5pr31IHW9wzUIPf2ee9hG+p5Arz3ZeQHsK8pmu++2Iw628jNyUsvSQORSwRe9mPBcjzZe85xcv8Ohq+oM6nkR2PdUGQu4KRVbLCN/SXzZ9zt9dNRlc/A3fIsuY7G9te6ogmW7TgcV8kv6aSyV+USUbIMAOdskRDIdPVbWOHuOREEM/v0lc7NqynR/1x4PxnDWMKSnjJ79cPsZabMRsP7oUrHzqKZm9caNqH7HSQHLMhlzDXNvvNc/nM/jPvEWcfoGDS5UQIHxXlqxmo983AxC7kgir5RP4VzIyZ2HMbS2EcmabBV2rcB2buNklwnpeRlaznoA+vzkaPvi1h5xQDleepKLFeh/IswboGVu+hgnWTdVQeoyNyoBMPbmXAafr6vIIqinf+95l66CrRjPW4PoOCDwtkdC85GLU1avOt47Zp25ix1iThsbeKFcz+jSboWEOG+kgG28McV+dBEgaVlPExfQBu09/Na0zV26nwOzReXGqpoD8z8nDqQL//yE8pzBtzYzDvADWiBHXpvAIb9WTGQB3hzDQdOZYevaORIVZBie6FxePHCZY/FklRrOciYv0cKJDIbETd6sy8M5nHm41j4EGfWHYkCb86Gij3gHn/pN26Ht+E/fytzRPhfkeBuR7eKWagveSTi78VtLnGY59FH9XI5bN0fK/Hzy/eE8U66oj6sN/myYz2M0i31io49zwaqZE6fOYPQvkdu8Sh0jI+HGOPcxxqk62fsw4H9dKxtXg75KR3ztipIv9EHSUPaDhO/V7zgD1yrwfyBzrRvigZJImM0465oH1G0Y5sPf4qNcJ8Xuabih+1Vfw+sdompWnwrfZYLHDfIV69JHOsT8TENRoCdlUUBZszb7aRrWsH4cc1rDPXvC3G4zt7WrS9mIy3SfSZg4p1LzZtvIJjJ1w4mV3HuS4ycrO/n7XQMYk88roq/aprOeSHiiSXht0/FbioFQcr3rLVPKUgu0vH2HEGGrQ0ULqVC0HUv188h9Xt6MUDyyJfJOdZC0ChbTJyMdsWJqenp2roYmatRZHoUNzAiZcDsZPc7LNTwt6MHKPYNBE+LAplOFfDWO97MqvW2h0rssroXZa60kxCsrlOcD4Nd25TY5jvA/5kFaFL6LmSglpkivEVJfjdzMW5MtB5qopGt3ncUyWMpk8MZT9csFGfqaeJ9J1+jxS0jGY2NN9Hc9nh4rmsf0XOzeiCfCkZq9LLYeAJGYHMB+1myGgjvRKbStKzqXHXyTgHZhvWe9DOpt0w14tZapKKYy3Ma+0qRv9Pw0l7Q/ScoKJNAx15mmrWc9rpmwqjRdO1tq/jd4n10dWFJ7mhSUfmO2r/rTcahi1X8akK664Cz+2NCrm7eb2V50pWHOnTC1mvK8i4WMf/vigYPELFqRwSujBfLVKCUZljXMhDR6PJwXhRgL76dosty3EV16j9X5kvbjHXr7lE7U4ZhKjW/HfOrRfHsPYcA8eZ/csvqo4J5Jc8iQZ0cvPV18yL4eGiQCUJ6z4ZyFDGD8qxRFRXNZxjDywj1+dmFiz/R8aV3gbOD5SQm/PUj9rYZI6EazMljAqWkH4rDOlFdJTh+VcqniZmPzcw8uZhIV5oiKZHXrsdjMAgFQMqD8SmCAUFp4Vj/L52mD1WtvJuaIqE7dSr2s34z8wCMNdU7sKa7e5Hhq9oINu5osjAvmnOjG/TEtCOWamjh4ZR7TaI7MxmwdSnqMsunLvtwInjnHuOE7am2/7UpWeQM+vQ7857DEKuLDqunioonuZScDo3dWicjMsdNWwPI5fFx8Ej8T9xOquO5cxCp5hvulzJKLqSLXY0V7CwqB2jqk4SGwaF4dh8F5ZyniaQOUtscWFJRwXV2zIr7FshzLXGZ+s6wkq9s/lskdFhn2rd7zjKccj8n4EdEbr1vttzctwJ6qxYJyGa9Rt2WkVKttzsu0Oi8TkDN4tE4E2IOwJzxiOOfl5vQVlUDfojzOu3FcI5Tsy8jf44caUkc2OWeHyuK+PFcx1dwjTEMP/4Lo2Guc5wNHX3y3lJBDTMLXKsIgOzt2f2KyOOl++AcwOPiK1dmO/XmesbKZhKlgibLKM+PTq0J4+1rrlmKOvdR4FxX8Vaz2SM6pBFNOtEPeG5+dGHGmysIC7WKQCtP1mCddu7t4RK9EIP9lSL8b64zVo112lxW0l2THIihl73OiPrj15ymlxvXi+r8/en6MxMfGVuEtpv0xHyJRLpGTRsJRtV9uA4L+2NPF+cKNMrCZfmk9k8VdGPn5HmkFCXnjqMGbWTY5v4AR3DLzL/XNVQ0DcZW45+sZl8GTBuhc3RW0PrA7L17E7EeNVaN+PPC+r9LhU1yQK2c90gbX8g1P46qnkr8HbXUOatgnrMfzI9JvSjjPxLokTJTAqk1Ty2iG6oRT00c/q2HCqydKsrbuTSsKN1b+v5wPSxQ0X8BAMOjt+9Gwo69+X8kkvLMRvnb/PAViukhMjiJSMv81cbakexvzo2kXPXnj8h1M5J6FSb80IezJ+gI7eXBllRrft3qbqMuvS2JqcHWmt8m8+jH9+oILKwhtLMJ7sK6PgBDVFlVUyPduHWAfperIrIgzKK1TsrJjyR0Z9clX+zCyE3BmHP1mwofy4EtyKobZenihTmpBxkZfNdPfO6ZJuxzBTUDs9DCgqTC1PnqDCoXwPWJuCGrw7jsAHznf4bi2V0XqzgSIzT0tf3e/Ja64isWFlOPIuV0CHcic6lZBR2GNY9uLNTnbi2QLX48leEhMFkl6Ax8ZixNhrBffOLZzOYZ9hXIRGGdf1gdqFkzCWXzWedP6f/9khSrfXc6lZ04SoUTPNKwvd3Eq5/q4wX9OjN98gw1MMWzNUnyDeLf+gQ5ru4tRLxzo05o1Y5sWOTEy9ZC2aNra6vYdwvcuxZF9oUl3A2RkOH/ynW2i9P27mQvZCGplsCEclaCCe7tMkjowWz7Ips7OvWBub8+CE2fc0m3H5GIHC+RtZR8ZQ69aDrQLF3I8dweAJW9Iiznrt8XU9GUPFkXGhMreZ5nvZVccJci5j5ItNsb7xo/O8ZbHu0eV46Ejv+tZV90BZ76RV/SxuI68yswmNdPV/HtFL8s+862vL/jVmUU8wi108ZLGFEEQMN7+hIfhuNA5zDEpWScekP65b5ZQCZek4xspe3Du+jzF7Uw437k+CihuXpp2JofwUd2Bezt7O3WhjI2ljBn54yyjBL/iVz5KEOP9ohY7a59o3TgNtJZomrMg7NYf8bCUgl7+0eZEeWxvTEXNR98re5Xm5X1uWweZ2w53kSeizl98Rp1jpak8mIs/yTETHinUibpiGSc1LEZ7L47O/CobcynjxSMa2aih70ohX0+3p21uMYCc2ZfSeQDWq4G8iXzh7oFoFNzPi3VisYJzmw3WgGhNpRvYaKMTMVVOgo41XNFlhGzi/bUMFmau6p/+YJc73SntRkkcJezLVOnPhDjaXODi+k4LGfaq0r/pe6GJczGReZQ1bsIXPxsy4K9kwQ+eazjP1tWljvPOwQEgpfVuF/TkXXOoXFr7sqch93oUFXDVWoS3/IINXCDfyvrYoLq3ieIfTz1nGIYUbsvERD0g4FD8ktKWMULCtfQTyZRB06wrxOTi6uheBbKcWaywDWY65PGjozwzWuLeF8aiCm1Uu06rDRTQdiyxiI2scaZg2dCEnGHh6vea9/Gf3a4xX5i976bIgL5nuLGaa5oFJDAtpesFW9GorrNw207amiOmtvf2VyWyb2Ty8FvS6qyEMNM+89bHhgWOs9RoRyfJaxRmt0w/wXzFCsIc8bGmYWMDCA878qUMKlfDLKtU9GGWbEC9ldKN3Ljjf5DXzy9ULx1RlEly3UYfaVuYeBh32seF1Twg7y8MZoX5FE7zbXGAlq9Mo2cbBirS8yd6ILV8g2ywvUE6upTdM536dcA5CDfb5vpwY/jkuHygZ8qFmfDkuooEiIuHFVmOvlqsyEy8fLcNAX02aZ+23o1n3NYnV0vD9O32VmrbJUwfs1LuzaXZGMYaBnGvM7x/kYz2fDgGTEZTHQMecAKHlri7PvdNR3ME+9c2JfOx03F6qYmsbMUkWxOC+NHGmuTdz7rx1xuQwEL9CQEqzhpUoG7eIumqWyN6lzhVMSsHFTFJ5VMpDI3uhBTenSWcdgskNacWbLhpr1HmSH+TzmkZ0wmLxblZp+nnlgT1Q/KPycwvRg81rtPLJJ/yAN3kXHiPbZD9vuf2edbjPQ67mEg0fo/6NVhAczJ44x1y7hmD/V0HAk/X19aXHhnoKVhobfkyQksL5HsudyU7+ekrU3B40SJ4INxHJ8bs4KRNkmCl5yfMxng3pSj1tr5jqSOh5HMqsWcRe3c6pYk8/AWWpojscaJi3ohivsl03+CnaQ2/r8UJCvfmZxmJkvrC7ri7zx3MeFMfSok+Z7HL3Icapqvet54a+GCmEqnjP7e21nBm3pwJd5CgrddCFiw3lbuxHNRakCkvVMg7l26XLmgPfUBNs5B1YMUK179zs2xYnuq7OJ7uyFEpPtmD+L3H/IZT2X+pd98Ib5bAW1KstC6gnn7Gqb9tYzPneZx/Y5qRWFmb2+OZD1ioK07BoaVU7GWWa/Y/1kXKiZiIcOb+RtryOlsYzjuoElV+ugdzUvsX3SZjGttxNNKyj43o19Qe7oFhplvSfttsWw3tGYGiahyRIJ4epR8eOsgeTNBsx7Aj0C+TvUx88zVHSIV6z3gQduY55pYKB9gIYtw5PgTd76Nb+qqD7VQN6xBtxDDWQv40IhT3KtruJ/+ZmFfkj0kySMT/QXe8lIS2pE48SfOJx5quIZa3bhYQ0j+hh4tlvBqgUKYhw63Jc60aCEgrvMwV04F5euqijww2Fxdtn/JHg9ixZlNiv4Ea5j1sH+mHVTxSPq2fPcCibuTcDQNuy38Wni/W8dfyok40aDD7as67Mia6qMA8xlVwa50I+6VoJMFlWG5/SRXjGIvHV0EO7W4/i+1ZH5SlZxKuczW/mYl6JAMwXdLhtY/UHGY/ZuZurZSb9/z2RAIxNTUxoOqYHf1Otvf7JhelUDxcepiK0dYqteykDMrSR0LRcG8dqJldccuDxyh9h4OBEjCjnQhJ+rf5PR69dmsYm8/Tc9A2JGkInznhUj6U1VyMe3QmTEk41Vb45FKlnnqwNVoxTcc1bFmVgXJoQw/zCfmmvHPBmhoVsifZbMaa5NdvWnjlrUP4fkQkt6Q2vmjg7kZVsT1gM90DejivXMwnkSFDz6RoYPl3HnpYoM7IvQKF9MbK3iwAeeb5yOKksMfCwVg4SCMvpQiwZQ0yvdlBHr6bDe7+/6w4Wavi6kJHvjPmvLfLaq8btQDCbPdN4eidyze6HyRLu1PlG+iQoGntdwmUxf8iFrn/z7gl5eo2YImnRSMOeEYu2VMT9dt95xnHkoVPjdUlBf9IBtcBgWfasgbrAn37/VULO6ipiJEhos15D9uYpcPjI/k5zxnsdExjDIopey2RFIvu662MDE0xUxmWPhJO9cohdfq1wRftThQSXtKDKBPDuemic07PzLeXim4fsRJ2r0V1FxgIRyX5hL2Yf9XzBLHSN/S6yf6Q0wqxxrmbxSlTzrU9IXebdXRscPDmufoy+5xwjtVUHcLFgRHYcZ2HRKR8HtidjK/FO9oY6TzJ/x0cyzFU+Koa01+Owk6/L4E0L/PbN8ermOO+SvQqV01KWeTTjogtQ+CSM5Z+Y6Lt2ZZe++fyPMNQ4HZKVXMEO1ZQ/nuWKgxtZwaCN1BDIjH7+mYMNiFQVlsumwZMxI0lAtt4w6T+iB9N1eXRKQ/FFCrs3M2sN1y4/bX3Ahjd+XQNbJz+y4YE4T9CMPV/xPQ+U2MobRP92TDSQE6RiSqCKgABm50VOhzTLQevVAaLNlqMOpvZ0iMfh+YzgLO/A/5oUkaoGZLYb30PEwmPO3szq+UmeXMMddC+4jltH/ey1UrGe1X1DrSt7VkaEk2XqgZr0bF+ulYtgdA5m8k5HxrGo9Qxrakmyy/d89uAD2h9TJQDM/O86GuDD5s2Zd7zfXAmyZ1YlbTg2dUlzYvMBdRLkn42e/MKSUVrFplb84uOSLrRXz17APOhbWIou/L4uvdVXY/nOhYHVyUYKGkvl163r1YKHgFXmnNnV/4ToVD1NbogjzyZW6ZDotClW+OzDzsguvHlBf9nPsiySjzyXWJ7Vih3csQg3O++Ai1nOgntTX2310JClk0iQJbQfKqDdHstZiaXkjzRZxiXOUquF+rSjRigzU8JBmrck3hL6a6QN7O3KSuP9Ds97JrruedRClY94nGXtrTRZTTtI7yOHFRiXC7RX5m/lnD7VkBzOMuVZhvkkyWu8jk7/qhsH+1LQprPuFviKAeb+CYeBxaxmR9PDUyzoO8zwvknVuDCcD/WyEUv4aApmHNwxU8ICsHTbYBwOpGw+pkQOYP0vuqo85g22izGsVP7YpcGc9avRWN46jiz1pPhtRcqqMxFX3RQNy9aXr7ZD+lTqrs+/XO3HVl+ObXUb54fvF4TQdt3bqCK5nWO+EfmUm60n9SJysoHwFFbeox9cqObH8ei+Ya2n0YC6Z1kvG8Asabi4rKkbSd3yYr8Oa0gsuyxiyLheObnaIwAQV6WTT481YQzerYeAaGbUb068eSPg746wtK8emZdEk1ll1DCNjPiphIIS/E7FIxboxKkaw/gpk1XG1r4yh1+kf1xriWMN/70QdM8iyHWPEOhu9aK6Mw2V0bDwQJfZsTEDxCGoE+dDB/qnATLtjsAMn3lZFpX0yxrh0dA6ipnSsJlJY/2O+aLjF2tHpb205NsrtcbZsq8jUrVSAv79pqIp55OXK3irqvZHxlbm+YDMJk0ax//idPckYxag5eZWjohaZ6fwGzVpv+fO+aPRlrtvVzMDB+3bcYw+PHqAjlGPRn+f032kD10apGL2pK76T/bTuOvp3Tsbx0YPJdjoutKA3uVxQajvRODKTeJGrrCib+77tt6eOjqvmigvs6xbzZLSn7o8erGPfJwlKexUd41VceqUh4KELd9dp8MinWvt7mNcjn9/SUG8FPX2tgVY2BR7vOdbTNQwNGshMy/ytaNYaCOb6L5d/S4i9oCLq1AAk2hOw3SmjGj//0HEF4Y2jcIvHXCvegaHd7Xi9hufTREKLYmSHOxqiMyhAGwP7pyn4nIs9T13/S57pt7QnltJP6/dKxI42Tgxlv737raA2PWhRbBLs+xVsI8v3fOLCGifzyl8JH8hxM8KYo1qq+EJv9CPDfntSAydnKKgT6SaaF2NeYx7rWlhDqhaOt8y+h+ijm5krD4xxosAixZrbh+ydts9caEb29KiYjO/Mpd/aZBM5+rvQP6+E7uUNjLwh41S4huLtHfidnTklt4bYDDJG94qGoF4uprZ7GGdt/8X7YBM9ZHOiE15xTiRyzM1rum70go3HPtumz9SxqGxJUXubhhxXqJ1xI0Wr+wqc1XsJ833zkPesOY63ub5D25oanua7Yytentl5HFl8GjNkThf2HOc8Ud+0IzpyvXslEpnTfc+q1rWIoXuplRMnioxDVBQNUHBlN3XJUDHqbV2sTKcP8bMXlmEuoUab123FWBVnetHHPrLfqREbistIpke7nVKwuGQQ9le9JHbc4WfVUREYJ2PkAhk5eX7d3Tzg5+bCmb8cg1+qlQkP0wtyNuYcscb21mQNkydzdWUuaKfCt148qmxifzZgXT3qKczeyhEsW+8XRN6iNuZSoaVnFqcGFhbDx84V5dduE+a7ZfHsteoTdETST/0KavhEL0rZoKLSPSe+kWea9VdQb5G574CCdl5bRPmSZOFqLvhSl8Z7ShiZj5xLH8oV2F08LiNjy24JP46zF5gtHpwhe5d3WWsF/WSdlQ7vab27c3SDjs+fk9GVvDmC/PSZXpSJrFNxnYy4yQY2jN5gK83zdJGZjhQiKzC/NU10ocBlBW+3JOH3UwVvQtlP0/tj5Mn7olAWQ8RdisKL9sxRo5Nw8ouM3R1U6CWni2prRomjzXRkKqHCnz5v7mlScVcM5rRnRlpnWM+ctQvTcLu6gnf3BiH4PevqETX7Pf2wFv2GmW+Lp4HnY+i/43Vk3z7Aet9z3Y5kPCa/PrnNMbPzv7+SG3sbOJeBPce/az53O/kodaW9jE73DbwnU2f4nxP9qe3m/bXnzN2lqbltCtBbVzixnnPcrCzZgHllbWwjMZuau6EVtb5fAryolUMuk1u/sRcz6Wi22C4+k4vG+ybAzdw3jt6+lVw5cb8Ti75LsG15b/ser+OokHBhFseK49ukgwvezIRn90nYxRxmamw5LRfeUiNrLdaQGMAcseSHLakua4EaPLetgg657AgpctvWpngMSuXgn8+m18Q7rWsDG6h/zSbLaJTghyJemcXkXBquMJOZaxg+KKqiab8uqN1ewqiFuZFxtYSlgdTevOT94CQcTtVx7i59layZJy+z1v806/7mAvZ/rsHM/b05X8wwI+ivrnQ7itHHsjErT7ks8c8kXLpHbsyoY7KXjspkiAzsi9S/8fhJzfU/nIT4wQqONWqKPjyn9/OirPtd/l9jUIF1mJ51EF7PkXHjgIZjlbtj5Q1+5h4v7HvCuZhOTS9NDXjoL0ZeV5H9rRPDZzmt/VA77zSwbhNzXZyCMeeyixffEjGjtAu1j0VjcJtBOLFUxdbvOrakOPHUr6AouYtjU1bBwkH5hCf7/hh9Lv9jB3bRd1yz2cfdvosyzw1MK0GNdSo4XkBBtkqqtabz2746PnFOr3lT28my6qwuYl47Da+CVIzh3EWTC1KfNUUYmc+8jlCtJzmorY40ZvOq1KjlbVXcWatYa7NF3lDRpxK9kTmvXJSKMP5ZW3pDlZq6dQ13WDmye8YKok3vsrgzVMJyjsdxNxV18srWPpSDzGeF6QXdr9mx/AM9JaeMHWTp0eQZh7tmvQe8ldo9ZxBzIGsGa/n/ZhUVmeglS9VBSAin7lQagMW6gmf8/mUP2wupdKT1vEhL6p4H+2LP9v22lykavPskoXtEHnEjQMb7vhdsDb0N1I4ph8KjNGS+usuWhfVwIjYY2lsVRb63RIeN1G9mpuvM2x/TqZE3FNxYckrc+jYI+y4qWJctyXrHN62mAvsZDXumc7zJo5noJZOHO3B6vwu7FgyEp7M0ql1nJj3FzHnNhY82FZ2XrxGVxnQSVSKcCKB+JjNHhZaXUfY2e320honnZHguV+DLz7t1sjE+e4bAjznjL9ksvrCO9dPpF3VdOHohFpGny6JIlMvSgzn/MdNu5+cUISeMvSOGcAzeHJOttcQCyEdF56sYyf5Iqp+AE0fIGUf+rdF9yV/B18oKPtZXrDVAZx11oe0DBZNetsW8nbPERM7TYzJC25EGci1RYK6fGl4mIy6216191PZUlrGKvR7WXUbQcQn1M+bEyUHksXcubHgehxiOZb55921FuuroVCcJS8aba3sa1t6qW266sI76/5Z52kMn85fyE7mfu7DJvK9CXag7sYEQdQx8I5tX28rs1tQFTMwsHr3juBfSsI8sq+Z1YPFq5ixyaip19PlqDUd6MRsWTMCsSgZCG6nW9e8d9NqFdWUkfFNxnzxdsbfCLJssXj7W0TqbCm96R9bLsUhlLc6Yo2M2s+LhN05EVfdDEvWjVs664hB7ZNQ8DXeZJWcei8LW+ECxeqJqvTsbncgMtkfCvgpknrsKxpIzGtXS8Ka/bD0vHp4lUOgXNWRtrcPcZ9CzhQHn+9ziik88qnEMzjxTcaqdjIFx//Z6O1rGQLb9BpaRKx/YU2xmbv5d33w2g30VqeApuaI56ye61zqbuR9B9rk6ms/wEhfoQ+Z+EI9/MKdf1FGLbJVy3w89Oc9/CpcQ8eQUc/+PEV0ywHyv64hPVcw9zN5uZ+Am/e8dvbkWv/9AiVyo4ZDw5BrPY6uCAc0NTAqQ0DCGeTvzNGG+D72+pYwmXciO5jpLzB2PX+UWu05XFQ9fc845BxHDFLCrMOGvyUb07wO1kf/ZHlvjAJ3nYVjvsefzktHgixPryEzXfioI/aLDy7yWwNy0g0wbXTgaqceDsI3595ikYN92FYXWUPdy0O/Ym2mv2+PG/bfidm4DWxfJKMZ6CaJvziU/N9zbC2cm7bWtpYctnUHGqpQMu8Tv7F4bEw8moEkrBdW7qEg+pmLnKub0qsxZT6kRU5iDziRh6BnqSGdqf4SCkcy45ntYC9dVxb49Gjzp0V0indg708DVV8Gic3cN2faGYGwXF24sGC4Wsk5msSfNvbvN+yCRL9krXxRrr77WhfpgwRZqDHPF8IIGXKEqatILKz5OQkfO7ZcEHfHk61bUlhMlZEyfoOJlZzIIs+vmaAnNXj2zme+UmOvdTp3E+WnZF+NraPjAzHT9ioxWi8n7DYEKfWSUKsLP4rHNLi0hiJkrgTm2ZzQ95Q39b9hFcUbIyG5nzkqJhe8KF35ec+IPM7l3UR3p0Ym4108hF+jwyWuHH70jMzP8CeaBNzzm828M3HqksF40ZGjCrNxYw8WhCsa/zivKdlLRlZwWxzkqapeQVGa9iL+nYA/P4dNiBW4vyHBvO2BcLQVL32jW3hjbmOH2xocjZp4O228D5d/kEQXGyLhHTfBeTz8eH4XtUxXU53wF0nMb/09Bn6U8ltsKGrfkdxWIwIlcE21q3XRh79YD19ckIJXMdYw1PXqRE+/rafBiZr8XE4mz1ETNx0AVZooMs7eK+TPJDdNbiLQBSRidMRnu28jD5Y/aGlQx0JC1XWCrbr0zNneUjrZlvTDaj/NNPfJjRvfMRMalb614oKJUHR1nNkUgqSnzdlMnprdTcJm5dmphByYwrw/J/++94iY2pzDfazm0jNq7voToxLrdezkULVqTVXKq1votB7cbaPTdXGOcevpNQviYc6LMFU+RZ1yS9f7Uj11xuDm8oFhxUUbD/1HneZ7zFmq439KJE9TmL2TQ2s+phYOroD9r9i77clx2DSN/aniXYqCQ3EjkPUcvYOY/Qd1oUJucuckOn+kuzKeWej6WrWfMq/eJRwFNsp4rNPf1eMyclVbKiVOs/WLdFXxvXxHbyYL5yb5R1NavGRMw5Km5l5yK2RN1BFODzXd/txVXcMlk0+EGgsmdXZoYmE0mm7JDRdmR7G1y+c5cirVOhteHeGTjsY6iN+w+bz47pllzfppM3auHgRoL6HmTZHTMKqFfGD2zhsu612yuG1LG3B961ByRQvYPLWDgBP2s5AgVk3tmgy//rrmXjpTbhfI8ZnO96wdkiz3zU8TgiFa4Saa+vTkMv5mbfzZoIoSnirVk/vNktOwt+yO2nB0Ffino0lpBwqsx4pFfZlFcdsHzoI78z1Vs/EwfsUfBXAfU3lzHG6/tokHe4mIBudzcA/3QXRXtmXOLbG4o9lPDrnZUMDRqoXg42onc9Oj3p2IwoaunCKjIOmAvmetHNdtdBEG7ybMJCgrnWiLUGsn4tiyTmMG5MfdZbkt+Pt6EvhrC/NaTn5EzFq8zu8Ev4d/eJxuYFX1baqjyTsX1/6ir6IgzSzQ4Oe51onQs33VNbO9l4OFgGZ8PStg4ykCCFCP+Y168OFDCPGaQq/mSUZq56gT1Zck6FSvJVc/ZIw+96Nc/JewpGIdSzKD9mOmXdt0vGuYrLdZMZa/lMHBq0r99op53kTGO/Vc5rIR4t16BB2t7lG+ytdZ6jVZRiIiR4B+i47qsw5csphflvO1m38SSARonoXddBa+yMAe9a4HpV1NF+BwF/b/b8YB8so69PTJcQdF4BYXKqLi4VSZzahgYQvYeEo08hwyU+kzudNet+59XyLrT77kwjRxxYshC2w6O2/SeCpI+OxC2jZzUhh57vK0IYrbf30W3ngHaV5JseT8RK9jjrzhu3ehtGxvrWOtZCiHMWZODdYgvPqJdMWasur1F6pYhwmSF0c1dcCoqcjympqgayuzVcaqWHZ326dY7v+a+4Y87kW8d1O33/N6BCXhY0okB7snWvuNVz/dGrrU85ut2lD+moGEbA2/IKUtfcT75z48VOfH0go4Zcm/MI5e17KYhaUJzi9FeTtPxmN9tXlP+uYT5oCn/4feO4mf/yKygwQYJg/0k67jMfb3a7ErA5XY6Fs/S0bGbjMnkdf8gA5WYa45uJb+S7/vfTEJsfSdCW+qIia4uzHfEll/RcJB+upuZ/X/kif2f2OsHnfh4Y40oxCy+7L6Kj7GZRIbuKuR9Lmxkprs8X0NwoIzDv7zxzENGF89BIscpam21f3sW3+Ac9qQ3VTobi5dGXmu9h1VNY3CZua7Plkwil6ZCZU0XGkDGCUiC3DUcp5ir35Ols3dSMPe4Yq3PtyhSw1r2TguHht/LNGy/rKPMLQVb0l+LvCl2JPI7j+RV0KSahofLnJhEffBvouARPSxgqo4qMrXzrowz/WPwXmiIeath5fO2yFHQYa3HdVVm3yQ4cJJau6KqHTfohQOYjbplTEKnjMzIzCKVPAz0eF8Pgbt1lP2iokfcI1v7mv+upYyJiRQz+Hc6BLHfuhuY3/CLGFo8k7WnyrvxLjwdIVlrvPQjFwXbdGtdn1fkRVdBzbrH9DuuA64Ee+Irc9rX9XnhO8mwrj0MMsgWrDlzP6M3LmYzX3oNx7bEcRkj6Jfx5JPVSmv8b4ATiYVklL9Hlj2lIH6lgSH0Yjf+Xin+js7c926AjGWlzorHk13WsynK4nhkyLjIZu43XZ/seIyMXJVZe3APjjF96Fu8CxnHk8U4P5mDyA3mehge5G7y1v4jHfGWGfNSGScaTVLwkIyg5VExinOgcixDeyYwZ6no35dz+6wjau+tisr7FCjM442WGwg8ruLFE+bbQANpLSW8Ji9M6+nEaf5ZLPXVXIfn2hXdWrP37xsZ81+ba42ryEVvPNyK/f8mBMXzqphKz59YylxvWMOAR/T58hy3bRK2kj3vDpVRmZ7rwRwdEGfgTEMnHOR5t1HUo8PkwE0SZrC2trRYI96eZ60nuqzrGotkd2G+tzrmnoxyp7sA9RsJ8338eR2d2HcyCa7tDvy3QcVXjuGpQBULeD6rZ//z6QqFnOjN/kreoKDbFA1PqG/5zXdfOe9rn7ow5Ch5gvVoG6LAu1R+Yd6fqtjvkrh0wYWJrKW3yQrqllexZKOEr8yMVei9S4LicSWuEpKvOjF6i4rQvtSuegrOpb2wPQlQUSJdw7Kur0Sp3MkoQv3dwJ4ptUdBezJaNHv++5JkNOfx2Eu6Yxc99EiiHfFk28asu6LVyVFzQhFwPAHrs2nYwB5P47jOcjsnzLWjy2cm9zEzXXy0zhbW9B93feL3+ZLf/9aS8YC18EnX6Hka/jY8YRswQkP6cA2f6KHdW84V1Xb1wfsd1MYdA8WVmzLycpzd8+u4WTQBTxemiEYZNGwjy64sp0Odm1WY679++qxgsNwV7mGqtffAi3QF9Q6OEpV4zL1rqGjdRMIZ1sNjXzIFP/sj/zH36RovK4j8oSA1t4ILrxXIHsn4NUmx1tLrbq8pukbquNpPR71HsvW8Y13vShjf79++ZnMzyoh115AyLx7zqJv5vUrAj55UYZEON+rAsKfNkCncXBtUQlP648WGOlYz/y5gX5m18GFtEgZn5bmwnszn8h+EKIhYzbxeg+fMzDWC59mGbDmA2uDIkowEnkft/6noSM7vymy12HxeiN+7rSN5JswuqpPDRr1S0O9DMVwcRg48H4P+8wPxOr+Ci6/oZyEGalJ/a/lnF7d2KdjkrVprJm1jHpu+VrLuK//0vWrbcJR84kWP5bkP/lpBxA+x4wyZpDFZffrN47Yf8Tngt0VHadbjfjJe5gl9kZteUI/evsXbia/MpeZ615UOqHAPdlr3RuIuk30GkyGpT9JuF4ZnUXFpmIFrrP8iZJUh16k15wzsvqDAk3k0paqBZ2SHKWTOfMyeB09H4w6P4b9I5i5Pfm/HWFsrzucyryniF/24cOt0kXMv2ZYZ1r85e2G6hulZDdyoS619VQUOxxzx3lPDsBX8jOk66uRMttaK2XpSRQ3+nNSRXs98WsVZXwzMoKMCM/Jp6tKVdh9ERAXJuv/8OdWBSgtkjGUeb0lW3ES/eco5WUymfDiH+ZiMNLI2+barjnKPcou87Jtjx6gJm2Xk+aNja2/W+DgJo/apKNa+hShfhPV2VrXelR6xQkVVnvviUS50va9YfycpXwJKjndgUj0DIe+Yq/v6o6S5TyJ9fc1IF1YtiUD9bPnQrHdlHI6OxDdm9v1ZZGzvxuzB3PjwYgIS+tCPHgND1svwSZXgedoP809JmMux6dSKfDtSRfRhCa7JTtxgj05rWRMXfWsLRxsdeT4quE7+7NU6GW3iiuPzXAWJzF71mef6/1GwaqjL2uMwcZaCDOQX5wwXKv6IxPuWcegbqKOx5yDrvc61BRJwN1VFlef90W2CghXmnnBldLiYO8ptSiR7lEPRNxLaRjUSu1gP5h4uVTbTF35ts6nMLO/Hy3AW55iRwyt6MPvZFcRV1hHWLh4jYnV6hAob9e/0IwnjOJ/dJQW3yhg4yHw5sxPzN/WhPnNN4uKOmFEmGhfp00eiNdwrqaM4eTCA/3/J7sW22K0uhFBrrtUYgCHeBjJwDLbQN/OY66DGqXh7jf99S8eiXgqy3tdQ9Bp/1lZwhnqTkUwz8392xPSTkZiJHtpNR2p+O26m6vhGba8iUfepLyHUvJ2snyB6ypUCDlxdUxA1itFDQ6gJlQzk4c9i4QY+0Hf/1y8R+nkHgjX6PRl3/HYJC3P+24umkK+K3vTbyNHknFkaShdR4Vkhr5g9ScWbhHhr7YXgGxJ21DLwnhp1qpACg9npTz4Dmbq7sL61F54vJTNFGZg62cCKJSqa8vwKB/2wmetk556aDB/PKGxm7R3+XUzELqf3liCzLIsRB2epmHArARt6aZjaQsXvgqzHQ5q1t+apAnZ0XsrPSw6HKG5Y+4158fzMvQqS5pjXDTU0fK3iypbK2HJGxlOHgfvUlQZb3cSPt4lYV54+6OLvLFIw0EmtijEwj37UcNdXkZSNbLBXhf2sHVvTDgpzf4xFN53w43g2C1RwiP3kW0aCPt9feNysj9HUsN/s/yRqbjRrqD39XKX+VOhs4I+bgsnJOva+0zGEufRhPjvKbNes/W3cCktoxh4EtbZXazIdayDIR0M56Hgx1sC4HBomZzeQQk9RDw8R5hqTeavznJLIGJUl6zq+IJ/s4LzdO8t8x0w/Y41i3X8u/tSBqt84F2913C5BHo2/Lm4v1eH+v29iIL0nH7NgOXrp4ALJ6FZLt+6b1E9wIi6FPOfmQNsi7A8fyVpbV/uqYTVzz+B3/9ZFmXNUwzlmgBLU3W/n7VAHGZh1mjqwzIWVT3XM2kXdS8sgfvlp1p475h7KHtPMZzqe2L6d09B3m4ygvyoaRhsozXN8EMScUaetMNcHfKIw41yJx6kVZLrm/54zq5UcLhbQOxu/ZA1R5wJqaCjIetjHOvt5R0dr5vfW2XSc60QeJIu/IqvsKUWf5byVpj6v8tIhUzdimfcKu+kIrlMKE8+3s97BLzhPwk6y6813Cu6kBiA/PUK6KCNuYS6RbZoT8lMJhRcl4qnqQt8lMRhZJcHam+JvdzLfLNni5NQd5rMMMo7Ra3+O97OZ92/njYjAj+YygrvrmHJDx4S+d2xrNlwQ38hNRfuSFRokYRlz3nP26oVhE4R/MwUrmWVdLyXMypqAitUNrGHGL0a+/UF/KFVct/ZUm5uqoUMBctLJRDxgDhr28Ls4v8eBB/4a/peXGsL6bJndjojPnDuTfcljIic9YY2GOwdGCnO9gkW7a4tdH3V0/huHOuV6YXB4D9jHaShJJgwiX/+llnZjb77sr8OxRoL3EQWdyb19Cp8Rp5btss2trlnPUNUepeM485j5XrK1v+g5HaHUx/q9DXRhHd67QyaP6oz9zOTvyL/muzb1TQ9uo0EEeiA1q4rRtdOFHtUP5fx8cHY2M8xoGbtkcqMi4fpLFd2YQ508tkMOF74wL7We98PmYE4ut0rHLWb4XmsVHD68Wjzdk4SOjVyokJiAZxHUsI+ZUfdPXtg53hXZ92Y2euumWvsjDsnB8SEzX8pEthtJrmKOyN+AuS17VdGonYLvzVRMO6DDOYC8I2lYF3vF1mHbVlvH3Kz30Tpmk22+NGPPPJ4g+tf3R2dqcKat9FjmscyrFongfRLqqTp2PpAweYJu3bvS2vxjwRPMdrv2yAiMXiQ+39LwsrSBnHX/eTfqGhjAz92y0NQ7sgYzqrle6vmeOgqSKbQPDms/u5BtzF6shTmTIhBUvpjIecMF9yw6ag5W8JJsm6uQhCUZE609Nr7MYF6hX2Wl95YrJiGE+f6lvwN35iv4fGWvrd9kejl7PylHMm68qCeqruffbyFZ68w/6GbH7PcabheV8WKTYu0bEj9RwVAvT6zskNl6l2sofXYidfYvGepuHgn3yqmYd4r/Tf7x2KRi+F0PuHEOvdNkdKcn1VwnY3QA+y05Gesz9EV4nghU5RhPSnPgSc4iuOjUkZGZ6MtP5klDtp4NmMt++xZqoNUgas5y3Vr78speMllpGStaN8WKn2dtbt8LiK0e1TDfweMpHCMKurmQwnOrE+ErGvZ7I7KHudCCXISSEWiaU4Y7+9o/12/bMWpOec5do80xiD1Bb0qScfa/7PhvoIGq4YnYx5o1alFT/ashYZ2BpszWk1kfZ032GxiGvp46PlNXlfucO553Tc7N/Rc6uiSRjar0QOhjCTcW5MbD9joejZZQk71rvl87gJw6btAgHCnNrBtRGLvpJ8mjVeS/mISoPgbi6qgYxJ+nyc7BsYr1TvtnHkurpuzR6uQi8kR6DQVrFqpY9lizfKd2WQNbJ+nWtcsvR1VM6aZi7bQkiIISqjOnd63ijqyZNcyvZlj7Sh2lj6TfiMSJ3040P55b+Devic3krOpV9tkaJOrw+CChU2EPYV/1b9/Wmb4a/LpEIfSZhOiCOp59C0cFMnZh5pQDSf/2lbJf0GAjJ3cqq1r75G1jry74ngGDmVfLMoMPOrXaNqYaP6cP67mnjJlP+D2J3fDKvw0eMGMsJ8uWuhGMnMHUPvcZwruUAffPKm4yL7c/J+HFHpe15mD9vaXFbXLXsrnx6OinwLHz3/2eqM8GpJUGlvcOEY38ddx9pGMl+XGm0DCa+cq9DfuJnjmMNfgglOx+yMA9em3jVRqeFV8mYlhjPYIN1FOSkeZuWOv91KF3Gd1kzM7vwpgeOkbupu7Ec/55XE+ZhTr4BGD4RH9spjelZNJRv7KMax1UzOF51hyuYjuzecxdzXqvNLR+RpG7ioSnEsd/NzOIrmPPmsviVqdGyFUnGJHUvTfMapd9e4jH+1lPXjKuFOkO6Tt94oSC+ZyDYfSUjtXM9wSWi0WnDwhfavaH4v+eGzavTb0It8NcP/N8WXrGYQV3yW13FpB1dXp7ddm6J56T3LuIOSTwjY54ZiA50onns+3CO5Dewt5Ys1HF1PoaNtZORnBnHfYXinVv5zr1/jl1ZVMYmZr91Y25YiK1p+kKCd8matgb0BPTYw0s2nXGFs56ve2WDL/Af/vtTSUP1CSjNvbW0JwZopOHDt3NjlDWdnowfW6SP+5T/44kkHle8rwnGsh8Owrhdgl3ptPLDGaAExIezXHhYLSOJrfIhKf/rSXf8cgtYa6TfHWBCr2uA1nIPhPdFcRX1LB+xAfbUHJhZWb37W4asnKOe1HLCtzRrD3Zh2e2w2u1hnc87l1kvG0tdQytUxL93LMiyVNFsk1Bg30yeoz1RlQR3XrG7w1z77vRBlblLIzRzeMwvUYkDjc08GuChloPdfQd9Mo21sdLLPRjfZ/vj7DMyQjNqFo8cqehuWdBHqhF6ctL8yPkDpk9WUX4Rhkt+qioe8HA93QZrZl9b9+ReH4y1n40EEYODvlDnr+m4rU7+fW2jI5d/93HmcuaMfc9MfftWJHuQAb62/5M9NIFzYV/sIST/TV8ztoK3Yvy+/ldeVi//1urYgdr4s1nGdVqsr4L8Zwm/FsD8gDrZy5r+RdZemPEK5G4ScP5OXZ4R2ioe4l1a2PGm9VZTKH23IuQ0K2HavWNjWO14KCBvvT5rcu/2cz9db6kOJCvkIqhWW+LbxUlVEomwyWR3645kb5Twe5F/LuvVFwgixdhzZvfqW7TLUauTA9ZyFpfXM6AaBKAOxyPnplVtBjtIdzoO8OLuvDuno47hzaJGH6HyRBpgmP4S8Vjfod53/BeDhUp1ENFrSnMNQ6W3aqIAv0kfE1tiVj6ai+yzpmHGlLJE581AyfvOVCmnBMlOX7ehem9LRT8idGQHTJS7/RCwAAvtP2qwuOnjAzLFQTwfGbepf7UyCj8OD/TzP0DflDLNprPgsr0OQ3HxRsxdC658DL1KEcYvMip5rWn3Jzzh4tVRFD7bpGrb9wZYpvFDHvuuASP2hqe+Mjo2tmB2DDWjg/HcLNkrTHeivob+1qDs5+G4Z8MDPFwITs5L0usisVe1KdXHL8YhXmVPEA+0be7EDuW3tpVw+ARJtur+JjFhd3UzQ/3VHQ2nwmtRz5mHV1grZ9nxjLz3eRKirWHSvwJ3dpbOLV1JHZLwbZMNVz442tH7CIZJ8n0V7q60H6QjOvDJMzZqSNfoox+PN8FBjNn/s4YRa0PqeDAyf0KpCgdXjHMcsxIzRzmehePxL6nMpqSf3MkS6jSWkKxN048zaUjW2MFrZgH29V0oV0xGXemVhGexw30qh+KQWvbWGuGn73JMUkKB7JUQwyZeU+5GjDGxkAqYsCTvHV5hYah5I5P1Af3suyZvk7UP2mHz0oFfuQdP/Z+wFvJ2kvXfHZuJH3M3MdkyE4NDfJJ+FNXt/ZEKlqDWneAGlzHhU5/6WHrDcxOzmW9G1iHc3gz5zHbD/Z402oyypv71d/rKl6uChCpzLHmM0Y/whTMJieh8XDhviMZg76plv9VLkaO3sIap84Oo6Z9JvuUD/93LWvfpn/PCq0fwyy/S0H+wgYOkafcyA0Ze5UlW7MGMklo0Zj6ye/OeZ1aHU198GBWXJeI1rPikC2IHkBWq9JEhlr8hm1um1IYRk2uNFTHUmZVjfmwdhcnklmzl1bLeNmO58tsYq4zmMrejp8Tj4cFNOveWIYcidaeG0XHs9bGMhOc3ylWFlOt9eLWca4HMG+bz3M3v6SRQ11oov179rYMdcWHGTighIFqc8eJUvTu1jn6iRWbYqAM9hcrDQlhfxRrTfpxt2RrTbyrLubu18xfZLEuT1zWPfOy1FffAQaiZsag00QVX0s7YdTPhEHMKl+vuax7lO87GrjGGl7CGl8ePRCnhyrQynB+7sSi3T5y0BEVsaytDc0GIbnCAHjR29ZRW0ee0bCCfJXjo4Tn7ezWvrEF0rxQd6vDeqYhYZaC8DDyfzsNmdh/MwOm2vJRo2qkc7wKqugX0Nk6r+LMcj0v6njpbkdLDwPb1zDXb1Gw6LKB7BNlHO5poHtvBYeWtULAKQMPpjown5k/5beOx+xN873t3+zHueMUPKEPfuS8Bjd1MNvL6CPcrLWRz7akdsyhDm934l7FUOzaGWK9r/KjawR2PorCROaNVfRSM0f+nqGhO+ux83lyvDu9pEhmTCxBZnpWFJepnzNZb96/mFVbUSduqLCVTEat91EYkqLh9yFzzxcD873J98wiZ700mNcTFfbU5l0qqqTZrTVcik/dL1aSyefQX+RwnvtPw7r38WL7KjH0giw+RMg4lCceu54nwkWGj2fN//CWcEXI2FI0Bme76NZ7yz1bqej/QMMf6k0RDxWB1OUG8RqK9KeelG+Bte4q3lN7F/wtIdK7y+jkreM3x655BwMZg1RcK8fjKqpae4qZa8V8YY6Z+FzBu9DWombjvKLSSw1e11X05s+YjAaeDVewmnnctqkBnvdS0I/e7usnQ+wz7x85UJvca35msp+KgHbMBNOYs19nEVsUHfNZYy+azbH1Nd8B3Bln7T/Uh/VZjX206+ggbPqqoP4Gh3X/IqCEhIm5ZEQZA/Hq9xHRlho5eACzIbmwqc4MuFVDz0uy1de/qCfvVzInv9Cs/HtliiQGrHMglDq+8qCKDReLYVcxBadTXMiTNRkHT9ixo8xnm/ku40yO44/iZB16pOpmoOc6FbmbXBRqJfpHXReqDVTwv6fU+HAeR61IHJjPueOfvQ9KsFiuOfsjA3/Hdpzet9aJm1s5D8xN0WXJazNVtNrOWsqh4xPZZWkyOYcMaa4xYq6dZCdzpZLrinFeWwY8EyEtDonZLclw1JejZNZ9rRU0JMuMnaQgokAjjK7uJuqe1nD9FbnwjYziwcz5B13WfoE/Trqs9fnajVdQLjYPqmRsKBI4FhFHme2nVoXaNhl1izO7jfJAJLnUrZqCbqqEgVvob22SrXUTKoSqqHVcweCzGrKM/HdvpsVzenWuiaJwDQ1uNXTMkUz/roOf5N0VuSLQOFbG1SdDxShfHbXoLa+Ha0hnra9v7MK1Coa1z/y0OzJalc4qxnqcFn+vJ6GGQ8NSsuXKtRK2pKlIIj+uSpgkXjJrrXmm4WdrstM9asIMA+2XUT9YJ/n585JPeRE/mpmWvdlouIHnTxMwcq6GCcwoBQ+tEk+Wkne72q19zKKH81z3cFzmaTh6WsIUsvWdLrK1D+ODtjoc3xKhf1Lgs0THwxgXVvTUkZWsNole1udIO3RpqKJGQmEEno9B7QX1sG0C82/Wf9eX06htZn2aubutub4sc2wH6tC0KWSIHypGUPuz98gt5qsNbAcWupBE/bG9dWEyOe1w0wGYXSwZ5+vksPZ+OHROR/B9Mh09/hvroV0xCeuTDOzbaiD3vD4iosdtsaCPjITbLnF08Wub1GOErfv3UzZzv+Vh7HufKWTyguQQMvru8QnYXMWFwKYyBvxkPRd2Ya6sojs5c1A6dZJMVrxnRTyPVPFuqIQk1uneyxJe0s/NPeensd/mFZZxjvrxmBz/lGw9z1ynpjj5gfklsLULQXEa8qudxWay78VWdlxbImH+QP7ZtX972Heaq+KuUlMsZ369OIZsn7bDdrRyNIqxNlT61EayQQ/6UNHJ7AWOm7w9h7UHhbk/TSCz55LV9NEJCrCPWZR5wzGdPlJMw8pun4S5To0X+3yTO2sMKuq92yEuX0vCzl0uHClfQaRTY/pMZ568Ms8W/MWA/nSKiK0Santfld6RU8NB9rq5L+X7pir8SzFvV1BQjXk0u+cz69malMuxuH3chZ856CGDiolVrOWNx1wY2uukuMO+eMA5nsB+Xls0CT65f4ppY3R8HCGj6lnmcnqg01PG9jPh8J5PL16oIvWdE2+pA3PWFUAItXmVoiJbnQQcLC1hR00VhzhnM+jDZk4bEyBhGj1AKxqGUndcaNVgnlgURT9IEui5lHOzTUESa2TTWQXZmFsnZ9Sx/6SMotSSWXWYt1Qd/h9161qsB3PI/bzk62MGfv7R8dc9AX6LNVzzGIx17DFvvTM8mSuDw+eL9W1bw4/a/fK2Cy/o+StDZWRty1qiZg0gS9Upa1g+7vPFfOZXxW7/kmJtJwnF9RD0OKdg7BKyA2swsJaKtFvMoh0VpJNFhvSsLX4fY05jbZnrlSndDIT2YJ3SA4dt5HwHObFsHOuNfpFGDW2WqGDNdPLxDwVfmNuPXSDT86f57vzih3ZIWQ2Mi3bC8cBl7Xc2rLaCVQdaohV9eO18F0Y2MrBway3su6ehLHvZfJ83m7+MinXjcWFuZdSsXAgv0iXsZFYbxRx+nrraJ1G11jRWUnT4uXSkFRoiRjXX0ZDMEjhXQVV/HgM1vHEVeqZLwrpHLkzk7+eIZt+Rf8eydzvsj4Nbn2ic4zzPOkiv5ryW8mHW43E5vVV61kjRwmngqRt1uL2Ow5uzY2+WBIhT5ju0TmtdjqfMrVOOFhP3qednbriQQG6IeK6j6E0Vlw7K0CMVlD1ZU/whQ5nPei7+7CNKTmX+eKfgFee6SU7medbmj6kGYs86Uci8/9tDw4JeXUSNNyrav/QQ3TMZKJozAWvfJFhrDJffL1n7Mdz7GYWZf86LrRnjUJTZ9hH7eMfUSPzl9/+tvkroq5PxlZnyvIeM6aydTvllHKc/vQxzoct0Ay2ouSYj5iOnmWvKm9cqs1+Tsagc64V5q6DDXPs7HrXIouuYdVdO0LGNOc681jN9s4xTJe0QrIlSFXQ84Jj8WcDxWBRjcdbBLCqcddm3S11YxXnaGMx+q8px3dwJgvncfO6jOX8nPJuKTuT4Jl8icKKyjlOzXfhGLoq+riAn53a/quAT56oas79XUCy26N1RI7+O9ez5zKwxc29x8/3xXB9U5FisW8/C+DN7+NyT4D2H9c/a/u1S0bD3v3dI5+1xINP/SzrruCq2NgpjgS1e7G5FLBBFhbOXHaBitxiogNKcc6aPfe0W9RrX7hZbP7u7C7sLE72YfGvGP/zda3BmZu/3XetZZ2b25rH3kpdf07v8yNc5DurolltDILPtAWrrgnZONEiORk/OXUV6l9RYR5mLGsKzVhfbd0sozXzT/HIwZsRL8IkehlwN4zB+soEhn3+JT+P6onYPCUfp8Qq14MxtCcuW/7aZz+etpSYM28PzYG2ba+gXKiGhX9nDottXDfcbA2lX6WF/xyGkUh5RnPo/87GMv3MquBOqQ1RmfuLxpEAFSez1hTk5B9Ul3M2rQa9Krd2koNkgCdOnUqu7ajhv7mW9h3M4vx9uH0jCdXJHpXUKPk5XcJm5uS1zQVN/5gbmoqhnMh7Sly/Qa5LWanhBPvOiTr2U6GXPUm1XBlwUfUqpyHYvEVfJfCH8Ob8v9PTyOq6+VeDPuhtynL//oeNMPx2tr24Ti9cr+Dq7D5Z58PebWBeb7Qgko24f5of9gdHWmkbqWBcukyE6ytTnKgrakHF6epJvOddNujoxJDoauXK7YGNPO5nxPj0aiA5N+mDrdwlznpMh+ida75o/mrLeNmcO2YI9pnj/JQ601vClADmMPzOFTFCsq7sw35c42tyJZHLom6oCqaEa6pUJRIkAjm/e/EhvRx2b3QbnMvrgPjNEms9wOA62xnhql3kvxoM1b65bt4z1WZ/+ti+WGf4qz7XwG9GhQV/rXdYTV1jz7hoSsyXiwhgFwZqMduckrP3C+XhB3m/LvMl6rXFLQq4fG2yTb6ko28SJ3Q2oGW3JEV4K0iFjNPNC25W3xMiizGjk7myct1+tZWSu+2a7xv+/4abh2lEFl1oNR2V3B/q4FxAbGndF9QEKwrvQVzimT8lgY/KQ1Qd8FWfLuFBruPlOL392tIp3xakz5v0T1om5ZvbJIwoSyFweKWT2GWSWjLbCfZ2E1R4HbQXy/3m2y1GEfsFcUOSgE5WXyFgX+FhcJz+GC+bDTAUZ3xT8fq5aezNe/oes/zrc+q5qyDHOi/5nLeQSzEqNTg5F7+1+IqV7RXE4zMC0vsz/B+zwvqWgc9FkceUusxr7eiN77mSmhvJk4qt3yK5vElGM2uUgR3ynLpnPaHcpo1vruJ9zKsi6zEDgcpeoVi2fuJ7stNbBNjNVg7QE1GK2CIGBzQfILQ7qRMBNcTg0Dl9elBMSa243NWb/y3xCN9fk5vgdX6qhc0UV6QsTUZx173ZbRtEyCmZXog4V+2l7wXNYP4ocwKz7+ADnmRn55lvmlRF1xP+KOhD+FzMv2efddRnBe3nst6xVSUcQ+WwwM425l1z29U4cTFXRrQnPfwX1criGgjNlJNUmLzB7Jb1UcWshs/LJdOHXj+zKa7nP89hwREbjUJk5VLXuOd2eSEZmLfuSy+3mGg7r/6zZcbQhuXOdiq5nZevd5Wk+LutZ5bmlByF/PR2jSgXgA7PRhUezRSONvFODXNZHw5BviThNLprbz4nxCZXFTi8ZR+P5Ofz7xumJyDZZRVRYFjTtMggG+7J6OH2SdZTaUEeFLXZrP5itF+htuRNEGvW7fBjnqCF7/W0CpnROBMgP5v35qH5kqtoq5o9S8L2eE/PiEjHGaVh7WXsMY2YO2iWmp7DuEY3wbCoyimwUPv4zxSDq8XbWlMnHGxtoGMusflN3ILmfHXFTDYy4HYW51O+508nODVri4iwyFxn13woGig9wouJGMgrr8mxEPjHtTTQyyUwdu8o4Q52dzLy/NT0OQcwHJ9n3gzep2JPhRESGhOVkgvYROrIwr3Q8LSOyvhOetRSkXiPb/Kej8I8YMZoeV+tqZbE7lXnusm6tXXedfnl9HnWRuepKElnhexSGU/9rVC8qXs1QLS/4wPpuTd2swLpe33a02PpQhe8+1gB7NE9sHgTtHC4etdWR/pm/qmt4zD4a+MGw9m98dkDFPWq17x0Zd8iiqXuZtwr+uWdVh8cLTmbmZ5YawT4u7/5WXOHndO9YDRWo8w+nOjCTnlFrq2Ldw5rF3FR2agc0bGHAj5y1kT7d+6iHMPdKbjSX/L+I/BQYiPQdToTZEhBag5pdXMaPQ4lWNtk2SMOjleZ6OzLe7tSsPdMyH+yxHeHPRnCehh3zE217UEO/h6F0OhmHeaDtgSbiWRDP81tt0Yl1XOTfprhvNzD1ltO6l73+iYoQsnnSaycyqDXh9JlJrN+95TVIA+inzC9fZAOf6IORkoYHcic87USfrKvhI7ysteU/b1QRNkfC5iatrTVTT1RVsP6zjEkXsqPA/mY4QQ4vtC0JFZinN2XnXC47IbIdqSQWk327zlORQr4d2uvPO0vH87kQek3BiW927KumoQszxV3qvydz+Z1G00XZj91wczk1camKLkuz4tKhbWI/6znPfWpziQi4ddExhX2et7CO1PSrovoHDZP6q1gU4EIp6utSjllnekGOEZr13mnONynCjb3x6IWOjz80LN9DluumYlOqhKIRcVhtH4b+N0Kxpo6C/MzaI+7LSCEDoK2E9zXv2hYMLYwszIzYEIWh7HeFOjLCU0LjMDL8i7xifgA16J0OvZIMb8Ncf8LAu3vsnREyxjZNtN7PnkU/nrLSfNZcgydz/ejLmvWM4RyO1b/07R3jdXzvpcBtrBMFqQVlPzoQwOsvV4ka2PaUeBko4V9eS5kzDnx+URC/NQUVqtELc7OXJrpQtb0dJWe2RTDzQuIOAwfJ7e2GGVgVvFUcZnY11yHKTp0oG0sd9FAxcDzPMfsxsYYaGLmJGZp9WjGbjnE9DMxaouCktwQ7/aFxnI4HcUkY6Kfg/G9d2M5z3G+q1hqnBce70G2XjntzJfiyb5Z14GclGBiUf6ytvIve+Vli3myNB2Sy5sySl+06vkLHW2Zy7wUK5tLTp1Dj6+9ULUZTtim4kK6iw2kF13fQ66rrWE0uepWhojZ5Je8tO46e1LCNNTzuWSIKv1Sw64ITabnIt6Y+vqAWkK1urCkDY6IOZFIfDXMvcM3aK/H3Khfc6ipIJkN9oPbtZH54LJive9mh3lHQa9N1sY318fmkA7s/MM/V7YKSB2IQ95V+QC8L8I1DsVTq9EFyz6ClNnNNwpqqis9jcmBHOSccLxxoG0weWK1gUZIPhjQsJ24XUtDjnEq9ka3nFQdcjkPvvTICX6vQzpCJ+Xm5BxqIZH5d8VpDXGNeN1m15lVmerLX4RYFROPcBt5WG4AF+Q3MdnPheS4dz8hg56hRB3mskE0GvjbRsOApa5rj174j/65+QxwLoudyXtP45yE7E3C2qwr7eWaYlxLWXFcwPY38Qv07elKy1nioFani+EUZA6Z4C7d0Hft57p3OxuIi+d+gZ2yRvCFuKKi+UseYWvSyRSpybH5p2923hihB/j+wz4lSkrl/sYrsGTXQYKmO5fWYS+lJW8kmpZPjUHQ5c9EnA4cLJuJLck2xkLX/6rMTcYEyRrnHWOuFnkvUYYtzohf7uv0OHZ3JgyejDJSjt5zxmimipzqRteQUUYJZd/QuGdmZTyek8/M5z83Wy3gewhyR3cW+t2Om+SxobxWLmd/WdGCdr4tG9miDXKuiybgIHKRP5PA2EHtbhbm3+eVisda7Dc8/m+9F5YbEWvc97IOExzoS2GuTSiTCSTY6RT98eJqef06zclNatyYwfDX4H9Xws6dh1WJ++kjb0e2RP1HC+DEq8txNwkXqcQyzTRP2TYuZ7IHv9M4KOmR628dOMnKMltGiRVbRTVEwi1nn6z0FfXY5IB9n/TF/FKUvtujhhF5XRhprrW0Ef5FnfzZWMOKsgkPsldJuEq4xR+Ziz1V4aVhrAv9DZlqZWV08ZX4P47yvNHaL0t78PGaXddfboYzPQJj524PZe1491tGACASz/0+xxs1n3Kp8k7GaY5axpA6eHmDO+4feQbYJnaVjuGGgYxSvlR705jLzU1bmJOar6fSibuz130HM9WfIuczs3chBnZOpLXX+3IM2n3dq0IhZswA94biEb04nitVRcY0et5r1+Kqyg/rHeaF2e2+QUeQ/iADyguIqDmObig9kz34uBzqsdBddRhq4HkIGKN8cfbZ1ELUrheJuWxXJ1cnmL3jNPJf7ZJpnZHzpZhLysSbNfQEWUht2jnLi6e9EjK1k4BQ//xNz2cgLOhLDqMFb+uPDMmbl6RJm99LQiTp98UYcYjaQgxYyn48w0K6cuZ4ia/CthGaTA0R7mZ46tjxQKT8q2mJxvcI8sYlacV8Vopygfz04IPLHMtPcd+ILayyhwAKR74SMxFQFhd0ldP7KbEv261/VQLe8CvbRRyOFgdBXKpK6My/Sh/y31cXqDX/2Tf992MCoCANLm8vWPrin31JzturW+zYnPih4sDy/OF5bwqnkBJT/eUFs8neibHEydNdEzGQu8aT2FK42UqhKbYzMomINOar+PwpW8NdVZoNyj1UcomZV5hyXGawgO2vi9Ap+XhozeW8Dtc+okMx9aJlzxjALZM+loRT707dTMbFvTKz1rv88sru5lkNCxwZicryOPuT951Ecry1kkVYKbPNDhK+hYUNFHRd+BgtzLaNw6oW53rj5/ufnQ/y7PAZW/CJ/MTetOlcYRx/EIPalHTrzwchazBqSE3dOaxh1TUOWKYXFXHrt5JUKutIHblxcIc6Sbwq3qiPMtXHHhTiwqrmGFTO7w/+ShsrTmEk3ajgy2XyGkJltQjS+k+GmF+lh7aln7lXwMJ8Kf3LRzUgHGjMT6cwpwRU59vSwD/fJGwskPCTbzabnrRhFRn7C2t6RF+23FUPK67liPX/Gv108Wmx3oM19O37MScK6kfzZ6jJyFWSPPyEfPEsQ9ZP/EY2mJ2LlxWiMZi8P7KyhHXP96cUJaD/Dj1lQt/YHWEg2M9fKfOqRhBbkib3nHcj7NhrfQrJY35WmtJExPJ+Bq/dV693gsbPbiyku5rJf1IFlzFPMLdtcM0RsTfo2/X/kD8Xaa7rG2qe2s9S8v9kbpegtp9nD29c4kftEEhYObCau1zf3FNKwpC4Z45WOn4s1rJpkYMrecqiWzDxhrqfgS235liA8me2ms6ffPVAxmnn8RVwCcvpEQyOfTdee23BNRp7yKlo0UNCf3h/ub2BxM/rJERX9op6JWXPJbNGVxMKOMu52YX2VUGHy/TfWqL2VjmwTNAh6yZP6irXXY6dLDsyKDkde5ge3igqK7VcQxMxVIltJYe5Ldmp1EqZ5JiKEGa/GWBVXS/J41ITKzHh5Z5l76ag4s0pBmTtnbQWeJ6J33l7o9nEYwo/KKMX8eJY1dZUe5UkOSBmoYsXhLGIy633LTzs6eGm4SH6s8aK0GJS7LJr9q+ADNSV7fR2/R2rwrkoN41jn7+m03j3Id1tDRZ7f/SEKDtILPPYquOuvY9ehh2JGBH17TCAMZmU3OVQUr3dRTPlJ/WKmyVZcR36fptY7mxmePK+vDvi9kaw9zMx74Vl7slfSJeiFCqOQezyadCJ7lMq0pZna7uWCl7k+w4DNol0ZDbENnPjvIWvrXyeq8O/ztpLQi37an37+mnNcVjGQg3PS7Ka5v7WGWj8kDFgso3QdDS1zTBZVWe+TyGstOjKzt1HxiLwUc1XHVbJ+u1MOzHDTkElWN9eouOv+RURtdmDz6sHWepvSP2TMljqGLFTRhsdOppYMiNOwx0m9yeyJLh16Y+0zcoyXA+Hs66or7LhBbV0UoCCUTJ21N1msq4JP18LxdUAMRg9zF/3oJU7W28rVBtYPVdBZl7FvloZdeVXrWfQSN2VUT0mAGmH2+CXhvTYS3o+cWK8baET+Mr/XNtc8X/57hbir7bVFfpIxa7uKKTHZxFb29OCq1bCSuf353+wpjpNnxb74UbU/jrH2RpRKgPke5evOKj4y7xer9p9oxDzwraSCb3PIQblZ6yt0aMwTZ8zndzhWq5uSfU/+eRdqDfO617gknOI5T8qpWvtdi1MK2k4lx/5FneS1V+HP39qsI8e9MMBTRaK592g1BQF7yDD12Id7gNbzEpCPPma+a5it0jPxmx7bdOQMm/lO0d0Ap/Wuw2KOUxPvQfj7vIJ7jROw16bg+WmbWL0mAROYZYLSVBylx/YRCv67K+HGbXKwv4z/rQCuRTnxNQ+zPCTr/f2jhQ3Unc++GF0ds36TG9ibUxfKyKdoeN/fjl/kDjtZchuZyXzeyS850zaGutLCS0aVzawtScazahHo/jEY02OGQC5MTvimQhxjzmijoRz18Rr56uqLXsgl6xjVhtwQbGDeahUHmL2DVQ0FmT1LN54unDzGhsAM26V8Or6QXZezFxoVyosLZKagNw3gO1nGV7JwS2p/BrW3Ipk2S8lO2J+oYHY2w9pT+eUWDdcmHrfVy0P+ISuMSSkv1g1xII7zmGW2DEdZDd8322HoPRBm6OhGLUlqSD9oGiDc51B3t2u49z0GyT+TsNdfw3Oy4ziOwUDm8JtLNfQg7+/wbo2biopRV9Js5nNb+1gb5j47vWvkRl0nc6Hrpe3hbAnmvcZMcvBssvWovRLKM/etJAub+zqmPZUQmu5AyqJftrojZVz93z7hX85grZCFVhoYkd4MT7qY+1caSGLPeIxtB3/m1UVkj09dBuAx6+VKlknC5PGZjxQsrqmhDTOJYAassJz8ZT4PP5916v9ArHDZ4RWmYCy9MtdqGe04J3Ma6uh72o6mrG2byYC89nq3FTzt78Dbuqr1jG/HdknWc8Uq9bzUk1vicz8FbcgwWnxp1LioYHKBRDR9zGviPNX8S0NQsIwAjssbatL4ygYaT1smtlWWMWS/bt33GFTLhYfk7tCiCpb00WHfIuEj2bhVgpkdWGf/U+H1n4q5A4dhzX0dRQ9cFwVmJmEBeXlSEQcWNiRHUSs7sp6KHHDhkL8dQV/DcL+rgXTW4aUEHQOYvS9R6zMXLxGC+WtsAw0rp+toXVgV5tpXrvXDcKOkL4qa+/JtkZFaIBZl6K8pj5nROb/jD+nIeYFZKZcTFZ8wu1QxcOIws28pJy5lDETBFBkVqMtXNQP2y6zrAk4k7JTQ4gvZro6C4gcN6JfpVR90JJM9VzGbzP7kRIlCDhzRkhD1n4a19VLFwLpt4NM1HKdj8ony7KvV9LzM0XbrmcqGR3RMIhtLn1QMHelCs7ESqgjmrITOuMAc+Ji5bXpNBYM+Sijo5oC5tsRYbwVJPyX0oS7Xy5Twhf53iZ+zJLcLH9vb8bG7br37sb8Pc7aHy1r7NJL5zFx/3dxrqBDZ7/weevxg1n2zvOidut/mv4eaViZdlCuvYPgg5vfBPfCrArPYRQdeUSvMZ4QPL3oiJl6hh/zNeTwvwaddR/h9UVHjuY465M2MDQb+x2y1gjUQPzEeNckDYT9ZE32ZY5vR797rmFFcRYW8Q8TMkqq1J9RpHyfcyurIU5p6xBw6JjNCZA0/Kqow28/zp6YyP/tkicIx5ucj1P2fZ8y1Yd1F+ncJni009GL+ztzHMcxKnaFu9uur41qVXuhlrnW9nixUzIX6nQ3M2vrnPeZL5VzoOjIKd8u64DHYwNRtMpLIFq9eSZjvyXn7NoiZRcJVcteigna8aG+gzpY4PKyhW3uH9bmnIb24jIKL6Z9Dr9h+hChYdp76QD8azRpcvZn89JeEBb8V6GSpqTd8YWM++zyAHn6zC7onJAn3Zyrqlasp5hxiZoh34jL1r2YhDT9eFbTWr7jG/vqXfdmcx9m82I7ECMXaY0P8dVaY+ze2uulE2jwFjZREBJKNmk3PsMX8F4d9vk5suODAiu8O+DKjjS0GUTqXau0pUa4+eTJ2nvh5KwtGdiLftoxHJVVGgj0WBbqpiAtVEfOKGbES59zuwFTOx2Fm46IzVQw450ARXlvoNx133FVrXentwSqG5NBxomw4bo1OwrjoONxi1giBAveqKp5uOyWepkrIvGMgiw/1x4v9xdraFGjgEufM3G9xNf1/8jQy/vxIzLnjwraavbDfjVl+rgpzve4cg3Tc/62hMznlNzPLMtaXuabXlff0E7Ki84mO6d4TxIt/dWsv1pBG9MR95LVQHTVa2BG62Q/mM4irqe0VkjXrXpud17krSEXu7wrepccjvnMJ8SOXjIgQFQXIUEWZSaYwc/3Huh/HnylIhsxG7zbX5H0wvCzu7lcRttKO86tUDNqqYV9JBwq2UFGXOVnt5cQndxkpmoLBzMbySR2d3dLElwP8c5eEhLMJ+Ic6fT9cgj/zQHARHuuDhDtT2+Ckx0vr3aGaD4qKWmTuLUk6Bv2d37pX133iW7HHftrWIFJGg4ca8pm9W0vHpur0qvXkoBwFRW0PHemryfgHqV8uJ96MWC4SyOHOlIrC5zp7a1Bt8aAk811uckTLptjCnnw+4oTte7tYuFw6HpxNRDu7gnzd7NhITf3F3kmfoqFL6W7YeZlcficfkvIpmLDIH/8dTEJn5oDFO2WsX8nPDKZPeg2B51sFPqky/F0amt7gsWtpyG50xVlqfdH3ZDx/CT8vS7jkdGBLS/KGHIItU/947KhkFTdjVHQqRjZ9p2Lh3Tg46D8fn/GYL71wqpwMI7+KjGnVhXSkE0Z3N9A8K7mst4SAuyniE7XueVYnpjU1kPtia1T66cAOWxxKtn0jGugOnPeSkHhZwZz/SdjeYiiupyl4NSMBu8r+sqWx1t1XOeHPnn9XQUfob+b35QqqcV6f5yOLgvU3U8aLLuwv/nmVFgZmX84tslUzEH2cGbc2+T5XnGi1hez6lwu9GjPDaZyPkaz5i7FYnpN8niUWE6QyojKza8ppCZ8DCiF3q5ziHnXZnQy0i1n9rfkMN7kpCzXSo78TLfpS/2+7Iess8tXIRPTzN9ew9xMHezVAsdwOXM6uIviAZu05VmwBx2ZEIo43kpEe5rTePW2YOhAJ1DvvdTGo7SHjo98L2zPOiQf/bYtIDY3JTdc3OlH5m2TtZ94gsDNcZNdEetnrQeyjIXYU83NAnhtg7WHyNDUJ7+44cIyatYZjb+7/1IE+7O7J8wtUkdZEx5RVO8Sj0zIehxvoz3PrcGYotlGLy3SV8bOujtqxKeIxs+YN31e2F6U0HGBWivDWEazUw4j7fWzm9za32Z8NmdVuXlVx1yEhhZ6dxdxHZamO2APkkiQnZjGLbUpVUIK5s3YnamaIjPM5DRzO99w2touBEuNU/Mt6nDyd/eLHmlpk4Eoo++4Fj83+OcZeC6SG/qybhP3v6Hnk0R7UxWb1nVj31VzHl7XMrGnW65qkaiIPc2SlXey3ZsMQlTs7tKkKznTIhtUcqypk07WddVzwka29X7z6J6H2EvrcQAW9mT8+PWA/+2mIor+Y+8YE8pqltbK1B8g8Xwkvl60RLa6RhXyT4Nmviahd/s/6hpG7ZcjUPvN+RHhXDbuZsTJYV177DBSerWJwOR1b98u47btcrGOuMJ/NHmruGc08eDucGdxcg7EP80E/DS99ybY3OP4cj//Gy+g/rCAidxhoUEhH4lsn5jFLpR3S8LRmFBb9Fvg3yI6ynuS39+7iEnNfLrW0yE/tqsDsF7Ncx6+mDmv/hA7bdExl1okl16Xzs/2ZC33PMOPys1u+pn48j8fpHQoukCGzP2EOTFbg1sQhMnLpFi/nzuTfMd+epY52jrHjTW0NPZmvupAh13sUF+nvh1h1VHWdhnM5LtvMve5WXJJRpyL7ixlAfBwCn7MKZo6pZb3Hm/pJwXaO13L2QON3OqbRE0OqaqhfiD3yzoGdgU68DE/C+ecKJm0xcJws5j1Zx6woDX93/ws3zpMnmTm6zjVQaqcGL7LDBGbp81l0nCHPTngxGOtmaqgTZiBocH/6pYHfy5zWfmidszcXBUqwjsbJ1FgFtRYouEQd30Mfy5nHExsjJGvPk5+hTkxmFtnLusyskIAztzRoHGM9SMLZ+4nY/Z2ZsLqOuLUOPCM/28lc/X07i1ZkKH/qbXbDAZ9aZIotOowU1ge5bm8z6gjn568RMjqQW/P8jMffZDot4H+2LyWYSbvYkXFMxQJyzK1u1MpJBi78QwY+omEJuen1YB6DNRS9QEOtUAPzb8i4O/XPPvNf6Tuzme82PtDx930V9UsoyDNcw4cySfhJ9g0mW4RF2iF9V7GNnryzEceHDGo+i+3bRsHrkna8b6lis184qrFfx9V5ZTO/iz1LbU/if3twHifyug4d0FEIBvJmDhL3BmtYysw7+Rl7/7CKJtSOA18LIJPnuWIR54o+WKqiipEc//rrVJiMfIk6e5cZysuhIBU87xiyWVsd/w3XUaC/gmapTut+76zJ/VBzpo6HvPbLPMbdnPSNLPQ4es/KSgnI4R+FJcf+J7rRf57SJ9bEc8w6DsSCWZGQOH83rzDzkKvHdtAwO2qh6N9bwYNvTnSgpu4jj408U0IMXqNjjkcc4r9pKFDBgN9sDbdWlhFjs6p45lSxib5yi9dYr7yBbRyvt80lLP3Inve04xxzbS/m7nWHNWsfgrfsj+GlFTwurCOqVxwOg1mjOD1mhwzPdzyHIwoO92Q/UM8KrKI3TfvzjO+NIdSerAreMEcEcr5GcP4iM8kicKL/2Hi0uydhPXngws3pQiH3SeV1bMx8a9u3WsGJ5Q4ErDWwz6FhTykVx8mgQ1kvIZMlVNxpx/3hCurXN5DNnwx4UbW83tt1SPi9T8LRV8xaZI1x0WQRXRVXmzH/jpgkxtQnh1Rh7icbF26uo9LfMuaHhMH7Pa93QEHhkZcaV22I9X2V+XxQDvZkQ+b25UWcaNlLReAIFcMfPLCd/jLU2rMt791EfHGX4P7RgAfnyHxGrGo2F6YtYg1yno8IBVEVXDymzmOqOJ/JnMU5/etfBRVrq6g8IwJLIpkrmFEKMXcfjlURcJI635Q811PFhKPLhOdAO/IFUPeis4s9u2S4X1eR8x8Z+1wqpkSQ4yszSzYgExdJQvmpsrVvj2M5+2mlhg17DAwPjkfolO4Y+51M9kGGes6J+UuaoHmkin6Hl9lOLqkkPizUYOahqYftCGP+jdqlI2KqhGw9dBwcHYkc6+nt1Mu216lbmmQx86WtCr6wj3X67Jum3cS1s6q1D8bHlSoK0j+GejNTBDLrNnkrKlArm2x1YVeOPrgzV0KtYm9EcL7uWPsyVRS5WwajyRvm91U+jQ0899GQ+6uGBOZR895W4hwVe2qReVLI33k0TL8rQayiztdjr76rgHP8N/Eblggn/aNeB+YM8nLtruS8PAZ63qRm1HDHC3rVzxAdo+g/p8jqGdMUhO4i33ekBkYbKN8jGIb5PQK99kirPvi1RMH6HIa1ZlTPxfzcBcNQsY2MJ1V+24rWbgnRiTo0VrO+Sx1bQYKZqUs4YsTAVYmo+P6HzcefPvmQHrm3Lda0Oi3MvTTNdY8W7T8mavVLgsZMs7zqcKxtxWN/ktBokIS3ZTVUX+qAP7XDs6Bm3SMZHDVXPNiSgAL04EW+GrKM15B/+WzxvaOB1PYa1tDfzftl1QsoGHWEvUimiJg5GFkf63DSW9KYKUuTDyN8RghzXZ//MuzCXFtmM+fgInl45igNcyv9WWfsiruB79WdSGTGnfC4KKKovdGPVaRSb8qd4Fg1cmHfqz97dzWrIaEKtavHMGbObzL+nmcgJK+BPTvpaR0law2b0XF/ntf4Z5jKnKNjvtssccRrljDfLXR75EBlN/IhvWPPlawAPbHDMXruTw05ojWsLkW2z5qAghLHkZ49huw1L1PH7MUq+l7pKXL9oC5zvC4mG3hdQsJUPRYxK5qgYZkuWMra/2zuPb/qi+ioqdazRXnnySjGuq57QcFKMmzJpeSSVwp+kAtTypKfp8QhYv05YXMqaE/uMcY7EfxSxUU3fhY58EUaPeAss01aS6SRwUyfOHTZYe1dtUGWcZ+eVKgGzy23bN0/7OJvwJngQtz3DWItGXPHCzLjbPp0217YNkMGqME1+0mozvyVvFzFEx7nDfkus6GCU2d8xVv6v1kH68+pGJZdw9V+vAay4cF3Tlwgp0cPG4AS22Ws41xG+CTBqzT70vFn3aghI6NQ566KL1k5z/TFeh8hFtTxEoMzkzCRfNiKLGh+X24+R2iu2za0JFk5byJ8y2vYNF5FuR4Sfvi5UP2h3Xpf6GN7L3TmfPb7QfYYqaIq2fQVs7G51mn3v4ajJcejeY0BSPDMj8iRGp5tdWB8PeYoeuTKiwa8mxs4ER+Mary29fd09BrNeirgZ+0zdnNvb/FkUYpY+FJmXlOse6s1LsjY3CeHmDZShp15pk9O1mp55jfyTa1suvXclrkveUYZjv3LDtZ7QHlUO54WdaI99bPWIgWFqMVKpTI4ExSBfD2qi1xeLgSEmM/2MHsxnzf0d6FraxVd/RQM+FEZN5nbTi4bjMK+MvxQQxwiQw8iRxSTz4rrHRUkxsiYuTEedd0dmEAv35jFfM5PxoXvdgwpWgkr2hl4INjvk3T4tacvehmoPbE12mcwE5C17czKkzjuIZ9VzKTf5qG+jf3ihMcU+teTIERe1FG/n457I4dBP0ItfMXjNywgNs7T4TaIfVRWRVC/GNwna9cM53HP6+g+TsP/GmrY1Yg8OZv6ke7E2A9R8KBW9FhdCVPDVNxxk7GjUCPEkMOz0qNf+6jYxT/Lv0xGwdbUgwNNkeOWA0eZr2/xzzscpR44t4nC5Ipqg6lNjRWcZM+sUskqLTRsv0yWsOl4X6YeKrbUrT1rfQNUHHpD71UMLGGGmZo3DOkp54TMWtg9RrfWinuUqOHEbx1fyXCDNDt8YjQE6Zx/5s3aHirimCNSRk0X5l7M5juEq4/rqPb0zx5HacVkXKNOh5Nt+o0fik7MlVtWSRixilpPFi8wTEFfT9XS7Rm8virkLHMv8948p9tny+BoKc4XazdjBWufPZ21TgzeUicvF1ewn1oQuLi5aMrxaRbB2qRfregRh59HVYx9rSCgZBec55jPZX8nrNXR+7KMGQWYzTrwOvOEirIdeiKJ2flSvIzC7NUnEzuLvWeCRbMwHSWy3hJuzELesRIOdjLwwmXg/I1AMYX/rvVETYT+Yn39S98+mIT2R5gRyI1ZmtBT/8dM2FpDy3wyHlU0MOw4+cdLw2iex+PSZAzW0GQyZdQjFXWmaNj6NhoHW+RF1STmE2boqmpRMbaOy1qDMvevcFxbpVhrAu7oRL6cr6MxfbbMvXXi2m36h6FgGJmmVu1ByGgbifgqUfB5yByY2ALRbuRxc6+gVQG4OUHHANbDbNZtjfsGdtWREdXvms3cy713TnKm2yHbBPJ17unDMLAQ67yQC6EcP79b9cUo1oy5b0AbeuZv5uf62ZgnrrGeyIhLBjjgyxoodFuy1mHanh6DQoFFkbVQEDZXUrBznye6ViNPhKTZvmXzFuZ7uSbz5I91oqJkoHNWB36MTLR8KIF5ePpnHduYT6ctNBDVTMGQ+8zVqzkuT8i75MTm5Qz84BiUIeuC2vKKnlyVHLmjAb2QGSxrkBMDgt7YKlZJRB760c4mZOmezK6ZMip71IbNW8f2U92svRKzxU8TS9kny8j8X75wHLO6ULKuhiLUPW9m/+8nZWu9sNz0go59VQwNIgP71ULvk8yp5L0aDSUUvq7jDhk2IzNEmHuIlE7WcDSLhvuJCo5XM1D1poRDwYb1TOPeHkloM44ZhD7ShrnCGatY+6/NL2bAnp6EV9PJhoP574JdyN2HnuX0g/mcxALWX5lVUfhRQMJxT37mdwVbLjC/kGvD5uiYuJk9tEHGOOaQCw/+rLOZNOyMbRd59MB7s3eYmwc68WhzLBxTndgTHosT7IWfL5jhK5CzyT7vdsbghMsHES/Pi1LsR3Mve/MZlU5FJFRgzXsXUZF9korgUAXFewaKvdfolUP+whzq+hrze32OW8BvDaUrO1GZv99LFmv7TEP5nxJuDzDQiHVe1mD97bVjDMfrDX3XvM/eiTxwZZMfMjI0a42XH3f5+Q3IZbuYTxclIXk7fZrjPpE5pxD7oFR+8zsjGf+OVHD5uoRJZKDlZI4d1Ip6+Z3Y1rc0KtxnTc6IR9rx3hif54yIpDaZzwWtItuW3V0c5xdEIx+z7r2BZP4gFY8vK6jeiLxP7yg/iSzSUsN1dx0zeZ61vjF/tHQg8jqZZvIUMbrXVbGHGmOuGdXTo5xYSJ8OHqlj2PBiYtzEfsLc19h8T7VTcSc8B7PWmEv9yJ+1+2vWPtU7qrQQQZsU5DP3HGt5yhY6xokjKayFXQps1IYD9KURreKRTSe3MR+a6/s/G/PR1tNPQn6OSxj7JJhZL2KEE7Vjqa9h9LaeBtru1PE8jHMbw3zeRUO26XbEbnaguTML/LJH4WXGW2Gua3mR53G6hhOHmHO6FDbQd7GOqcyWRfaWF1PWqnBbpiFXEx2ZzNSuhjq+UKM25Fc5no+EQb7sVsSFTez7mWSxKayt7H3iMU1RMNspI521bq7Jbq6n+Mg+BJWYMcy1Kxvv1qy1nDYyCy7+2hnmnjzmnqN/D2A2oDZ+49yVXeZEWA76V7KMxayzhT4Sgjg/ATUN3Nxt7pOpQamjY7OnhDzNtopUZu+X1Ln6B56KmoHMNlPtqMnriLzuwPrDCuqUXi7K++ooTT871NWJBeSZt4VdaM4su3eSE3WyKFiyzkDXYB118+pYwDk9yOx7sC3PaY+O1OMSst9sgr5teW3L3MQd/rutbvRSsnin3w1ELFmmVR8y1H7m4JS+WEfNWNXCfE9ERyyzUxG5n7Vuuf8AsqT5fDvz9iFypnl/vQvP1/yOcOhV1n6Igta7nfhKb1040cABcvxw5r4daar1TlnooSriBxl4UnwTsbSlAc8gGcUjNIyLU9DouIrR/FzzubYXMtmuzA9by0IyDg2vhirlP4n2ZL1p7io8WpYUM/vWwFbmgi+soeLZDTjMe3V+5L7ITqLSJY4T2eBqayfSo5wocJvZaEkEVjODmGsfOsgUO7Mr2N5DRfHzKnZQz6Vd6eLIdQV3XRqcY8aKlzcN65npZpfD8dA9CScbHRMeg3ne4yQ0+8m+21RQmOsNZSXfms/33b6lYBzZtfixRJxbQS6gV9x6R0b6Ugdih269X1aTvtziuR0Ba+JxO4sL36lTl1gv5novp6kV+d5HInNMRTF3kYwHnbrh1zJm9Ne8BvrjUfdJIvmjjPgoB468lnGGDFdZL4FefSQUd0ZgPPsqD/v2YQ8Np36XFKWZ7X3i6MnMw6ejqQejZCwqryNxyQXblU0u/B9QSwMELQAAAAgAAAAhAHMREvD//////////xEAFAB0ZXN0X3Y1X2xhYmVsLm5weQEAEACTDgAAAAAAAOIBAAAAAAAArVbLTsNADJxc+YrcAlIPoEoc+ABuVFw4cEIRDQIJUZQiLsBX8MOUkofXHnsXxFaqsrve8aw9dvK5urq4vK7wirdm3W1v++asbt4fTppF3dxt+pe+fbrZ9Ovue/28fdx2u/Xtffvc7eaHy9Pj5eJoUX/Ufx0HqNxhtrD/aRMHITGFwoN7aNgkvtNFj7dymk4xkrI3iXhKIIinyYKD+QS1NcJI7vExEk+5ui5+R6IgmnKK8JS5CpIVCQJlSxCV4HSGmDHUnMDwCSrJnrmynmG07GR3moELpqQSMxeXLqTj6U6aR1wu4kGdZqWdBM8Pmyw9VujWN4XRC75SIdpNAjzngbYCc2ZaNj3AYeUgqBnmfhfIX1WraD4JFnMSRM0xKB1h5Vq3YdvQjCdjjpwBoRkd/sLrmivBIZYySzORb0Dcs9MZ3NOpapw8z1FnHKWNJ3mXDlMZ0USusw1/TghdBBFbyCLPJ9lClZUEE7CNgau9fx1GWYgKIxNCKOrQWZSNnerMuB61TKwLKVLdwXD1xg/dsapklEQauUu/jbC4hJT5gaA9W3Flvy7jbe9b19O4g2Y6HDQ1zOFDgGMKN4VxXmKWdUFJsRQlp5Gx8qUKdfWKVx9lax3mXxMiuGXKD9o2B562vwBQSwMELQAAAAgAAAAhAAcDopP//////////xAAFAB0ZXN0X3Y0X3J1bGUubnB5AQAQAJMOAAAAAAAAFgMAAAAAAACdlr2OE0EQhLc75CmcGaQLQCcR8ABkIBICImRxRiAh7uRDJMBT8MJ4d6e6vl47Yu/s/Zvp6qmq7vHft+/fvPsQ08/p1/7u+PjptH+12//++mJ/s9t/vj/9OB2+f7w/3R3n568P3x6P5+ePXw4Px/P909uXz29vnt3s/uz+93gyTTHNR6xf51Ms3/P1+kz381dq9BieY+jyWebOxzIkQ7EEELpUCA3Fc6MEoDxAU4hb6Dj0KqPNDC9uhHIWZ9gWJPI82/mFgmqFob9YiNCaGj9gcdymAgRYy2vp4xzK5CqGT1k3heBLAc6fHCnHmpAyrYjBuUgqzRbWJPSm7vYm9JB5BIMHJ1HXMTDhThpWp5AaiLLiJPxp17RIS3QwFaWSXVYJkX5Tqy/lEnLIiFKX8G1jM5xlK5VVKi2uuzZlZ/k3jBtyRCpNLzjahdAgIdcHdVg/yBs+AW1dms7Tavoq5+jS2b+8cHKbNCnMEie9OnkdciUqeONw3WrZ1UCWkNDAfm71KFi3rYRaID42p5kQ28W5DZxqMGkqyfKkZaFwKgVQh/Wyk9jsne+W9uonawQzXJYUm7qbrzDYHi6rMTYgopvjC6djAbtMW+UhlYp36yTpVWqGcQGwYIo9ZF27QVdbTQgV1ZbP3cJhuzcmzbI/LVTbFFvMadiqaIqMFtwp+XF3VXNUabKiq6wu9pdSbsK/2qoXFsy9ehbmDMttbLxBckHq/UVrASEbzeyCqpip4hGwIGy2ZWhrmVBlapuNEUGmu0JE7QvRFoPuW0KhUhJbzKZICqdt7EAvhSBw3SUSdhsS2QZJ1lIiGqtPMQC94aFsl02qSFtCvk21yexhKjKbYCkK4mopOQBAgRLRGsHpWI8fm9Oo/S1bmKp0Wxv+WN6N1cDvSQKGOQNdqaYK3uUKF5cW5spTSkH3MMSrH0t2ANi0/lkGH3NApRGMG1URTaH1Wvs19zQUGi0gw2AHZJKURxtaxZO3cwzJemhuw3iLOEzNIyyY/+t1gmc2q+Y0SdV7TTDWZh9UUP+aQQKQ8truYox+G9HA5+MfUEsDBC0AAAAIAAAAIQBP5Nbh//////////8SABQAdGVzdF92NV9yZXNjdWUubnB5AQAQAJMOAAAAAAAAawAAAAAAAACb7BfqGxDJyFDGUK2eklqcXKRupaBek2morqOgnpZfVFKUmBefX5SSChJ3S8wpTgWKF2ckFqQC+RrGZgbGOpo6CrUK5AIuhlEwCkbBYACMA+2AUTAUwWiyGUFgNLJHwSgYBYMOjBZMwwYAAFBLAQItAy0AAAAIAAAAIQBiKIvWKbYAAHThAAAPAAAAAAAAAAAAAACAAQAAAABvb2ZfdjJfbWV0YS5ucHlQSwECLQMtAAAACAAAACEAY8DrjxSqAAB04QAAEQAAAAAAAAAAAAAAgAFqtgAAb29mX3YyX2dsb2JhbC5ucHlQSwECLQMtAAAACAAAACEA1NaExMIFAAC9OAAAFQAAAAAAAAAAAAAAgAHBYAEAb29mX3YyX21ldGFfbGFiZWwubnB5UEsBAi0DLQAAAAgAAAAhAA58UB3iCwAAvTgAAA8AAAAAAAAAAAAAAIABymYBAG9vZl92Ml9ydWxlLm5weVBLAQItAy0AAAAIAAAAIQBHee9ZU7YAAHThAAAQAAAAAAAAAAAAAACAAe1yAQBvb2ZfdjNfYmxlbmQubnB5UEsBAi0DLQAAAAgAAAAhAHMREvDiAQAAkw4AABEAAAAAAAAAAAAAAIABgikCAHRlc3RfdjVfbGFiZWwubnB5UEsBAi0DLQAAAAgAAAAhAAcDopMWAwAAkw4AABAAAAAAAAAAAAAAAIABpysCAHRlc3RfdjRfcnVsZS5ucHlQSwECLQMtAAAACAAAACEAT+TW4WsAAACTDgAAEgAAAAAAAAAAAAAAgAH/LgIAdGVzdF92NV9yZXNjdWUubnB5UEsFBgAAAAAIAAgA9wEAAK4vAgAAAA=="""
blob=base64.b64decode(_FROZEN_B64.encode())
assert hashlib.sha256(blob).hexdigest()=="e1480451c5d635d180201ae1957c75f6ec0383c99be9f5fb930928c824c29073"
_npz=np.load(io.BytesIO(blob),allow_pickle=False)
oof_v2_meta=_npz["oof_v2_meta"].astype(np.float64)
oof_v2_global=_npz["oof_v2_global"].astype(np.float64)
oof_v2_meta_label=_npz["oof_v2_meta_label"].astype(np.int8)
oof_v2_rule_code=_npz["oof_v2_rule"].astype(np.int8)
oof_v3_blend=_npz["oof_v3_blend"].astype(np.float64)
test_v5_label=_npz["test_v5_label"].astype(np.int8)
test_v4_rule_code=_npz["test_v4_rule"].astype(np.int8)
test_v5_rescue=_npz["test_v5_rescue"].astype(bool)
del _npz, blob
assert len(oof_v2_meta)==EXPECTED_TRAIN_ROWS and len(test_v5_label)==EXPECTED_TEST_ROWS
print("Frozen minimal prior arrays loaded.")

Frozen minimal prior arrays loaded.

In [3]:
def find_competition_csv(filename,expected_cols,expected_rows):
    roots=[Path("/kaggle/input"),Path("/mnt/data/ifest_dac")]; candidates=[]
    for root in roots:
        if root.exists(): candidates.extend(root.rglob(filename))
    candidates=[p for p in candidates if "/kaggle/working/" not in str(p)]
    valid=[]
    for p in candidates:
        try:
            h=pd.read_csv(p,nrows=3)
            if list(h.columns)==expected_cols:
                d=pd.read_csv(p)
                if len(d)==expected_rows: valid.append((p,d))
        except Exception: pass
    if not valid: raise FileNotFoundError(f"Could not locate a valid {filename}. Attach the IFEST competition dataset.")
    valid.sort(key=lambda z:(len(z[0].parts),len(str(z[0]))))
    return valid[0]

train_path,train=find_competition_csv("train.csv",["id","title","content","label"],EXPECTED_TRAIN_ROWS)
test_path,test=find_competition_csv("test.csv",["id","title","content"],EXPECTED_TEST_ROWS)
sample_path,sample=find_competition_csv("sample_submission.csv",["id","label"],EXPECTED_TEST_ROWS)
assert train.label.isin([0,1]).all()
def id_sha(df): return hashlib.sha256("\n".join(df.id.astype(str)).encode()).hexdigest()
assert id_sha(train)==TRAIN_ID_SHA256 and id_sha(test)==TEST_ID_SHA256
assert sample.id.astype(str).tolist()==test.id.astype(str).tolist()
print("Dataset:",train_path.parent,"| shapes:",train.shape,test.shape)

Dataset: /kaggle/input/competitions/penyisihan-ifest-2026-dac | shapes: (14397, 4) (3603, 3)

## Frozen V5 reconstruction
The prior champion is reconstructed without training. Its OOF decisions remain the baseline for the new prospective DESIGN/LOCK experiment; V7A is not allowed to alter V2/V4 structural rows or V5 rescues.

In [4]:
TOKEN_RE=re.compile(r"[\w]+",flags=re.UNICODE)
SOURCE_SUFFIX_RE=re.compile(r"\s+kumparan\s+com\s*$",re.I)

def clean_ws(x): return re.sub(r"\s+"," ",unicodedata.normalize("NFKC",str(x)).replace("\xa0"," ")).strip()
def clean_title_for_model(x): return SOURCE_SUFFIX_RE.sub("",clean_ws(x)).strip()
def normalize_key(x): return " ".join(TOKEN_RE.findall(clean_ws(x).lower()))

for df in (train,test):
    df["title_model"]=df.title.map(clean_title_for_model)
    df["title_key"]=df.title_model.map(normalize_key)
    df["content_key"]=df.content.map(normalize_key)
    df["pair_key"]=df.title_key+"|||"+df.content_key
    df["content_words"]=df.content.map(lambda x:len(clean_ws(x).split()))

def build_graph_reference(ref):
    pair_to_label={}
    for k,g in ref.groupby("pair_key",sort=False):
        labs=set(map(int,g.label))
        if len(labs)==1: pair_to_label[k]=next(iter(labs))
    cpos=defaultdict(set); tpos=defaultdict(set)
    for r in ref.loc[ref.label==1].itertuples():
        cpos[r.content_key].add(r.title_key); tpos[r.title_key].add(r.content_key)
    return pair_to_label,cpos,tpos

def frozen_v2_graph(qry,ref,meta):
    pair,cpos,tpos=build_graph_reference(ref); rules=np.array(["semantic"]*len(qry),object); forced=np.full(len(qry),-1,np.int8)
    for i,r in enumerate(qry.itertuples()):
        if r.pair_key in pair:
            forced[i]=pair[r.pair_key]; rules[i]="exact_pair"; continue
        malformed=r.content_words<MIN_GRAPH_CONTENT_WORDS; pt=cpos.get(r.content_key,set())
        if not malformed and len(pt)==1 and r.title_key not in pt:
            forced[i]=0; rules[i]="unique_content_different_title"; continue
        pc=tpos.get(r.title_key,set())
        if not malformed and pc and r.content_key not in pc and meta[i]<V2_TITLE_GATE:
            forced[i]=0; rules[i]="gated_title_different_content"
    return rules,forced

# V2 semantic threshold is frozen from the prior experiment; it is not re-selected in V7A.
rank_oof=RANK_V3_WEIGHT*oof_v3_blend+RANK_V2_GLOBAL_WEIGHT*oof_v2_global

def base_v2(qry,ref,meta):
    lab=(np.asarray(meta)>=V2_META_THRESHOLD).astype(np.int8); rules,forced=frozen_v2_graph(qry,ref,np.asarray(meta))
    m=forced>=0; lab[m]=forced[m]; return lab,rules,forced

def apply_v4(qry,base,forced,rank,ref):
    q=qry.reset_index(drop=True); lab=np.asarray(base,np.int8).copy(); forced=np.asarray(forced,np.int8); rank=np.asarray(rank,float)
    _,cpos,tpos=build_graph_reference(ref); rule=np.array(["v2_fallback"]*len(q),object); lock=forced>=0; rule[lock]="v2_graph_locked"
    for ckey,g0 in q.loc[~lock].groupby("content_key",sort=False):
        if g0.content_words.iloc[0]<MIN_GRAPH_CONTENT_WORDS or g0.title_key.nunique()<2 or len(cpos.get(ckey,set()))>0: continue
        idx=g0.index.to_numpy(); cg=(g0.assign(_s=rank[idx]).groupby("title_key",as_index=False).agg(score=("_s","mean")).sort_values(["score","title_key"],ascending=[False,True]))
        if float(cg.score.iloc[0])<CONTENT_CANONICAL_MIN_SCORE: continue
        winner=cg.title_key.iloc[0]; lab[idx]=(g0.title_key.to_numpy()==winner).astype(np.int8); rule[idx]="test_content_canonical"; lock[idx]=True
    for tkey,g0 in q.loc[~lock].groupby("title_key",sort=False):
        if g0.content_key.nunique()<2 or len(tpos.get(tkey,set()))>0: continue
        idx=g0.index.to_numpy(); cg=(g0.assign(_s=rank[idx]).groupby("content_key",as_index=False).agg(score=("_s","mean")).sort_values(["score","content_key"],ascending=[False,True]))
        if len(cg)<2: continue
        top,sec=float(cg.score.iloc[0]),float(cg.score.iloc[1])
        if top<TITLE_CANONICAL_MIN_SCORE or top-sec<TITLE_CANONICAL_MIN_MARGIN: continue
        winner=cg.content_key.iloc[0]; lab[idx]=(g0.content_key.to_numpy()==winner).astype(np.int8); rule[idx]="test_title_canonical"; lock[idx]=True
    return lab,rule

def apply_v5(v4,rule,blend,glob):
    lab=np.asarray(v4,np.int8).copy(); rescue=(lab==0)&(np.asarray(rule)=="v2_fallback")&(blend>=V5_BLEND_MIN)&(glob>=V5_GLOBAL_ENTAIL_MIN)
    lab[rescue]=1; return lab,rescue

class UF:
    def __init__(self,n): self.p=list(range(n)); self.r=[0]*n
    def find(self,x):
        while self.p[x]!=x: self.p[x]=self.p[self.p[x]]; x=self.p[x]
        return x
    def union(self,a,b):
        a,b=self.find(a),self.find(b)
        if a==b:return
        if self.r[a]<self.r[b]:a,b=b,a
        self.p[b]=a
        if self.r[a]==self.r[b]:self.r[a]+=1

def component_groups(df):
    u=UF(len(df))
    for col in ["title_key","content_key"]:
        seen={}
        for i,k in enumerate(df[col]):
            if k in seen:u.union(i,seen[k])
            else:seen[k]=i
    roots=[u.find(i) for i in range(len(df))]; mp={r:j for j,r in enumerate(dict.fromkeys(roots))}
    return np.array([mp[r] for r in roots],np.int32)

groups=component_groups(train)
old_cv=StratifiedGroupKFold(n_splits=3,shuffle=True,random_state=SEED)
old_fold=np.full(len(train),-1,np.int8); oof_v5=np.full(len(train),-1,np.int8); oof_v4_rule=np.array([""]*len(train),object); oof_v5_rescue=np.zeros(len(train),bool)
for f,(tr,va) in enumerate(old_cv.split(train,train.label,groups)):
    old_fold[va]=f; ref=train.iloc[tr].reset_index(drop=True); qry=train.iloc[va].reset_index(drop=True)
    b,_,fr=base_v2(qry,ref,oof_v2_meta[va]); v4,r4=apply_v4(qry,b,fr,rank_oof[va],ref); v5,res=apply_v5(v4,r4,oof_v3_blend[va],oof_v2_global[va])
    oof_v5[va]=v5; oof_v4_rule[va]=r4; oof_v5_rescue[va]=res
assert (oof_v5>=0).all()
y=train.label.to_numpy(np.int8)
test_v4_rule=np.array(["v2_fallback","v2_graph_locked","test_content_canonical","test_title_canonical"],object)[np.clip(test_v4_rule_code,0,3)]
train_candidate=(oof_v5==1)&(oof_v4_rule=="v2_fallback")&(~oof_v5_rescue)
test_candidate=(test_v5_label==1)&(test_v4_rule=="v2_fallback")&(~test_v5_rescue)
print("Frozen V5 OOF Macro F1:",f1_score(y,oof_v5,average="macro",zero_division=0))
print("Frozen test V5 distribution:",pd.Series(test_v5_label).value_counts().sort_index().to_dict(),"| eligible:",int(test_candidate.sum()))

Frozen V5 OOF Macro F1: 0.8946909330297752
Frozen test V5 distribution: {0: 379, 1: 3224} | eligible: 2255

## Prospective DESIGN / LOCK split
The LOCK partition is created now but its labels are not accessed by the V7A selection logic. Coverage is selected using DESIGN OOF only; LOCK is opened once, after the risk function and coverage are frozen.

In [5]:
# 80/20 component-safe prospective split. First fold of a 5-fold SGKF is the untouched LOCK.
outer=StratifiedGroupKFold(n_splits=5,shuffle=True,random_state=LOCK_SEED)
design_idx,lock_idx=next(outer.split(train,train.label,groups))
design_idx=np.asarray(design_idx); lock_idx=np.asarray(lock_idx)
assert set(groups[design_idx]).isdisjoint(set(groups[lock_idx]))
assert 0.15 < len(lock_idx)/len(train) < 0.25

# DESIGN-only inner component folds.
inner=StratifiedGroupKFold(n_splits=DESIGN_FOLDS,shuffle=True,random_state=LOCK_SEED)
design_fold=np.full(len(train),-1,np.int8); design_splits=[]
for f,(a,b) in enumerate(inner.split(train.iloc[design_idx],train.label.iloc[design_idx],groups[design_idx])):
    tr=design_idx[np.asarray(a)]; va=design_idx[np.asarray(b)]
    assert set(groups[tr]).isdisjoint(set(groups[va])); design_fold[va]=f; design_splits.append((tr,va))
assert (design_fold[design_idx]>=0).all() and (design_fold[lock_idx]==-1).all()

split_table=pd.DataFrame({"id":train.id,"component":groups,"partition":np.where(np.isin(np.arange(len(train)),lock_idx),"LOCK","DESIGN"),"design_fold":design_fold})
print("DESIGN/LOCK sizes:",len(design_idx),len(lock_idx),"| component overlap:",len(set(groups[design_idx])&set(groups[lock_idx])))
print("DESIGN label prevalence:",float(train.label.iloc[design_idx].mean()))
print("LOCK remains sealed until the post-selection cell.")

def positive_examples(indices):
    d=train.iloc[np.asarray(indices)]
    d=d[d.label==1].drop_duplicates(["content_key","title_key"])
    return [(str(r.content),str(r.title_model)) for r in d.itertuples()]

def contrastive_examples(indices):
    d=train.iloc[np.asarray(indices)]; out=[]
    for ck,g in d.groupby("content_key",sort=False):
        pos=g[g.label==1]; neg=g[g.label==0]
        pkeys=pos.title_key.drop_duplicates().tolist()
        if len(pkeys)!=1 or len(neg)==0: continue
        prow=pos[pos.title_key==pkeys[0]].iloc[0]
        for _,ng in neg.groupby("title_key",sort=False):
            nrow=ng.iloc[0]
            out.append((str(prow.content),str(prow.title_model),str(nrow.title_model),str(ck)))
    return out

design_pos=positive_examples(design_idx); design_pairs=contrastive_examples(design_idx)
print("DESIGN distinct positive mappings:",len(design_pos),"| DESIGN real same-content contrastive pairs:",len(design_pairs))
del design_pos,design_pairs

DESIGN/LOCK sizes: 11548 2849 | component overlap: 0
DESIGN label prevalence: 0.899030135088327
LOCK remains sealed until the post-selection cell.
DESIGN distinct positive mappings: 8925 | DESIGN real same-content contrastive pairs: 733

## IndoBART-v2 training and teacher-forced scoring
The official IndoNLG tokenizer format is used: encoder inputs end with the Indonesian language token, and labels end with the same language token so MBART shifts it to the decoder start. Pair ranking uses length-normalized headline-token NLL.

In [6]:
def resolve_model_source():
    if LOCAL_MODEL_PATH: return LOCAL_MODEL_PATH
    root=Path("/kaggle/input")
    if root.exists():
        for cfg in root.rglob("config.json"):
            p=cfg.parent
            if (p/"sentencepiece.bpe.model").exists() and ((p/"pytorch_model.bin").exists() or (p/"model.safetensors").exists()):
                try:
                    z=json.loads(cfg.read_text())
                    if z.get("model_type") in {"mbart","bart"} and int(z.get("vocab_size",0))==40004:
                        print("Using local IndoBART checkpoint:",p); return str(p)
                except Exception: pass
    return MODEL_NAME

def hf_kwargs(src): return {} if src!=MODEL_NAME else {"revision":MODEL_REVISION}

class IndoBARTSentencePieceTokenizer:
    """Minimal encode-only tokenizer matching IndoNLGTokenizer token IDs.

    IndoBART uses a 40,000-piece SentencePiece vocabulary plus four Fairseq
    special IDs [javanese]=40000, [sundanese]=40001, [indonesian]=40002,
    <mask>=40003. V7A only needs encode() and those IDs; bypassing the legacy
    toolkit avoids its incompatibility with modern Transformers on Kaggle.
    """
    def __init__(self,vocab_file):
        self.vocab_file=str(vocab_file)
        self.sp_model=spm.SentencePieceProcessor(model_file=self.vocab_file)
        if int(self.sp_model.get_piece_size())!=40000:
            raise RuntimeError(f"Unexpected IndoBART SentencePiece size: {self.sp_model.get_piece_size()} (expected 40000)")
        self.bos_token_id=0; self.pad_token_id=1; self.eos_token_id=2; self.unk_token_id=3
        self.javanese_token_id=40000; self.sundanese_token_id=40001
        self.indonesian_token_id=40002; self.mask_token_id=40003
    def encode(self,text,add_special_tokens=False):
        ids=list(self.sp_model.encode(str(text).lower(),out_type=int))
        if add_special_tokens: return [self.bos_token_id]+ids+[self.eos_token_id]
        return ids
    def __len__(self): return 40004

def resolve_tokenizer_file(src):
    p=Path(str(src))
    if p.exists():
        vocab=p/"sentencepiece.bpe.model"
        if not vocab.exists():
            raise FileNotFoundError(f"sentencepiece.bpe.model not found under local checkpoint: {p}")
        return vocab
    return Path(hf_hub_download(repo_id=src,filename="sentencepiece.bpe.model",revision=MODEL_REVISION))

def load_tokenizer_model():
    src=resolve_model_source(); kw=hf_kwargs(src)
    try:
        tok=IndoBARTSentencePieceTokenizer(resolve_tokenizer_file(src))
        model=AutoModelForSeq2SeqLM.from_pretrained(src,torch_dtype=torch.float32,**kw)
    except Exception as e:
        raise RuntimeError("Failed to load IndoBART-v2. Enable Kaggle internet or attach the indobenchmark/indobart-v2 checkpoint and set V7A_MODEL_PATH.") from e
    model.float(); model.config.use_cache=False
    if USE_GRADIENT_CHECKPOINTING and hasattr(model,"gradient_checkpointing_enable"): model.gradient_checkpointing_enable()
    assert int(model.config.vocab_size)==len(tok)==40004
    return tok,model,src

def pad_2d(rows,pad_value,dtype=torch.long):
    m=max(len(x) for x in rows); out=torch.full((len(rows),m),pad_value,dtype=dtype)
    for i,x in enumerate(rows): out[i,:len(x)]=torch.as_tensor(x,dtype=dtype)
    return out

def encode_batch(tok,sources,targets):
    # SentencePiece wrapper lowercases internally, matching IndoBART pretraining.
    bos,eos,pad,lang=tok.bos_token_id,tok.eos_token_id,tok.pad_token_id,tok.indonesian_token_id
    src_ids=[]; labels=[]
    for s,t in zip(sources,targets):
        si=tok.encode(clean_ws(s),add_special_tokens=False)[:SOURCE_MAX-3]
        ti=tok.encode(clean_title_for_model(t),add_special_tokens=False)[:TARGET_MAX-3]
        src_ids.append([bos]+si+[eos,lang]); labels.append([bos]+ti+[eos,lang])
    input_ids=pad_2d(src_ids,pad); attention=(input_ids!=pad).long(); lab=pad_2d(labels,-100)
    return {"input_ids":input_ids,"attention_mask":attention,"labels":lab}

def title_token_mask(labels,tok):
    m=labels.ne(-100)
    for sid in [tok.bos_token_id,tok.eos_token_id,tok.indonesian_token_id,tok.pad_token_id]: m &= labels.ne(int(sid))
    return m

def per_sequence_nll(logits,labels,tok):
    # Loss math is explicitly FP32 and excludes special tokens from likelihood diagnostics/ranking.
    B,L,V=logits.shape
    z=F.cross_entropy(logits.float().reshape(-1,V),labels.reshape(-1),ignore_index=-100,reduction="none").reshape(B,L)
    mask=title_token_mask(labels,tok); denom=mask.sum(1).clamp_min(1)
    mean=(z*mask).sum(1)/denom
    top2=[]
    for i in range(B):
        vals=z[i][mask[i]]
        if vals.numel()==0: top2.append(torch.tensor(0.0,device=z.device))
        else: top2.append(torch.topk(vals,k=min(2,vals.numel())).values.mean())
    return mean,torch.stack(top2)

class ListDataset(Dataset):
    def __init__(self,rows): self.rows=list(rows)
    def __len__(self): return len(self.rows)
    def __getitem__(self,i): return self.rows[i]

def list_collate(x): return x

def amp_ctx(): return torch.autocast("cuda",dtype=torch.float16) if AMP_ENABLED else nullcontext()
def make_scaler():
    try:return torch.amp.GradScaler("cuda",enabled=AMP_ENABLED)
    except Exception:return torch.cuda.amp.GradScaler(enabled=AMP_ENABLED)
def unwrap(m): return m.module if isinstance(m,torch.nn.DataParallel) else m

def model_to_runtime(model):
    model.to(DEVICE)
    if GPU_COUNT>=2: model=torch.nn.DataParallel(model,device_ids=list(range(GPU_COUNT)))
    return model

def make_loader(rows,batch,shuffle,seed):
    gen=torch.Generator(); gen.manual_seed(seed)
    return DataLoader(ListDataset(rows),batch_size=batch,shuffle=shuffle,collate_fn=list_collate,num_workers=0,pin_memory=True,generator=gen if shuffle else None)

def cycle_loader(loader):
    while True:
        for b in loader: yield b

def train_indobart(train_indices,seed,tag):
    seed_everything(seed)
    pos=positive_examples(train_indices); pairs=contrastive_examples(train_indices)
    if not pos or not pairs: raise RuntimeError(f"Empty training population for {tag}: positives={len(pos)}, pairs={len(pairs)}")
    tok,base,src=load_tokenizer_model(); model=model_to_runtime(base)
    pos_loader=make_loader(pos,TRAIN_BATCH,True,seed); pair_loader=make_loader(pairs,PAIR_BATCH,True,seed+991); pair_iter=cycle_loader(pair_loader)
    opt=torch.optim.AdamW(model.parameters(),lr=LR,weight_decay=WEIGHT_DECAY)
    updates_per_epoch=math.ceil(len(pos_loader)/GRAD_ACCUM); total_updates=updates_per_epoch*EPOCHS
    sched=get_linear_schedule_with_warmup(opt,int(total_updates*WARMUP_RATIO),total_updates)
    scaler=make_scaler(); hist=[]; opt.zero_grad(set_to_none=True); global_step=0
    for ep in range(EPOCHS):
        model.train(); sum_ce=sum_rank=sum_total=0.0; nstep=0
        for step,batch in enumerate(tqdm(pos_loader,desc=f"{tag} epoch {ep+1}/{EPOCHS}",leave=False)):
            srcs=[x[0] for x in batch]; tgts=[x[1] for x in batch]
            pb=encode_batch(tok,srcs,tgts); pb={k:v.to(DEVICE,non_blocking=True) for k,v in pb.items()}
            with amp_ctx(): out=model(**pb); ce=out.loss.float().mean()
            pair_batch=next(pair_iter); c=[x[0] for x in pair_batch]; pt=[x[1] for x in pair_batch]; nt=[x[2] for x in pair_batch]
            qb=encode_batch(tok,c+c,pt+nt); qb={k:v.to(DEVICE,non_blocking=True) for k,v in qb.items()}
            with amp_ctx(): qout=model(**qb)
            qmean,_=per_sequence_nll(qout.logits,qb["labels"],tok); bsz=len(pair_batch)
            rank=F.softplus(qmean[:bsz]-qmean[bsz:]).mean()
            loss=ce+PAIR_LAMBDA*rank
            scaler.scale(loss/GRAD_ACCUM).backward(); sum_ce+=float(ce.detach()); sum_rank+=float(rank.detach()); sum_total+=float(loss.detach()); nstep+=1
            do_update=((step+1)%GRAD_ACCUM==0) or (step+1==len(pos_loader))
            if do_update:
                scaler.unscale_(opt); torch.nn.utils.clip_grad_norm_(model.parameters(),MAX_GRAD_NORM)
                scaler.step(opt); scaler.update(); sched.step(); opt.zero_grad(set_to_none=True); global_step+=1
            del out,qout,pb,qb,loss,ce,rank
        hist.append(dict(tag=tag,seed=seed,epoch=ep+1,positive_examples=len(pos),contrastive_pairs=len(pairs),steps=nstep,updates=global_step,ce_loss=sum_ce/max(1,nstep),rank_loss=sum_rank/max(1,nstep),total_loss=sum_total/max(1,nstep),lr=float(sched.get_last_lr()[0])))
    return tok,model,src,hist

@torch.no_grad()
def score_examples(model,tok,examples,batch_size=SCORE_BATCH,desc="score"):
    # examples: list[(content,title)]
    if not examples:return np.array([],float),np.array([],float)
    loader=make_loader(examples,batch_size,False,SEED); means=[]; tops=[]; model.eval()
    for batch in tqdm(loader,desc=desc,leave=False):
        b=encode_batch(tok,[x[0] for x in batch],[x[1] for x in batch]); b={k:v.to(DEVICE,non_blocking=True) for k,v in b.items()}
        with amp_ctx(): out=model(**b)
        m,t=per_sequence_nll(out.logits,b["labels"],tok); means.extend(m.detach().cpu().numpy()); tops.extend(t.detach().cpu().numpy())
        del out,b,m,t
    return np.asarray(means,float),np.asarray(tops,float)

def save_checkpoint(model,path):
    core=unwrap(model); core.to("cpu"); state={k:v.detach().contiguous() for k,v in core.state_dict().items()}; torch.save(state,path); del state
    return str(path)

def restore_checkpoint(path):
    tok,model,src=load_tokenizer_model(); 
    try: state=torch.load(path,map_location="cpu",weights_only=True)
    except TypeError: state=torch.load(path,map_location="cpu")
    model.load_state_dict(state,strict=True); del state
    return tok,model_to_runtime(model),src

def dispose_model(model=None):
    if model is not None:
        try: unwrap(model).to("cpu")
        except Exception: pass
        del model
    gc.collect(); torch.cuda.empty_cache()

## DESIGN-only 3-fold CV
Each DESIGN validation row is scored by a model that never saw its connected component. Strong same-content counterfactual pairs are evaluated in the same held-out fold. Fold checkpoints are stored temporarily for the one-time LOCK evaluation.

In [7]:
design_mean=np.full(len(train),np.nan,float); design_top2=np.full(len(train),np.nan,float)
training_history=[]; pair_rows=[]; fold_ckpts=[]; model_source=""

for f,(tr_idx,va_idx) in enumerate(design_splits):
    print(f"\n=== DESIGN fold {f} | train={len(tr_idx)} valid={len(va_idx)} ===")
    tok,model,src,hist=train_indobart(tr_idx,SEED+f,f"design_fold{f}"); model_source=src; training_history.extend(hist)
    # V5-positive pure-fallback candidates only.
    cand_idx=va_idx[train_candidate[va_idx]]
    ex=[(str(train.content.iloc[i]),str(train.title_model.iloc[i])) for i in cand_idx]
    m,t=score_examples(model,tok,ex,desc=f"fold{f} candidate OOF")
    design_mean[cand_idx]=m; design_top2[cand_idx]=t
    # Held-out real same-content pair ranking.
    vp=contrastive_examples(va_idx)
    if vp:
        pos=[(a,b) for a,b,_,_ in vp]; neg=[(a,c) for a,_,c,_ in vp]
        pm,_=score_examples(model,tok,pos,desc=f"fold{f} pair positive"); nm,_=score_examples(model,tok,neg,desc=f"fold{f} pair negative")
        for j,(content,pt,nt,ck) in enumerate(vp):
            pair_rows.append(dict(fold=f,content_key=ck,pos_title=pt,neg_title=nt,pos_mean_nll=float(pm[j]),neg_mean_nll=float(nm[j]),correct=int(pm[j]<nm[j]),margin=float(nm[j]-pm[j])))
    ck=TMP_DIR/f"design_fold{f}.pt"; fold_ckpts.append(save_checkpoint(model,ck)); dispose_model(model); del tok
    print("Saved temporary fold checkpoint:",ck)

training_history=pd.DataFrame(training_history); pair_metrics=pd.DataFrame(pair_rows)
assert np.isfinite(design_mean[design_idx[train_candidate[design_idx]]]).all()
pair_rank_acc=float(pair_metrics.correct.mean()) if len(pair_metrics) else 0.0
print("Held-out counterfactual pair ranking accuracy:",pair_rank_acc,"| pairs:",len(pair_metrics))

=== DESIGN fold 0 | train=7685 valid=3863 ===

sentencepiece.bpe.model:   0%|          | 0.00/932k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json: 0.00B [00:00, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

pytorch_model.bin:   0%|          | 0.00/526M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/267 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie model.shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie model.shared.weight to model.decoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie model.shared.weight to model.encoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

model.safetensors:   0%|          | 0.00/526M [00:00<?, ?B/s]

design_fold0 epoch 1/2:   0%|          | 0/1490 [00:00<?, ?it/s]

design_fold0 epoch 2/2:   0%|          | 0/1490 [00:00<?, ?it/s]

fold0 candidate OOF:   0%|          | 0/383 [00:00<?, ?it/s]

fold0 pair positive:   0%|          | 0/35 [00:00<?, ?it/s]

fold0 pair negative:   0%|          | 0/35 [00:00<?, ?it/s]

Saved temporary fold checkpoint: /kaggle/working/ifest_v7a_output/_tmp_checkpoints/design_fold0.pt

=== DESIGN fold 1 | train=7679 valid=3869 ===

Loading weights:   0%|          | 0/267 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie model.shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie model.shared.weight to model.decoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie model.shared.weight to model.encoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

design_fold1 epoch 1/2:   0%|          | 0/1481 [00:00<?, ?it/s]

design_fold1 epoch 2/2:   0%|          | 0/1481 [00:00<?, ?it/s]

fold1 candidate OOF:   0%|          | 0/396 [00:00<?, ?it/s]

fold1 pair positive:   0%|          | 0/29 [00:00<?, ?it/s]

fold1 pair negative:   0%|          | 0/29 [00:00<?, ?it/s]

Saved temporary fold checkpoint: /kaggle/working/ifest_v7a_output/_tmp_checkpoints/design_fold1.pt

=== DESIGN fold 2 | train=7732 valid=3816 ===

Loading weights:   0%|          | 0/267 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie model.shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie model.shared.weight to model.decoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie model.shared.weight to model.encoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

design_fold2 epoch 1/2:   0%|          | 0/1493 [00:00<?, ?it/s]

design_fold2 epoch 2/2:   0%|          | 0/1493 [00:00<?, ?it/s]

fold2 candidate OOF:   0%|          | 0/390 [00:00<?, ?it/s]

fold2 pair positive:   0%|          | 0/29 [00:00<?, ?it/s]

fold2 pair negative:   0%|          | 0/29 [00:00<?, ?it/s]

Saved temporary fold checkpoint: /kaggle/working/ifest_v7a_output/_tmp_checkpoints/design_fold2.pt
Held-out counterfactual pair ranking accuracy: 0.9154160982264665 | pairs: 733

## DESIGN coverage selection — Macro-F1 aligned
The risk formula and coverage grid are frozen. Coverage is chosen only from DESIGN OOF, with ties resolved toward the smaller intervention. LOCK labels remain unused in this cell.

In [8]:
def macro_f1(yt,yp): return f1_score(yt,yp,average="macro",labels=[0,1],zero_division=0)

def percentile_risk(mean_nll,top2_nll):
    a=pd.Series(mean_nll).rank(method="average",pct=True).to_numpy(float)
    b=pd.Series(top2_nll).rank(method="average",pct=True).to_numpy(float)
    return RISK_MEAN_WEIGHT*a+RISK_TOP2_WEIGHT*b

def select_top(indices,risks,fraction,ids):
    indices=np.asarray(indices,int); risks=np.asarray(risks,float)
    if fraction<=0 or len(indices)==0:return np.array([],int)
    n=min(len(indices),max(1,int(math.ceil(float(fraction)*len(indices)))))
    order=sorted(range(len(indices)),key=lambda j:(-float(risks[j]),str(ids[indices[j]])))
    return indices[np.asarray(order[:n],int)]

# Risk is percentile-normalized independently inside each DESIGN fold, matching future LOCK/test usage.
design_risk=np.full(len(train),np.nan,float)
for f,(_,va_idx) in enumerate(design_splits):
    ci=va_idx[train_candidate[va_idx]]
    design_risk[ci]=percentile_risk(design_mean[ci],design_top2[ci])

coverage_rows=[]
for frac in COVERAGE_GRID:
    pred=oof_v5.copy(); selected=[]
    for f,(_,va_idx) in enumerate(design_splits):
        ci=va_idx[train_candidate[va_idx]]; sel=select_top(ci,design_risk[ci],frac,train.id.to_numpy())
        pred[sel]=0; selected.extend(sel.tolist())
    base_f1=macro_f1(y[design_idx],oof_v5[design_idx])
    new_f1=macro_f1(y[design_idx],pred[design_idx])
    sel=np.asarray(selected,int); prec=float((y[sel]==0).mean()) if len(sel) else np.nan
    coverage_rows.append(dict(coverage=float(frac),selected=len(sel),base_macro_f1=base_f1,v7a_macro_f1=new_f1,gain=new_f1-base_f1,veto_precision=prec))
coverage_metrics=pd.DataFrame(coverage_rows).sort_values(["gain","coverage"],ascending=[False,True]).reset_index(drop=True)
SELECTED_COVERAGE=float(coverage_metrics.iloc[0].coverage)

# Freeze the chosen coverage now; no LOCK information has been accessed.
design_pred=oof_v5.copy(); design_fold_rows=[]
for f,(_,va_idx) in enumerate(design_splits):
    ci=va_idx[train_candidate[va_idx]]; sel=select_top(ci,design_risk[ci],SELECTED_COVERAGE,train.id.to_numpy()); design_pred[sel]=0
    b=macro_f1(y[va_idx],oof_v5[va_idx]); n=macro_f1(y[va_idx],design_pred[va_idx])
    design_fold_rows.append(dict(fold=f,rows=len(va_idx),candidate_rows=len(ci),selected=len(sel),base_macro_f1=b,v7a_macro_f1=n,gain=n-b,veto_precision=float((y[sel]==0).mean()) if len(sel) else np.nan))
design_fold_metrics=pd.DataFrame(design_fold_rows)
design_base=macro_f1(y[design_idx],oof_v5[design_idx]); design_new=macro_f1(y[design_idx],design_pred[design_idx])
design_gain=design_new-design_base
positive_folds=int((design_fold_metrics.gain>0).sum()); worst_fold=float(design_fold_metrics.gain.min())
DESIGN_OK=bool(SELECTED_COVERAGE>0 and design_gain>=MIN_DESIGN_GAIN and positive_folds>=MIN_POSITIVE_DESIGN_FOLDS and worst_fold>MIN_WORST_DESIGN_FOLD_GAIN and pair_rank_acc>=MIN_PAIR_RANK_ACC)
print("Selected coverage:",SELECTED_COVERAGE)
print(f"DESIGN Macro F1: {design_base:.6f} -> {design_new:.6f} | gain={design_gain:+.6f}")
print("Positive folds:",positive_folds,"| worst fold:",worst_fold,"| pair ranking:",pair_rank_acc,"| DESIGN_OK:",DESIGN_OK)
display(coverage_metrics.sort_values("coverage")); display(design_fold_metrics)

Selected coverage: 0.0
DESIGN Macro F1: 0.893167 -> 0.893167 | gain=+0.000000
Positive folds: 0 | worst fold: 0.0 | pair ranking: 0.9154160982264665 | DESIGN_OK: False

   coverage  selected  base_macro_f1  v7a_macro_f1      gain  veto_precision
0     0.000         0       0.893167      0.893167  0.000000             NaN
1     0.002        21       0.893167      0.890150 -0.003017        0.095238
2     0.004        39       0.893167      0.887281 -0.005886        0.076923
3     0.006        57       0.893167      0.885329 -0.007838        0.105263
4     0.010        95       0.893167      0.878957 -0.014210        0.073684
5     0.015       141       0.893167      0.872219 -0.020948        0.070922
6     0.020       189       0.893167      0.864915 -0.028252        0.063492
7     0.030       281       0.893167      0.851160 -0.042007        0.053381

,fold,rows,candidate_rows,selected,base_macro_f1,v7a_macro_f1,gain,veto_precision
0,0,3863,3060,0,0.887812,0.887812,0.0,NaN
1,1,3869,3163,0,0.898453,0.898453,0.0,NaN
2,2,3816,3119,0,0.893641,0.893641,0.0,NaN

## One-time untouched LOCK evaluation
LOCK is opened only if DESIGN passes. The frozen DESIGN coverage is applied without adjustment. The three DESIGN fold models score LOCK; raw likelihood signals are averaged before percentile normalization. No threshold or coverage is changed after seeing LOCK.

In [9]:
lock_metrics=pd.DataFrame(); lock_scores=pd.DataFrame(); bootstrap_df=pd.DataFrame(); LOCK_OPENED=False; LOCK_OK=False

if DESIGN_OK:
    LOCK_OPENED=True
    li=lock_idx[train_candidate[lock_idx]]
    means=[]; tops=[]
    lex=[(str(train.content.iloc[i]),str(train.title_model.iloc[i])) for i in li]
    for f,ck in enumerate(fold_ckpts):
        tok,model,_=restore_checkpoint(ck)
        m,t=score_examples(model,tok,lex,desc=f"LOCK fold-model {f}"); means.append(m); tops.append(t)
        dispose_model(model); del tok
    lm=np.mean(np.stack(means),axis=0); lt=np.mean(np.stack(tops),axis=0); lrisk=percentile_risk(lm,lt)
    lock_sel=select_top(li,lrisk,SELECTED_COVERAGE,train.id.to_numpy())
    # LOCK labels are accessed for the first time here, after coverage is frozen.
    lock_y=y[lock_idx].copy(); base=oof_v5[lock_idx].copy(); new=base.copy()
    pos={g:i for i,g in enumerate(lock_idx)}
    for g in lock_sel:new[pos[int(g)]]=0
    base_f1=macro_f1(lock_y,base); new_f1=macro_f1(lock_y,new); gain=new_f1-base_f1
    precision=float((y[lock_sel]==0).mean()) if len(lock_sel) else 0.0
    # Component bootstrap on untouched LOCK.
    rng=np.random.default_rng(LOCK_SEED+77); ug=np.unique(groups[lock_idx]); deltas=[]
    group_rows={g:np.where(groups[lock_idx]==g)[0] for g in ug}
    for b in range(BOOTSTRAP_REPS):
        sampled=rng.choice(ug,size=len(ug),replace=True); rows=np.concatenate([group_rows[g] for g in sampled])
        db=macro_f1(lock_y[rows],base[rows]); dn=macro_f1(lock_y[rows],new[rows]); deltas.append(dn-db)
    boot_pos=float((np.asarray(deltas)>0).mean())
    LOCK_OK=bool(gain>MIN_LOCK_GAIN and precision>=MIN_LOCK_PRECISION and boot_pos>=MIN_BOOTSTRAP_POSITIVE)
    lock_metrics=pd.DataFrame([dict(rows=len(lock_idx),candidate_rows=len(li),selected=len(lock_sel),coverage=SELECTED_COVERAGE,base_macro_f1=base_f1,v7a_macro_f1=new_f1,gain=gain,veto_precision=precision,bootstrap_positive_fraction=boot_pos,lock_ok=LOCK_OK)])
    lock_scores=pd.DataFrame({"id":train.id.iloc[li].to_numpy(),"mean_nll":lm,"top2_nll":lt,"risk":lrisk,"selected":np.isin(li,lock_sel).astype(int)})
    bootstrap_df=pd.DataFrame({"replicate":np.arange(BOOTSTRAP_REPS),"delta_macro_f1":deltas})
    print("LOCK opened exactly once."); display(lock_metrics)
else:
    print("DESIGN gate failed. LOCK remains sealed and V7A will fail-closed to V5.")

V7A_VALIDATED=bool(DESIGN_OK and LOCK_OPENED and LOCK_OK)
print("V7A prospective validation accepted:",V7A_VALIDATED)

DESIGN gate failed. LOCK remains sealed and V7A will fail-closed to V5.
V7A prospective validation accepted: False

## Final two-seed full-train fit and test intervention
Only a prospectively validated V7A is allowed to train final export models. Both seeds use all official training labels. Test coverage remains frozen from DESIGN; no test-specific threshold tuning occurs.

In [10]:
final_v7a=test_v5_label.copy(); test_mean=np.full(len(test),np.nan); test_top2=np.full(len(test),np.nan); test_risk=np.full(len(test),np.nan); proposed=np.zeros(len(test),bool)
final_seed_history=[]; FINAL_SEEDS=[SEED,SEED+1]; TEST_COUNT_OK=False

if V7A_VALIDATED:
    ti=np.where(test_candidate)[0]; tex=[(str(test.content.iloc[i]),str(test.title_model.iloc[i])) for i in ti]
    seed_m=[]; seed_t=[]
    for s in FINAL_SEEDS:
        tok,model,src,hist=train_indobart(np.arange(len(train)),s,f"final_seed{s}"); final_seed_history.extend(hist)
        m,t=score_examples(model,tok,tex,desc=f"test seed {s}"); seed_m.append(m); seed_t.append(t)
        dispose_model(model); del tok
    test_mean[ti]=np.mean(np.stack(seed_m),axis=0); test_top2[ti]=np.mean(np.stack(seed_t),axis=0)
    test_risk[ti]=percentile_risk(test_mean[ti],test_top2[ti])
    sel=select_top(ti,test_risk[ti],SELECTED_COVERAGE,test.id.to_numpy()); proposed[sel]=True
    TEST_COUNT_OK=bool(MIN_TEST_CHANGES<=len(sel)<=MAX_TEST_CHANGES)
    if TEST_COUNT_OK: final_v7a[sel]=0
    else: proposed[:]=False; final_v7a=test_v5_label.copy()
    print("Frozen coverage:",SELECTED_COVERAGE,"| proposed test changes:",len(sel),"| test-count gate:",TEST_COUNT_OK)
else:
    print("Prospective validation failed; final model training skipped and predictions remain frozen V5.")

# Locked champion decisions must remain immutable.
assert not np.any(proposed & (test_v4_rule!="v2_fallback"))
assert not np.any(proposed & test_v5_rescue)
V7A_ACCEPTED=bool(V7A_VALIDATED and TEST_COUNT_OK)
print("V7A final accepted:",V7A_ACCEPTED,"| changed rows:",int((final_v7a!=test_v5_label).sum()))

Prospective validation failed; final model training skipped and predictions remain frozen V5.
V7A final accepted: False | changed rows: 0

## Export reproducible audit bundle
The export always runs. If any gate failed, `submission_v7a.csv` is exactly frozen V5 while all diagnostics document why V7A abstained.

In [11]:
submission=sample[["id"]].copy(); submission["label"]=final_v7a.astype(int)
assert len(submission)==EXPECTED_TEST_ROWS and submission.id.astype(str).tolist()==test.id.astype(str).tolist() and set(submission.label.unique()).issubset({0,1})

train_diag=pd.DataFrame({
    "id":train.id,"label":y,"partition":np.where(np.isin(np.arange(len(train)),lock_idx),"LOCK","DESIGN"),"design_fold":design_fold,
    "v5_label":oof_v5,"v4_rule":oof_v4_rule,"v5_rescue":oof_v5_rescue.astype(int),"candidate":train_candidate.astype(int),
    "mean_nll":design_mean,"top2_nll":design_top2,"risk":design_risk,"v7a_design_label":np.where(np.isin(np.arange(len(train)),design_idx),design_pred,oof_v5)
})

test_scores=pd.DataFrame({
    "id":test.id,"v5_label":test_v5_label,"v4_rule":test_v4_rule,"v5_rescue":test_v5_rescue.astype(int),"candidate":test_candidate.astype(int),
    "mean_nll":test_mean,"top2_nll":test_top2,"risk":test_risk,"veto":proposed.astype(int),"label":final_v7a.astype(int)
})
changed=test_scores.loc[test_scores.veto==1].merge(test[["id","title","content"]],on="id",how="left")
all_history=pd.concat([training_history,pd.DataFrame(final_seed_history)],ignore_index=True) if final_seed_history else training_history.copy()

config={
    "version":"v7a-indobart-conditional-headline-likelihood-verifier","seed":SEED,"lock_seed":LOCK_SEED,"base":"frozen-v5",
    "model":MODEL_NAME,"revision":MODEL_REVISION,"model_source":model_source,"source_max":SOURCE_MAX,"target_max":TARGET_MAX,
    "training":{"epochs":EPOCHS,"lr":LR,"weight_decay":WEIGHT_DECAY,"warmup_ratio":WARMUP_RATIO,"train_batch":TRAIN_BATCH,"grad_accum":GRAD_ACCUM,"effective_batch":TRAIN_BATCH*GRAD_ACCUM,"pair_lambda":PAIR_LAMBDA,"gradient_checkpointing":USE_GRADIENT_CHECKPOINTING,"synthetic":False,"external_data":False},
    "risk":{"mean_weight":RISK_MEAN_WEIGHT,"top2_weight":RISK_TOP2_WEIGHT,"coverage_grid":COVERAGE_GRID.tolist(),"selected_coverage":SELECTED_COVERAGE},
    "gates":{"design_min_gain":MIN_DESIGN_GAIN,"min_positive_design_folds":MIN_POSITIVE_DESIGN_FOLDS,"min_worst_fold_gain":MIN_WORST_DESIGN_FOLD_GAIN,"min_pair_rank_acc":MIN_PAIR_RANK_ACC,"min_lock_precision":MIN_LOCK_PRECISION,"min_bootstrap_positive":MIN_BOOTSTRAP_POSITIVE,"test_changes":[MIN_TEST_CHANGES,MAX_TEST_CHANGES]},
    "status":{"design_ok":DESIGN_OK,"lock_opened":LOCK_OPENED,"lock_ok":LOCK_OK,"validated":V7A_VALIDATED,"test_count_ok":TEST_COUNT_OK,"accepted":V7A_ACCEPTED}
}
provenance={
    "train_path":str(train_path),"test_path":str(test_path),"train_id_sha256":TRAIN_ID_SHA256,"test_id_sha256":TEST_ID_SHA256,
    "frozen_blob_sha256":"e1480451c5d635d180201ae1957c75f6ec0383c99be9f5fb930928c824c29073",
    "torch":torch.__version__,"transformers":transformers.__version__,"sklearn":sklearn.__version__,"gpu_count":GPU_COUNT,"gpus":[torch.cuda.get_device_name(i) for i in range(GPU_COUNT)],
    "timestamp_utc":pd.Timestamp.utcnow().isoformat()
}

artifacts={
    "submission_v7a.csv":submission,
    "design_split_v7a.csv":split_table,
    "design_oof_scores_v7a.csv":train_diag,
    "design_coverage_metrics_v7a.csv":coverage_metrics,
    "design_fold_metrics_v7a.csv":design_fold_metrics,
    "pair_ranking_metrics_v7a.csv":pair_metrics,
    "lock_metrics_v7a.csv":lock_metrics,
    "lock_scores_v7a.csv":lock_scores,
    "lock_bootstrap_v7a.csv":bootstrap_df,
    "training_history_v7a.csv":all_history,
    "test_scores_v7a.csv":test_scores,
    "changed_rows_v7a.csv":changed,
}
for name,df in artifacts.items(): df.to_csv(OUTPUT_DIR/name,index=False)
(OUTPUT_DIR/"config_v7a.json").write_text(json.dumps(config,indent=2,default=str))
(OUTPUT_DIR/"provenance_v7a.json").write_text(json.dumps(provenance,indent=2,default=str))

manifest={}
for p in sorted(OUTPUT_DIR.iterdir()):
    if p.is_file() and not p.name.endswith(".pt"):
        manifest[p.name]={"bytes":p.stat().st_size,"sha256":hashlib.sha256(p.read_bytes()).hexdigest()}
(OUTPUT_DIR/"manifest_v7a.json").write_text(json.dumps(manifest,indent=2))
zip_path=OUTPUT_DIR/"results_v7a.zip"
with zipfile.ZipFile(zip_path,"w",compression=zipfile.ZIP_DEFLATED) as z:
    for p in sorted(OUTPUT_DIR.iterdir()):
        if p.is_file() and p.name!="results_v7a.zip" and not p.name.endswith(".pt"): z.write(p,arcname=p.name)

# Temporary fold checkpoints are not exported; all training/config provenance is preserved.
shutil.rmtree(TMP_DIR,ignore_errors=True)
print("Submission:",OUTPUT_DIR/"submission_v7a.csv")
print("Results bundle:",zip_path)
print("Final label distribution:",submission.label.value_counts().sort_index().to_dict(),"| changed vs V5:",int((submission.label.to_numpy()!=test_v5_label).sum()))

Submission: /kaggle/working/ifest_v7a_output/submission_v7a.csv
Results bundle: /kaggle/working/ifest_v7a_output/results_v7a.zip
Final label distribution: {0: 379, 1: 3224} | changed vs V5: 0